### ISSUE TITLE
Canonical XML

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#100]
See https://faustedition.uni-wuerzburg.de/wiki/index.php/31._M%C3%A4rz_2016#Protokoll_Pre-Meeting

**Comment by gerritbruening** [comment]
See https://github.com/faustedition/xml/issues/42.

**Comment by thvitt** [comment]
ist dank der neuen Diff-/Merge-Funktionalität im Oxygen 19 wahrscheinlich auch weniger wichtig geworden

**Comment by gerritbruening** [comment]
Ach, das war ja was anderes! (Whitespace, Umbruch), nicht TEI-Konformität.

**Comment by dietmarpravida** [comment]
erledigt?
