### ISSUE TITLE
Same testimony, two source documents

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#103]
Some testimony entries ([e.g., Gräf 895](http://dev.faustedition.net/archive_testimonies#graef_895)) are identified in two source documents. It needs to be decided what should happen in these cases, especially since a web link cannot point to two documents at once …

(a) it's a mistake
(b) two links into the _Druckort_ column, but to which text? ← do we need the _text_ from the Druckort column in the long term, or could we replace it by a standard bibliography entry generated from the bibliography in the wiki?

**Comment by gerritbruening** [comment]
* http://dev.faustedition.net/archive_testimonies#graef_895 -- in welchem WA-Band steht der Brief wirklich? Wenn nur in einem, muss der Brief in der anderen Datei gelöscht werden.
* Bie3 2840: DP fragen, welcher Druck der primäre sein soll; andere Datei unter xml/attic/testimony/ speichern und in xml/testimony/ löschen
*QuZ II-1211: Wenn dieser Text in wa_IV_43 steht, den entsprechen Text aus der Datei quz_2 ausschneiden und in xml/attic/testimony/ speichern

@sandrakrause, können Sie das übernehmen?

**Comment by sandrakrause** [comment]
Text aus quz_2 ist in WA IV vorhanden und ist in attic abgespeichert.

Bei den anderen beiden Fällen werden in der Faustedition-Tabelle keine 2 Quellen (mehr?) angezeigt. Ist das schon behoben? Allerdings scheinen im attic auch keine neuen Dateien hinzugekommen zu sein. Oder habe ich da was übersehen?
