### ISSUE TITLE
baldensperger1932 "kein Literaturverzeichniseintrag", but present

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#106]
Die Tabelle sagt:
> kein Literaturverzeichniseintrag für faust://bibliography/baldensperger1932

Aber auf der Wiki-Seite steht :
```
* faust://bibliography/baldensperger1932
** Baldensperger 1932
*** Baldensperger, Fernand: Fragments inédits des lettres de J.J. Ampère à Albert Stapfer sur sa visite à Goethe. In: Revue de littérature comparée 12 (1932), S. 208-216.
```

https://faustedition.uni-wuerzburg.de/wiki/index.php/Bibliographische_Verweise#B

**Comment by thvitt** [comment]
Ja, weil [Dietmar das erst heute hinzugefügt hat](https://faustedition.uni-wuerzburg.de/wiki/index.php?title=Bibliographische_Verweise&diff=49584&oldid=49583) und [das letzte Update der Bibliographie schon länger her ist](https://github.com/faustedition/faust-gen-html/blob/master/xslt/bibliography.xml). Kommt mit den nächsten Updates zu faust-gen-html.

**Comment by gerritbruening** [comment]
Wer lesen kann, ist im Vorteil ...
