### ISSUE TITLE
XML for InDesign

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#109]
XML import of ID does not support neither attributes nor the hierarchical positon of elements. Thus, any feature which is to rendered has to be put in an unambiguous element name or plain text.

| feature | match | output                                                      |
|---------|-------|-------------------------------------------------------------|
| Verszählung | `l/@n`  | text in steps of five at the beginning of `<l>` equivalent followed by a tab |
| Beginn einer neuen Versgruppe |             |                                                                                             |
| eingerückter Vers |      |                                                             |
| Hervorhebung im Vers |  | |
| Hervorhebung in Bühnenanweisung |  | |
| Apparateintrag |           |                                                             |
|Anmerkungen (2,V)|           |                                                             |

We probably should also normalize whitespace.

**Comment by thvitt** [comment]
Siehe auch [z.B. diesen Beitrag von Martin Kraetke](http://www.xporc.net/2015/05/14/xml-und-indesign-i-tuecken-des-xml-imports/). 

Gibt's einen Zeitplan?

**Comment by gerritbruening** [comment]
Das hat noch Zeit: https://faustedition.uni-wuerzburg.de/wiki/index.php/Druckausgabe#Zeitplan

**Comment by gerritbruening** [comment]
Aber wir sollten den Workflow im Sommer schonmal testen, auch, ob der von Kraetke beschriebene Weg tatsächlich offensteht.

**Comment by thvitt** [comment]
we decided for an IDML based solution
