### ISSUE TITLE
Specify form of app entries in reading text

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#110]
What about something like

    <l n="4625">Sein Innres reinigt von verlebtem
      <note type="textcrit"><it>4625</it> Lemma] Variante <it>Sigle</it></note>
      Graus.</l>

**Comment by thvitt** [comment]
Visual Markup? `Lemma]`? Please use semantic markup instead (isn't there `<rdg>` and `<lem>` and `<ref>`?).

We need a transformation for the Indesign stuff anyway, and if we ever want to do something fancy (styling, linking) in the web version this kind of markup makes it unneccessarily hard.

**Comment by gerritbruening** [comment]
Agree!

The `<it>` stuff was intended for the file for print, admittedly.

But I can't promis that we can rely on the `app` etc. elements. Things would be easier with a `note`-like element which may contain text. `app` is structured, so that we would need an element container for all text. It may also force us to put some text into attribute values, but let's give it a try and see.

"Lemma" and "Variante" are just Lorem ipsum. The closing angle bracket separates the two.

**Comment by thvitt** [comment]
What's problematic about sth like:

```xml
<l n="4625">Sein Innres reinigt von verlebtem
  <note type="textcrit">
     <app loc="4624">
        <lem>Lemma</lem>
        <rdg wit="faust://document/faustedition/2_H">Variante</rdg>
     </app>
  </note>
  Graus.</l>
```

Could be transformed to the following to be suitable for Indesign:

```xml
<l n="4625">Sein Innres reinigt von verlebtem
  <note type="textcrit">
     <app loc="4624" aid:pformat="apparat">
        <ref aid:cformat="app_versno" cref="4624">4624</ref>
        <lem aid:cformat="lemma">Lemma]</lem>
        <rdg wit="faust://document/faustedition/2_H" aid:cformat="app_variante">Variante <ref aid:cformat="app_sigle" target="faust://document/faustedition/2_H">2 H</ref></rdg>
     </app>
  </note>
  Graus.</l>
```

But it could also be parsed to include, e.g., different styling for `]`, links for the sigil etc.

**Comment by gerritbruening** [comment]
`note` mit `@ target`.
