### ISSUE TITLE
For reading text, expand most abbr with no expan sibling

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#112]
For this, we would need a list of all text nodes of `abbr`:

| abbr/text() | output |
|----|----|
|Mephiſt.| Mephistopheles.|

Ideally, the output text would have an `expan` as parent.

@thvitt, could we have this as part of prepare-reading-text?

**Comment by thvitt** [comment]
With 041a114, the pipeline creates an XML file with all unexpanded values of `<abbr>`. For `<abbr>`s that have an `<expan>` elsewhere, this is inserted, otherwise the template is filled with the abbr so you don't have to type too much :-)

Code that replaces the `<abbr>`s with the correspondin `<expan>` can be written when you have edited & committed the file. You may join abbrs if you like:
```xml
<choice>
   <abbr>Meph.</abbr>
   <abbr>M.</abbr>
   <expan>Mephistopheles.</expan>
</choice>

**Comment by gerritbruening** [comment]
Great, thanks!
Where is this XML file?
Do you want me to edit it although it is generated?

**Comment by thvitt** [comment]
> Where is this XML file?
`$target/expan-map.xml.in`
> Do you want me to edit it although it is generated?
Copy it to `expan-map.xml`, add it to git, edit it.

**Comment by gerritbruening** [comment]
I have edited and pushed `https://github.com/faustedition/faust-gen-html/blob/master/expan-map.xml`.

**Comment by thvitt** [comment]
Are the `<abbr>`s to expand encoded as (1) `some text <abbr>abbr.</abbr> more text` or as (2) `some text <choice><abbr>abbr.</abbr></choice> more text`?

**Comment by gerritbruening** [comment]
If they have no corresponding `<expan>` sibling they are encoded as (1).

**Comment by gerritbruening** [comment]
`//note[@n]/abbr` is to be excluded from this procedure.

**Comment by gerritbruening** [comment]
Thanks!
Don't find `$target/expan-map.xml.in` anymore, though. Is this file generated in line with the other reading text stuff?

**Comment by thvitt** [comment]
The file is only generated by `prepare-reading-text.xpl` which is not part of the regular workflow. OTOH, it might be best to directly edit `expan-map.xml` since there is no merge code IIRC.

**Comment by gerritbruening** [comment]
Wouldn't it make sense to integrate this into the reading text generation?
XML sources might be slightly edited in the near future, so I would like to see `expan-map.xml.in` generated regularly.

**Comment by thvitt** [comment]
could migrate this, would require handling of existing expansions

**Comment by gerritbruening** [comment]
> would require handling of existing expansions

Heißt, dann gibt es Folgeprobleme? Dann bliebe es vllt lieber in prepare-reading-text.

**Comment by thvitt** [comment]
nein, es muss halt nur implementiert werden, sonst musst du die alten Änderungen jedesmal von hand übertragen

**Comment by thvitt** [comment]
so, ist jetzt teil der Pipeline.

**Comment by gerritbruening** [comment]
Sehr gut, danke, kümmere mich gerade drum!

**Comment by gerritbruening** [comment]
Bin soweit durch.

Was noch komisch aussieht ist das hier:
```
   <!--additional expansions from the old expan-map.xml:-->
   <choice>
      <!--before_8811, before_8813, before_8815, before_8817, before_8819, before_8821, before_8823, before_8825, before_8856, before_8860, before_8864, before_8868, before_8872, before_8876, before_8917, before_8921, before_8924f, before_8925f, before_8926f, before_8927f, before_8954, before_8971, before_8974, before_8994, before_9010f, before_9054, before_9060, before_9068, before_9069f, before_9588f-->
      <abbr>Phork:</abbr>
      <!--TODO-->
      <expan>Phork:</expan>
   </choice>
```
und folgender Eintrag.

Statt `<expan>Phork:</expan>` hätte ich `<expan>Phorkyas</expan>` erwartet.

**Comment by thvitt** [comment]
Das sind einfach die Einträge aus der alten Datei, für deren `<abbr>` es keine Entsprechung im aktuellen Lesetext gibt, einfach kopiert.

**Comment by gerritbruening** [comment]
Ah, jetzt verstehe ich das, danke!
