### ISSUE TITLE
Ignore ge:stage='#posthumous'

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#115]
Should be done by https://github.com/faustedition/faust-gen-html/commit/9ee4fd00c8b44a53b486a8b538255f0fccc4cc0f.
But I have the effect of ge:stage='#posthumous' in the result of `prepare-reading-text`.

**Comment by thvitt** [comment]
The problem is underspecified. 9ee4fd0 causes elements like `<del ge:stage='#posthumous'>` to be ignored in the emendation phase in the sense of they are not executed but copied verbatim. You'll need to describe what you'd expect in more detail.

**Comment by gerritbruening** [comment]
That's exactly what I thought. I have edited `test.xml` so that such things as 

                        <l>Dies ist eine <subst ge:stage="#posthumous">
                            <del>simple</del>
                            <add>einfache</add>
                        </subst> Ersetzung.</l>

appear in it.
However, when I transform it I still get 

     <l>Dies ist eine einfache Ersetzung.</l>
 
in the result. And so for the other kinds of revision.
There must be something that I am missing. Can you tell me?
