### ISSUE TITLE
Handle addSpan, delSpan and transpose when posthumous

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#116]
Maybe it's a feature, see https://github.com/faustedition/faust-gen-html/commit/749c13310f8283459caeea1c9b0189aa2e5c6f19, but while I now get

    <l>Dies ist eine <add ge:stage="#posthumous">einfache</add> Hinzufügung.</l>

when I process `test.xml` with `prepare-reading-text`, I get 

                        <addSpan spanTo="#addSpanposth" ge:stage="#posthumous"/>
                        <l>Erster und …</l>
                        <l>… zweiter gemeinsam hinzugefügter Vers.</l>

**Comment by gerritbruening** [comment]
I have a `delSpan` as well as a `transpose` case in the real data. These correspond to the following sample cases in `test.xml`:

                        <delSpan spanTo="#delSpanposth" ge:stage="#posthumous"/>
                        <l>Erster und …</l>
                        <l>… zweiter gemeinsam getilgter Vers.</l>
                        <anchor xml:id="delSpanposth"/>

And

                    <ge:transpose ge:stage="#posthumous">
                        <ptr target="#sp2"/>
                        <ptr target="#sp1"/>
                    </ge:transpose>
                    ...
                    <sp xml:id="sp1">
                        <p>content of the speech sp1 (originally the first one)</p>
                    </sp>
                    <sp xml:id="sp2">
                        <p>content of the speech sp2 (originally the second one)</p>
                    </sp>

**Comment by thvitt** [comment]
__Only for the text__, not for the witnesses

**Comment by gerritbruening** [comment]
Great, thanks!
