### ISSUE TITLE
Some sic and corr lost in prepare-reading-text

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#117]
When I transform `C(1)4_IIIB24.xml` with

                                <l n="9542" rend="indented"><choice>
                                        <sic>Alt- Wälder</sic>
                                        <corr type="correction">Alt-Wälder</corr>
                                    </choice> ſind’s! Die Eiche ſtarret mächtig</l>

I only get 

                                <l n="9542">Alt- Wälder sind’s! Die Eiche starret mächtig</l>

in the result, i.e., the `sic` content. I would like to keep the whole `choice` element.

Can you tell me what went wrong here?

**Comment by thvitt** [comment]
That's probably from emend-core.xsl:

```xslt
    <!-- only in emendation mode -->
    <xsl:template match="choice|app" mode="emend">
        <xsl:apply-templates select="(orig|abbr|sic|lem)/node()" mode="#current"/>
    </xsl:template>
```
You can overwrite that in the including stylesheet as you please, e.g.

```xslt
<xsl:template match="choice[sic]" mode="emend">
  <xsl:copy>
    <xsl:apply-templates select="@*, node()" mode="#current"/>
  </xsl:copy>
</xsl>
```

**Comment by gerritbruening** [comment]
OK, great, works.
Thanks!
