### ISSUE TITLE
insert app entries

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#119]
Somehow we have to insert editorial interventions.

Our current practice is to manually write lists of editorial decisions in some formal style, for example
> _11160_ fremdem] fremden _H [Typ 2a]_

My plan is to write these list entries in such a way that they can be transformed into code that automatically inserts the readings and the app entries into the xml:

                        <l n="11160"> Vor <seg xml:id="l_11160fremdem">fremdem</seg><note
                                target="#l_11160fremdem"><app loc="11160">
                                    <lem>fremdem</lem>
                                    <rdg wit="faust://document/faustedition/2_H">fremden</rdg>
                                </app></note> Schatten schaudert mir, </l>

I have experimented with an exchange table, but the `replacement-string`s are quite long and clumsy.

Most editorial interventions happen on phrase-level within `n` numbered chunks. Some of them, however, involve more than one chunk, and sometimes inter-level elements may be overlapped.

**Comment by thvitt** [comment]
I basically don't understand anything below your code snippet except "its complicated".

1. I'd suggest handling the easy and various complex cases differently. E.g., _easy_ could be defined as exactly one `@loc`, and the part of the original XML that is to surround with `<seg>` contains the text exactly as in the replacement list you write manually, i.e. no inline elements, no whitespace differences etc (so we can easily find this using `<xsl:analyze-string/>`. 
2. List should preferrable be xml or at least some easily-parseable plain-text format (i.e. no italics as marker, separate fields should be easily identifiable). E.g. `<v n="11160" lem="fremden"><r w="2 H">fremden</r></v>`

For this, one could write something like this (pseudo-xslt, not tested) to transform the source TEI:
```xslt
<xsl:template match="*[@n = $apparatus/v/@n]//text()">
  <xsl:variable name="loc" select="data(ancestor::*[@n][1]/@n)"/>
  <xsl:variable name="currapp" select="$apparatus/v[@n=$loc]"/>
  <xsl:variable name="pattern" select="string-join($currapp/@lem, '|')"/>
  <xsl:analyze-string select="." regex="{$pattern}">
    <xsl:matching-substring>
      <xsl:variable name="appentry" select="$currapp/v[@lem=.]"/>
      <seg xml:id="l_{$loc}_{$appentry/@lem}">
         <xsl:copy-of select="."/>
      </seg>
      <note target="#{$loc}_{$appentry/@lem}">
            <app loc="{$loc}">
               <lem><xsl:value-of select="."/></lem>
               <xsl:foreach select="$appentry/r">                 
                  <rdg wit="{f:lookup-sigil(@w)}"><xsl:value-of select="."/></rdg>
               </xsl:foreach>
            </app>
       </note>
    </xsl:matching-substring>
    <xsl:non-matching-substring><xsl:copy-of select="."/></xsl:non-matching-substring>
  </xsl:analyze-string>
</xsl:template>
```
Complex cases need to be looked at separately, with code examples.

**Comment by gerritbruening** [comment]
I agree with both of your suggestions. How would plain text have to / could look like?

**Comment by thvitt** [comment]
Depends on the required use cases. Basically, we'll have to parse it in the XSLT that inserts the stuff into the reading text and make XML out of it (so we can use it in XPath), and the less ambiguity (e.g., whitespace = separator or significant?) the better.

So maybe 

* 1 apparatus = 1 single line
* fields separated by a character that doesn't appear in text
* all whitespace significant, no quoting:

```
verse|lemma|rdg1|wit1|rdg2|wit2
11160|fremden|fremden|2 H
```

if you consider this still to clumsy, we might talk about introducing ] or whitespace, but if we leave the world of XML we don't have validation any longer and increase the risk of misinterpretions or ambiguities.

**Comment by gerritbruening** [comment]
Thanks, I don't think this is too clumsy. We should have a list of all `|information bits|`, though.

1. `n` value
2. human-readable reference for the printed volume (identical to the `n` value when only a single verse line is involved)
2. phrase of the base text which is to be replaced
3. phrase which is to be inserted in the base text
3. lemma for the apparatus entry
4. witness(es) that support the inserted phrase (not specified in case of obvious errors)
5. variant reading
6. verbal information about the reading (when necessary)
6. witness(ess) that support the variant reading
7. second variant reading (if present)
8. witness(ess) that support that reading

**Comment by gerritbruening** [comment]
@dietmarpravida, would agree to an XML form of list entries, or would you prefer plain text with unambigous separators?

**Comment by gerritbruening** [comment]
As I see the amount of possible fields, XML seems clearly preferable, doesn't it, @thvitt, @dietmarpravida?

**Comment by gerritbruening** [comment]
OK, so let's elaborate [Thorsten's](issuecomment-312909744)

    <v n="11160" lem="fremden"><r w="2 H">fremden</r></v>

What does `v` stand for?

**Comment by thvitt** [comment]
“**v**ery short tag name you may feel free to replace with something appropriate”

**Comment by gerritbruening** [comment]
OK, something like

    <listApp>
        <entry n="11160">
            
            <replace>fremden</replace>
            <insert>fremdem</insert>
            
            
        </entry>
    </listApp>

?

**Comment by gerritbruening** [comment]
Maybe introduce `seg`s and `anchor`s in textual transcripts.

**Comment by gerritbruening** [comment]
Provisional XML:
* `n` attribute
* `<rep>` for phrase of the base text which is to be replaced

**Comment by gerritbruening** [comment]
> some easily-parseable plain-text format

What I now have is this:

`4679[Lebenspulse]{Lebens Pulse} <i>4679</i> Lebens Pulse <i>2_H</i>] Lebenspulse <i>2_I_H.0a [type=2aa]</i>`

meaning
`@n[replace]{insert} <i>human-readable ref</i> lemma <i>URI</i>] reading <i>URI [type=...]</i>`

@thvitt, do you think that this may be easy to parse?

**Comment by thvitt** [comment]
anything repeatable in there?

**Comment by gerritbruening** [comment]
Thanks for this, just a few questions or possible alternatives:

1. maybe put `<note>` directly after the corresponding `<seg>` if this is feasible.

**Comment by thvitt** [comment]
We should also check that all app entries from the list actually make it into the text. Probably this requires a specially crafted id

**Comment by gerritbruening** [comment]
In the `txt`, look out for

- `!SPAN`
- `<i>none</i>` meaning that there is no witness supporting the lemma.

**Comment by thvitt** [comment]
Der Standardfall sieht so aus, dass Text in `[]` bzw. `<f:replace>` innerhalb einer Zeile (`n`-Attribut) zu ersetzen ist durch den Inhalt des `{}` (`<f:ins>`) zu ersetzen ist. Letzteres kann durchaus auch wohlgeformtes XML enthalten (TODO!)

Davon abweichend gibt es folgende Sonderfälle, für die @thvitt noch die Codierung definiert:

1. Alecto-Fall: Apparat an existierendes Element anhängen, keine Ersetzungen
1.1 `@n`
1.2 `xml:id`

2. neues XML einfügen
2.1 vor/nach ex. element
2.2.1 `<milestone unit="lg"/>` temporär einfügen → wird zu lg
   a) in ex. lg
   b) direkt in sp, dann lg erzeugen

3. lg/@rend-fall

**Comment by gerritbruening** [comment]
Not sure about this:

    
    <rdg wit="2_I_H.0a" hand="Ri G" type="2d">verkündet … entzündet<note>vorschl bill</note></rdg>

I see the reason behind it, but if we try to follow this path, `f:proposedBy` and `f:acceptedBy` would be more fitting to the rest of our encoding practice.

**Comment by thvitt** [comment]
```xml
<rdg wit="2_I_H.0a" hand="Ri G" type="2d">verkündet … entzündet<note>vorschl bill</note></rdg>
```
I think I've only seen hands w/o vorschl/bill in the app when I implemented this.

Mixing `bare' hands and "vorschl _Hand_ bill _Hand_" needs some thinking about the RE, too tired now.

**Comment by thvitt** [comment]
Ich würde jetzt folgendes vorschlagen (noch nicht implementiert!)

* alle Änderungen, die keinen existierenden Text ersetzen, verwenden spezielle Codes in den `[]` Ersetzungs-Klammern
* neue Inhalte kommen in die `{}` insert-Klammern und können XML enthalten, sofern alle Tags korrekt geschlossen werden. TEI-Namespace wird angenommen. `<i></i>` ist natürlich verboten.
* Änderungen, die sich nicht auf Zeilen mit `n`-Attribut beziehen, sondern auf eine Elemente mit einer `xml:id`, verwenden z.B. `#v1234_bla` für die XML-ID `1234_bla` am Anfang der Zeile (da, wo sonst der n-wert stünde). Der Rest bleibt gleich.

Im Detail:

> 1. Alecto-Fall: Apparat an existierendes Element anhängen, keine Ersetzungen
> 1.1 `@n`

    before_5357[]{} <i>vor 5357</i> <speaker>Alecto</speaker> <i>2_I_H.0a</i>] Alecto. <i>2_H :</i> <stage>Die Furien.</stage> <speaker>Alecto.</speaker> <i>G [type=2c0]</i>                                                                                                             


> 1.2 `xml:id`

    #v5347_sp_alecto[]{} …

> 2. neues XML einfügen
> 2.1 vor/nach ex. element

mit `[^]` (vor) bzw. `[$]` (nach), das neue XML kommt in die Insert-Klammern

> 2.2.1 `<milestone unit="lg"/>` temporär einfügen → wird zu lg
>    a) in ex. lg

z.B: vor Vers 9876 soll die lg unterbrochen werden

    9876[^]{<milestone unit="lg"/>} <i>vor 9876</> Versgrenze in …

>    b) direkt in sp, dann lg erzeugen

genauso

> 3. lg/@rend-fall

braucht eh eine sonderbehandlung. Wie wärs mit

    10067[@lg]{rend=indented} <i>10067-10074</i> <i>eingerückt</i> <i>2_H [type=1c]</i>
bzw.

    10067[@lg]{rend=} <i>10067-10074</i> <i>nicht eingerückt</i> <i>2_H [type=1c]</i>

**Comment by gerritbruening** [comment]
OK, ich versuchs mal, und schaue, ob alles geht!

**Comment by gerritbruening** [comment]
Frage zu 

    10067[@lg]{rend=indented} <i>10067-10074</i> <i>eingerückt</i> <i>2_H [type=1c]</i>
bzw.

    10067[@lg]{rend=} <i>10067-10074</i> <i>nicht eingerückt</i> <i>2_H [type=1c]</i>

`10067[@lg]{rend=indented}` bedeutet: Ist nicht eingerückt, soll im End-Text aber eingerückt sein, richtig? Ich frage, weil der Apparateintrag behautete, die Einrückung sei schon da.

**Comment by thvitt** [comment]
ach, das ist alles zu verwirrend für mich :-)

In den `{}`-Klammern soll das stehen, was dann auch im Lesetext-XML stehen soll. Also `{rend=indented}` → `<lg rend='indented'>`, `{rend=}` → `<lg>`

**Comment by gerritbruening** [comment]
OK, danke, so hatte ich das auch verstanden!

**Comment by gerritbruening** [comment]
Solche Einträge
> _vor 9393 Spatium H fehlt C1 4_

wäre es gut, segmentiert zu bekommen:
> _vor 9393 Spatium H&nbsp;&nbsp;&nbsp;fehlt C1 4_

Gilt auch für Fälle wie
> _5441–5456 Einrückung fehlt I H.0a_

**Comment by thvitt** [comment]
Hä?

    9393[]{//lg[@rend="indented"]} <i>vor 9393 Spatium H fehlt C.1_4 [type=2aa]</i>

ähnelt nur sehr entfernt der vereinbarten Codierung

und an dem anderen Beispiel versteh ich nicht was du willst?

**Comment by thvitt** [comment]
Vielleicht mal etwas präziser – das Suchmuster sieht zunächst folgendes vor:

__ganze Zeile__

1. ein `@n`-Wert, oder mehrere durch | getrennt
2. `[` Ersetzungstext `]`  (statt ersetzungstext ggf. Code für Spezialaktion oder leer)
3. `{` Einfügetext `}` (ggf. XML-Fragment)
4. ggf. Whitespace, dann `<i>` menschenlesbare Referenz `</i>`
5. ggf. Whitespace, dann Lemma, ggf. Whitespace, dann `<i>` Lemmazeuge `</i>]`
6. Readings, s.u.

Ein __Reading__ sieht so aus, es können mehrere kommen:

1. ggf. Whitespace, ggf. Reading-Text, ggf. Whitespace
2. `<i>`
3. References & Notes (s.u.) 
4. optional `[type=` oder `[Typ ` Typ `]`, ggf. Whitespace
5. ggf. `~`
6. `</i>`

Die Unterteilung in mehrere Readings erfolgt also mithilfe der `</i>`.

__References & Notes__

Wird an Whitespace in Tokens geteilt. Jedes Token wird geprüft, ob es (a) in der Liste der Siglen (d.h. letzter Teil der Faustedition-URI, siehe sigils.json) oder (b) in der Liste der Hände (hartcodiert, z.Z. G, Gö, Ri und Re) vorhanden ist. 

----

In dem 9393-Beispiel gibt es nur ein `<i>`, in dem ref (vor 9393) und alle Readings zusammengepfercht sind, ein Lemma gibt's auch nicht und die Sigle ist nicht standardisiert, wie soll das Skript das segmentieren? Woher soll es wissen, wo ein neues Reading beginnt?

m.E. müsste mindestens 'ne Lemmaklammer da rein und nach Label / zwischen die Readings nichtkursive Leerzeichen oder so.

**Comment by gerritbruening** [comment]
Ich weiß, deswegen hab ichs ja aufgebracht ...
Nichtkursiver whitespace müsste gehen, Lemmaklammer sowieso.

**Comment by thvitt** [comment]
Man muss halt irgendwie die Grenzen erkennen ohne den Text wirklich verstehen zu müssen. Und da die Siglen nicht nur am Ende des Apparatkommentars stehen können und der Location-Marker vielfältige Formen annehmen kann, reichen die allein nicht.

**Comment by thvitt** [comment]
Ich habe das Script jetzt nochmal angepasst, um Kursivierungen im Lemma zuzulassen. Dazu wird das Lemma (nach der `<i>Stelle</i>`, vor dem `]`) genauso bearbeitet wie die Readings (nach dem `]`)

**Comment by gerritbruening** [comment]
Danke!
Ich hatte sonst überlegt, unkursives, expliziteres XML reinzuschreiben.

**Comment by thvitt** [comment]
für _Trüber Tag. Feld_ würde ich übrigens vorschlagen, dass ihr einfach mit den reflines als `ttf_12` an Stelle der n-Werte codiert. Ich muss das vermutlich sonderbehandeln, da TTF im XML für Print vermutlich als `<p>` landen soll und nicht als Verssimulation wie im Web, aber das implementiere ich erst, wenn ich da was zum Bauen habe

**Comment by gerritbruening** [comment]
> einfach mit den reflines als ttf_12 an Stelle der n-Werte 

Also doch! Das ist sehr praktisch, danke!

**Comment by thvitt** [comment]
looks like the textcrit notes for, e.g., ttf_4 is inserted, but removed later?
