### ISSUE TITLE
Handle addSpan / delSpan -- space -- anchor in text-emend.xsl

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#120]
It's not only text content that is affected by `addSpan` or `delSpan` but also element nodes, for example:

                            <delSpan f:revType="soon-or-late" spanTo="#delSpan_Naturdichter"/>
                            <space quantity="1" unit="speeches"/>
                            <anchor xml:id="delSpan_Naturdichter"/>

If I understand it right, `text-emend.xsl` does not cover this at the moment, right?

**Comment by thvitt** [comment]
might be interesting to replace Wendell Piez' approach with something based on set operations
