### ISSUE TITLE
Something wrong with watermark "gekröntes Rautenkranzwappen über Stuetzerbach"

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#125]
http://dev.faustedition.net/watermark-table#gekr%C3%B6ntes_Rautenkranzwappen_%C3%BCber_Stuetzerbach
seems to have a dublicate in the following line:
> gekröntes Rautenkranzwappen über Stuetzerbach gekröntes Rautenkranzwappen über Stuetzerbach

Secondly, I would expect that the countermark "JGH über N3" is listed in the next column. Or is this not intended?

**Comment by thvitt** [comment]
`JGH über N3` is in [2 I H.0a](http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/archival/dla_marbach/Cotta-Archiv_Goethe_23.xml&page=1&view=structure) but it never appears in the _Gegenzeichen_ column
