### ISSUE TITLE
Column "Zeugen (nur Gegenzeichen)" missing in watermark-table

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#126]
Or is this intended?

**Comment by thvitt** [comment]
ich checks nicht ganz. 

1. Seien A, B Haupt- und c, d Gegenzeichen. In einem `<metadata>`-Block eines Zeugen kommt Hauptzeichen A und Gegenzeichen c vor. Mit welchen Kombinationen kann ich in irgenwelchen `<metadata>`-Blöcken in irgendwelchen Zeugen rechnen?

* [x] Ac
* [ ] A-
* [ ] -c
* [ ] Ad (also gleiches Haupt-, aber anderes Gegenzeichen auf demselben Bogen)
* [ ] Bc (also gleiches Gegen-, aber anderes Hauptzeichen)

2. Und wenn ich folgende Codierung habe:

```xml
`<archivalDocument>
  <metadata>
    <watermarkID>A</watermarkID>
  </metadata>
  <disjunctLeaf>
    <metadata>
      <countermarkID>c</countermarkID>
    </metadata>
  </disjunctLeaf>
</archivalDocument>
```
– hat das disjunctLeaf dann `Ac` oder `–c`?
