### ISSUE TITLE
Metadata-only testimony pages when no XML is present?

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#129]
Für Entstehungszeugnisse wie [Biedermann³ 2789](http://dev.faustedition.net/archive_testimonies#bie3_2789), für die wir (noch) keine XML-Transkripte haben, sind zur Zeit keine Informationen zugänglich, die nicht in der generierten Tabelle liegen.

Es wäre wohl möglich, eine HTML-Seite nur mit Metadaten (aus der Excel-Tabelle) und einem Hinweis (»Volltext für dieses Entstehungszeugnis noch nicht erfasst« oder so) zu generieren (analog zu den [QuZ-Zeugnissen, Beispiel](
dev.faustedition.net/archive_testimonies#quz_I-1016)), wenn da was interessantes drin steht. In der _Auszug_-Spalte könnte dann z.B. ein Link mit der Beschriftung `(Beschreibung)` oder so stehen.

Ist das sinnvoll, sollen wir das machen?

**Comment by thvitt** [comment]
Die beste Lösung ist wohl, im Testimony-Workflow nach dem Zusammenstellen des Index der in XML vorliegenden Entstehungszeugnisse (`testimony-index`) für jeden Eintrag der Tabelle, der _nicht_ in diesem Index steht, eine rudimentäre TEI-Datei analog testimony-split zu erzeugen, die im Wesentlichen den `<xenoData>`-Abschnitt enthält und ein `<desc>` oder so. Der restliche Workflow kann dann eigentlich für beide Varianten gemeinsam laufen.

**Comment by dietmarpravida** [comment]
ja, scheint mir auch so.
