### ISSUE TITLE
breadcrumbs in Lesetext and Print views

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#13]

**Comment by gerritbruening** [comment]
Text > Faust I > Szenenüberschrift
Text > Faust II > Akt # – {Szenenüberschrift}

**Comment by thvitt** [comment]
ist umgesetzt, oder fehlt da noch was?

**Comment by gerritbruening** [comment]
There is an error in Faust I, for example:
"Text > Faust II" etc.
Should be:
"Text > Faust I"

In Faust I we can go without the intermediate level "Der Tragödie Erster Theil."

Breadcrumbs are now directly taken from the text. In Faust II we should have "Akt 1" etc. (according to http://beta.faustedition.net/archives.php?view=manuscript-concordance). As for the Scene headings, we should confine to the subscene level in the way it is done here: http://beta.faustedition.net/chessboard_faust_ii.php
Likewise, the scene headings in the breadcrumbs should be normalised.

All these headings are defined directly in the respective svg. Is it better to leave it like that or have a separate list with the definitions?

**Comment by thvitt** [comment]
Ah, I see.

[This](https://github.com/faustedition/faust-web/blob/master/data/scene_line_mapping.js) is the source of the headings used in the webapp, except when they're directly displayed from the SVG. They need to be manually converted to the `scenes.xml` in this repository using `scl2xml.js`. 

We'll need to see whether using these as source for the breadcrumbs will work in all cases, I believe the scene mapping isn't encoded and we need to go via the line numbers?

**Comment by gerritbruening** [comment]
Yes, the scene mapping isn't encoded in each transcript.
