### ISSUE TITLE
excerpt extraction broken for some testimonies

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#133]
* [x] [only `…`, although rs present](http://dev.faustedition.net/testimony/pniower_105) ①
* [x] [`… …`, although exactly one rs present](http://dev.faustedition.net/testimony/graef_863a) wie ①
* [ ] [many `…` before the actual rs](http://dev.faustedition.net/testimony/graef_1709#graef_1709), this document contains multiple testimonies in one div ②
* [ ] [Incipit w/o terminating ellipsis](http://dev.faustedition.net/testimony/graef_1834)

More instances: sort testimony table by excerpt

**Comment by thvitt** [comment]
① Pniower 105: Testimony extraction is broken:
```xml
         <text copyOf="#pniower_105" type="testimony">
            <body>
               <p>
                  <gap reason="irrelevant"/>
               </p>
            </body>
         </text>
```

**Comment by thvitt** [comment]
① it's an encoding error, `spanTo` points to the starting milestone itself:

```xml
<milestone unit="testimony" spanTo="#pniower_105" xml:id="pniower_105"/>Ich wünſche morgen von Ihnen zu hören daß der <rs><hi rend="antiqua">Faust</hi>
                    vorgerückt</rs> iſt.<anchor xml:id="pniower_105_end"/>
```

**Comment by gerritbruening** [comment]
@sandrakrause , könnten Sie sich das mal ansehen?

**Comment by thvitt** [comment]
② here the milestone content is extracted correctly:

```xml
         <text copyOf="#graef_1709" type="testimony">
            <body>
               <p>Sobald
                    als meine <rs>Compoſition bis zum zweiten Acte</rs> vorgeſchritten war, trieb es
                    mich zu Goethe. Ich meldete ihm daß es mir jetzt gelungen ſei, im erſten Acte
                    die gewünſchte melodramatiſche Behandlung eintreten zu laſſen. So werde der
                    Erdgeiſt, indem er ſingend auftrete, in jeder Beziehung einen Gegenſatz zu Fauſt
                    bilden. Goethe genehmigte nicht nur meine ganze Auffaſſung, ſondern verſprach
                    auch, er wolle mir noch einige Zuſätze ſchicken, die ich auch bald
                        erhielt.<gap reason="irrelevant"/>
               </p>
            </body>
         </text>
```

The problem here is probably that [textimony2html.xsl/get-citations](https://github.com/faustedition/faust-gen-html/blob/master/xslt/testimony2html.xsl#L147) calls `find-rs()` for every milestone – legacy from the pre-split-era
