### ISSUE TITLE
End-user suitable message for missing XML / missing ID

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#135]
1. Für Entstehungszeugnisse, für die wir kein XML haben, wird im Augenblick z.B. `kein XML für »bie3_2789«` angezeigt. Hierfür setzen wir entweder #131 um oder wir bräuchten eine bessere, Endnutzergeeignete Meldung.
2. Für Entstehungszeugnisse, die weder Gräf-, Pniower-, QuZ- noch Biedermann³-Nummer haben, können wir im Moment keine ID erzeugen & drum auch nichts verlinken. Für diese Zeugnisse steht im Moment in der _Auszug_-Spalte die Meldung `keine/komische ID: »«`. Da sollte entweder eine bessere Meldung hin (aber welche?) oder es wird auch für diese Zeugnisse #131 umgesetzt, die ID muss dabei aus einer der (volatilen) lfd Nr. erzeugt werden. 

Bitte entscheiden und dann mir zur Umsetzung zuweisen …

**Comment by gerritbruening** [comment]
* `kein XML für »bie3_2789«` --> sowas wie `noch kein Text vorhanden`, dies verlinken auf eine Seite wo der übliche Kopf steht und unten dann wieder `noch kein Text vorhanden` in dem Stil wie die Seiten für QuZ. OK, @dietmarpravida ?

**Comment by dietmarpravida** [comment]
solllten wir mal telefonisch besprechen

**Comment by dietmarpravida** [comment]
Die Zeugnisse einfach wie #131 zu behandeln scheint mir dann nicht so sinnvoll, wenn das Zeugnis vorhanden, nur nicht adressierbar ist.

**Comment by thvitt** [comment]
Ich hab's jetzt pseudo-adressierbar gemacht, mit einem temporären ID. 

z.B. [in der dev-Version zwischen Gräf 850a und Gräf 850b](http://dev.faustedition.net/archive_testimonies)

**Comment by thvitt** [comment]
Da es nun keinen unbehandelten Fall mehr gibt, gibt's auch keine Meldungen mehr → erledigt
