### ISSUE TITLE
support multi-milestone testimonies with milestones in multiple main divs

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#137]
Der zweite Teil des Excerpts zu [Pniower 31](http://dev.faustedition.net/testimony/pniower_31) kommt gar nicht in dem Zeugnis vor‽

**Comment by thvitt** [comment]
Die Situation hier ist dass sich das Entstehungszeugnis über zwei Einheiten (hier: Tagebucheinträge) erstreckt:

```xml
            <div type="diaryentry">
                <p>
                    <date when="1780-03-23"/>23 Eyersuchen der Kinder im Redoutenhause. <milestone
                        unit="testimony" spanTo="#pniower_31_end" xml:id="pniower_31"
                        next="#pniower_31_b"/><rs>Hälfte der Helena</rs> bey [*Herzogin Anna Amalia].<anchor
                        xml:id="pniower_31_end"/></p>
            </div>
            <div type="diaryentry">
                <p>
                    <date when="1780-03-24"/>24 <milestone unit="testimony"
                        spanTo="#pniower_31_end_b" xml:id="pniower_31_b"/>Ordnen und auslesen <rs>abends
                    Helena andre Hälfte</rs>.<anchor xml:id="pniower_31_end_b"/></p>
            </div>
```

@gerritbruening, @dietmarpravida, @sandrakrause: Ist das codierungstechnisch OK? Wenn ja, müsste `testimony-split.xsl` so angepasst werden, dass es das 2. div entsprechend mitnimmt (auch alle dazwischenliegenden, falls sowas vorkäme?)

**Comment by gerritbruening** [comment]
Wir haben das erstmal provisorisch so gehandhabt. Wenn sich jetzt zeigt, dass das Processing zu mühsam ist, können neue `div`s mit neuen `milestone`s und `anchor`s versehen werden.

**Comment by thvitt** [comment]
kann man schon machen, muss man nur wissen.

Angenommen, der Eintrag wäre so:

```xml
            <div type="diaryentry">
                <p>
                    <date when="1780-03-23"/>23 Eyersuchen der Kinder im Redoutenhause. <milestone
                        unit="testimony" spanTo="#pniower_31_end" xml:id="pniower_31"
                        next="#pniower_31_b"/><rs>Hälfte der Helena</rs> bey [*Herzogin Anna Amalia].<anchor
                        xml:id="pniower_31_end"/></p>
            </div>
            <div type="diaryentry">
              <p><date when="1780-03-23T18:00"/>23 abends In unentdecktes Ey gesetzt. Gebadet.</p>
            </div>
            <div type="diaryentry">
                <p>
                    <date when="1780-03-24"/>24 <milestone unit="testimony"
                        spanTo="#pniower_31_end_b" xml:id="pniower_31_b"/>Ordnen und auslesen <rs>abends
                    Helena andre Hälfte</rs>.<anchor xml:id="pniower_31_end_b"/></p>
            </div>
```

soll dann der mittlere Eintrag mit auf die Pniower-31-Seite?

**Comment by gerritbruening** [comment]
Ja, alles was zwischen `milestone` und `anchor` steht, würde mitkommen sollen. Bei Unterbrechungen wäre ein zweiter `milestone` vorhanden.

**Comment by thvitt** [comment]
Du hast nicht genau genug hingeguckt … da _ist_ ein zweiter Milestone.

Vereinfacht:

```xml
<div n="1"><milestone unit="testimony" xml:id="m1" next="m1_a" spanTo="m1_end"/>kram<anchor xml:id="m1_end"/></div>
<div n="2">kram außerhalb des testimony-bereichs</div>
<div n="3"><milestone xml:id="m1_a" spanTo="m1_a_end"/>kram<anchor xml:id="m1_a_end"/></div>
```

Soll `div n="2"` enthalten sein?

**Comment by gerritbruening** [comment]
Ach so, jetzt bin ich wieder bei Bewusstsein.
Trotzdem ja: `div n="2"` sollte mit enthalten sein. So wie wir ja grundsätzlich umgebenden Text mit anzeigen, obwohl er bei Gräf oder Pniower nicht wiedergegeben wird.
