### ISSUE TITLE
render transcript:m-dash as html:m-dash in reading text

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-gen-html#151]
In den Transkripten der Drucke stehen Geviertstriche, im Lesetext aber Halbgeviertstriche, was in der Synopse zu Pseudovarianten führt:

![132](https://user-images.githubusercontent.com/26788529/32103747-123f119a-bb22-11e7-8e90-e5fbbf9a0515.JPG)

**Comment by thvitt** [comment]
das hat der @gerritbruening explizit in die Zeichennormalisierung zu den ſ und den ē geschrieben …

Wenn ich's rausnehme, ist der Lesetext immernoch eine Variante (wegen des ſ). Wenn ich nichts tue und https://github.com/faustedition/faust-web/issues/283#issuecomment-292175292 implementiere, erscheint die Form mit ſ und — — in klein unter der  Form mit s und – –.

**Comment by gerritbruening** [comment]
Ach ja richtig. Das muss dann wohl wieder raus.

**Comment by thvitt** [comment]
nein, nicht notwendigerweise, siehe meinen aktualisierten Kommentar. Tatsächlich bin ich für _wontfix_ und faustedition/faust-web#283, wenn es nicht _jetzt_ zu sehr stört.

**Comment by dietmarpravida** [comment]
vorläufig wontfix ist okay mit mir (wenn man so sagen darf)

**Comment by gerritbruening** [comment]
Ich bin fein damit, auch!
