### ISSUE TITLE
empty @ hand info on f:questionedBy

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#152]
http://dev.faustedition.net/print/faust1.all#l4501

The XML has `f:questionedBy="#re_t"` but it is not displayed. Is there a mapping in the code somewhere?

**Comment by thvitt** [comment]
https://github.com/faustedition/faust-gen-html/blob/27359afac291206a65332908205b2d01389f2963/xslt/apparatus.xsl#L388-L400

**Comment by gerritbruening** [comment]
Thanks!
