### ISSUE TITLE
sp/note does not appear in text view

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#167]
Applies to
* before^_12037^_b
* before_12045_b 

Note that `sp/note` is not common.
Does not appear neither in the reading text nor in 2&nbsp;H.

**Comment by thvitt** [comment]
These have been flush right in #88 using `float: right;` -- however, they are now invisible, probably covered by something.

Should they really float to the right, i.e. usually be on the same line than the following text, or should they rather be flush-right on a line of their own?
