### ISSUE TITLE
Extra indentation of lines within indented lg

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#168]
Applies to http://dev.faustedition.net/print/C(1)4_IIIB24#l9165
1. no `lg` but part of the same `lg rend="indented" as preceding lines 9152--9164.
2. significantly indented further in comparison to the preceding lines which are also indented

In the rendering, this extra identation should be visible.

**Comment by gerritbruening** [comment]
Note that templates with `l/@rend` in `prepare-reading-text.xpl` would have to be updated, since `l/@rend` is not be ignored completely, but only if `l rend="indented"` appears as first line in an `lg`.

**Comment by gerritbruening** [comment]
I have updated the encoding. C1, C.2, C.3:

                            <lg rend="indented">
                                <l n="9152">Aufgeht mir das Herz! o, ſeht nur dahin</l>
                                ...
                                <l n="9164">Sich, gräßlich zu ſagen! mit Aſche.</l>
                                <l n="9165" rend="indented">Aber die ſchönſten</l>
                                ...

In 2 H:

                     <sp>
                        ...
                        <l n="9164">Sich, gräßlich zu ſagen! mit Aſche.</l>
                        <l n="9165" rend="indented">Aber die ſchönſten</l>
                        ...

**Comment by thvitt** [comment]
currently, there are no styling for indented `<l>` whatsoever, only for `<lg rend='indented'> → text-indent: 3em`. So do I understand the requirements correctly:

* `<lg rend='indented'>` should trigger all its descendents to be indented by at least 3 em 
* `<l rend='indented'>` …

    * should be ignored if this is the first `<l>` in an `<lg rend='indented'>`
    * should be indented by 6 em if it is in any other position inside `<lg rend='indented'>`
    * should be indented by 3 em if it does not have a parent `<lg rend='indented'>`?

**Comment by gerritbruening** [comment]
Exactly!

**Comment by gerritbruening** [comment]
Good, thanks.
I see it in 2 H, but I don't see the indentation in the prints C.1, C.2, C.3. Reopen? Or is this <s>indent</s> intended?

**Comment by thvitt** [comment]
Fixed in 2ae001665c29455e747b12c772d85552932d5d48

**Comment by gerritbruening** [comment]
Danke!
Hatte dabei etwas nicht bedacht:

**Comment by gerritbruening** [comment]
Jetzt sollte es passen.
