### ISSUE TITLE
render columnar layout as textual feature

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#17]
Some texts have columnar layout not only as a documentary, but also as a structural feature.

**Comment by thvitt** [comment]
How is this encoded in the textual transcripts?

**Comment by gerritbruening** [comment]
It is encoded with the <table> element.

There is another thing which I would rather call a list:
Halbchor
andre Hälfte}   der Studenten
Tutti.

This kind of structure is not yet encoded in any suitable way. I am going to think about that problem.

**Comment by gerritbruening** [comment]
Sehr schön, danke!Ginge zwischen der ersten und zweiten Spalte noch etwas mehr Abstand? Ich würde zu sichtbar mehr als einem Leerzeichen tendieren.Herzliche GrüßeGerritThorsten Vitt <notifications@github.com> hat am 25. September 2015 um 17:26 geschrieben:Closed #17 via c01026d.—Reply to this email directly or view it on GitHub.
