### ISSUE TITLE
scene that starts with a subscene → TOC cluttered

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#171]
[C.3 12](http://dev.faustedition.net/print/C(3)12_IIIB27) has a scene that does not have any content before the first subscene starts. Currently, the subscene's text content is used as scene heading in the toc, which is not a good idea. But what should we do instead? no scene heading? 

```xml
<div type="scene">
    <div type="subscene">
        <head n="before_4728_a" rend="centered small letter-spaced">Kaiſerliche
            Pfalz.</head>
```

**Comment by gerritbruening** [comment]
Thanks, this was a bug in the data that is now fixed in

                    <div type="scene">
                        <head n="before_4728_a" rend="centered small letter-spaced">Kaiſerliche
                            Pfalz.</head>
                        <div type="subscene">
