### ISSUE TITLE
Ambiguous rule message in prepare-reading-text because of comment()

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#172]
I get an ambiguous rule message in prepare-reading-text.xpl which seems to be caused by this change:
https://github.com/faustedition/faust-gen-html/commit/4a9ddf9c36501f901da938253418ae3e6c745ab4

> System ID: C:\Users\bruening.FDH-FFM\github\faustedition\faust-gen-html\prepare-reading-text.xpl
Scenario: prepare-reading-text
XProc file: C:\Users\bruening.FDH-FFM\github\faustedition\faust-gen-html\prepare-reading-text.xpl
Engine name: Calabash XProc
Severity: warning
Description:  Ambiguous rule match for /TEI/teiHeader[1]/profileDesc[1]/creation[1]/ge:transposeGrp[1]/comment()[1]
Matches both "comment()" on line -1 of file:/C:/Users/bruening.FDH-FFM/github/faustedition/faust-gen-html/prepare-reading-text.xpl
and "( element() | text() | comment() | processing-instruction() )" on line -1 of file:/C:/Users/bruening.FDH-FFM/github/faustedition/faust-gen-html/prepare-reading-text.xpl

What I would like to do is to exclude comments. Ideally this would work within the previous template, but if I add `| comment()` there, the transformation even fails. @thvitt , do you have an idea why this is the case?
Admittedly, I do not see to which the second part of the message refers to:
> ( element() | text() | comment() | processing-instruction() )" on line -1

**Comment by thvitt** [comment]
The `node()` rule has the same priority as the `comment()` rule as per XSLT default priorities.

Probably best to factor out the stylesheet from the pipeline to get better error messages. Also, there's a namespace warning, indicating another problem in the pipeline …

**Comment by gerritbruening** [comment]
Thanks for the quick fix!
Agree to move the templates to a separate stylesheet.
