### ISSUE TITLE
addSpan sometimes preserved in prepare-reading-text

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#173]
It is not preserved when 391098 is transformed, but it does survive when transforming 390706.

**Comment by thvitt** [comment]
have you fixed that? I don't see any addSpan in the results?

**Comment by gerritbruening** [comment]
Well, I quickly added `addSpan` to the empty template (https://github.com/faustedition/faust-gen-html/commit/46e21420594ffb23d7839d7d619177ff1a9629aa), but I find that a bit dirty because it seems `addSpan` is normally excluded by something else.

**Comment by thvitt** [comment]
Should have been dropped by this:

**Comment by gerritbruening** [comment]
Seems mysterious.
