### ISSUE TITLE
handle orig

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#179]
Basically this means `<orig>Ae</orig>` etc. --> `Ä`.
Note that in A8 and C.1 4 we only have `Ae` etc. 

@dietmarpravida, are there any cases where `Ae` should not be rendered as Ä? I remember that we discussed words of Greek or Latin origin as possible candidates (roughly in order of appearance):
- Aeolsharfe, Aeolischer
- Aether (-ische, -blau)
- Oedipus
- Aesculaps
- Aegäischen
- Aegypten
- Aeonen

None of these words appear with `Ae` etc. in HA.
AA Faust 2 (Faust I) keeps `Aeolsharfe` but has `Äther`.
FA only keeps `Aegäischen` (I do not see why, cf. 7501 ägäischen).
MA keeps all `Ae` etc.

Salvio meliore let's 
- [ ] replace `orig` with its content (irrespective whether it contains `Ae` or only `a`)
- [ ] replace `Ae` etc. (but not `ae` etc. ) by `Ä` etc.

@thvitt, is this feasible?

**Comment by dietmarpravida** [comment]
I see no reason for retaining any _Xe_'s in Faust I.

**Comment by thvitt** [comment]
These are all RE matches for `<orig>\w+</orig>` in the current version of the reading text with context:
```xml
<orig>Ue</orig>ber
<orig>Ae</orig>ste,
Flammen-<orig>Ue</orig>bermaas,
<orig>Ue</orig>bel
<orig>Ue</orig>beln
<orig>Ue</orig>brige
<orig>Ae</orig>hrenkranz.
<orig>Ue</orig>ber
<orig>Ae</orig>pfel
<orig>Ue</orig>bel
<orig>Ue</orig>berall
<orig>Ue</orig>bermaas
<orig>Oe</orig>d’
Sä<orig>a</orig>le.
D<orig>a</orig>mmernde
S<orig>a</orig>ulenschaft,
<orig>Ae</orig>ltere.
<orig>Ue</orig>bertriebne,
<orig>Ue</orig>berzeugung
<orig>Ue</orig>bermaaß
<orig>Ue</orig>berbleicht
<orig>Ue</orig>bermaaß
<orig>Ue</orig>berbleicht
<orig>Ue</orig>ber
<orig>Ae</orig>sten
<orig>Ue</orig>berschwemmung,
<orig>Ae</orig>rzte
<orig>Ue</orig>bermaß
<orig>Ue</orig>bermuth
Kr<orig>a</orig>fte;
<orig>Ue</orig>berwundne
<orig>Ae</orig>lter,
<orig>Ae</orig>ste
<orig>Ae</orig>ste
<orig>Ue</orig>b’
<orig>Ue</orig>berflüssig,
```

So I'd expect:

* `<orig>[AOU]e</orig>` → Ä
* `<orig>a</orig>` → ä?

Is that fine? Anything else? Also `[AOU]e` outside of `<orig>`?

**Comment by gerritbruening** [comment]
As I said above, orig with only a in it is to be preserved because these case need explicit emendation.

There are lots of Ae etc. outside orig, e.g. the whole of Faust I.
