### ISSUE TITLE
define header for reading text

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#182]
Following elements mandatory:

    <teiHeader>
      <fileDesc>
         <titleStmt>
            <title>Faust</title>
            <title>Eine Tragödie</title>
            <title>Konstituierter Text</title>
         </titleStmt>
         <publicationStmt>
            <p>Publication Information</p>
         </publicationStmt>
         <sourceDesc>
            <p>Information about the source</p>
         </sourceDesc>
      </fileDesc>
   </teiHeader>

**Comment by dietmarpravida** [comment]
erledigt?

**Comment by thvitt** [comment]
nein

**Comment by dietmarpravida** [comment]
siehe auch #281

**Comment by gerritbruening** [comment]
Ich habe mal ein template für einen möglichen Text-header gepusht: https://github.com/faustedition/xml/commit/9d5d56247d263eb6bbbc9a2af814830c4bc5fbe7
Aber TEI nervt:
* Es scheint nicht ohne weiteres möglich zu sein, Editionstitel und Texttitel gemeinsam unterzubringen.
* Die Formulierungen sollten sich für den digitalen und gedruckten Teil möglichst wenig unterscheiden, aber das erlaubt `titleStmt` im Grunde nicht (erst `resp`, dann `name` etc.)

Davon unabhängig müssen wir uns überlegen, ob und wo dieser Inhalt erscheinen soll. Was im Druck von uns drei als Personen verantwortet wird, sollte online nicht komplett anonym erscheinen, denke ich. Aber wir haben keinen richtigen Ort dafür.

**Comment by gerritbruening** [comment]
> Was im Druck von uns drei als Personen verantwortet wird, sollte online nicht komplett anonym erscheinen, denke ich. Aber wir haben keinen richtigen Ort dafür.

- [ ] In die Zitierempfehlung (#178) aufnehmen.
- [ ] Button Faust --> Konstituierter Text (wegen Parallelität zu "Apparat")
- [ ] http://dev.faustedition.net/print/faust Hinweis auf Responsibilities, z.B. am Rand.

**Comment by gerritbruening** [comment]
- [ ] Zitierempfehlung
- [ ] Button "Faust" --> Konstituierter Text
- [ ] Auf Seite http://dev.faustedition.net/print/faust Hinweis auf responsibilities

**Comment by gerritbruening** [comment]
@thvitt, do you know where the header template has gone?

**Comment by thvitt** [comment]
attic branch

**Comment by gerritbruening** [comment]
Hab 
![grafik](https://user-images.githubusercontent.com/10358005/46688065-b7c2e380-cbfc-11e8-898b-8bfa062ef8e2.png)
probiert um da hinzukommen. Das ist wahrscheinlich Blödsinn.
Die working copy sieht aus wie vorher.

**Comment by thvitt** [comment]
btw. `git worktree add attic attic` für unterverzeichnis attic in deiner arbeitskopie, siehe git help worktee
