### ISSUE TITLE
render text-critical notes in html

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#184]
`<note type="textcrit">` needs to be rendered.

Apparatus is probably best rendered as a margin note, see [Tufte CSS](https://edwardtufte.github.io/tufte-css/) for a beautiful CSS-only solution. We'll probably need to shift the navigation elements around, however.

**Comment by thvitt** [comment]
The essence of the stuff is

```css
.note.type-textcrit {
  float: right; 
  clear: right;
  margin-right: -60%;
  width: 50%;
}
```

Maybe put the navigation in the right as well?

**Comment by thvitt** [comment]
Feedback for the [basic rendering implemented by now](http://dev.faustedition.net/print/faust.29#act_1) is appreciated. Known issues:
* no highlighting of apparatus attachment in text
* before/after verse numbers
* witness links go to main witness, not to position in witness

**Comment by gerritbruening** [comment]
Terrific!

I would render the `[Typ ...]` in normal brackets `(...)`.
Plus, as soon as we have proper verbal descriptions for the types, it would be great to have these as tooltips.

**Comment by thvitt** [comment]
4989: Ich verstehe hier die Aufteilung nicht ganz
    4989|4990[Wenn|Wenn]{Wem|Wem} <i>4989–4990</i> Wem … Wem <i>2_H</i>] Wenn … Wenn <i>2_H :</i> Wem … Wem <i>durch Rasur</i> Wenn … Wenn <i>2_I_H.0a [type=2aa]</i>

Wird vom Skript geparst als:

1. Lemma, 2 H, 'Wem … Wem'
2. Reading, 2 H, 'Wenn … Wenn'
3. Reading, 2 H, 'Wem … Wem' durch Rasur
4. Reading, 2 I H.0a, 'Wenn … Wenn'

Korrekt?

**Comment by gerritbruening** [comment]
Ja, scheint mir richtig!

**Comment by thvitt** [comment]
I've added an em space before each rdg. For the type association, some kind of simple XML table would be helpful, e.g. `<types><type xml:id="type_4711">Nach Besprenkelung mit Kölnisch Wasser veränderte sich auf magische Weise die Handschrift</type>…</types>`. I can easily generate an initial version from, e.g., an excel table if that's easier for you.

**Comment by gerritbruening** [comment]
Looks good, thanks!

Table will follow ...

**Comment by thvitt** [comment]
I'd like to experiment with replacing the em spaces with a line break and proper indention some time, since we've probably enogh vertical space.

e.g.:

> 4989–4990 Wem … Wem] _2 H_
>   Wenn … Wenn _2 H_
>   Wem … Wem _durch Rasur 2 H_
>   Wenn … Wenn _2 I H.0a (Typ 2aa)_

**Comment by gerritbruening** [comment]
Makes sense, especially when readings are longer than single words.

**Comment by gerritbruening** [comment]
Yes, we still do not have these short phrases such as "Korrektur Ia" oder "Korrektur (sprachlich sinnlos)" or whatever.

**Comment by dietmarpravida** [comment]
Frankly, I don't want those.

**Comment by gerritbruening** [comment]
Not even as tooltip text? I do not intend to replace the type numbers by these short phrases.

**Comment by thvitt** [comment]
We need some sort of heading anyway for the categories in #279. If there are no shorter versions, I'll display those headings in the tooltip, and I refuse to implement #279 if you insist on _Typ II a_ as the sole heading of that category 👿

**Comment by dietmarpravida** [comment]
Typ 1a = Textkorrektur
Typ 1b = (Korrektur der) Zeichensetzung
Typ 1c = (Korrektur der) Typographie

Typ 2a = (Emendation einer) Störung im Grundtext
Typ 2b = (Emendation einer) Fortgesetzte(n) Störung im Grundtext 
Typ 2c = (Emendation durch) Autorvariante
Typ 2d = (Emendation einer) Fremdvariante

Typ 3 = Konjektur

Typ 4a = Konservierter Grundtext
Typ 4b = Änderung in der Druckvorlage 
Typ 4c = Konservierte Interpunktion des Grundtextes

Typ 5 = Spätere Autorvariante

Typ 6 = Postumer Eingriff

Typ 7 = Erläuterungebedürftige Stelle

Typ 8 = Typographische Besonderheit

**Comment by dietmarpravida** [comment]
#279

**Comment by dietmarpravida** [comment]
#279

**Comment by gerritbruening** [comment]
Sonst bin ich einverstanden.
