### ISSUE TITLE
Query handShift / rewrite combinations in 2 H

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#188]
> Fall 1:
> * Die zugrundeliegende Schicht ist Goethe - Bleistift.
> * Die Fixierung ist Goethe - Tinte oder Goethe - rote Tinte.
> Es soll schwarze oder rote Serifenschrift erscheinen (= Fixierung).
> 
> Fall 2:
> - Zugrundeliegende Schicht ist Goethe - Bleistift.
> - Die Fixierung ist nichteigenhändig - Tinte.
> Es soll schwarze Schrift [Serifenschrift oder Serifenlose?] mit grauem Schatten benutzt werden.
> 
> Fall 3:
> - Die zugrundeliegende Schicht ist nichteigenhändig Bleistift.
> - Die Fixierung ist Goethe - Tinte.
> Es soll schwarze Serifenschrift erscheinen (= Fixierung).

**Comment by gerritbruening** [comment]
Fall 1:
`//text()[preceding::tei:handShift[1][@new="#g_bl"] and ancestor::ge:rewrite[@hand[contains(.,"#g_t")]]]`

@thvitt , könntest du mir helfen, die Abfragen zu komplettieren?

**Comment by gerritbruening** [comment]
Fall 2 müsste wahrscheinlich `//text()[preceding::tei:handShift[1][@new="#g_bl"] and ancestor::ge:rewrite[not(@hand[contains(.,"#g_t")])]]` sein.

**Comment by thvitt** [comment]
Der Logik nach müsste Fall 3 `//ge:rewrite[contains(@hand,'#g_t')]//text()[preceding:tei:handShift[1][contains(@new, '_bl') and not(contains(@new,  '#g_'))]]` sein.

Ist bei den Handangaben immer an das führende `#` gedacht worden?

**Comment by gerritbruening** [comment]
Danke!
> Ist bei den Handangaben immer an das führende # gedacht worden?

Ja, das sollte der Fall sein, könnten wir aber mal mit `not(contains(@new, '#'))` abfragen.

Wäre es jetzt möglich, die betreffenden Textknoten

**Comment by thvitt** [comment]
[ZIP-Datei mit Ergebnissen und produzierendem XSLT: issue188.zip](https://github.com/faustedition/faust-gen-html/files/1657695/issue188.zip)
(XSLT ausführen mit saxon -xsl:issue188.xml -it start path=/path/to/folder)

**Comment by gerritbruening** [comment]
Danke, das ist ideal!
Ich hatte aber etwas vergessen: könntest du noch `rdg` content ignorieren?

So gibt es nämlich zwei Falschtreffer, durch die DR in Verwirrung geführt werden könnte:

    2 | 0363 | Hier | #g_bl | #jo_t

    2 | 0363 | mit freyem Volke | #g_bl | #jo_t

Sonst dürfte er mit der Tabelle wahrscheinlich perfekt arbeiten können.

**Comment by thvitt** [comment]
Ging nur um Kontrolle seitens DR? Dann mach ich das zu hier

**Comment by gerritbruening** [comment]
Ja, bislang.
Ob es dann auch entsprechende Wünsche für die online-Edition geben wird, werden wir sehen.

**Comment by gerritbruening** [comment]
Ich würde jetzt gern noch etwas anderes abfragen:
* nichteigenhändiger mit Bleistift geschriebender Text, also `//text()[preceding::tei:handShift[1][@new[contains(.,"_bl")] and not(@new[contains(.,"#g_")])]` oder so ähnlich
* mit nichteigenhändiger Tinte fixiert, also, in Bezug auf denselben `text()`: `ancestor::ge:rewrite[@hand[contains(.,"_t")] and not(@hand[contains(.,"#g_")])]`  oder so ähnlich

**Comment by thvitt** [comment]
[letzte Tabelle](https://github.com/faustedition/faust-gen-html/files/2222353/issue188.zip)

- da ist zeug drin das nach kommentar aussieht‽
- whitespace-only-text hab ich rausgenommen
- dein Pattern matcht auch auf blau, hab ich korrigiert

**Comment by gerritbruening** [comment]
Vielen Dank!
1. Es werden auch Textknoten ausgegeben, die gar kein rewrite haben? So sieht es auf den ersten Blick aus.
2. Ich könnte 1. leichter prüfen, wenn ich den Inhalt der `ge:line` hätte, so wie das bei der ersten Tabelle der Fall ist.

**Comment by thvitt** [comment]
1. ja, in deinem 1. bullet point steht nix von rewrites, das müsstest du noch näher spezifizieren. Wenn auch der 2. Bullet-Point zutrifft, hat die Tabelle mehr Spalten.

**Comment by gerritbruening** [comment]
Ach so, die beiden bullet points hatte ich als **und**-Beziehung gedacht, sorry for the confusion. Gesucht wird also `text()`, für den beides gilt.  Hatte es nicht hingebracht, dass in einen XPath-Ausdruck zu packen.

**Comment by gerritbruening** [comment]
Verspätet danke! Das wird DR so ohne Probleme umsetzen können.

**Comment by thvitt** [comment]
Da DR ja hat … falls jemand nochmal das Skript braucht, muß dort `f:st` nachgezogen werden (nach mod)
