### ISSUE TITLE
Display search results from reading text at the top

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#189]
It seems to be quite common that users navigate by means of the search, thus evading the need to find their path through the subpages.
So if they want to navigate to the "Nacht" scene, they may type `habe nun` in the search slot.
However, the Lesetext hits are hidden far below, especially when users do not search for `"habe nun"`.
Maybe we make this easier by displaying hits from the Lesetext at the top?

**Comment by thvitt** [comment]
ist schon länger umgesetzt (ece3e35abfc709d50a108ccae62a7c676b8397d7 ?)

**Comment by gerritbruening** [comment]
Ja, scheint so
