### ISSUE TITLE
duplicate app entries

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#191]
Example:
```xml
            <sp>
                <speaker n="before_3422i">Faust.</speaker>
                <l n="3422" part="I">
     <seg type="lem" xml:id="lem.3422.muß">Muß</seg> man?<note type="textcrit">
        <ref>3422</ref>
        <app from="#lem.3422.muß">
           <lem wit="faust://document/faustedition/A faust://document/faustedition/B faust://document/faustedition/B.a">Muß</lem>
           <rdg wit="faust://document/faustedition/1_H.5">Muss</rdg>
           <rdg wit="faust://document/faustedition/S">Muß <note>[type=2a⌐] (entfallene Sperrung)</note>
           </rdg>
        </app>
     </note>
  </l>
            </sp>
            <sp>
                <speaker n="before_3422f">Margarete.</speaker>
                <l n="3422" part="F">Ach! wenn ich etwas auf dich könnte!<note type="textcrit">
        <ref>3422</ref>
        <app from="#lem.3422.muß">
           <lem wit="faust://document/faustedition/A faust://document/faustedition/B faust://document/faustedition/B.a">Muß</lem>
           <rdg wit="faust://document/faustedition/1_H.5">Muss</rdg>
           <rdg wit="faust://document/faustedition/S">Muß <note>[type=2a⌐] (entfallene Sperrung)</note>
           </rdg>
        </app>
     </note>
  </l>
    <l n="3423">Du ehrst auch nicht die heil’gen Sacramente.</l>
</sp>
```
Here, the app should only be in the first part. Cf. #119

**Comment by thvitt** [comment]
Duplicate app entries can appear in these cases:

1. Antilabes. There are multiple lines with the same `n`, each containing an app, but only one contains a matching `<seg>`. The duplication appears since we generate the app note at the line level, not immediately after the seg, in order to generate apparatus which don't correspond to a part of the pattern matching verbatim. Solution: either remove all instances which don't have a seg in their own parent, but for which a seg exists in the document, or move the app generation to the seg, losing all dangling apparatus entries (which shouldn't be anyway). Example at [813](http://dev.faustedition.net/print/faust.5#l813)
2. An app with contains multiple f:ins. This will create multiple apps which _appear_ duplicate, but have different `@from` values. We would want one apparatus notes with multiple `@from` values instead. Example at [4989-90](http://dev.faustedition.net/print/faust.29#l4989)
3. A replacement occuring multiple times. Example at [2092](http://dev.faustedition.net/print/faust.8#l2092), if this is really intended this way. We need to adjust the seg's xml:ids since they may not be duplicate.

**Comment by dietmarpravida** [comment]
fixed 2092
