### ISSUE TITLE
Umbruch in längeren BA zentr.

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#193]
@pglatza
> Die Textpassagen „In einem hochgewölbten, engen, gothischen Zimmer“ und „Faust unruhig auf seinem Sessel am Pulte.“ sind in XML in einem `stage`-Element, nur von einem Komma getrennt. Doch im InDesign-Template wurden daraus zwei Absätze.

**Comment by gerritbruening** [comment]
Der Umbruch in diesen BA gehört wohl zum Feinsatz.

Wichtig wäre, dass der Abstand zwischen den Absätzen geringer ist als der Abstand zwischen zwei aufeinanderfolgenden BA (für den Fall dass das vorkommt, siehe https://github.com/faustedition/xml/issues/219).

**Comment by gerritbruening** [comment]
@pglatza, brauchen wir da ein neues Absatzformat wie `BA neue Zeile` oder tut es da auch `BA zentr. 0,0`? Frage wäre wohl an Markus zu richten, den ich aber noch nicht assignen kann.

**Comment by markusciupke** [comment]
Vgl. meinen Kommentar in #251.

**Comment by gerritbruening** [comment]
> Wenn ihr den Umbruch der BAs schon in XML festlegt, bekomme ich hier zwei Absätze.

Das tun wir nicht.
Es kann lediglich sein, dass aus einer BA in den Daten zwei Absätze werden, weil eine Quasi-Replik vorliegt (#239).
