### ISSUE TITLE
Ellipsis in text: insert blank before it, insert u+202f between dots

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#196]
* `<g>..</g>`
* `<g>...</g>`
* `<g>....</g>`

Example for desired transformation:

    wissenswürdig<g>...</g>
    -->
    wissenswürdig <g>.&#8239;.&#8239;.</g>

**Comment by gerritbruening** [comment]
Ich schaue mal in der MA nach, wie die `..` zu vorhergehender Interpunktion spationiert werden.

**Comment by thvitt** [comment]
* Soll das Ersetzungszeichen nicht lieber … sein, also die Ellipse aus der Schrift?
* steht immer ein `<g>` drumherum?
* Was für'n Leerzeichen soll da hin? Geschütztes normales? 
* m.W. ist die moderne typographische Regel: Ersetzt's ein Wort (oder mehr), Abstand davor, ersetzt's einen Wortteil, dann nicht.

**Comment by gerritbruening** [comment]
> * Soll das Ersetzungszeichen nicht lieber … sein, also die Ellipse aus der Schrift?

Es gibt dummerweise auch zwei und vier Auslassungspunkte (s.o.), sonst natürlich ja.
> * steht immer ein `<g>` drumherum?

Nach meiner Prüfung ja.
> * Was für'n Leerzeichen soll da hin? Geschütztes normales? 

Davor? Sollte egal sein, aber wir können gern ein geschütztes nehmen. Sollte online keinen Unterschied machen, weil selbst bei starkem Zoom des Browsers die Zeilen nicht umgebrochen werden, oder?
> * m.W. ist die moderne typographische Regel: Ersetzt's ein Wort (oder mehr), Abstand davor, ersetzt's einen Wortteil, dann nicht. Dieser zweite Fall kommt nicht oder nicht mit `<g>` vor?

Ja, so kenne ich die Regel auch. Und meines Wissens haben wir kein `F<g>...</g>` oder so.

**Comment by thvitt** [comment]
ah, ich hatte es so verstanden, als ob aus .., ... und .... im Lesetext immer … werden soll, aber dem ist nicht so, ok.

**Comment by gerritbruening** [comment]
Ah, sorry, das hatte ich so deutlich nicht gesagt.

**Comment by gerritbruening** [comment]
Danke für den Fix!
Wie findest du's?

**Comment by thvitt** [comment]
da ist immernoch teils irgendein Leerzeichen zuviel, z.B. [Revier  . . .](http://dev.faustedition.net/print/faust.29#l6027) 😿

**Comment by gerritbruening** [comment]
Ja, ich sehs. Kann es übrigens sein, dass der narrow space in Ubuntu nicht vorhanden ist und durch einen anderen Font ersetzt wird? Für mich sieht es ein bisschen so aus, als sei der Unterschied zum normalen Leerzeichen nicht so groß.

**Comment by thvitt** [comment]
tatsächlich ist es nicht da. K.A. wie das Fontrendering das macht, ein kurzer Test in Inkscape legt nahe, dass es zumindest auf meinem System auch mit korrekt ist.

Könnte's natürlich hinzuzufügen. Nur: Wie breit soll's denn sein? Unicode ist uneindeutig (“a narrow form of a no-break space, typically the width of a thin space or a mid space“ mit thin space = ⅕em oder ⅙em und mid-space ein ganz normales Viertelgeviertleerzeichen). Kurze Stichprobe auf meinem Rechner legt nahe, dass NARROW NO-BREAK SPACE i.d.R. bei einem Achtelgeviert ist und zwischen thin (scheint ⅙ zu sein) und hair space liegt.

**Comment by gerritbruening** [comment]
Ja, an ein Achtelgeviert hatte ich so in etwa gedacht. Da muss man online wohl mit Schriftgröße basteln?

**Comment by thvitt** [comment]
Nein. Wir haben ja eh schon unsere eigene Ubuntu-Variante mit 〈〉 und m̄ und so, da können wir auch ein NARROW NO-BREAK SPACE in Achtelgeviertbreite einbauen.

**Comment by thvitt** [comment]
use thinsp, cf. #325
