### ISSUE TITLE
Blocksatz in BA

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#201]
Automatische Zuweisung von 'BA Blocks. 0,0' fraglich.

@pglatza:
> Unter welchen reproduzierbaren Bedingungen muss dieses Absatzformat zugewiesen werden? Ausgezeichnete Textstelle im InDesign-Template: „Auf einem niedrigen Herde steht ein großer Kessel über dem Feuer“

**Comment by gerritbruening** [comment]
@pglatza, ist das damit geklärt? Sonst einfach kommentieren.

**Comment by pglatza** [comment]
Ja, das reicht mir. Danke.
