### ISSUE TITLE
Sprecher 0,5 und BA zentr. 0,5 bei Antilaben

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#203]
@pglatza:
> Gibt es ein System für die Anwendung des Absatzformates 'Sprecher 0,5'? Bspw. immer dann, wenn der vorangegangene Vers mit einem En-Dash oder einem Frage-/Ausrufezeichen endet?

**Comment by gerritbruening** [comment]
Hierzu gibt es folgende Erklärung:
> Sprecher haben grundsätzlich einen Abstand von 1,5 mm nach oben (exakt 1,552 mm = 4,4 pt = 1/3 Zeile). Sprecher 0,5 (exakt 0,582 mm = 1,65 pt = 1/8
Zeile) habe ich dort eingesetzt, wo bei einer Antilabe der voranstehende Versteil nicht über den Sprecher ragt (also meistens), so dass ein Abstand von 1,5 mm nach oben unverhältnismäßig groß erscheinen würde (siehe vor allem die Szene »Ein Gartenhäuschen«, S. 48-49).
Ansonsten ist der Abstand 1,5 mm nach oben auch bei Bühnenanweisungen eingesetzt, wenn hier ein Abstand nach oben da sein muss (z.B. vor 243, vor
4613 und nach 4665). Vor allem aber erscheint er bei Figurenreden mit Regieanweisung.
Das Format BA Blocks. 1,5 kommt in meiner Beispieldatei nicht vor.
Das Format BA zentr. 0,5 kommt bislang nur einmal vor (in Vers 3205 wegen der Antilabe).

**Comment by gerritbruening** [comment]
@pglatza, lässt sich das automatisieren? Lohnen würde es sich evtl.:

> wo bei einer Antilabe der voranstehende Versteil nicht über den Sprecher ragt (also meistens)

Wenn ja, müsste man Markus fragen, wieviel kürzer der Vers sein muss im Verhältnis zum Anfang der Sprecherbezeichnung, z.B.

    Das ist doch nicht die
                           SPRECHER
                          Möglichkeit!

Oder ob der Vers gar nicht kürzer sein muss.
Sonst Feinsatz.

**Comment by pglatza** [comment]
Das ist abhängig von der Breite der einzelnen Schriftzeichen des Verses und Sprechers.

Doch ja, wir können Berechnungen für das Zuweisen des Formates einsetzen.
Müssten eben eine goldene Mitte finden (z.B. Vers < 20 Zeichen UND Sprecher nicht größer als 10 Zeichen, etc.)

**Comment by markusciupke** [comment]
Tatsächlich sollte der obere Vers nicht nur nicht über den Sprecher ragen, sondern bereits vor dem Sprecher enden. Vorschlag: drei Geviert (= ca. 6,5 mm). So haben wir eine Regel für ein definiertes Phänomen, das ich für ästhetisch vorteilhaft halte. – Wenn das nicht automatisiert werden kann, mache ich das im Feinsatz.

**Comment by dietmarpravida** [comment]
Sprecher sollten grundsätzlich einen Abstand von 1,5 mm nach oben haben (gerne auch mehr), komme was da wolle.

**Comment by gerritbruening** [comment]
Mit welchem Entwurf hielt das 0,5 Format Einzug? Können wir uns mal den vorherigen Zustand zum Vergleich ansehen?

**Comment by markusciupke** [comment]
Ich weiß es nicht mehr. – Hier kommt die Szene auf Doppelseiten im direkten Vergleich. Es ist kaum zu erkennen, macht aber auf die ganze Seite eine Zeile aus. Und auch, wenn man es kaum erkennen und also bewusst wahrnehmen kann, bin ich überzeugt davon, dass der Zusammenhang der geteilten Verse mit dem verringerten Abstand unbewusst besser wahrnehmbar ist und damit der Lesefreundlichkeit dient. Und darum geht es für mich bei einer Leseausgabe. Mein Anspruch als Setzer ist, dem Leser zu dienen und nicht einem System, das nicht berücksichtigt, wie Feinheiten auf den Menschen wirken. – Letztlich bleibt die Entscheidung bei den Herausgebern und Bearbeitern.
[Gartenhäuschen Test.pdf](https://github.com/faustedition/faust-gen-html/files/1693375/Gartenhauschen.Test.pdf)

**Comment by pglatza** [comment]
Ich würde mich auf das Zählen von Zeichen konzentrieren. Aktuell setze ich just 20 Zeichen als Grenze an. Wenn im vorangegangenen Absatz weniger als 20 Zeichen stehen, dann wird das Format 'Sprecher 0,5' angewendet. Andernfalls 'Sprecher 1,5'.

Mit Werten wie "drei Geviert (= ca. 6,5 mm)" kann ich aktuell noch nichts anfangen. So weit ist unsere IDML-Synthese noch nicht. Sprich, in Abhängigkeit der verwendeten Unicode-Zeichen die Breite der einzelnen Lettern bzw. eines Schriftbildes zu berechnen.

**Comment by gerritbruening** [comment]
Danke!
Ich nenne mal die Gesichtspunkte, die hier eine potentiell Rolle spielen:
- Orientierung an der Überlieferung
- Orientierung am XML
- konsistentes Verhältnis von Formatvergaben zu Textmerkmalen
- Minimierung von händischen Eingriffen
- bestehende Konventionen des Dramensatzes
- Übereinstimmung mit den prozeduralen Prinzipien der digitalen Ausgabe
- ästhetische Vorlieben
- Leserfreundlichkeit

**Comment by gerritbruening** [comment]
Momentan scheint mir die Konsistenz in der 
Behandlung aller BA und Auftrittsbezeichnungen vorrangig, unabhängig von etwaigen Antilaben. Dazu gibt es eine Reihe von Issues, die ich erstmal klären würde.

**Comment by gerritbruening** [comment]
@markusciupke:
> Vom Sprecher 0,5 und der BA 0,5 für Antilaben habe ich mich verabschiedet. Alle Sprecher und BAs mit Auftritt oder Figur und nachfolgendem Sprechtext haben einen Abstand nach oben von 1,5.
