### ISSUE TITLE
Verkürzte Siglen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#205]
> Apparat (`note[@type='textcrit']`): Siglen in "druckbarer Form" in `<wit>`-Elemente, hier bräucht ich noch Mappingregeln, wenn die Siglen irgendwie verkürzt werden sollen

**Comment by gerritbruening** [comment]
Hier eine erste Mapping-Tabelle:
[siglen-mapping.docx](https://github.com/faustedition/faust-gen-html/files/1673407/siglen-mapping.docx)

C.2alpha kommt hier nicht vor, da muss ich mal in den errors nach schauen.

**Comment by thvitt** [comment]
Ihr mit euren Hochstellungen wieder. Das distinktive soll also ganz klein in die Ecke 😈 
- führende arabische Ziffer weg
- Dann schreib ich für `2 III H.3a:2` → `<wit>III H<hi rend="superscript">3a:2</hi></wit>` in den Apparat und überlass den Rest @pglatza

**Comment by gerritbruening** [comment]
Ich weiß ...

Ja, ich denke `<hi rend="superscript">` ist das beste.
