### ISSUE TITLE
Einrückung bei Antilaben

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#207]
> Bei den Antilaben wäre es ideal, die Länge des vorherigen Versteils zu 
> ermitteln und dann entsprechend einzurücken oder diesen als Text mit 
> der Schriftfarbe Weiß einzufügen o.ä.

@pglatza, wäre es evtl. möglich, die Dickten der vorhergehenden `//l[@part]`-Zeilen zusammenzuzählen? Das schiene mir im Grundsatz etwas seriöser.
Detailzusatzregel: Wenn vorhergehende `//l`-Textknoten mit n-dash enden (485), wird der folgende `//l[@part]` um ein Leerzeichen mehr eingerückt.

**Comment by pglatza** [comment]
Ja, daran habe ich auch schon gedacht.
Mir fallen dabei zwei Vorgehensweisen ein, die eingerückte Darstellung in InDesign zu erreichen:

- Die vorangegangenen `l[@part]` wiederholen und mit transparenter Farbe auszeichnen. Das hat den Vorteil, dass im PDF dann dieser Text nicht auffindbar ist. Also anstelle weißer Farbe, wie bis jetzt vorgeschlagen.
- Mit Tabulatoren der Art 'Einrückung bis hierher' im vorangegangenen Absatz arbeiten und Tabs in der aktuellen Verszeile setzen.

Hierzu möchte ich noch Feedback vom InDesign-Umbruch einholen.

**Comment by gerritbruening** [comment]
Schiene mir beides plausibel.

**Comment by markusciupke** [comment]
Die erste Variante finde ich praktikabel. Bei der zweiten weiß ich nicht wie das technisch geht. Bislang habe ich manuell eine Hilfslinie ans Ende der vorangehenden Zeile gezogen und dann einen Tab auf die Hilfslinie gesetzt. Das ist aber umständlich und zeitaufwendig.

**Comment by markusciupke** [comment]
Das mit der transparenten Schrift kannte ich bislang nicht. Vor allem, dass der Text dann nicht im PDF auffindbar ist. Vielen Dank. Hab ich schon umgesetzt und funktioniert wie es soll.

**Comment by gerritbruening** [comment]
@pglatza, ich habe gerade das Transformationsergebnis angeschaut und gesehen, dass das im Prinzip umgesetzt ist.

Mir sind lediglich Einzelfälle vorgekommen, wo ein Leerzeichen am Ende steht, das da m.E. nicht hingehört, z.B. `du?_` in

            <ZF_Antilabe_transparent AppliedCharacterStyle="CharacterStyle/Antilabe transparent">
               <Content>Was thust denn du? </Content>
            </ZF_Antilabe_transparent>

Je nachdem, was du vorziehst, können wir das Issue hier closen und für die Einzelprobleme neue aufmachen oder das hier offen lassen.

**Comment by pglatza** [comment]
Ich habe mich für den kürzesten Weg entschieden: ich normalisiere das bei der IDML-Synthese. Ist in Rev 19.
