### ISSUE TITLE
Satzspiegel

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#209]
Meine Anmerkung:
> Das Ziel, eingerückte Verse in der Tendenz "auf Mitte" zu setzen, 
> würde ich grundsätzlich teilen, aber die jetzt sehr weite Einrückung 
> macht, dass sie stark herausstechen. Von mir aus sollten sie ruhig 
> etwas weiter links beginnen als die darüberstehende Sprecherbezeichnung.

MCs Antwort:
>  Wo nun alles auf Zentrierung angelegt ist, muss man die eingerückten Verse auf optische Mitte bezogen auf die Sprecher und die Kolumnenzeilen setzen.

**Comment by gerritbruening** [comment]
Das sehe ich ein, wir sollten daher nochmal über den Satzspiegel nachdenken. 
Ist es nicht erträglicher, im dritten Akt einige umbrochene Tetrameter zu haben, wenn dafür die Verhältnisse im allgemeinen erträglicher sind? So ließe sich beides mildern, die Linkslastigkeit der Verse und die Weite der Einrückung.

**Comment by markusciupke** [comment]
Ich werde bei Gelegenheit noch mal Probe-Layouts machen. 
Da die Linkslastigkeit des gesamten Textes durchgehend das Gesamtbild beeinträchtigt, überlange und daher zu umbrechende Verse dagegen seltener sind, halte ich einen schmaleren Satzspiegel für wünschenswert.
Eine weitere Möglichkeit ist die von mir schon zu Beginn vorgeschlagene Einrückung der Sprecher um ca. 20 mm. Das würde für sehr viele Verse des Dramas zu einer ungefähren Zentrierung der Sprecher zum Vers führen und den Umbruch der langen Verse vermeiden. 
Für ein solches Vorgehen kenne ich kein Vorbild. Das muss aber kein Argument dagegen sein. Man kann ja auch mal innovativ sein, wenn es zu etwas Gutem führt.
Eine dritte Möglichkeit ist größere Schrift, dann aber müsste man auch den Durchschuss erhöhen, und dann kommen wir auf wesentlich mehr Seiten.
Vielleicht ist das auch eine Frage an die drei Herausgeber?

**Comment by gerritbruening** [comment]
>  Vielleicht ist das auch eine Frage an die drei Herausgeber?

Ich denke, den Herausgebern müsste eine vertretbare Lösung präsentiert werden. Eine "man könnte, man könnte aber auch"-Alternative scheint mir wenig hilfreich.
Bei Gelegenheit würde ich den kleineren Satzspiegel mal sehen wollen.

**Comment by markusciupke** [comment]
> Ich denke, den Herausgebern müsste eine vertretbare Lösung präsentiert werden. Eine "man könnte, man könnte aber auch"-Alternative scheint mir wenig hilfreich. 

Das sehe ich auch so. Aber ich habe nur von einem schmaleren Satzspiegel geschrieben, nicht von einem kürzeren. Ein kürzerer Satzspiegel würde uns beim WNT auch nicht helfen, weil zu viele Zeilen fehlen, bei der Zueignung würde er aber schaden.

> Bei Gelegenheit würde ich den kleineren Satzspiegel mal sehen wollen.

Das mache ich noch.

**Comment by gerritbruening** [comment]
> Ein kürzerer Satzspiegel würde uns beim WNT auch nicht helfen, weil zu viele Zeilen fehlen, 

Dann bliebe noch, weniger Repliken auf eine Seite zu setzen (Umbruch / Durchschuss).

Auch die Zueignung muss m.E. nicht mehr als drei Zeilen abgesenkt werden.

**Comment by markusciupke** [comment]
Wollen wir das nicht testen, wenn der Apparat mit den 8 Versen in 2 Strophen dabei ist? Wie sollen die überhaupt gesetzt werden? Fortlaufend und durch Virgeln abgetrennt? In Versen mit Verszähler? – Jedenfalls kann man den Herausgebern erst dann eine definitive Lösung anbieten.

> Auch die Zueignung muss m.E. nicht mehr als drei Zeilen abgesenkt werden.

Die Verse der Zueignung sollen auch nur um 3 Zeilen abgesenkt werden. Das würde ich bei der Strophe des Theatermeisters genauso machen wollen.

**Comment by gerritbruening** [comment]
Gut!
> Wollen wir das nicht testen, wenn der Apparat mit den 8 Versen in 2 Strophen dabei ist? 

Ja
> Wie sollen die überhaupt gesetzt werden? Fortlaufend und durch Virgeln abgetrennt? In Versen mit Verszähler? – 

Siehe https://github.com/faustedition/faust-gen-html/issues/276#issuecomment-364256223

**Comment by gerritbruening** [comment]
@markusciupke schrieb andernorts (https://github.com/faustedition/faust-gen-html/issues/327#issuecomment-383039201):

> Hierzu auch (eigentlich ein eigenes Issue, aber wie immer hängt alles mit allem zusammen): da kurz zuvor von Vers 9582 bis 9628 Trochäische Tetrameter vorkommen, habe ich hier den breiten Satzspiegel genommen. Von 9992 bis 10038 kommen dann die nächsten Langverse. Wenn ich euch richtig verstehe, ist ja der Wunsch, in Teilen des Dritten und Vierten Aktes den breiten Satzspiegel zu nehmen. Wie soll das konkret aussehen? Immer ganze Szenen oder nur Doppelseiten auf denen Langverse vorkommen? Wenn letzteres der Fall ist, muss ich auf diesen Seiten hier den schmalen Satzspiegel nehmen (beachtet hier auch vor 9695):
[Faust 390-391 MC 5.pdf](https://github.com/faustedition/faust-gen-html/files/1931227/Faust.390-391.MC.5.pdf)
[Faust 390-391 MC 6.pdf](https://github.com/faustedition/faust-gen-html/files/1931228/Faust.390-391.MC.6.pdf)
[Faust 390-391 MC 7.pdf](https://github.com/faustedition/faust-gen-html/files/1931229/Faust.390-391.MC.7.pdf)
[Faust 390-391 MC 8.pdf](https://github.com/faustedition/faust-gen-html/files/1931230/Faust.390-391.MC.8.pdf)
Ich habe mal geschaut, welche und wieviele Verse im Zweiten Teil durch den schmalen Satzspiegel einen Zeilenumbruch erhalten und wieviele Zeilenumbrüche davon sich durch eine leicht engere Laufweite vermeiden lassen:
8531: 1 Fall; lässt sich vermeiden.
8909-9126 auf ca. 5 Doppelseiten: 16 Fälle; lässt sich in 5 Fällen vermeiden, es bleiben 11.
9582-9628 auf ca. 2 Doppelseiten: 22 Fälle; lässt sich in 9 Fällen vermeiden, es bleiben 13.
9992-10038 auf ca. 2 Doppelseiten 23 Fälle; lässt sich in 7 Fällen vermeiden, es bleiben 16.
10849-11042 auf ca. 4 Doppelseiten: 3 Fälle (10890, 10892, 10922); lassen sich alle vermeiden.
8531 erledigt sich Im breiten Satzspiegel.
In 8909-9126 bleiben 2, von denen sich aber 1 vermeiden lässt. Es bleibt 8959.
In 9582-9628 bleiben 3, von denen sich aber 1 vermeiden lässt. Es bleiben 9599 und 9623.
In 9992-10038 bleiben 5, von denen sich aber 3 vermeiden lässt. Es bleiben 9994 und 10029.
10849-11042 erledigen sich Im breiten Satzspiegel.
Durch den breiten Satzspiegel lassen sich also insgesamt 35 von 40 unerwünschten Zeilenumbrüchen vermeiden. Ich würde vorschlagen nur die betreffenden Doppelseiten ausnahmsweise mit dem breiten Satzspiegel auszustatten. Wenn ihr das so entscheidet, sind oben die Varianten 5 bis 8 die relevanten.
Im Ersten Teil taucht das Problem nur 1 mal auf (1147), lässt sich aber durch leicht engere Laufweite vermeiden.

**Comment by markusciupke** [comment]
Der letzte Stand ist: Schmaler Satzspiegel (94 mm), außer für Doppelseiten mit Langversen (104 mm):
8909-9126 auf ca. 5 Doppelseiten: Es bleibt 8959.
9582-9628 auf ca. 2 Doppelseiten: Es bleiben 9599 und 9623.
9992-10038 auf ca. 2 Doppelseiten: Es bleiben 9994 und 10029.
(Diese Angaben sind ohne Gewähr.)
Von meiner Seite her kann dieses Issue geschlossen werden.

**Comment by gerritbruening** [comment]
Wenn noch schmaler keine gute Option ist, close ich das hier.
