### ISSUE TITLE
Absenkung

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#210]
Betrifft folgende Seiten:
* Zueignung
* Vorspiel
* Prolog
* Walpurgisnachtstraum
* Akte
* Szenen

Auf diesen Seiten entfällt die Kolumnenzeile.

XML:
* `div/div[@type="scene"]/head[1]` außer
  * die `div[@type="scene"]/head` wo die `div` die erste `div` innerhalb von `div[@type="act"]` ist (weil da die `div[@type="act"]/head` die Absenkung bekommt)
  * head n="before_4223_a" (https://github.com/faustedition/faust-gen-html/issues/246#issuecomment-362438121)

**Comment by markusciupke** [comment]
Absenkung betrifft folgende Formate:
• Titel --> 7 LZ
• Der Tragödie erster Teil --> 7 LZ
• Der Tragödie zweiter Teil --> 7 LZ
• Teil/Akt --> 5 LZ  (Zueignung, Vorspiel, Prolog, Walpurgisnachtstraum, 1. bis 5. Akt)
• BA zentr. 0,0 nach Teil --> 5 LZ (nach Vorspiel und Prolog)
• Vers nach Teil --> 3 LZ (nach Zueignung)
• Szene nach Teil --> 3 LZ (nach Der Tragödie erster Teil)
• Szene --> 3 LZ

Frage:
• Theatermeister (neues einmaliges Format auf neuer rechter Seite) --> 3 LZ wie nach Zueignung oder 5 LZ wie nach Vorspiel und Prolog?

Weitere Frage: Trüber Tag. Feld auf neuer Seite oder auf neuer rechter Seite, weil der WNT ein eigener in sich geschlossener Teil (Intermezzo) ist? Die Frage ist relevant, da der WNT mit Apparat auf einer rechten Seite enden wird.

**Comment by gerritbruening** [comment]
Anstelle von 
>  BA zentr. 0,0 nach Teil --> 5 LZ (nach Vorspiel und Prolog)

würde ich 3 Leerzeilen sagen.
Ich erinnere mich noch an den Anfangs bestechenden Grund (Platz für virtuelle Szenenüberschrift, Göttingen mdl.), aber das scheint mir nicht klug zu sein. In A gibt es solche Räume für virtuelle Elemente nicht, und es gibt keinen Grund, sie editorisch zu suggerieren. Deswegen würde ich von diesem Einfall wieder abrücken.

**Comment by gerritbruening** [comment]
Ich glaube, mir ist grundsätzlich das Prinzip hinter der Absenkung nicht klar.
Ich sehe zwei Arten von (möglichen) Kriterien:
* Position in der Hierarchie (hohe Position --> starke Absenkung, in diese Richtung scheint mir @markusciupke|s https://github.com/faustedition/faust-gen-html/issues/262#issuecomment-363935339 zu gehen)
* Titelseite mit dafür typischer Position der Titelzeilen, d.h.:
  * weiter unten als der Schmutztitel, weiter oben als seinerzeit die Titelzeilen in A
  * Position abhängig von der Anzahl der Titelzeilen (die eine Zeile der Zueignung beginnt weiter unten als die zwei Zeilen des Vorspiels)
* Abschnittsbeginn des Textes (meist, aber nicht immer mit Überschriften)

**Comment by markusciupke** [comment]
Einverstanden! Und lasst uns doch bei 7 Zeilen für den Titel »Faust / Eine Tragödie« bleiben.

**Comment by gerritbruening** [comment]
> Und lasst uns doch bei 7 Zeilen für den Titel »Faust / Eine Tragödie« bleiben

Gut, einverstanden!

**Comment by pglatza** [comment]
Habe die Absenkung nun so bei der IDML-Synthese umgesetzt.
