### ISSUE TITLE
Apparateinträge

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#211]
Aus den Apparateinträge (`note type="textcrit"`) werden fußnotenartige Konstrukte ohne Fußnotenziffern werden, so dass diese bei veränderten Seitenumbrüchen beim Feinsatz automatisch mitverschoben werden.
@pglatza, darüber hatte ich mich mit @gimsieke anfänglich ausgetauscht.

**Comment by gerritbruening** [comment]
- [ ] Zeilenreferenz
- [ ] Zeichenformat für Lemmaklammer
- [ ] vergrößerte Abstände zwischen Siglen und folgender Lesart
- [ ] variable Abstände zwischen Siglen und folgender Lesart bei zeilenfüllende Apparateinträgen?
- [ ] Ersatz für Caret (Tiefstellung möglich?)

**Comment by dietmarpravida** [comment]
weiteres Sonderproblem: Einträge, die bloß aus Editortext bestehen.

**Comment by gerritbruening** [comment]
Danke, ist oben unter die 
> Sonderprobleme

aufgenommen.

**Comment by pglatza** [comment]
Ja, textkritische Noten können wir bei der IDML-Synthese als Fußnoten umsetzen.
Zu den Kindelementen bräuchte ich noch genauere Anweisungen (ignorieren, darstellen/mappen).

**Comment by gerritbruening** [comment]
> Zu den Kindelementen bräuchte ich noch genauere Anweisungen (ignorieren, darstellen/mappen).

Ist geschehen: https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#apparateintr%C3%A4ge.

**Comment by gerritbruening** [comment]
Für den Rest habe ich eigen Issues angelegt.

**Comment by gerritbruening** [comment]
Ich reopen das hier zum Zweck der Umsetzung in idml (fehlt noch).

**Comment by pglatza** [comment]
Die Fußnoten selbst sind nun umgesetzt (Uploadformular ist aktualisiert).

**Comment by gerritbruening** [comment]
Danke, die Fußnoten sehe ich. Wie ist hier jetzt der weitere Fahrplan: Erst #374, dann hier weiter?

**Comment by pglatza** [comment]
Ja, klären wir zunächst #374 bzw. wenn es sich ergibt, ein mit diesem aktuell verknüpftes Issue.

**Comment by gerritbruening** [comment]
> bzw. wenn es sich ergibt, ein mit diesem aktuell verknüpftes Issue

Was heißt das?

**Comment by pglatza** [comment]
Damit meinte ich die referenzierten Issues in der Liste dieses Tickets oben: https://github.com/faustedition/faust-gen-html/issues/211#issuecomment-362241864

**Comment by gerritbruening** [comment]
Alles klar, danke!

**Comment by pglatza** [comment]
> #374 (comment) nicht vergessen.
Hierbei handelt es sich um ein `note`Element zwischen zwei Versen.
@gerritbruening, an welcher Stelle soll diese (Fußnote) dargestellt werden? Am Anfang des vorhergehenden `l`-Elementes oder am Anfang des darauf folgenden `l`-Elementes?

**Comment by gerritbruening** [comment]
Spezialfall, deswegen eigenes Issue: #456.

**Comment by gerritbruening** [comment]
Verbleibende Probleme wurden als einzelne Issues weiterverfolgt.
