### ISSUE TITLE
BA Blocks. 1,5 

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#212]
Ja, das kommt bislang nicht vor. Vielleicht kommt es auch überhaupt nicht vor. Ich wollte es nur parallel zu BA zentr. 1,5 vorbereiten.

>  kommt in meiner Beispieldatei nicht vor

> Bei den Absatzformaten fehlen auch noch einige Zuweisungen: Vers, Antilabe, Vers lateinisch (Vers rechts kommt bislang nicht vor), BA zentr. 0,5, BA zentr. 1,5, BA Blocks. 0,0, **BA Blocks. 1,5**, Zwischenzeile.

Gibt es das überhaupt? Oder ist das ein Irrläufer der Diskussion? @pglatza, weißt du etwas darüber? Wahrscheinlich muss hier erst @markusciupke eine Auskunft geben.

**Comment by markusciupke** [comment]
Kommt inzwischen vor: vor 2465.
