### ISSUE TITLE
BA zentr. 0,5

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#213]
> kommt bislang nur einmal vor (in Vers 3205 wegen der Antilabe)

![grafik](https://user-images.githubusercontent.com/10358005/35560492-e80dde20-05ad-11e8-8b00-cf52d68f102b.png)

@pglatza, lässt sich das über den rechten Rand des vorhergehenden `l part=` und den linken Rand des `BA`-Absatzes automatisieren? Sonst überantworten wir das dem Feinsatz.

**Comment by pglatza** [comment]
Ja, das Zuweisen von 'BA zentr. 0,5' in diesem Fall können wir beim Mapping berücksichtigen.

**Comment by gerritbruening** [comment]
Siehe auch #213.
