### ISSUE TITLE
Remove parentheses in reading text's stage elements

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#217]

**Comment by gerritbruening** [comment]
I still see them in the generated file.

**Comment by gerritbruening** [comment]
Irgendwas scheint mir hier immer noch komisch:

                            <stage n="before_5199_b">
                                .<hi>Fischer und Vogelsteller</hi>. (Mit Netzen, Angel

Kannst du nochmal schauen?

**Comment by thvitt** [comment]
Original:
```xml
                            <stage n="before_5199_a"><hi status="name">Geſpielinnen.</hi> (jung und
                                ſchön geſellen ſich hinzu, ein vertrauliches Geplauder wird
                                laut)</stage>
                            <stage n="before_5199_b">
                                <hi status="name">Fiſcher und Vogelſteller</hi>. (Mit Netzen, Angel
                                und Leimruthen, auch ſonſtigem <subst f:revType="soon">
                                    <del>g</del>
                                    <add>G</add>
                                </subst>eräthe treten auf, miſchen ſich unter die ſchönen Kinder.
                                Wechſelſeitige Verſuche zu gewinnen, zu fangen, zu entgehen und feſt
                                zu halten geben zu den angenehmſten Dialogen Gelegenheit)</stage>
```
Nach Postprocessing:
```xml
                            <stage n="before_5199_a"><hi>Gespielinnen.</hi>jung und
                                schön gesellen sich hinzu, ein vertrauliches Geplauder wird
                                laut.</stage>
                            <stage n="before_5199_b">
                                .<hi>Fischer und Vogelsteller</hi>. (Mit Netzen, Angel
                                und Leimruthen, auch sonstigem Geräthe treten auf, mischen sich unter die schönen Kinder.
                                Wechselseitige Versuche zu gewinnen, zu fangen, zu entgehen und fest
                                zu halten geben zu den angenehmsten Dialogen Gelegenheit.</stage>
```

Scheinen drei Probleme:

1. der whitespace-only-Textknoten am Anfang von before_5199_b erzeugt ebenfalls einen Punkt.
2. Klammern, die nur einen Teil der BA umschließen. Was soll denn passieren? Alle klammern weg? Oder endklammer nur weg, wenn am Anfang der BA eine Klammer steht?
3. der verlorene Whitespace nach dem `</hi>` in before_5199_a

**Comment by thvitt** [comment]
Der überflüssige Punkt ist nun weg.

@gerritbruening, die Frage mit den Klammern mitten in der Bühnenanweisung ist noch offen. Sollen grundsätzlich alle runden Klammern, die irgendwo in Bühnenanweisungen stehen, entfernt werden? Oder können wir irgendeine Regel angeben, die auch die ( oben erschlägt, aber keine erhaltenswerten?

**Comment by gerritbruening** [comment]
Treten die Binnenklammern auch an Stellen auf, wo nicht direkt ein hi-Element vorhergeht?

**Comment by thvitt** [comment]
Na gut, selbst mal nach `//stage[contains(., '(')]` gesucht. Neben den og Fällen kommt folgendes dabei raus:

```xml
<stage n="after_7213">Faust (entfernt sich</stage>
<stage n="before_8424i_a">Galatee. (auf dem Muschelwagen nähert sich</stage>
```

ein besonders spaßiger fall:

```xml
                     <stage n="before_10849_a"><hi>Kaiser</hi>, mit <hi>Vier Fürsten</hi>treten
                        auf) Die <hi>Trabanten</hi>. (entfernen sich</stage>
```

klammern noch da wg. hi:

```xml
<stage n="before_11286_b">
                           <hi rend="latin">(ad Spectatores)</hi>
                        </stage>
```

für mich klingt das nach 'klammern grundsätzlich weg in hi, egal was sonst', aber das würde ich nie ohne editorisches Kommando tun :-)

**Comment by gerritbruening** [comment]
Gut, danke. Ich notiere:
* before_5199_a
* before_5199_b
* after_7213
* before_8424i_a
* before_10849_a
* before_11286_b

**Comment by dietmarpravida** [comment]
Klammern weg

**Comment by gerritbruening** [comment]
D.h. auch in den aufgelisteten Fällen? Ich bin noch nicht dazu gekommen sie durchzusehen.

**Comment by gerritbruening** [comment]
D.h. auch in den aufgelisteten Fällen? Ich bin noch nicht dazu gekommen sie durchzusehen.

**Comment by gerritbruening** [comment]
@thvitt, was ist mit `).`-Fällen wie

                            <stage n="before_8647_b">welche die Thürflügel
                                offen gelassen hat, bewegt).</stage>

Sollten diese Klammern eigentlich schon weg sein? Sind diese Fälle vom Pattern noch nicht erfasst?

**Comment by thvitt** [comment]
Bislang werden nur ) am Ende einer BA entfernt. Diese ) steht nicht am Ende einer BA (Punkt dazwischen). Wenn ich euch mittlerweile richtig verstehe, sollen einfach alle runden Klammern aus BA entfernen, egal wo sie stehen. Wenn ich das implementiert habe, wird an der og stelle `bewegt.</stage>` stehen.

**Comment by gerritbruening** [comment]
Ja, jetzt ja. Es war aber im Prinzip nicht schlecht, sachte vorzugehen, weil wir so auf fehlende `hi` und andere Probleme gekommen sind. Sorry für die Mühe!

**Comment by thvitt** [comment]
schnapp dir doch die without-app.xml von jetzt und such im Oxygen nach `//stage[contains(., '(') or contains(., ')')]`. Diese ganzen Ausnahmeregeln sind etwas nervig zu schreiben, weil man jeden Spezialfall (a) vorhersehen (oder mit vorgenanntem Ausdruck im Oxygen suchen), (b) operationalisieren (c) testen muss.

**Comment by gerritbruening** [comment]
Jetzt gibt es doch keine Spezialfälle mehr? `stage/text()` --> Klammer entfernen.

**Comment by thvitt** [comment]
ah, sorry. Habe das falsche Tempus gelesen
