### ISSUE TITLE
Render html app entries as separate list

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#219]
So wie sie momentan im Text aussehen, nur halt in einer Liste.

**Comment by thvitt** [comment]
wo soll das hin? in die Edition? wo verlinkt? oder nur für intern?

**Comment by gerritbruening** [comment]
Es würde reichen, erstmal dahin, wo die anderen generierten Sachen liegen.
Ist erstmal nur für interne Zwecke. Aber wenn wir mehr Gefallen daran finden, können wir es auch online stellen.

**Comment by thvitt** [comment]
They are at http://dev.faustedition.net/text-app – and of course they only include those app entries that are actually inserted into the reading text, cf. the validation.

**Comment by gerritbruening** [comment]
Super, danke!
