### ISSUE TITLE
"Gesamtansicht" for Faust I, Faust II

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#220]
> In der Text-Szenenansicht wird nur der Wechsel zur Gesamtansicht zur Wahl gestellt; man möchte aber eigentlich meist auf die Ansicht von Faust I oder II wechseln. Vielleicht sollte, je nachdem, in welcher Szene man sich befindet, die Option ganz-Faust I oder ganz-Faust II statt der Gesamtansicht zur Wahl stehen? (Bei Zueignung etc. aber aus hierarchischen Gründen wohl die Gesamtansicht?)

**Comment by gerritbruening** [comment]
> Bei Zueignung etc. aber aus hierarchischen Gründen wohl die Gesamtansicht?

Da schiene mir der Wechsel zur Faust I-Gesamtansicht plausibler, die dann aber die drei Vorspann-Texte mitumfassen müsste.

**Comment by thvitt** [comment]
a) was genau sind die Use Cases für die Gesamtansichten?
b) die Aufteilung des Lesetexts in der Webansicht sollte eh nochmal besprochen werden

**Comment by gerritbruening** [comment]
Könnte am besten @dietmarpravida sagen, aber mir würde einfallen:
* ganzen Faust I sehen, um mit strg-f darin zu suchen (dafür hätte man dann aber eben gern Vorspiel ff. mit dabei)
* ganzen Faust I sehen, um mit strg-f darin zu suchen

**Comment by thvitt** [comment]
Hier müssen m.E. folgende Entscheidungen getroffen werden:
1. Was ist der Standardeinstieg in den Text – Gesamt-Inhaltsverzeichnis wie jetzt oder separat Faust I und Faust II wie früher?
2. Welche Gesamtansichten benötigen wir?
     a) Faust gesamt – Apparatscript etc. ist langsam aufgrund der Größe
     b) Faust I / Faust II
3. Falls irgendwas oben separat für Faust I erstellt werden soll – was ist Faust I? (a) Alles außer Faust II oder (b) nur _Der Tragödie erster Teil_?

**Comment by dietmarpravida** [comment]
zu 1: Wie jetzt, würde ich sagen
zu 2: beide, aber der Nullfall wäre für mich eher Faust I/II
zu 3: Das ist eine gute Frage. Für die Ansicht wäre ich aber für Anzeige von allem außer Faust II.

**Comment by gerritbruening** [comment]
Danke, lang aber konsequent!

**Comment by thvitt** [comment]
da ist noch ein Bug drin. Das eigentlich erwünschte Verhalten ist:
* Szenen in Faust II haben Link _Gesamtansicht Faust II_
* Szenen im Rest haben Link _Gesamtansicht Faust I_
* Inhaltsverzeichnis Gesamt hat Link _Gesamtansicht_. (Die hätte ich aufgrund der Größe und dementsprechenden problematischen Performance gern möglichst nicht so wahnsinnig prominent)

**Comment by thvitt** [comment]
2e3adc8f8bac5160b269a2349d3ced72b936d604
