### ISSUE TITLE
Display of ellipses in app entries

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#223]
![grafik](https://user-images.githubusercontent.com/10358005/35622352-d8006068-0687-11e8-8f76-23a9f344904c.png)

In current app entries wie have the `…` ellipsis but this is rather implicit. In the XML it would be cleaner to transform these into `<gap reason="ellipsis"/>` elements which in turn could then be rendered as dots, _bis_, dash or whatever we like.

@dietmarpravida, do you have an opinion on that?

**Comment by dietmarpravida** [comment]
Agree. Is the <gap reason="ellipsis"/> sensitive to verse borders or may it ramble freely?

**Comment by dietmarpravida** [comment]
What should happen to the "..." in the Word file? I would strongly prefer to keep them readable for non-mechanical philologists.

**Comment by gerritbruening** [comment]
Sure, no need to change ... in the docx source.

**Comment by gerritbruening** [comment]
We need a decision on how ` <gap reason="ellipsis"/>` is to be rendered, though. Are ellipsis dots OK or do you prefer _bis_, dash, etc.?

**Comment by dietmarpravida** [comment]
No dots please. The Emilia Galotti edition flaunts "bis" in another (sans serif) font (editorial text is generally sans serif in this apparatus). Should we go for italics?

**Comment by dietmarpravida** [comment]
In Faust I sind es bisher jedenfalls Ellipsenpunte. Es wäre kein Problem, sie durch kurisve "bis" zu ersetzen, aber Kursive dürfte bei der Transformation unnötige Zusatzumstände bereiten.

**Comment by thvitt** [comment]
fehlt noch im [Lemma](http://dev.faustedition.net/print/faust.30#l4989)

**Comment by gerritbruening** [comment]
Danke!
