### ISSUE TITLE
Sigle des Ausgangstextes hervorheben

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#226]
Nur für den Faust II relevant. Ich könnte diese im docx fetten oder Intervalle angeben. @thvitt, was wäre für die Weiterverarbeitung günstiger?

**Comment by thvitt** [comment]
ich versteh's nicht. Was ist der Ausgangstext? Ist das nicht der dessen Sigle im Lemma steht?

**Comment by dietmarpravida** [comment]
ni ih firnimu, wie wir im Athochdeutschen zu sagen pfegen, zu deutsch: ich verstehe es auch nicht

**Comment by gerritbruening** [comment]
> Was ist der Ausgangstext? Ist das nicht der dessen Sigle im Lemma steht?

q.e.d.
Manchmal ist es auch der Zeuge, der hinter der abweichenden Lesart steht.
Der Verbraucher fragt sich oft: Was ist denn hier an der Stelle nochmal die Textgrundlage? Da könnte Fettung der Sigle Klarheit bringen. Was man um Druck nehmen könnte, wäre noch die Frage.

**Comment by thvitt** [comment]
hm, langsam schwant mir was: Es geht um die 'großen' Grundlagen für den Lesetext, A, H, H.0a, C.1 4?

**Comment by gerritbruening** [comment]
Genau.

Das einzige, was mir einfällt, wäre

    <app>
       <rdg wit="#faust://document/faustedition/Sigle"><witStart/></rdg>
    </app>

**Comment by thvitt** [comment]
Soll's dafür eigentlich auch 'n verbalen Apparateintrag geben? 'Textgrundlage ab hier: XXX' oder so?

**Comment by thvitt** [comment]
Also, ad was wäre mir lieber – Bruchstellen bei der Generierung von faust.xml auf die o.g. Weise markieren und das dann bei der Darstellung oder beim einfügen des Apparats verwenden

**Comment by gerritbruening** [comment]
> Soll's dafür eigentlich auch 'n verbalen Apparateintrag geben? 'Textgrundlage ab hier: XXX' oder so?

Eher nicht.

**Comment by thvitt** [comment]
Nee, wo soll der Tooltip denn dranstehen? Im Gesamttext wird der schon für die Belegdichte / Variantenzahl benötigt

**Comment by gerritbruening** [comment]
Ja, stimmt, schade, hätt ja sein können. Vielleicht gibt es noch irgendeine andere Möglichkeit.

**Comment by gerritbruening** [comment]
> Also, ad was wäre mir lieber – Bruchstellen bei der Generierung von faust.xml auf die o.g. Weise markieren und das dann bei der Darstellung oder beim einfügen des Apparats verwenden

OK, gut!

**Comment by thvitt** [comment]
soll das auch im gedruckten Apparat berücksichtigt werden oder nur im Web?

**Comment by gerritbruening** [comment]
Wir sind uns noch nicht sicher und würden daher ein Zeichenformat vorsehen dafür (siehe https://github.com/faustedition/faust-gen-html/issues/211#issuecomment-362241864), das aber evtl. am Ende dieselbe Formatierung enthält wie die anderen Siglen.
