### ISSUE TITLE
Remove dots from abbreviations in app entries

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#232]
Applies to: see @dietmarpravida|s comment below.

Dot may already be present.

**Comment by dietmarpravida** [comment]
ci.
em.
mon.
bill.
vorschl.

**Comment by gerritbruening** [comment]
For the online rendering, it is an open questions whether dots may be dropped again (to be consistent with the rest of the online renderings).

**Comment by thvitt** [comment]
Also da sollen überall Punkte dran oder was soll ich damit machen? Das ist doch kein Apparat hier, da dürft ihr weniger kryptisch schreiben!

Wenn ich da ran muss, pack ich die alle in ein `<abbr>`, dann kann man da im Web Expansionen dranschreiben (die Ihr noch liefern müsst).

**Comment by gerritbruening** [comment]
Ja, überall Punkte dran, und `abbr` ist perfekt.

**Comment by thvitt** [comment]
Äh, was ist mit dem Klammerlatein in @dietmarpravida‌s Liste?

Vielleicht kann man statt der Abkürzungen auch Emoticons einsetzen. 👍, 👎, 🔨 etc.

**Comment by gerritbruening** [comment]
> Äh, was ist mit dem Klammerlatein in @dietmarpravida‌s Liste?

Welche Liste?

**Comment by gerritbruening** [comment]
Kenne ich jetzt, wurde mir eben erst bekannt.

**Comment by thvitt** [comment]
Im [2. Kommentar zu diesem Issue](‌https://github.com/faustedition/faust-gen-html/issues/232#issuecomment-362289182), geschrieben von @dietmarpravida, stand vorhin noch lediglich eine Liste mit Abk., die ich expandieren soll. Inzwischen sieht der Kommentar nach Edits von Dietmar & Dir anders aus, da stehen noch klammern drin.

**Comment by gerritbruening** [comment]
@dietmarpravida, bitte so präzisieren, dass ...

**Comment by gerritbruening** [comment]
Dieses Latein, also ich weiß nicht. Muss das sein, @dietmarpravida?

**Comment by thvitt** [comment]
ist `fehlt` eine Abk.? Soll da ein `<abbr>` drum und ein `.` dahinter?

**Comment by gerritbruening** [comment]
Nein :-)

**Comment by dietmarpravida** [comment]
zum Latein: ich hänge nicht daran, finde ber "bill", "vorschl" usw ziemlich dilettantisch, die lateinischen Formulierunge sind immerhin eingeführt; konsequenterweise sollten wir dann auch "em" (zu "emend.") und "ci" (zu "konj.") verdeutschen?

**Comment by thvitt** [comment]
Also ich versteh _ci._ nicht so ohne weiteres, bin aber auch kein Editionsphilologe. 

Für die Webedition sollten wir, wie auch immer die Abk. lauten, einen hinreichend allgemeinverständlichen Erläuterungstext in den Tooltip packen.

**Comment by dietmarpravida** [comment]
wir machen es deutsch und legen zugleich eine Liste der verwendeten Abkürzunge an; bei dieser Gelegenheit formulieren wir gleich die Tooltips; auch in "Über die Ausgabe" muss etwas zu den Abkürzungen zu finden sein (es steht da m.W. derzeit auch noch nichts über die Textkonstitution)

**Comment by thvitt** [comment]
`<abbr>` ist gesetzt. Bitte reassignt mich, wenn Ihr eine Liste der Abkürzungen habt, dann bau ich das ein.

**Comment by gerritbruening** [comment]
@dietmarpravida, machst du das?

**Comment by dietmarpravida** [comment]
Als Abkürzungen kommen vor (hier mit Punkten, in den Dateien z.T. derzeit noch ohne Punkte):

bill. = billigt, Billigung (durch)
emend. = emendiert, Emendation
erg. = ergänzt, Ergänzung
konj. = konjiziert, Kenjekttur
mon. = moniert, Monitum (von)
verw. = verw(ischt?), Verwischung(?) @gerritbruening 
vorschl. = schlägt vor, Vorschlag

Soll das noch weiter ausformuliert werden?

----

Es kommen auch noch vor:
alR = am linken Rand
mglw. aus = möglicherweise (hervorgegangen) aus

**Comment by gerritbruening** [comment]
Abkürzungs- und sonstiger Kram jetzt unter #233.

**Comment by dietmarpravida** [comment]
ist das noch aktuell?

**Comment by gerritbruening** [comment]
@dietmarpravida, soll nach allen Abkürzungen ein Punkt stehen, und @thvitt, wird er auch gesetzt? Dann wäre das hier erledigt.

**Comment by thvitt** [comment]
Ich stelle den Punkt sicher, wenn #233 implementiert wird

**Comment by dietmarpravida** [comment]
@gerritbruening Punkt oder nicht?

**Comment by gerritbruening** [comment]
Ich bin eher gegen Punkte, weil sie mir un-apparatig vorkommen und wir sie online nicht haben. Gibt es einen Grund für diese Differenz zwischen online und gedruckt?

**Comment by dietmarpravida** [comment]
okay, dann keine Punkte
