### ISSUE TITLE
5388 beging’] 

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#236]
Validierung mit leerem Feld Bemerkung und 

> 2750 ſtünden grau] 5388 beging’] 

Wo könnte hier der Fehler liegen?

**Comment by thvitt** [comment]
Wo? Was? Die beiden Apparateinträge werden doch eingefügt und in der Validierungsseite stehen sie nicht?

http://dev.faustedition.net/print/faust.11#l2750
http://dev.faustedition.net/print/faust.29#l5388

**Comment by gerritbruening** [comment]
Ja, aber es gibt jetzt immer noch die Meldung in zu "beging" in "Apparat-Notes, nach Länge sortiert". 

"stünden grau" ist verschwunden, wir haben da auch was geändert:
https://github.com/faustedition/faust-gen-html/commit/281e8c5852914d5849e445171d214e0759b973ec#diff-86da7489d035aef254aa3eb175b90d8fL170

**Comment by thvitt** [comment]
Ah, das ist das Leerzeichen hier zwischen den beiden segs. 

```xml
<rdg wit="2_I_H.0a" hand="Ri G" type="2d">beging’ <note><seg type="hand">Ri</seg> <seg type="hand">G</seg></note></rdg>
```

Das ist kein Problem; die 'kurzen Notes' habe ich nur aufgelistet, damit ihr ggf. nicht erkannte Siglen und Schreiber findet.

**Comment by gerritbruening** [comment]
> die 'kurzen Notes' habe ich nur aufgelistet

Das können wir auch gut brauchen, damit wir vereinheitlichen können.
