### ISSUE TITLE
app entries without lemma

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#238]
Sind schon ein Problem, oder?

**Comment by thvitt** [comment]
Vermutlich. Sag mal'n Beispiel, ich kann mir da jetzt nichts drunter vorstellen

**Comment by gerritbruening** [comment]
Z.B.
_vor 2366--2377 Die Verse fehlen ..._

(Korrekter @n Wert ist noch nicht gepusht.)

**Comment by thvitt** [comment]
Wenn man das so codiert, kommt es zumindest (mit zwei Warnungen) durch den Python-Parser:

```
before_2366[]{} <i>vor 2366–2377</i>] <i>Die Verse fehlen in S. [type=7]</i>
```

Das ] wird z.Z. benötigt. So wären dann noch mind. folgende Probleme zu lösen

* kein/leeres `<lem>` → keine ] im HTML (und ist das valides TEI?)
* Siglen mitten im Apparattext :( d.h. hinfort du schön strukturiertes TEI, wie bei den Händen.

**Comment by gerritbruening** [comment]
Es heißt jetzt:
`before_2366[]{} <i>vor 2366–2377 Die Verse sind in S nicht enthalten. [type=7]</i>`
und zugleich `No match:` -- weil das Lemma fehlt?

> Siglen mitten im Apparattext :( d.h. hinfort du schön strukturiertes TEI, wie bei den Händen.

Ja, aber das ist an sich ein wohletabliertes Problem:
https://wiki.tei-c.org/index.php/Critical_Apparatus_Workgroup#Representing_.22verbose.22_apparatus

`<i>vor 2366–2377</i>]` können wir sicher machen, oder, @dietmarpravida?

**Comment by thvitt** [comment]
no match weil das ] fehlt. Das ] ist notwendig, um die verschiedenen Teile der Zeile auseinanderzuhalten, nur mit kursiv/nicht-kursiv ist das einfach zu ambig.

Die Siglen werde ich wohl so codieren:

```xml
<rdg wit="…"><note>Die Verse sind in <wit wit="…">S</wit> nicht enthalten.</note></rdg>
```

in `@wit` jeweils die faust-URI, im `<wit>` die ggf. für den Druck aufbereitete Kurzsigle (#205), für's Web wird hier ein Link mit der regulären Sigle gesetzt.

**Comment by gerritbruening** [comment]
Können wir dann nicht einfach so etwas wie
> _1234_ PSEUDO-LEMMA _A_]

reinsetzen und später wieder rauswerfen?

**Comment by gerritbruening** [comment]
`wit` ist in `note` afaik nicht erlaubt, d.h. wir müssten das Schema anpassen. Ich fänds in Ordnung!

**Comment by thvitt** [comment]
PSEUDO-LEMMA _A_ ist m.E. gar nicht nötig, die ] kann direkt nach dem Label kommen.

**Comment by gerritbruening** [comment]
"Label" heißt...?

**Comment by thvitt** [comment]
Zeilenbereich, hier: `<i>vor 2366–2377</i>`

**Comment by gerritbruening** [comment]
OK, danke!
@dietmarpravida, kannst du dann die Einträge entsprechend mit `<i>vor 2366–2377</i>]` (mit Lemmaklammer) etc. versehen?

**Comment by dietmarpravida** [comment]
mache ich

**Comment by dietmarpravida** [comment]
nach 4334, 3994-3995, 3990-4015, 3974-3977, 3871-3911, 3787-3788, 3550-3551, nach 3409, 3356-3357, 3095, 2709, 2540-2552, vor 2540, vor 2366–2377, Beiersdorf_2322, 988, 852-859

**Comment by thvitt** [comment]
ich sehe hier nichts mehr für mich zu tun. Wenn Ihr den Apparat angepasst habt, sollte automatisch sinnvolles Rendering dafür entstehen, sonst bitte melden.

**Comment by gerritbruening** [comment]
Ja!
