### ISSUE TITLE
before_2532_a Die Hexe ... (Quasi-Repliken)

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#239]
Hier gibt es mehrere Punkte.

Man sehe die Kodierung in A:

                            <stage n="before_2532_a" rend="centered small"><hi
                                    rend="normal letter-spaced">Die Hexe.</hi><lb/>mit ſeltſamen
                                Geberden, zieht einen Kreis und ſtellt wunderbare Sachen<lb/>hinein;
                                ...

und beachte den `<lb/>` hinter "Die Hexe.", die infolgedessen wie ein Sprecher aussieht.

Man sehe dann die vereinfachte Fassung im Lesetext-XML:

                    <stage n="before_2532_a">
                        <hi>Die Hexe.</hi> mit seltsamen Geberden, zieht einen Kreis und stellt
                        ...

und beachte den verschwundenen `<lb/>`.

# Fragen an @thvitt
- [x] Die Apparatanweisung wird klaglos geparst, aber für den Text nicht befolgt. Das liegt wohl an dem `hi`, @thvitt ? (Und sollte nicht eine Problemmeldung ausgegeben werden?)
- [x] @thvitt, gleich nach dem betreffenden `app` hat sich noch ein `<ref>vor 2583</ref>` und danach nochmal ein `<app from="#lem.before_2532_a.hexe">` eingeschmuggelt, wie kommt das?

# Fragen an @dietmarpravida
- [x] Sollten Zeilenumbrüche solcher Art konserviert werden, um dann auch in den Satz einzufließen?
- [x] @dietmarpravida, `speaker` im Apparateintrag scheint mir nicht korrekt, es müsste heißen `hi`, denn hier liegt keine Sprecherbezeichnung vor.
- [x] Deswegen schiene es mir auch OK, "Die Hexe" und das folgende in eine Zeile zu setzen, anders als bei der Aufeinanderfolge von Sprecherbezeichnung und BA (`speaker` und `stage`). Das Gegenteil (Zeilenumbruch) schiene mir auch möglich (`stage/hi` an erster Position ohne `text()` davor, und direkt danach `lb`).
- [x] @dietmarpravida, warum soll hier der Punkt entfernt werden, nicht aber `before_2270_a`? (Mephistopheles. bohrt,)

**Comment by thvitt** [comment]
> Die Apparatanweisung wird klaglos geparst, aber für den Text nicht befolgt. Das liegt wohl an dem hi, @thvitt ? (Und sollte nicht eine Problemmeldung ausgegeben werden?)

Bug im XSLT, das über den `.` stolperte. Wird in 40e804b8e33f48a8d2f979c3a6f503d34fb9538a repariert. Die Validierung findet das nicht, weil sie z.Z. nur nach Apparateinträgen und nicht nach den zugehörigen `<seg>` schaut.

> @thvitt, gleich nach dem betreffenden app hat sich noch ein <ref>vor 2583</ref> und danach nochmal ein <app from="#lem.before_2532_a.hexe"> eingeschmuggelt, wie kommt das?

Aus diesem Apparateintrag, der mittlerweile korrigiert zu sein scheint?

    before_2532_a[Hexe.]{Hexe} <i>vor 2583</i> <speaker>Hexe</speaker><c>^</c> <i>S B B.a</i>]   <c>Hexe.</c> <i>A D.1 [type=1c]</i>

**Comment by gerritbruening** [comment]
> `before_2532_a[Hexe.]{Hexe} <i>vor 2583</i>`

Ja, das muss der Grund gewesen sein!

**Comment by dietmarpravida** [comment]
- [ ] @dietmarpravida, `speaker` im Apparateintrag scheint mir nicht korrekt, es müsste heißen `hi`, denn hier liegt keine Sprecherbezeichnung vor.
-- ist mir egal
- [ ] Deswegen schiene es mir auch OK, "Die Hexe" und das folgende in eine Zeile zu setzen, anders als bei der Aufeinanderfolge von Sprecherbezeichnung und BA (`speaker` und `stage`). 
-- ist in allen Drucken so
- Das Gegenteil (Zeilenumbruch) schiene mir auch möglich (`stage/hi` an erster Position ohne `text()` davor, und direkt danach `lb`).
- [ ] @dietmarpravida, warum soll hier der Punkt entfernt werden, nicht aber `before_2270_a`? (Mephistopheles. bohrt,)
-- nach "Die Hexe" kommt kein Punkt, weil BA-Text folgt (siehe S); der Punkt bei "Mephistopheles" entfällt ebenso

**Comment by dietmarpravida** [comment]
neuer Apparateintrag: 

"before_2540 . In S findet sich ein Satzfehler, da die Angabe „Die Hexe“ nicht hervorgehoben und innerhalb der Bühnenanweisung nicht ebenso abgesetzt ist, wie dies bei der vorangehenden Bühnenanweisung vor 2532 und der nachfolgenden vor 2583 der Fall ist. Möglicherweise deutet diese Unregelmäßigkeit (zusammen mit der unterbliebenen Einrückung der Verse 2540–2552) auf eine Unregemäßigkeit (durch nachträgliche Einfügung?) in der Druckvorlge von S. In A wird die fehlende Auszeichnung der Angabe „Die Hexe“ berichtigt, doch weicht die typographische Gestaltung der Bühnenanweisung vor 2540 infolge dieser Korrektur in A von der der Bühnennweisungen vor 2532 und 2583, die sich an S orientiert, ab. [Typ 1c*]"

Was ist hier editorisch zu tun? Da die Unregelmäßigkeit auf die DV zurückgehen könnte, sollte man hier vielleicht eher A folgen als S zu rektifizieren.

**Comment by dietmarpravida** [comment]
Das scheint mir ein spezielles Problem, das wir eigens besprechen müssten.

**Comment by gerritbruening** [comment]
Um Phänomene dieser Art 

                            <stage n="before_2532_a" rend="centered small"><hi
                                    rend="normal letter-spaced">Die Hexe.</hi><lb/>mit ſeltſamen
suchen und behandeln zu können, brauchten wir einen Match für folgendes Aufeinandertreffen:
* `stage/hi` mit `hi` an erster Position (davor evtl. Whitespace)
* dieses `hi` direkt gefolgt von einem `lb` (dazwischen evtl. Whitespace)

@thvitt, ich kriege das nicht hin. Könntest du evtl. helfen?

**Comment by thvitt** [comment]
Das Pattern hier erlaubt zwischen hi und lb auch anderen Textcontent, dies zu verbieten bleibt dem Leser zur Übung überlassen:

    //stage[node()[normalize-space(.)!=''][1][self::hi]/following-sibling::*[1][self::lb]]
    ---1--- --2-- ----------3------------ -4- ---5----  ---------6--------- -7- ---8----

Erläuterung:
1. suche ein stage irgendwo
2. darin nimm alle Knoten
3. die nicht nur aus whitespace bestehen
4. davon den ersten
5. wenn's ein hi ist
6. jetzt davon die folgenden Geschwisterchen
7. davon den ersten
8. wenn's ein lb ist

wenn irgendeiner der Teilausdrücke 2-8 auf die leere Sequenz auswertet, wird das Prädikat falsch & damit das stage verworfen.

Habe nix gefunden in faust.xml, aber mit head statt stage gips 1 treffer

**Comment by gerritbruening** [comment]
> rektifizieren

ginge so:

    before_2540_c[@stage]{rend=}

(bedeutet, der `@rend`-Wert `inline` würde wegfallen, d.h., die BA beginnt auf einer eigenen Zeile)

**Comment by gerritbruening** [comment]
> erlaubt zwischen hi und lb auch anderen Textcontent, dies zu verbieten bleibt dem Leser zur Übung überlassen

Übung vergeigt (._.)

**Comment by gerritbruening** [comment]
Gilt nicht für Auftrittsbezeichnungen.

**Comment by dietmarpravida** [comment]
@gerritbruening Haben wir eine Liste mit weiteren Stellen, die mit `[@stage]{rend=} ` kodiert werden müssen? Oder muss das nach bestem Wissen geschehen?

**Comment by gerritbruening** [comment]
Nein, die müsste man idealerweise durch Kollation mit S ermitteln.

**Comment by gerritbruening** [comment]
Betrifft auch Auftrittsbezeichnungen wie `before_3544_b`.

**Comment by gerritbruening** [comment]
Im IDML müssen sicherheitshalber (wg. BA Blocks.) zwei Absätze draus gemacht werden.

**Comment by gerritbruening** [comment]
In Einklang mit https://github.com/faustedition/faust-gen-html/issues/344#issuecomment-381054829 würden wir hier `type="semantic"` einfügen.

Um das gescheit tun zu können, brauchte ich jetzt noch Nachhilfe von @thvitt in Sachen https://github.com/faustedition/faust-gen-html/issues/239#issuecomment-363907574 ff.

**Comment by thvitt** [comment]
ich verstehe das Problem nicht; wenn der Ausdruck oben schon keine Ergebnisse bringt wird ein speziellerer das doch auch nicht tun?

**Comment by gerritbruening** [comment]
Nein umgekehrt, er bringt zu viele, weil er auf die Grundtexte anzuwenden ist. Im jetzigen faust XML landen die betreffenden lb gar nicht.

**Comment by thvitt** [comment]
//stage[node()[normalize-space(.)!=''][1][self::hi][normalize-space(following-sibling::node()[1]) = '' and following-sibling::*[1][self::lb]]]

**Comment by gerritbruening** [comment]
Danke, das scheint genau der Ausdruck zu seine, den ich suchte.
Ich habe die `lb` in der XML-Quelle, die konservieren sind, mit `@type` versehen.

**Comment by thvitt** [comment]
Ist für mich (oder für sonst wen) hier noch irgendwas zu tun?

**Comment by gerritbruening** [comment]
Nein, es sollte jetzt für alles gesorgt sein, solange @pglatza die `lb` in Zeilenumbrüche umsetzt (ist, glaube ich, schon der Fall).
