### ISSUE TITLE
print/faust toc broken

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#240]
http://dev.faustedition.net/print/faust

Faust I seems OK, but Faust II does not.

**Comment by thvitt** [comment]
yes, I think the problem is the titlePart in the beginning of Faust II which needs to be cleaned up.

**Comment by gerritbruening** [comment]
The title page structure ist dissolved, isn't it?
So maybe `titlePart` into `head type="titlePart"`?

**Comment by thvitt** [comment]
yes, needs to be implemented in assemble-reading-text.xsl or text-cleanup.xsl

**Comment by gerritbruening** [comment]
OK, wouldn't it be the easiest solutions to just pick out `before_4613_c` from `391098` and insert it at the beginning of the Faust II-`div`?
