### ISSUE TITLE
Satzzeichen und Sperrung

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#242]
Irgendwoher habe ich folgende Information zur Formatierung: 

> Satzzeichen, die vom Muster miterfasst werden, (z.B. before_243_b `<hi>Der Herr, die himmlischen Heerscharen,</hi>`) erhalten das Zeichenformat "Auftritt" nicht.

Das ist mir nicht klar. Warum sollen Kommate nicht mitgesperrt werden? Das Komma nach "Heerscharen" S. 17 sieht auch gesperrt aus, ohne dass mir das problematisch zu sein scheint. Das Komma in "Herr," klebt dagegen.

**Comment by markusciupke** [comment]
In Auftritten werden nur die auftretenden Personen durch Auftritt gekennzeichnet, nicht aber Satzzeichen und andere Textbestandteile (»nachher«). So habe ich das in beiden Auftritten (vor 33 und vor 243) gehandhabt. Dass das Komma an HERR mehr klebt als an HEERSCHAREN liegt am Schnitt der Lettern. Wenn man das im Einzelfall schöner machen will, ist das was für den Feinsatz. Oder Philipp müsste so programmieren, dass Kommata nach bestimmten Buchstaben mit dem Zeichenformat Auftritt gesperrt werden.

**Comment by markusciupke** [comment]
Ergänzung: So ist es auch in der Cotta-Ausgabe. Man kann aber auch entscheiden, Satzzeichen grundsätzlich ebenfalls zu sperren. So auch Leerzeichen vor und nach den auftretenden Personen (z.B. vor 2337).

**Comment by dietmarpravida** [comment]
M.W. werden Satzzeichen einfach nicht gesperrt, oder?

**Comment by markusciupke** [comment]
So habe ich das auch gelernt.

**Comment by gerritbruening** [comment]
Das scheint von den Satzzeichen abzuhängen:
> * ... werden mitgesperrt,
> * ebenso die Satzzeichen (außer orthographischer Punkt, Anführungszeichen und Arabische Ziffern).

([W. Beinert](http://www.typolexikon.de/sperren/))

**Comment by gerritbruening** [comment]
Betrifft übrigens auch Stellen wie 1224ff., wo unmittelbar angrenzende Satzzeichen das Zeichenformat nicht ohne pre-processing erhalten:

         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Sperrung">
            <Content> Wort</Content>
         </CharacterStyleRange>
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Content>!“</Content>
         </CharacterStyleRange>

**Comment by dietmarpravida** [comment]
Gerrit scheint recht zu haben, überall, wo ich nachsehe, steht folgendes: "Bis auf Punkt und Anführungszeichen werden Satzzeichen, Bindestrich und Trennstrich mitgesperrt." (So Duden 1996, S. 77 und vielfach in ähnlichen Werken.)

**Comment by gerritbruening** [comment]
Gut, dann ist das so beschlossen:
* umgebende Satzzeichen werden mitgesperrt
* Ausnahmen:
  * Punkt
  * Anführungszeichen

**Comment by pglatza** [comment]
Ist eingestellt. Upload-Formular ist auch aktualisert.

**Comment by gerritbruening** [comment]
Manchmal glaube ich noch Punkte zu sehen, die mit im gesperrten Zeichenformat stehen, z.B.

      <ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/C BA zentr. 2,3 / 0,0">
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Auftritt">
            <Content>Faust. Mephistopheles.</Content>
         </CharacterStyleRange>
         <Br/>
      </ParagraphStyleRange>

@pglatza, kannst du dazu eine Auskunft geben?
Denn manchmal hat es auch wie erwartet funktioniert:

         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Auftritt">
            <Content> Chorgesang</Content>
         </CharacterStyleRange>
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Content>. </Content>
         </CharacterStyleRange>

**Comment by pglatza** [comment]
Es wurden von mir nur stage-Elemente mit der hi-Auszeichnung berücksichtigt. Die hi-Auszeichnungen werden in später zu Auftritt (Zeichenformat).
Der genannte Fall gehört zur Gattung von stage-Elementen ohne hi-Auszeichnungen, bei denen allerdings ein move-Element voraus geht. In diesem Fall wird der komplette Inhalt des stage-Elementes mit dem Zeichenformat Auftritt in InDesign ausgezeichnet.

Diesen Fall (8 Vorkommen) habe ich nun auch berücksichtigt.

Upload-Formular ist aktualisert.

**Comment by gerritbruening** [comment]
Danke, hab das Formular gerade nochmal ausprobiert und bekomme folgendes Ergebnis als ersten Treffer für `Auftritt`:

      <ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/C BA zentr. 2,3 / 0,0">
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Auftritt">
            <Content>Director, Theaterdichter, lustige Person.</Content>
         </CharacterStyleRange>
         <Br/>
      </ParagraphStyleRange>

Das entspricht dem was du sagst:
>  In diesem Fall wird der komplette Inhalt des stage-Elementes mit dem Zeichenformat Auftritt in InDesign ausgezeichnet.

Aber soll das jetzt immer noch so sein? Oder ist da ein Änderung bei mir nicht wirksam geworden?

**Comment by pglatza** [comment]
Das Verhalten der IDML-Synthese ist zu dieser Problematik nun angepasst und das Upload-Formular aktualisiert. Sprich, in solchen Fällen wird der Absatz nicht mehr automatisch mit dem Zeichenformat Auftritt versehen.

**Comment by pglatza** [comment]
Mir ist noch folgender Satz in der idml.md aufgefallen:

> Formatierung: Abstand nach unten wie BA ... mit Auftritt (siehe #251 (comment)).

Das müsste überarbeitet werden, @gerritbruening?

**Comment by gerritbruening** [comment]
Danke für den Hinweis, ist mit https://github.com/faustedition/faust-gen-html/commit/e1416890132097f9d05f92b59a3c61ef6707adb6 gefixt.
Das hatte aber sonst keinen Zusammenhang mit diesem Issue, oder?

**Comment by pglatza** [comment]
Nein, ist mir bloß aufgefallen.

**Comment by gerritbruening** [comment]
OK danke!

**Comment by gerritbruening** [comment]
Verbleibende Probleme wurden als einzelne Issues weiterverfolgt.
