### ISSUE TITLE
Do not add full stop at end of reading text's stage when there is punctuation (comma)

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#243]
Applies to

                        <stage n="before_350_a">Der Himmel schließt, die
                            Erzengel vertheilen sich,.</stage>

and 

                            <stage n="before_2284_a">Nachdem die Löcher alle
                                gebohrt und verstopft sind,.</stage>

**Comment by thvitt** [comment]
cf. #204
