### ISSUE TITLE
BA zentr. 1,5

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#247]
> ...  [(siehe #203)](https://github.com/faustedition/faust-gen-html/issues/203)
> Ansonsten ist der Abstand 1,5 mm nach oben auch bei Bühnenanweisungen eingesetzt, wenn hier ein Abstand nach oben da sein muss (z.B. vor 243, vor
4613 und nach 4665). Vor allem aber erscheint er bei Figurenreden mit Regieanweisung.

**Comment by markusciupke** [comment]
vor 243 hat nach unserem Telefonat vom 1. Februar BA zentr. 0,0 / 2,3 unten erhalten, weil die BA mit dem Auftritt des Herrn, der himmlischen Heerscharen und Meph.s ebenfalls BA zentr. 0,0 / 2,3 unten hat. So braucht »Die drei Erzengel treten vor« keinen zusätzlichen Abstand nach oben. Denkbar wäre für »Die drei Erzengel treten vor« auch BA zentr. 1,5. Dann wäre die BA mehr dem Text der Erzengel zugeordnet. (?)

vor 4613 hat ebenfalls momentan  BA zentr. 0,0 / 2,3 unten. Frage: was soll das darüber stehende »Dämmerung« für ein Format bekommen? Momentan BA zentr. 2,3. Also 2,3 nach oben, 0,0 nach unten. Soll es auch 2,3 nach unten bekommen. Dann brauchen wir ein neues Format ( BA zentr. 2,3 / 2,3)

vor 4665 hat tatsächlich BA zentr. 1,5. Das scheint mir korrekt. Da die Replik darunter 1,5 nach oben hat, steht diese BA schön in der Mitte.

Grundsätzliche Frage: Ist der neue größere Abstand 2,3 (nach unten oder oben) gut so? Oder reicht auch 1,5 nach unten wie bisher?

**Comment by gerritbruening** [comment]
Das sind alles Einzelstellen, keine Regeln.

**Comment by gerritbruening** [comment]
Die genannten Einzelstellen, sind jetzt im Rahmen anderer Issues behandelt.
