### ISSUE TITLE
Remove dot in speaker-like stage/hi elements (Quasi-Repliken)

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#248]
See the following example:
https://github.com/faustedition/faust-gen-html/issues/217#issuecomment-362532555

See also https://github.com/faustedition/faust-gen-html/issues/239

**Comment by gerritbruening** [comment]
Does also apply to dots after `hi`, see https://github.com/faustedition/faust-gen-html/issues/291#issue-296690459.

**Comment by thvitt** [comment]
We currently remove `.` in the following places (text-cleanup.xsl:160ff):
* before `</speaker>`, including whitespace between `.` and `</speaker>`
* before `</head>`, including whitespace between `.` and `</head>`

If I understand this issue and #291 correctly, we additionally need to remove `.`:

* immediately before `</hi>` when it's inside `stage`
* immediately after `</hi>` when it's inside `stage`

I intend to keep whitespace here since it's probably significant.

**Comment by gerritbruening** [comment]
Two exceptions worry me:
* `before_6173_b` (`<hi>Faust</hi>. <hi>Mephistopheles</hi>.`)
* `before_10345_c` (`<hi>Kaiser</hi>. <hi>Obergeneral.</hi> <hi>Trabanten</hi>`)

**Comment by gerritbruening** [comment]
> I intend to keep whitespace here since it's probably significant.

Which kind of whitespace do you mean? `_</hi>` should be insignificant. `_</hi>abc` would be sloppy at least if not wrong.

**Comment by gerritbruening** [comment]
@dietmarpravida, wir müssen hier entscheiden, ob es Apparateinträge geben soll, z.B. für
* before_4728_f (habe ich einen angelegt)
* before_12032_a (habe ich keinen)

**Comment by dietmarpravida** [comment]
sind für mich drei-bullet-points-Fälle (DBPFs): im einschlägigen Anhang verzeichnen, nicht im Apparat, da es sich um eine typographische Konvention handelt, nicht um Texteingriffe

**Comment by gerritbruening** [comment]
@thvitt, how do you think we could handle the [three exceptions](https://github.com/faustedition/faust-gen-html/issues/248#issuecomment-365629813) mentioned above?

**Comment by thvitt** [comment]
ignoring them would be easiest :) (read: I don’t understand the problem.)

**Comment by gerritbruening** [comment]
OK; three dots get lost:

> * `before_6173_b` (`<hi>Faust</hi>. <hi>Mephistopheles</hi>.`)
> * `before_10345_c` (`<hi>Kaiser</hi>. <hi>Obergeneral</hi>. <hi>Trabanten</hi>`)
> * `before_11167_b` (`<hi>Mephistopheles</hi>. <hi>die drey gewaltigen Gesellen</hi>`

due to our removal of dots.

**Comment by thvitt** [comment]
So which dots should be kept? Criterion might be  _don’t remove . after `</hi>` from text nodes if the text node contains nothing but `.` and whitespace and if it is immediately followed by another hi_ (would create `<hi>Faust</hi>. <hi>Mephistopheles</hi>` if we consider parentheses removal)?

**Comment by gerritbruening** [comment]
Terrific, thanks!
