### ISSUE TITLE
Drop space from Faust I

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#249]
Right now, `space` is used ambiguously in `faust.xml`.
In Faust I it is for typographical spacing which is to be ignored.
In Faust II it is for remaining gaps in the Text (not to confuse with `gap`s in the transcription or in app entries).

I once had `space[ancestor::text[@type='print']]` in an empty `xsl:template`, somewhere in the clean-up steps which have moved.

**Comment by thvitt** [comment]
Es gibt `<space>` jetzt überhaupt nur noch an einer Stelle, nach Vers 6062.

**Comment by gerritbruening** [comment]
Es sollte space noch an einer weiteren Stelle geben:
nach 6358.
Dieser space ist von einem posthumous-delSpan betroffen. Das wird wohl im Moment noch befolgt?

**Comment by thvitt** [comment]
ja, #116 ist noch offen

**Comment by gerritbruening** [comment]
OK, davon abgesehen entspricht das einmalige Vorkommen von `<space>` (nach 6062) den Erwartungen. Mehr als diese beiden sollte es auch nicht geben.
