### ISSUE TITLE
app entries with normalized characters in reading text

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#250]
Eg., [Hättſt in v.278](http://dev.faustedition.net/print/faust.3#l278). The corresponding app1norm.txt line is:

    278[Hättſt]{=} <i>278</i> Hättſt <i>A</i>]   Hätt’ſt <i>B B.a [type=4a]</i>

Of course, `Hättſt` is never found in the reading text since it had been normalized to `Hättst` before, so I'll probably have to run character normalization on the `[replace]` and `{insert}` texts before processing. What about the apparatus? I presume the writing in the apparatus shall be preserved, so the apparatus would look like

> <small>278</small> Hättſt ] **_A_**  Hätt’ſt _B_ _B.a_ _(Typ 4a)_

although it's _Hättst_ in the text?

**Comment by gerritbruening** [comment]
Sorry, I forgot. Long s is to be replaced by s in the whole of the entries.
