### ISSUE TITLE
Vor 33 / vor 243

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#251]
("Director, ..." / "Der Herr, ...")

Hier habe ich jetzt verschiedene Formate:
* `BA zentr. 0,0 nach Teil (Vorspiel/Prolog)` (Stand 1.2.)
* `BA zentr. 0,0 / 2,3 unten` (Stand 2.2., Signalfarbe Orange) für die zweite der beiden.

Hat die erste der beiden BA auch dieses Absatzformat? Ist `BA zentr. 0,0 nach Teil (Vorspiel/Prolog)` sozusagen umbenannt worden?

**Comment by markusciupke** [comment]
Das kommt darauf an, wie ich den Text geliefert bekomme. Wenn ihr den Umbruch der BAs schon in XML festlegt, bekomme ich hier zwei Absätze. Der erste Absatz sorgt dafür, dass der Auftritt  auf eine neue rechte Seite kommt mit Abstand 0, 0 nach unten (BA zentr. 0,0 nach Teil (Vorspiel/Prolog)), der zweite sorgt dafür, dass der Abstand nach unten 2,3 ist (BA zentr. 0,0 / 2,3 unten).
Eine Lösung ist, in solchen Fällen ein weiches Absatzzeichen einzufügen. Dann kann ich neue rechte Seite und Abstand nach unten in einem (!) Format festlegen. --> wie liefert ihr?
Vor 243 sind es momentan sogar drei Absatzformate: BA zentr. 0,0 nach Teil (Vorspiel/Prolog) – BA zentr. 0,0 – BA zentr. 0,0 / 2,3 unten.
Weiteres:
Der Abstand von »lustige Person« zu »DIRECTOR« ist 1,5 + 2,3 ist. --> So gewünscht?
Der Abstand von »Mephistopheles« zu »Die drey Erzengel treten vor.« ist 2,3. --> So gewünscht?
Der Abstand von »Die drey Erzengel treten vor.« zu »RAPHAEL« ist 2,3 +1,5. --> So gewünscht?

**Comment by gerritbruening** [comment]
> vor 243 hat nach unserem Telefonat vom 1. Februar BA zentr. 0,0 / 2,3 unten erhalten, weil die BA mit dem Auftritt des Herrn, der himmlischen Heerscharen und Meph.s ebenfalls BA zentr. 0,0 / 2,3 unten hat. So braucht »Die drei Erzengel treten vor« keinen zusätzlichen Abstand nach oben. Denkbar wäre für »Die drei Erzengel treten vor« auch BA zentr. 1,5. Dann wäre die BA mehr dem Text der Erzengel zugeordnet. (?)

(https://github.com/faustedition/faust-gen-html/issues/247#issuecomment-362798863)

**Comment by gerritbruening** [comment]
> Der erste Absatz sorgt dafür, dass der Auftritt auf eine neue rechte Seite kommt 

Dafür sorgt @pglatza oder hat schon dafür gesorgt.

Den Rest der Kommentare verstehe ich nicht ganz. Ich würde vorschlagen, wie diskutieren das im Rahmen der BA-Systematik weiter:
https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#ba-nach-%C3%9Cberschrift-mit-auftrittsbezeichnung-nicht-sprecher

**Comment by gerritbruening** [comment]
> Denkbar wäre für »Die drei Erzengel treten vor« auch BA zentr. 1,5. Dann wäre die BA mehr dem Text der Erzengel zugeordnet. (?)

Tiese `BA` gehört zum Typ "BA nach BA", siehe https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#ba-nach-ba.
Wenn diese ein Problem darstellen, wäre das ein eigenes Issue.

**Comment by markusciupke** [comment]
Was auch immer: ich fände parallel zu vor 4613 (#255) immer BA zentr. 1,5 ausreichend und richtig. Wir verzetteln uns, wenn wir für alle möglichen Kombinationen von BAs mit und ohne Auftritt, Figur, Sprecher eigene Absatzformate definieren wollen. Mein Vorschlag ist also: 
• Abstand »lustige Person« zu »Director« 1,5 durch Sprecher 1,5
• Abstand »nachher Mephistopheles« zu »Die drei Erzengel treten vor« 1,5 durch BA zentr. 1,5
• Abstand »Die drei Erzengel treten vor« zu »Raphael« 1,5 durch Sprecher 1,5

**Comment by gerritbruening** [comment]
> Wir verzetteln uns, wenn wir für alle möglichen Kombinationen von BAs mit und ohne Auftritt, Figur, Sprecher eigene Absatzformate definieren wollen.

Siehe die Systematik. Sie teilt 700 BAs in 8 Typen ein, und diesen Typen weist sie dann das von dir definierte Absatzformat zu. Auf deren Anzahl hat sie zunächst keinen Einfluss. Die Anzahl der Formate muss auch nicht der Anzahl der Typen entsprechen, da mehrere Typen demselben Format zugewiesen werden können.
Typen brauchen wir eh, da wir ja nicht 700 Einzelentscheidungen treffen wollen.

**Comment by gerritbruening** [comment]
Was ich noch schwierig finde ist die Kombination von Abstand nach unten bei Absätzen und dann fehlendem Abstand beim folgenden. Das müsstest du uns mal im Rahmen einer Telko erklären.

**Comment by markusciupke** [comment]
Welche Stelle(n) z.B. meinst du?

**Comment by gerritbruening** [comment]
Folgende Prämissen:
1. Überschriften erhalten einen Abstand nach unten.
2. BA mit Auftrittsbezeichnung erhalten Abstand nach oben und unten.
3. Repliken erhalten Abstand nach oben.

Anwendung auf Szene Nacht:
- Die Überschrift erhält Normalabstand nach unten.
- Die BA erhält diesmal keinen Abstand nach oben, obwohl Auftritt, weil für den Abstand ja schon die Überschrift der Szene sorgt.
- Der folgende Sprecher erhält auch keinen Abstand nach oben, weil für den Abstand ja schon die vorhergehende BA sorgt.

Oder sollen die Abstände immer aufaddiert werden?

**Comment by gerritbruening** [comment]
Teil von #299.
