### ISSUE TITLE
BA Abstand

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#253]
gibt es nicht mehr, oder?
(Siehe https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#ba-abstand)
((Darauf hat mich @pglatza aufmerksam gemacht.))

**Comment by markusciupke** [comment]
Nein, gibt es nicht mehr, weil ich einige Formate umbenannt habe, um sie sprechender zu machen. Es gibt momentan nur die Formate wie sie im Screenshot vom 2.2. zu sehen sind.
[Bildschirmfoto 2018-02-02 um 10.36.35.pdf](https://github.com/faustedition/faust-gen-html/files/1698207/Bildschirmfoto.2018-02-02.um.10.36.35.pdf)

**Comment by gerritbruening** [comment]
Und was ist an die Stelle von `BA Abstand` getreten?
Oder anders gefragt: Wie heißt das Format der BA, die zwischen Versgruppen stehen?

**Comment by gerritbruening** [comment]
Teil von #299.
