### ISSUE TITLE
Format für Bibelstellen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#254]
Vorläufig:
- https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#nn-bibelstelle-eigene-zeile
- https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#nn-bibelstelle-in-zeile

@markusciupke, könntest du hierfür eigene Formatnamen vergeben?

**Comment by markusciupke** [comment]
Klar, kann ich. Mach ich, wenn ich die Probe für einen schmaleren Satzspiegel bzw. nach links gerückten Sprechern mache. Dann erhalten auch die Akte ein eigenes Absatzformat (neue Seite statt neue rechte Seite).

**Comment by gerritbruening** [comment]
> Klar, kann ich.

Im Grunde brauchst du mir nur zu sagen, was die von dir favorisierten Namen wären. Dann setzt @pglatza das so um.

**Comment by gerritbruening** [comment]
So wie es aussieht, wird es [bibelstelle-eigene-zeile](https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#nn-bibelstelle-eigene-zeile) nicht geben.

**Comment by gerritbruening** [comment]
Zeichenformat: "Bibelstellen".

**Comment by pglatza** [comment]
'Bibelstelle' in der IDML-Synthese vorbereitet. Commit (und Test), sobald das hierzu überarbeitete Template zur Verfügung steht.

**Comment by pglatza** [comment]
Wie mit https://github.com/faustedition/faust-gen-html/issues/501#issuecomment-394943312 geschrieben, sind die Bibelstellen mit passendem Zeichenformat ab nun korrekt vorhanden.
