### ISSUE TITLE
vor 4613 

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#255]
> vor 4613 hat ebenfalls momentan BA zentr. 0,0 / 2,3 unten. Frage: was soll das darüber stehende »Dämmerung« für ein Format bekommen? Momentan BA zentr. 2,3. Also 2,3 nach oben, 0,0 nach unten. Soll es auch 2,3 nach unten bekommen. Dann brauchen wir ein neues Format ( BA zentr. 2,3 / 2,3)

(https://github.com/faustedition/faust-gen-html/issues/247#issuecomment-362798863)

**Comment by gerritbruening** [comment]
@markusciupke, zu vor 4613: Da sehe ich folgende Typen:
1. BA nach Überschrift, kein Auftritt
2. BA nach BA, nicht in Figurenrede (2x)

Zur Behandlung siehe
* https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#ba-nach-%C3%9Cberschrift-kein-auftritt
* https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#ba-nach-ba-nicht-in-figurenrede

Anlass für vergrößerten Abstand nach unten (2,3) sehe ich hier nicht.

**Comment by markusciupke** [comment]
Es geht hier ja leider immer hin und her. Wenn ich mir die Stelle vor 4613 anschaue, denke ich, dass die drei BAs (ob sie nun einen Auftritt, eine Figur, einen Sprecher oder nur Anweisung/Beschreibung beinhalten ist egal) in sich abgeschlossen sind und daher einen Abstand zueinander haben können. H lässt diese Interpretation nach meiner Ansicht vor »Dämmerung« zu. Nach »Dämmerung« nicht unbedingt, wäre aber zu rechtfertigen. In solchen Fällen, wenn BAs in sich abgeschlossen sind und nicht unmittelbar aufeinander Bezug nehmen würde ich einen Abstand machen. Also
Faust auf blumigen … --> BA zentr. 0,0 (es ist ja schon ein Abstand zur Szene vorhanden)
Dämmerung --> BA zentr. 1,5
Geister-Kreis schwebend --> BA zentr. 1,5
Ariel --> Sprecher 1,5
So haben alle Absätze eine Abstand von 1,5 mm nach oben. 

> Anlass für vergrößerten Abstand nach unten (2,3) sehe ich hier nicht.

Sehe ich auch so. Ich frage mich überhaupt, ob wir dieses Format wirklich zusätzlich zu BA zentr. 1,5 brauchen.

Sehe ich das richtig, dass die BA nach »Ariel« auf neue Zeile soll? Das fände ich hier gut.

**Comment by gerritbruening** [comment]
> Also
Faust auf blumigen … --> BA zentr. 0,0 (es ist ja schon ein Abstand zur Szene vorhanden)
Dämmerung --> BA zentr. 1,5
Geister-Kreis schwebend --> BA zentr. 1,5
Ariel --> Sprecher 1,5

Ja, einverstanden.
Die Gründe dafür sollten sein:
1. Faust auf blumigen … [folgt auf eine Überschrift](https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#ba-nach-%C3%9Cberschrift-kein-auftritt) 
2. Die folgenden BA [folgen jeweils auf eine andere BA und sind nicht Teil einer Replik](https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#ba-nach-ba-nicht-in-figurenrede)
3. Ariel steht in einer [BA, mit der eine Replik beginnt](https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#b%C3%BChnenanweisungen-aus-speaker-und-stage)

Die genannten drei Punkte sollten die Gründe für die Zuweisung der Formate sein,
- damit die Zuweisung auf editorischen Prinzipien beruht
- damit wir nicht bei gut 700 Bühnenanweisungen 700 Einzelentscheidungen fällen (das müssten ja @dietmarpravida und ich tun, und das wollen wir nicht)
- damit @pglatza auf der Grundlage der von mir formulierten XML-Matches die Zuweisung machen kann

Das gute an XML ist: Alle Strukturen, die für die Zuweisung der Formate gebraucht werden, sind darin bereits ausgezeichnet (oder sie werden, wenn sich jetzt Lücken zeigen, nachgetragen). Was eine editorisch relevante Einheit bildet und wie der handschriftliche Befund eingeschätzt wird, steht da alles drin. Das heißt, die Anwendung von editorischen Prinzipien lässt sich 1:1 formulieren als Anwendung von XML-Processing-Regeln.

Was wir uns von dir vor allem wünschen, ist die Umsetzung dieser Prinzipien in ein typographisches Konzept. Dass du dich darüber hinaus auch für die Handschriften und Drucke interessierst, hie und da vielleicht sogar Fehler oder Mängel unserer Transkriptionen entdeckst, ist sehr erfreulich und erleichtert das bestimmt. Trotzdem müsstest du beim Setzen idealerweise versuchen, von diesen Informationen ganz und gar zu abstrahieren, so als gäbe es nur die von uns gelieferten Daten und nichts anderes daneben. Wenn die von uns gelieferte Vorlage aus deiner Sicht keine eindeutige Handhabe für den Satz vorgibt, müsstest du Faksimile und online-Bilder beiseitelegen und uns auf dieses Problem hinweisen. Dann präzisieren wir entweder die Daten oder das Processing.
D.h., Satz ist gleich XML-Informationen, in idml übersetzt, plus typographisches Konzept (plus etwas Feinsatz) -- und nicht XML-Informationen in idml plus Gedanken über Handschriften und Drucke (gilt auch für DP und mich) plus usw., denn das wäre, um wieder philologisch zu werden, "Vorlagenmischung".

**Comment by gerritbruening** [comment]
@pglatza, der Anlass für dieses Issue ist zwar speziell, die von mir vorgeschlagene Lösung aber allgemein. Könnten wir mal gemeinsam schauen, wie sich die [von mir versuchte Zuordnung von Matches zu Absatzformaten](https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#ba-unterschieden-nach-kontext) zu deiner bisherigen Zuweisungspraxis verhält?

**Comment by gerritbruening** [comment]
Teil von #299.

**Comment by gerritbruening** [comment]
Das wichtigste jetzt in https://github.com/faustedition/faust-gen-html/issues/299#issue-298042425.
