### ISSUE TITLE
Scene numbering in scenes.xml

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#258]
See https://github.com/faustedition/faust-gen-html/issues/206#issuecomment-362910441.

AFAICS scene we use this numbering only in the XML, and not throughout the whole corpus.

We may reconsider the scene numbering some day.

**Comment by gerritbruening** [comment]
Hintergrund:
> Die drei- bzw. viergliedrige Zählung wird beibehalten: Die erste Position drückt die Unterscheidung zwischen Faust I („1“) und Faust II („2“) aus. Unter „Faust I“ wird dabei die bibliographisch im Erstdruck gegebene Einheit verstanden, als deren Teil die Rahmentexte zusammen mit „Der Tragödie erster Theil“ erschienen sind. ([Wiki](https://faustedition.uni-wuerzburg.de/wiki/index.php/23._Juli_2014#Z.C3.A4hlvorschlag))

**Comment by dietmarpravida** [comment]
(if this is still an issue)

> A has scene numbering only for TTF

And the other prints? 

@gerritbruening shouldn't we supply scene numbers for all scenes of F-I?

**Comment by gerritbruening** [comment]
Was I too lazy for. Need we that?

**Comment by dietmarpravida** [comment]
>  For processing, some things would be easier with scene numbers

**Comment by thvitt** [comment]
Bei TTF wars nötig weil keine Verse sonst wird zz halt geraten anhand der Versnummern. Wenn da irgendwas nicht passt, könnte man das Problem durch ein explizites `<div n="…"` beheben

**Comment by gerritbruening** [comment]
War im Grunde ein Alibi-Ticket, um die vorgeschlagene Änderung der Szenenzählung aus #206 rauszuhalten.
