### ISSUE TITLE
Neue rechte Seite für TTF

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#259]
Siehe https://github.com/faustedition/faust-gen-html/issues/206#issuecomment-362910441, insbesondere
> TTF muss dann meines Erachtens wiederum auf einer neuen rechten Seite beginnen

Außer in C.1 12 beginnt TTF immer mit einer neuen rechten Seite, weil die Setzer es einrichten konnten, den Walpurgisnachtstraum bis auf die vorhergehende linke Seite laufen zu lassen.
Eine leere vorhergende Seite müsste vermieden werden, um keine falsche Strukturinformation zu vermitteln. Wenn es nicht möglich ist, den Walpurgisnachtstraum auf einer linken Seite beginnen zu lassen, müsste TTF auf einer linken Seite beginnen.
So richtig, @dietmarpravida?

**Comment by dietmarpravida** [comment]
Wapurgisnachtstraum muss wohl auf jeden Fall mit einer rechten Seite beginnen, das scheint mir gar nicht anders möglich, im Vergleich dazu ist ziemlich egal, ob TTF links oder rechts beginnt

**Comment by markusciupke** [comment]
Da der WNT wie Zueignung, Vorspiel, Prolog mit einer Titelseite und einer neuen rechten Seite für die Verse beginnt, würde ich wie dort die folgende Szene ebenfalls auf neuer rechter Seite beginnen lassen. Da der WNT nach meiner Berechnung (vor allem wegen der Wiedergabe der zwei zusätzlichen Strophen im Apparat) auf einer rechten Seite enden wird, ist die Folge, dass vor TTF eine linke Seite leer bleibt. Das aber verdeutlicht umso mehr die Funktion des WNTs als ein in die Handlung eingeschobenes Intermezzo. Ebenso handhabt es Schmidt in der WA, nicht aber Schöne in der FA.

**Comment by gerritbruening** [comment]
Neue rechte Seite mit WNT-Ende auf der gegenüberliegenden linken Seite:
* A
* B
* C.3 12
* JA

Neue rechte Seite nach **leerer** gegenüberliegender linker Seite:
* WA

Neue **linke** Seite:
*  C.1 12
* AA
* FA
* Gaier 2010

**Comment by dietmarpravida** [comment]
Ich habe alle Dramenbände von S als der sorgfältigsten aller Ausgaben eigens durchgesehen; nicht ein einziges Mal gibt es innerhalb eines Dramas eine Leerseite, obwohl ohne Ausnahme alle Akte auf einer rechten Seite beginnen. Beim Walpurgisnachtstraum könnte ich mir - anders als bei den Akten in Faust II, vor denen keine Leerseite stehen sollte - eine Leerseite immerhin vorstellen, würde sie aber gerne vermieden sehen. Wir sollten keine strukturellen Elemente einführen, die in der/den Vorlage/n nicht eindeutig vorgegeben sind, besonders nicht zu einer (vermeintlichen oder echten) Verdeutlichung, denn die Drucke von Faust I weisen eben an einigen Stellen Inkonsistenzen in der Systematik auf, die nicht ohne Not eliminiert werden dürfen, da gerade sie auf handschriftliche Uneinheitlichkeiten zurückgehen können. (Wo sie auf sicher auf die Setzer zurückgehen, wäre es ein nderer Fall.)

**Comment by markusciupke** [comment]
Mit allem einverstanden! – Ich würde genau wie @dietmarpravida den WNT gern auf einer neuen rechten Seite beginnen lassen, könnte mir aber vorstellen die Strophen links beginnen zu lassen,  auch wenn das in A nicht so ist, damit dann TTF auf einer rechten Seite beginnen kann. 
WA steht tatsächlich ziemlich alleine da, aber Gaier und die FA sind nach meiner Ansicht in dieser Frage keine guten Referenzen, da ersterer ansonsten Szenen sogar auf Anschluss setzt, wo wir Gaier ja sicher nicht folgen werden. Wieso sollten wir ihm also in der Frage von TTF folgen? Und die FA lässt die Strophen beim WNT auf der nächsten linken Seite beginnen, was zur Folge hat, dass auch TTF auf einer linken beginnt.  Auf der anderen Seite spart sich die FA aber gegen A die eigene Seite für die Überschrift »Zueignung« und lässt die Verse von Vorspiel sowie Prolog auf neuen rechten beginnen. Das ist alles inkonsequent, hier ist wohl über diese Frage gar nicht nachgedacht worden.

**Comment by gerritbruening** [comment]
> könnte mir aber vorstellen die Strophen links beginnen zu lassen

würde man freiwillig wohl auch nicht machen.

Verschieben wir doch die Entscheidung nach https://github.com/faustedition/faust-gen-html/issues/209 + https://github.com/faustedition/faust-gen-html/issues/211. Da wird doch in Gottes Namen eine Seite bei rausspringen.

**Comment by markusciupke** [comment]
Ein schmalerer Satzspiegel bringt gar nichts: die letzten Strophen kommen trotzdem auf eine rechte Seite. Eine Seite würde nur rausspringen, wenn ihr ganz viel Apparattext verfasst (ohne Apparattext ist momentan nur 1 Strophe auf der letzten rechten Seite des WNT).

**Comment by dietmarpravida** [comment]
WNT links beginnen zu lassen geht m.E. nicht, da nicht auszuschließen ist, dass die Verse in der Druckvorlage von 1806 eine echte Titelseite hatten; dagegen gibt es keinen zwingenden Grund, TTF nicht links bginnen zu lassen, außer dass es nicht gerade schön ist

**Comment by markusciupke** [comment]
In Ordnung: 
• Titel WNT neue rechte Seite
• folgende linke Seite leer
• Strophen WNT neue rechte Seite
• TTF neue Seite (voraussichtlich links)
Das hat immerhin den Vorteil, dass die Szene Kerker dann voraussichtlich links endet (es sei denn, es gibt viel Apparat). Und damit bliebe die linke Seite gegenüber »Der Tragödie zweyter Theil« leer, was sonst nicht der Fall wäre.

**Comment by gerritbruening** [comment]
Wenn sich am WNT nichts drehen lässt, finde ich diese Lösung gut.
Frage zu
> Vorteil, dass die Szene Kerker dann voraussichtlich **links** endet (es sei denn, es gibt viel Apparat). Und damit bliebe die linke Seite gegenüber »Der Tragödie zweyter Theil« leer

 **rechts** endet?

**Comment by markusciupke** [comment]
rechts endet!

**Comment by gerritbruening** [comment]
Gut, dann behandeln wir TTF als einen normalen Fall von `Szene`.
