### ISSUE TITLE
Spacing before lemma ] missing sometimes

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#261]
![grafik](https://user-images.githubusercontent.com/10358005/35864953-790b22e8-0b53-11e8-83e0-6c8862eac14a.png)

**Comment by thvitt** [comment]
da fehlt auch die Sigle für das Lemma, no?

**Comment by gerritbruening** [comment]
Ja, die fehlt! (da müsste `none` stehen).
Das ist die Ursache?
