### ISSUE TITLE
Format Akt

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#262]
Aktanfänge auf linker Seite:
* C.1 41 Faust II,2
* WA Faust II,2
* WA Faust II,5

Aktanfänge auf rechter Seite bei leerer linker Seite kommen in der Tradition des Dramensatzes offenbar nicht vor, sollten also auch bei uns nicht eingeführt werden.

Leere linke Seiten vor Aktanfängen kann ich nicht zugestehen. Wenn sich eine leere Linke Seite nicht vermeiden lässt, muss ein Aktanfang auf neuer linker Seite hingenommen werden.

Der Gebrauch des Formats `Teil / Akt` ist also aufzulösen, oder sein Gebrauch faktisch auf Teil-Überschriften zu beschränken, das Format `Akt` ist einzuführen. @markusciupke, wärst du bereit, das zu tun?

**Comment by markusciupke** [comment]
Das ist mir nie aufgefallen. Nach der raumgreifenden Einrichtung der drei Rahmenteile und dem Beginn des 1. Aktes auf neuer rechter Seite war ich wie selbstverständlich davon ausgegangen, dass Akte auf neuer rechter Seite beginnen. Das habe ich nie überprüft. Tatsächlich wird so aber eine Inkonsequenz geheilt, die in meinem Vorschlag einer hierarchischen Gliederung immer noch besteht, dass nämlich Teile und Akte auf einer Ebene stehen. Dem ist tatsächlich nicht so. Ich habe das in meiner Gliederung nun entsprechend angepasst. Und so bin ich überzeugt und selbstverständlich bereit, das Format Akt mit neuer Seite einzurichten. – Ansonsten muss man sehen, ob sich neuer Akt auf neuer rechter Seite, was  ansich ja schöner ist, nicht vielleicht von selbst oder doch mit behutsamer Nachhilfe ergibt. Aber wenn nicht, dann ist das eben so.

**Comment by markusciupke** [comment]
Ich weiß jetzt, wieso ich gedacht habe, Akte beginnen immer auf einer neuen rechten Seite, auch nach leeren linken: weil es in H immer (!) so ist. Aber das muss für die Einrichtung des Konstituierten Textes natürlich nicht maßgeblich sein.

**Comment by gerritbruening** [comment]
> Und so bin ich überzeugt und selbstverständlich bereit, das Format Akt mit neuer Seite einzurichten.

Danke!
> Ansonsten muss man sehen, ob sich neuer Akt auf neuer rechter Seite, was ansich ja schöner ist, nicht vielleicht von selbst oder doch mit behutsamer Nachhilfe ergibt. 

Das wäre von Vorteil.
> Akte beginnen immer auf einer neuen rechten Seite, auch nach leeren linken: weil es in H immer (!) so ist.

Das ist richtig, das liegt in der Entstehung und Lagenstruktur des Konvoluts begründet. Häufig folgen auf die Akte noch mehrere leere Blätter.

**Comment by gerritbruening** [comment]
Bei dieser Gelegenheit möchte ich auch fragen, ob die Absenkung der Aktüberschriften nicht von von 5 auf 3 Zeilen reduziert werden sollte. Mir scheint nicht recht klar, warum Aktüberschriften stärker abgesenkt sein sollten als Szenenüberschriften.

**Comment by markusciupke** [comment]
Weil Akte hierarchisch über den Szenen stehen und daher eine stärke Betonung in Form einer stärkeren Absenkung erhalten. Ich finde das sinnvoll und auch schön. In H sind sie ebenfalls stark hervorgehoben, und auch in C haben die Akte eine starke Absenkung, die Szenen gar keine.
Aber ich käme auch mit 3 Zeilen Absenkung zurecht.

**Comment by gerritbruening** [comment]
> Ich habe das in meiner Gliederung nun entsprechend angepasst. Und so bin ich überzeugt und selbstverständlich bereit, das Format Akt mit neuer Seite einzurichten.

Danke, dann close ich das hier. Für die noch offene Absenkung sorgt #210.
