### ISSUE TITLE
"Faust" instead of "Der Tragödie zweiter Teil" in Text toc

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#263]
Known bug?

**Comment by thvitt** [comment]
Es wird halt aus den `<titleParts>` genommen. Also ist die aktuelle Anforderung für den Lesetext: Die 2H-Titelseite weg und stattdessen ein `<head>Der Tragödie zweiter Teil</head>`? Gut, machen wir das …

**Comment by gerritbruening** [comment]
Ich denke: 
> wouldn't it be the easiest solutions to just pick out `before_4613_c` from `391098` and insert it at the beginning of the Faust II-`div`?

(https://github.com/faustedition/faust-gen-html/issues/240#issuecomment-362540831) und dementsprechend dann das toc, denn der content von `before_4613_c` ist genau der, der gebraucht wird.
