### ISSUE TITLE
Text und App-Eintrag zu 3356–3357

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#264]
Hier scheint mir die Struktur noch nicht so ganz zu stimmen:

                        <ref>3356–3357 In 1_H.5 bilden 3356–3357 zwei Verse, in S wurde daraus aus Versehen des Abschreibers oder des Setzers nur ein Vers (</ref>
                        <app from="#lem.3356.175">
                           <lem>Und ich, der Gottverhaßte, hatte nicht genug,&lt;i&gt;). [type=2b</lem>
                        </app>

Komisch sind v.a. die Klammern `( ... &lt;i&gt;).`
@dietmarpravida, ist denn der docx-Eintrag in Ordnung so?

**Comment by dietmarpravida** [comment]
Habe den docs-EInrg jetzt geändert, dass er ohne Klammern auskommt, um den Preis allerdings von Auslassungspunkten (die erhlten bleibe müssen):

"[kursiv]In H5 bilden 3356–3357 zwei Verse, in S wurde daraus aus Versehen des Abschreibers oder des Setzers nur ein Vers:[/kursiv[ [recte]Und ich, der Gottverhaßte, hatte nicht genug,[/recte] [kursiv][…]. [Typ 2b][/kursiv]"

**Comment by dietmarpravida** [comment]
Die Struktur scheint immer noch nicht zu stimmen, oder? Ich verstehe oben das `<lem>` nicht so recht. Wo kommt das denn her? Aus dem recte-Zeichenformat in Word?

**Comment by gerritbruening** [comment]
Sollte jetzt passen, vgl. den referring commit.

**Comment by gerritbruening** [comment]
Noch wird nicht der richtige Text hergestellt:

                        <l xml:id="d5270e15830" n="3356 3357">Und ich, der Gottverhaßte, hatte nicht
                                genug,

Beabsichtigt ist:

        <l n="3356">Und ich, der Gottverhaßte,</l>
        <l n="3357">Hatte nicht genug,

Das, @dietmarpravida und @thvitt, müsste erstmal hingekriegt werden.

**Comment by gerritbruening** [comment]
Ich habe jetzt den Apparateintrag in XML geschrieben und bitte @dietmarpravida um inhaltlich-sprachliche Prüfung: https://github.com/faustedition/faust-gen-html/commit/5ec3036337de7dbe6404570fe16f3a1a94630f61#diff-62d902c026cea28dac4c69d62caf0daaR36.

**Comment by gerritbruening** [comment]
@thvitt, wenn du eine Meinung dazu hast, was ich statt dem falschen `<f:ins n="3356" place="only-app"/>` schreiben soll, kannst du mich wieder assignen.

**Comment by thvitt** [comment]
Vorher:
```xml
<l n="3356 3357">Und ich, der Gottverhaßte, hatte nicht genug,</l>
```

Apparatvorschlag, nicht ausprobiert, grad keine Zeit dazu:
```xml
<app>
    <f:replace n="3356">Und ich, der Gottverhaßte, hatte nicht genug,</f:replace>         
    <f:ins n="3356">Und ich, der Gottverhaßte,</f:ins>
    <f:ins n="3356" place="attributes"><l n="3356"/></f:ins>
    <f:ins n="3356" place="after"><l n="3357">Hatte nicht genug</l></f:ins>
    <!-- ref, lem, rdg und so -->
</app>
```

**Comment by gerritbruening** [comment]
@dietmarpravida: http://dev.faustedition.net/print/faust.17#app.3356.only-app

**Comment by gerritbruening** [comment]
OK, danke, habe ich [eingebaut](https://github.com/faustedition/faust-gen-html/commit/8f77cb81ff0c6817323fc23bc3ef76b538be03f5).

**Comment by thvitt** [comment]
Argl: [geht immernoch was schief](http://dev.faustedition.net/print/faust.17#l3356) (After wird auch in der Zeile noch eingesetzt), muss ich in Ruhe debuggen

**Comment by gerritbruening** [comment]
Danke für den Zwischenstand.

**Comment by thvitt** [comment]
0f672d5aa2d978bf494567c0f9bf41325f5b8226
ca4a39484c3b16f2952d2da823be7afa6a1d0d48
