### ISSUE TITLE
br in app entries

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#265]
These are to be replaced by proper markup, aren't they?

**Comment by thvitt** [comment]
ja. Finde nur eine Stelle dazu (4051), das ist eh komisch.

**Comment by dietmarpravida** [comment]
ja, 4051 ist speziell (Verflucht Geschnarr)

**Comment by thvitt** [comment]
4334 kommt gar nicht durch's parsing, [siehe die Validierung](http://dev.digital-humanities.de/ci/job/faust-gen-fast/lastSuccessfulBuild/artifact/target/lesetext/app-validation.html#app2xml). Was soll denn jeweils mit dem Text passieren? Der Apparatteil ist einfach mit den üblichen XML-Tags zu versehen, also tipp `<sp><speaker>Tanzmeister.</speaker><l>…</l>…</sp>` aufrecht im Word, ohne irgendwelche Formatierungen und Linebreaks.

**Comment by gerritbruening** [comment]
Formatvorlagen sind für mich okay, weil TUSTEP daraus gleichnamige saubere XML Tags macht.

**Comment by gerritbruening** [comment]
> da müsste mir gesagt werden, was ich tun soll

Der Anfang sieht so aus:
 
    4051[[<speaker>Mephistopheles.</speaker>]{=}
Nach [den Regeln](https://github.com/faustedition/faust-gen-html/blob/master/text/README-app_norm.md) wäre `4051[]{}` richtig bzw. ausreichend. Eingefügt wird er Eintrag aber auch so.
Was ich nicht so richtig verstehe, ist `[<speaker>Mephistopheles.</speaker>`. Ersetzt werden soll das doch wohl nicht, denn es ist im Vers ja gar nicht vorhanden?

**Comment by dietmarpravida** [comment]
@gerritbruening Geändert wird ja die Zuweisung des Texts dieses Verses (der damit zugeich aus der Replik herusgetrennt wird) von Mephistopheles an Faust. Die ist im Vers nicht handgreiflich vorhanden, ergibt sich aber latürnich aus dem Kontext. Die Kastenklammern sind dafür ungeeignet. Aber wie sonst? Eigentlich muss hier die ganze Mephistopheles-Replik 4041-4059 durch eine M-F-M-Replikenfolge (mit neuer Antilabe in 4051) ersetzt werden.

**Comment by gerritbruening** [comment]
"Ersetzt" werden soll doch gar nichts, oder? Der Text bleibt wie er ist, nur ein Apparateintrag wird eingefügt?

**Comment by dietmarpravida** [comment]
äh, ja. Ändert aber nichts an der Frage, wie der Apparateintrag kodiert werden soll

**Comment by gerritbruening** [comment]
Bei mir kommt in ähnlichem Falle so etwas raus:
`11203[]{} <i>11203–11206</i>] <l>Wir alle fordern</l> <l>Gleichen Theil.</l> <speaker>Mephist.</speaker> <l>Erst ordnet oben</l> <l>Saal an Saal.</l> <i>Ec 2_H [type=6]</i>`
(https://github.com/faustedition/faust-gen-html/blob/master/text/app2norm.txt#L160)

In der Word-Vorstufe habe ich gleichnamige Formatvorlagen. An den Grenzen wie `</l> <l>` füge ich ein geschütztes Leerzeichen ein, damit TUSTEPs import-Makro nicht denkt, die beiden benachbarten `<l>` dürften zusammengefasst werden.
Ich verzichte auf `<sp>`, da dieses Element zu Überlappung führen würde.
Außerdem verzichte ich auf Verszählung. Aber vielleicht brauchen wir die jetzt noch nicht unbedingt.
Wenn dir die Formatvorlagen zu nervig sind, halte dich an @thvitt|s Rat:

> also tipp `<sp><speaker>Tanzmeister.</speaker><l>…</l>…</sp>` aufrecht im Word, ohne irgendwelche Formatierungen und Linebreaks.

**Comment by dietmarpravida** [comment]
4051 (Verszahlen wohl doch nicht so?):
`Verflucht Geſchnarr! Man muß ſich dran gewöhnen.] A B Ba H1 C1 C3  <sp><speaker>Faust.</speaker><l n=4051_I>Verflucht Geſchnarr!</l></sp><sp><speaker>Mephistopheles.</l></speaker><l n=4051_F>Man muß ſich dran gewöhnen.</l></sp>`

nach 4334:
`†nach 4334] In H1 C1 C3 folgen die (ganz oder teilweise auch in H16 und H17 enthaltenen) Verse 4335–4342 (hier wiedergegeben nach H1) [Typ 5*]: <sp><speaker>Tanzmeister.</speaker><l n=4335>Wie jeder doch die Beine lupft! </l> <l n=4336>Sich wie er kann herauszieht!</l> <l n =4337>Der Krumme springt, der Plumpe hupft</l> <l n =4338>Und fragt nicht wie es aussieht.</l><sp><sp></speaker>Fideler.</speaker><l n =4339>Das haßt sich schwer das Lumpenpack</l> <l n =4340>Und gäb sich gern das Restchen;</l> <l n =4341>Es eint sie hier der Dudelsack</l> <l n =4342>Wie Orpheus Leyer die Bestjen.</l><sp>`

**Comment by gerritbruening** [comment]
> `<l n=4051_F>`

Nein, wenn dann mit `"..."` und ganz genau entsprechend der sonstigen Zählung, die hier kein `_F` hat. @thvitt sagt irgendwo, dass wir die Zählung wohl erstmal nicht brauchen. Hier wahrscheinlich tatsächlich nicht. Bei den 8 Zusatzversen wären vielleicht Fünferschritte ganz gut, auch für den Satz.

**Comment by dietmarpravida** [comment]
Die Verszahlen erstmal wegzulassen, ist natürlich kein Problem. Vielleicht sollten wir sie hier überhaupt weglassen? Die Kodierung von 4051 ist m.E. so oder so noch ungelöst.

**Comment by gerritbruening** [comment]
[4051.docx](https://github.com/faustedition/faust-gen-html/files/1725670/4051.docx)

**Comment by gerritbruening** [comment]
`br` kommt im Pipeline-Output nicht mehr vor.
