### ISSUE TITLE
c in app entries

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#266]
See also https://github.com/faustedition/faust-gen-html/issues/265.

Da stehen wohl Kapitälchen oder Großbuchstaben-Formatierungen im docx dahinter.
@dietmarpravida, kannst du mal schauen, ob die alle wegkönnen oder durch propere Formatvorlagen wie `speaker` ersetzt werden könnten?

**Comment by dietmarpravida** [comment]
Die Großbuchstaben-Formatierungen sind im Augenblick **Teil** der speaker-FV. Muss die auch geändert werden? Kapitälchen sollte es keine mehr geben.

**Comment by gerritbruening** [comment]
Ja, ich finde jetzt auch keine < c > tags mehr.
