### ISSUE TITLE
Auslassungspunkte

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#267]
Zum Pre-processing siehe https://github.com/faustedition/faust-gen-html/issues/196.

Für Auslassungspunkte wird vorsorglich ein eigenes Zeichenformat eingeführt: https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#auslassungspunkte.

Im Satz: schauen, ob der [narrow no-break space (U+202F)](http://www.fileformat.info/info/unicode/char/202f/index.htm) in Garamond dargestellt wird. Sonst evtl. mit Sperrung arbeiten?

**Comment by markusciupke** [comment]
Garamond hat natürlich ein eigenes Zeichen für die drei Auslassungspunkte GID 369 bzw. Unicode 2026.
Mit der Bezeichnung narrow no-brak space (U+202F) kann ich nichts anfangen. Was soll damit dargestellt oder bewirkt werden? Schickt mir doch einen kurzen Text, in dem das Zeichen vorkommt, dann können wir testen, was beim Importieren geschieht.

**Comment by gerritbruening** [comment]
Wie sehen denn die drei Auslassungspunkte aus?

Das Problem ist, dass wir folgende Fälle haben
* . .
* . . .
* . . . .
also nicht nur die bekannten drei Auslassungspunkte.

Wie sehen denn die … in der Garamond aus? Oft laufen diese Punkte recht schmal, so dass sie für unsere Zwecke etwas zu gedrängt wirken könnten. Die in der FA laufen sehr weit, da scheint ein ganzes Leerzeichen verwendet worden zu sein.

**Comment by gerritbruening** [comment]
Hier ein kurzer Text mit den schmalen Abständen:

8><   8><   8><
abc . . def . . . ghi . . . .
8><   8><   8><

**Comment by thvitt** [comment]
Hier: . . . .

**Comment by markusciupke** [comment]
Hier ein paar Beispiele zum Vergleich. Mir gefallen die Punkte mit Achtelgeviert Abstand am besten. Das entspricht dem Abstand des Zeichens für drei Punkte in einem.
[Auslassungszeichen.pdf](https://github.com/faustedition/faust-gen-html/files/1705051/Auslassungszeichen.pdf)

**Comment by gerritbruening** [comment]
> Hier ein paar Beispiele zum Vergleich. 

Danke!
> Mir gefallen die Punkte mit Achtelgeviert Abstand am besten. 

Tendiere ich auch zu.

**Comment by gerritbruening** [comment]
Gut, dann brauchen wir kein weiteres pre-processing zwischen online- und Druck-Text, da der Fix von #196 schon für Achtelgeviertabstände zwischen Punkten sorgt. Wenn das nicht der Fall sein sollte, reopen.

**Comment by gerritbruening** [comment]
Handling idml.md dokumentieren, einschl. Leerzeichen davor.

**Comment by pglatza** [comment]
Bis jetzt ist nur das Element `g` für dieses Verhalten definiert.
Wir haben noch nicht besprochene Auslassungspunkte: `<gap reason="ellipsis"/>`. Wie soll sich die IDML-Synthese hier verhalten?

Beispiel in `seg[@xml:id="seg.260.aufslandvomlandaufs"]`

**Comment by thvitt** [comment]
_bis_ #223

**Comment by gerritbruening** [comment]
Die `gap`-Elemente im Apparat (siehe jetzt https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#auslassung) und die Auslassungspunkte in `g` sind "falsche Freunde". Der Attributwert `ellipsis` soll nicht aussagen, dass hier Auslassungspunkte eingefügt werden sollen.

**Comment by pglatza** [comment]
Laut https://github.com/faustedition/faust-gen-html/issues/223#issuecomment-362068609 soll das Wort 'bis' kursiv dargestellt werden.

@gerritbruening, ich hätte dafür das Zeichenformat 'Kursiv (Apparat)' wiederbelebt (https://github.com/faustedition/faust-gen-html/blob/e1224942d8b9c2ce79e6642ee46c9b5017beff13/idml/idml.md#kursiv-apparat). Doch das Format fehlt im aktuellen Stand der IDML-Datei. Deshalb weise ich erst einmal das Zeichenformat 'Kursiv' zu.

**Comment by gerritbruening** [comment]
Markus meinte, die Zeichenformate im Apparat brauchen den Zusatz nicht, weil der Absatzkontext im Bedarfsfall berücksichtigt werden kann. Also müsste einfach 'Kursiv' ok sein.

**Comment by pglatza** [comment]
Gut, dann muss nichts weiter hier passieren.
Nach einer Sichtkontrolle kann das Ticket geschlossen werden.

**Comment by markusciupke** [comment]
In der Datei, die ich heute erhalten habe, sind zwischen den Punkten immer »Geschützte Leerzeichen (feste Breite). Da diese nach meiner Überprüfung sonst nirgendwo vorkommen, kann ich sie durch Achtelgevierte ersetzen. Es kann aber auch irgendein anderes eindeutiges Zeichen zwischen die Punkte gesetzt werden, und ich ersetze sie dann. Ein Zeichenformat benötigen wir dafür nicht.

**Comment by gerritbruening** [comment]
> Geschützte Leerzeichen (feste Breite)

d.h. keine Achtelgevierte? schade

> Da diese nach meiner Überprüfung sonst nirgendwo vorkommen, kann ich sie durch Achtelgevierte ersetzen. ... Ein Zeichenformat benötigen wir dafür nicht.

Gut, dann hoffen, wir dass das so bleibt. Im Apparat gibt es wohl geschützte Leerzeichen geben, aber die wären vom Ersetzen ausgeschlossen?

**Comment by thvitt** [comment]
äh, mach _ich_ irgendwas falsch? Was genau (Unicode-Zeichen) sind denn diese »Geschützte Leerzeichen (feste Breite)« und wo kommen die her? Wirklich das hier? `U+00A0 NO-BREAK SPACE
UTF-8: c2 a0 UTF-16BE: 00a0 Decimal: &#160; Octal: \0240`

**Comment by thvitt** [comment]
Ich kann die Transformation von narrow no-brak space (U+202F) auf thin space (U+2009) ändern (#196) und dann den thin space auch in unserer Webschrift so anpassen, dass er ein Achtel- statt eines Sechstelgevierts (glaub ich) repräsentiert. Dann sollten wir überall diese Dinger haben, es sei denn, @pglatza macht sie weg …

**Comment by pglatza** [comment]
> Dann sollten wir überall diese Dinger haben, es sei denn, @pglatza macht sie weg …
Ja, sollten wir. Die IDML-Synthese reicht die Zeichen alle durch.

**Comment by pglatza** [comment]
@325
