### ISSUE TITLE
Umbruch TTF nach A?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#268]
@dietmarpravida, hier brauchen wir demnächst ein Votum. Wenn du das befürwortest, würde ich zusehen, dass die entsprechenden Zeilenumbrüche (`lb`) konserviert und entsprechend behandelt werden.
Mir scheint das ja immer noch sehr fraglich: Niemand zitiert diese oder irgendeine andere Ausgabe (allenfalls vielleicht noch die WA) nach der Zeilenzählung. Scheint mir überehrgeizig. Zitiert wird eher nach Seiten, und die sind ja nicht A-getreu. Wenn man eine A-getreue Zitierung erlauben wollte, müsste man den Seitenwechsel am Rand markieren und in die Zeile u.U. | setzen.

Im Moment ist wohl der Satzspiegel 15 mm schmaler.

**Comment by dietmarpravida** [comment]
Ich bin da nicht festgelegt; eigentlich entspricht es aber nicht unserem Konzept, A auch bei nichtstrukturellen Elemente nachzubilden, d.h. eher nein, kein Umbruch TTF nach A

**Comment by gerritbruening** [comment]
@markusciupke, kannst du nochmal Stellung beziehen?

**Comment by markusciupke** [comment]
Es war nicht meine Idee, sondern nach meiner Erinnerung die von AB. Ich fand die Idee nicht umcharmant (um DP zu zitieren), aber sie hat tatsächlich auch etwas gezwungenes. Sogar im wörtlichen Sinn, weil ich manchen Zeilenbruch durch sehr weite oder sehr enge Wortabstände erzwingen muss. Letztlich ist die Satzspiegelbreite in Relation zur Schriftgröße auch etwas zu schmal (es sind tatsächlich 15 mm weniger). Weiterhin gefällt mir nicht, dass die Seitenzahlen nicht in einer Linie mit dem Textblock stehen, und man wird sie auf diesen Seiten nicht nach innen ziehen wollen. Also nehme ich meine anfängliche Begeisterung zurück und sage: kein Umbruch nach A.

**Comment by thvitt** [comment]
das führt (in der Annahme, dass die `<milestone unit="reflines"/>` den Umbruch nach _A_ repräsentierten) allerdings zu dem Problem, dass TTF dann online und im Druck anders umbrochen wird – und falls das Ding Zeilennummern bekommt, dass die Zitierung online/Druck auseinanderläuft. Für die Onlineausgabe den Druckumbruch nachcodieren würde dazu führen, dass dies bei _allen_ Zeugen, die TTF haben, geschehen muss, da der Variantenapparat ja über die reflines läuft.

Alternativ hier explizit keine Zeilennumern hin, damit niemand zeilenweise zitiert?

**Comment by markusciupke** [comment]
Verdammt, das stimmt. – Dann aber wäre ein Zeilenumbruch nach A wohl doch eine immerhin begründbare Variante. Der Online-Text orientiert sich jedenfalls bereits an A, vermeidet aber dessen Trennungen. Kommt daher vielleicht die Idee (von wem auch immer geäußert), in der Druckausgabe den Umbruch von A nachzuahmen?
Ich finde, es ist mit den vermiedenen Trennungen nichts halbes und nichts ganzes. – Wie aufwendig ist es denn, für die digitale Ausgabe, den Umbruch von A genau nachzuahmen, mit einem Zeilenzähler zu versehen und die Angaben bei allen Zeugen anzupassen?
Keine Zeilenzählung halte ich für keine  gute Lösung. Wer immer nach der Druckausgabe zitiert, würde entweder nur die Seite unserer Ausgabe angeben, oder für jede Seite eine neue Zählung ab 1 beginnen und mit der Seite nennen, oder er würde die Szene auf eigene Faust (!) durchzählen. Da halte ich es doch für besser, das zu lenken. – Was ist das eigentlich für eine Zählung in grau am rechten Rand? Ich habe dazu nichts gefunden. Die Seitenzählung von A ist es jedenfalls nicht.
Wenn man es also doch so machte, könnte man überlegen, den Text nicht zentriert sondern links, 
auf die Seite zu setzen. Dann wäre der rechte Textrand und der Vers- bzw. Zeilenzähler wenigstens immer an der gleichen Position.

**Comment by markusciupke** [comment]
vorletzte Zeile meint »der linke Textrand« (ich habe offenbar ein links-rechts-Problem).

**Comment by gerritbruening** [comment]
> Wie aufwendig ist es denn, für die digitale Ausgabe, den Umbruch von A genau nachzuahmen, mit einem Zeilenzähler zu versehen und die Angaben bei allen Zeugen anzupassen?

@wissenbach hatte seinerzeit gute Argumente für die Aufhebung der Worttrennungen. Der philologische Purismus hätte sie damals sonst gern gewahrt. Ich kriege die Argumente jetzt nicht mehr zusammen, vielleicht kann Moritz aushelfen?

**Comment by gerritbruening** [comment]
> Was ist das eigentlich für eine Zählung in grau am rechten Rand? Ich habe dazu nichts gefunden. Die Seitenzählung von A ist es jedenfalls nicht.

@markusciupke, kannst du einen Link auf die Seite schicken, wo du das beobachtest? Ich weiß gerade nicht, worauf sich das bezieht.

**Comment by markusciupke** [comment]
Ist nicht beim Konstituierten Text, sondern bei den jeweiligen Varianten. Z.B. in A8 die 221 und 222:
http://beta.faustedition.net/print/A8_IIIB18.26#scene_1.1.23

**Comment by gerritbruening** [comment]
OK, danke.
Doch, das sind die Seiten von A. Warum sollten sie es nicht sein?

**Comment by markusciupke** [comment]
Nun, in meinem Faksimile des Erstdruckes findet sich TTF auf den Seiten 291 bis 294. Ihr sagtet mal mein Faksimile sei parallel zu A 8 gesetzt und deswegen entsprechend nutzbar. – Hat mein Faksimile einen anderen Seitenumbruch? Entschuldigt die dumme Frage.

**Comment by gerritbruening** [comment]
Ach so deswegen. Das ist der Druck hier:
http://beta.faustedition.net/meta/D(1)
"Erstdruck" darf hier nicht im strengen Sinn verstanden werden.
D.1 ist 'satzidentisch' mit A, wg. eventueller Abweichungen muss man sich jedoch vorsehen.

**Comment by markusciupke** [comment]
Okay, A 8 und D 1 sind nicht seitenidentisch gesetzt. Danke.

**Comment by gerritbruening** [comment]
Man könnte auch die Zeilenzählung der digitalen Ausgabe im Druck erscheinen lassen, ohne dass der Umbruch davon bestimmt wird:

    5	dahin! – Verräthrischer, nichtswürdi|ger Geist, und das hast du mir verheimlicht! –
    	Steh nur, steh! wälze die teuflischen Augen ingrimmend im Kopf herum! Steh und trutze 
    	mir durch deine unerträgliche Gegenwart! Gefangen! Im unwiederbringlichen Elend! Bö-
    10	sen Geistern übergeben und der | richtenden gefühllosen Menschheit! Und mich wiegst du 
    	indeß in abgeschmackten Zerstreuungen, verbirgst mir ihren 

Die `|` müsste man nicht erscheinen lassen.
Vorbild wären die Aristoteles-Ausgaben, wo auch die konventionelle Zeilenzählung bei verändertem Umbruch mitgeführt wird.
Beim ersten Anblick wird das aber fehlerhaft wirken, weil es beim Faust keine eingeführte Zeilenzählung gibt.
Ich fände es vertretbar, zwei unterschiedliche Zeilenzählungen zu haben -- es wird niemand bemerken. Die Druckausgabe wird eh immer etwas anders zitiert werden als die digitale.

**Comment by dietmarpravida** [comment]
Der Sinn des Vorschlags erschließt sich mir nicht. Bei Aristotelesausgaben ist es so, dass die Seiten nach Bekker zitiert (und überall mitgeführt) werden, die Zeilen aber oft nach OCT (Oxford Classical Texts)-Ausgaben. In der Reclam-Ausgabe der Poetik ist es wahnsinnig lästig, dass keine sichere Zeilenzählung verfügbar ist, vor aallem weil man die Zeienangben aus der Literatur nicht einfach wiederfindet. Allerdings gibt es dort eben die Zitierkonvention nach Zeilen, was es in der Germanistik so nicht gibt.

**Comment by gerritbruening** [comment]
>  wahnsinnig lästig, dass keine sichere Zeilenzählung verfügbar ist

Ja, stimmt.
> Allerdings gibt es dort eben die Zitierkonvention nach Zeilen, was es in der Germanistik so nicht gibt.

Ja, deswegen sollten wir hier nicht zu viel Wesens machen und die Zeilenumbrüche und Zeilenzählung einfach unterschiedlich sein lassen. 
Der gedruckte TTF-Text wird, wenn überhaupt, nach Seiten gezählt werden. Und die können wir dann, wenn wir wollen, auch online markieren. Es sei denn wir wollen, dass die Seiten von A zitiert werden, dann müssten wir die halt im Druck und online anzeigen.

**Comment by markusciupke** [comment]
Momentan ist TTF nach D.1 gesetzt. Entsprechen die Zeilenbrüche in D.1 denen von A.8? Wenn ja, und wenn wir das also so ließen, bekämen wir einen Zeilenzähler im Textband, der sowohl mit der (virtuellen) Zeilenzählung von A.8 deckungsgleich ist, als auch mit einer (noch einzurichtenden?) Zeilenzählung der Online-Ausgabe, mit Ausnahme derjenigen Fälle nur, in denen das Zitat, auf das mit Zeilenangabe verwiesen ist, ausgerechnet mit einem Wort endet, das in A.8 und im analogen Textband getrennt ist und also eine Zeile darunter endet. Dieser Fall ist recht unwahrscheinlich und kann daher vernachlässigt werden. Wir schlügen also alle Fliegen mit einer Klappe, wenn wir den Umbruch von A.8 exakt nachahmen, und die digitale Ausgabe könnte so bleiben wie sie ist, wenn es zu aufwendig oder technisch zu schwierig ist (wegen Wortsuche?), die Trennungen hier ebenfalls nach A.8 einzurichten.

Nicht gut finde ich »/« oder »|« im Lesetext oder im digitalen Text, und auch den völligen Wegfall einer Zeilenzählung finde ich nicht gut.

**Comment by markusciupke** [comment]
> Der gedruckte TTF-Text wird, wenn überhaupt, nach Seiten gezählt werden.

Ich würde die FA nach den Zeilennummern zitieren, die Schöne dort durchgezählt gibt. Und so würde ich auch mit unserer Ausgabe verfahren, wenn ein Zeilenzähler da ist.

**Comment by wissenbach** [comment]
@gerritbruening, wenn ich mich recht erinnere, hatte ich meine Vorbehalte gegen Worttrennungen aus dem Grund, dass getrennte Wörter eine besondere Kodierung und Behandlung in den weiterführenden Verarbeitungsschritten (Volltextsuche, Kollation, Referenzierung, ...) benötigen. Als Beispiel: Wenn in der Volltextsuche ein Wort gesucht wird, das getrennt auftritt, würde es nicht so ohne weiteres gefunden. Angesichts des geringen Prosaanteils schien mir eine spezielle Kodierung und Verarbeitung unverhältnismäßig.

**Comment by gerritbruening** [comment]
Danke, das ist gut zu wissen.
Ich bitte nun um abschließende Stellungnahme, damit wir hier bald zu einer Entscheidung kommen. Die realistischen Möglichkeiten sind, wenn ich recht sehe:
* Umbruch genau nach A (mit Worttrennungen)
* Umbruch genau nach Online-Edition (ohne Worttrennungen)
* Umbruch gemäß normalem Satzspiegel, unabhängig von A wie auch der Online-Edition

**Comment by markusciupke** [comment]
• Umbruch genau nach A liegt vor und sieht gut aus. 
[TTF wie A8.pdf](https://github.com/faustedition/faust-gen-html/files/1739740/TTF.wie.A8.pdf)
• Umbruch genau nach Online-Edition wäre nur ohne Blocksatz möglich. Das sieht gar nicht gut aus und lässt sich aus der Leseausgabe heraus auch nicht begründen.
• Umbruch gemäß normalen Satzspiegel ist auch gut. Die Relation von Schriftgröße zu Satzspiegelbreite ist hier nicht ganz optimal. Ein etwas schmalerer Satzspiegel wäre besser. Das kann man nur für diese Szene mit Blocksatz machen, aber es steht auch noch ein Test mit schmalerem Satzspiegel für den ganzen Text aus. Für die Grundsatzentscheidung hier spielt diese Frage keine Rolle.
[TTF normal.pdf](https://github.com/faustedition/faust-gen-html/files/1739742/TTF.normal.pdf)

Da es keinen eingeführten Zeilenzähler gibt (die WA zählt sogar die Sprecher und die BA mit), kommt auf jeden Fall ein neuer hinzu. Umbruch nach A hat allein den Vorteil, dass er sich aus A heraus begründen lässt, und dass er darüberhinaus fast genau der Online-Edition entspricht. Künftige Nachweise nach der Druckausgabe würden dann in der Regel auch auf die Online-Edition anwendbar sein (wenn denn dort noch ein Zeilenzähler der Textzeilen eingerichtet wird) und umgekehrt. Deswegen erhält der Umbruch genau nach A mein Votum.

**Comment by dietmarpravida** [comment]
Nach Markus' statement scheint eigentlich das meiste für A zu sprechen; an sich wäre Übereinstimmung mit der Online-Edition zu wünschen, aber die unterscheidet sich ja nur bei den Worttrennungen. 

Der Prosa-Zeilenzähler müsste, wie ich bemerke, noch besprochen werden. Eine Prosazeilenzählung nur der Replikentextzeilen und ohne Berücksichtigung der Parazeilen (sit venia verbo) ist mir (glaube ich) noch nicht vorgekommen.  Sollte wir also so verfahren werden wie WA? @thvitt: Oder wäre es für die Zählung des Onlinetextes einfacher, nur Replikzeilen zu zählen?

**Comment by thvitt** [comment]
In der Onlineausgabe behandeln wir TTF ja so, als ob es ebenfalls Verse wären. Für die Zählung wär's da am einfachsten, wenn nur der Sprechtext gezählt würde, da wir dann für die Zeilennummern einfach von den [in der α sichtbaren](http://dev.faustedition.net/print/faust.26#scene_1.1.23) `ttf_`-Labels den nummerischen Anteil nehmen können

**Comment by dietmarpravida** [comment]
Dann scheint mir nahliegend, dass wir das im Buchtext auch so machen sollten, oder? Es ist dann die einzige Stelle, wo wir eine ganz eigene neueingeführte Zählung haben.

**Comment by markusciupke** [comment]
… die sich aber immerhin am Satz der Erstausgabe orientiert.

**Comment by dietmarpravida** [comment]
@markusciupke  Bei den Trennungen in der pdf habe ich aber noch ein Problem: ich würde gern nur an Wortbildungsfugen trennen, also "unend-licher", nicht "unendli-cher". Außerdem stehen mir hier zu oft (z.B. in der ersten Replik) zwei Trennungen hintereinander, A hat das klugerweise vermieden. Ich möchte zwar nicht A einfach nachbilden, eher im Gegenteil, aber an dessen Worttrennungen kann man sich ein Vorbild nehmen. D.1 ist ein umbrochener Satz von A8, der die Zeilengrenzen nicht bewahrt, an dem darf man sich nicht orientieren. Hier ist ein Link auf A8: https://books.google.de/books?id=GQVUAAAAcAAJ&printsec=frontcover&hl=de#v=onepage&q&f=false

**Comment by markusciupke** [comment]
Bei deinen Trennungswünschen bin ich total bei dir, aber in A8 ist nun mal leider »unendli-cher« getrennt. Und jetzt versteh ich nicht was A ist. Kannst du mir einen Link zu A senden, dann kann ich den Umbruch danach einrichten.

**Comment by dietmarpravida** [comment]
Ups, in der Ausgabe bei dem Link wird "unendli-cher" getrennt, in der mir vorliegenden Ausgabe (zugeich Vorlage der Edition) aber "unend-licher"! Das ist mir ganz neu. @gerritbruening Wir müssen Markus unser Digitalisat von A8 zur Verfügung stellen. Und die Trennungen in den verschiedenen Ausgaben von A klären (*seufz*).

**Comment by markusciupke** [comment]
Da haben sich unsere Comments exakt gekreuzt. Aber was für eine schöne Ausgabe liegt dir denn vor?

**Comment by gerritbruening** [comment]
Na Wunderbar, ein Doppeldruck!

**Comment by markusciupke** [comment]
… wo der Setzer noch ein wenig gebessert hat?

**Comment by dietmarpravida** [comment]
Ich gebe hier mal die Trennungen in A8 nch meinem Exemplar an:
Seite 221,3/4 Ge-schöpf
221.10-11 ver-birgst
221.13-14 unend-licher
222.19-20 er-scheinen
222.2-3 Ver-derben
223.6-7 Verlegen-heiten
223.9-10 Er-schlagenen

**Comment by markusciupke** [comment]
Weiterer kleiner Hinweis: in der Ausgabe vom Link steht »Wandl«, im digitalen Text aber »Wandl’«.

**Comment by dietmarpravida** [comment]
NB die verlinkte Ausgabe hat anscheinend dieselben Worttrennungen wie D1. Daraus ergibt sich wohl, dass noch einmal Exempaare von A gesetzt wurden, nachdem der Satz schon einmal für D.1 umbrochen worden war. Oje, ich sehe lange Nächte auf mich zukokmmen.

**Comment by thvitt** [comment]
A8's XML hat die `<lb>` korrekt incl. der Trennungen, dh. wenn Gerrits 
https://github.com/faustedition/faust-gen-html/commit/5d0fa1bfdc3442eec2f44783123bd019ae5aece8 durch ist, kann auch einfach an denen umbrochen werden. Die Zeilenzählung ist dann vom in der Zeile liegenden `<milestone unit="refline"/>` zu nehmen. 

In der Onlineausgabe wird an den `<milestone>` getrennt und die lb weggeschmissen damit die Synopse vernünftig klappt.

**Comment by dietmarpravida** [comment]
Äh, entschuldigung für die Aufregung, Ich nehme alles zurück. Ich hatte gerade die ganze Zeit nicht mit einem Exemplar von A8, sondern von B9 gearbeitet. Schade eigentlich.

**Comment by markusciupke** [comment]
Schade, dass wir nicht B9 als Vorlage nehmen können, dann wären die Trennungen schöner. – Wenn wir denn die Trennungen nach einer historischen Vorlage einrichten wollen. Bleibt es nun dabei?

**Comment by dietmarpravida** [comment]
Das ändert ber nichts an dem Schverhaalt, dass B9 bei prinzipielll gleicher Einrichtung die besseren (regelgerechteren) Trennungen enthät, Da wir überhaupt kein Interesse daran haben können (wie ganz oben schon einmal bemerkt), A8 in seinen nicht-strukturellen Details - wozu die Worttrennungen rechnen - nachzubilden, wäre es daher trotzdem überlegenswert, die Trennungen von B9 zu übernehmen:

221,3-4 Ge-schöpf
221.10-11 ver-birgst
221.13-14 unend-licher
222.19-20 er-scheinen
222.2-3 Ver-derben
223.6-7 Verlegen-heiten
223.9-10 Er-schlagenen

**Comment by markusciupke** [comment]
Ich sehe keinen Sinn darin, den Text von A8 zu nehmen und die Trennungen von B9. Und der Zeilenfall führt dann nun mal zu größeren Abweichungen zur digitalen Edition als das bei Satz nach A8 der Fall ist (ab wann wären hier Abweichungen zu groß, wer legt das wie fest?). Dann müsste man die digitale Edition doch auch ändern. Aber wie gesagt, will man hier wirklich eine Mischung von A8 und B9?

**Comment by dietmarpravida** [comment]
(sorry, den letzten Beitrag von @markusciupke hatte ich bei Niederschrift meines letzten Posts noch nicht gelesen) Ich würde bei prinzipieller Orientierung am Zeilenfall von A8 die Worttrennungsstellen von B9 nehmen (es muss auch nicht in jedem einzelnen Fall dieselbe sein), wir wollten ohnehin nie eine dokumentarische Wiedergabe von A8 anstreben, gerade nicht bei solchen Fällen unsorgfältiger und hässlicher Trennungen.

**Comment by gerritbruening** [comment]
Eigentlich nicht.

> bei prinzipieller Orientierung am Zeilenfall von A8 die Worttrennungsstellen von B9 nehmen (es muss auch nicht in jedem einzelnen Fall dieselbe sein)

Scheint mir nach wie vor tragfähig.
Ich muss noch schauen, ob in der XML das Richtige rauskommt.

**Comment by markusciupke** [comment]
Das muss ich doch sowieso im manuellen Satz machen. Da ihr euch nun für die Trennungen nach B9 entschieden habt (ich fände Trennungen nach A8 weiterhin besser), mache ich das nach obiger Liste. Eventuelle Korrekturen könnt ihr dann in der 1. Fahne vornehmen.

**Comment by gerritbruening** [comment]
In den Daten ist alles da.
