### ISSUE TITLE
Format Leerzeile wird doch gebraucht

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#269]
Siehe https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#leerzeile. @markusciupke, bist du einverstanden, wenn das erzeugt wird?

**Comment by markusciupke** [comment]
Natürlich kann ich zwei Formate einrichten die Leerzeilen 2 und Leerzeilen 5 heißen können.
Wenn du mich nach meiner Meinung dazu fragst: 
An der ersten Stelle würde ich es nicht machen. Hier hat der Schreiber möglicherweise Platz gelassen, damit später eventuell noch weitere Verse eingefügt werden können, was aber nicht mehr geschehen ist. – Wenn man das hier macht, müsste man sowas wohl auch an weiteren Stellen machen, z.B. nach 5572, wo möglicherweise noch Platz gelassen worden ist für einen weiteren Vers. Und nach 6306 habe ich mich schon immer gefragt, ob die drei leeren Seiten nicht eingefügt oder gelassen worden sind, um eventuell noch Fausts Gang zu den Müttern auszuführen. Wie reagiert man dann auf so etwas im Konstituierten Text?
An der zweiten Stelle willst du vermutlich Eckermanns Umstellung weglassen und stattdessen 5 Leerzeilen setzen? Ich bin skeptisch. Eckermanns Umstellung wegzulassen ist deine Herausgeberentscheidung. Aber die Leerzeilen wären eine Zugabe, die man dann wohl ebenfalls auch an anderen Stellen machen müsste, z.B. nach 4665?

**Comment by gerritbruening** [comment]
Es ist schon richtig, man kann nicht aus jedem Freiraum eine Lücke im Text ableiten.

Zu 5572: Lücke von ursprünglich zwei Versen, die mit einem Vers gefüllt wurde. Die Lücke ist damit geschlossen.

Zu 6306: Leere Seiten nach Szenen kommen öfters vor. Dass hier der Gang zu den Müttern fehlt, ist entstehungsgeschichtlich belegt, aber man würde nicht so weit gehen, aus leeren Seiten generell fehlende Szenen abzuleiten und diese durch Lücke zu repräsentieren.

Zu 6358: Ohne Eckermanns Änderung folgen zwei Reden Mephistos aufeinander (siehe die Sprecherbezeichnung auf der folgenden Seite).

Wir wollen das weitere abwarten.

**Comment by gerritbruening** [comment]
Ist jetzt Format `Eine LZ`.
