### ISSUE TITLE
rdg/titlePart --> rdg/head

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#270]
<rdg>
                        <titlePart>Faust.</titlePart> 

Sowas ist wohl nach der neuen Logik nicht zulässig, es müsste `head` heißen, richtig?

**Comment by thvitt** [comment]
worum gehts? in {insert} sollte `head` stehen, was Du in den Apparat schreibst, ist mir wurscht; `titlePart` bliebe als titlePart im note stehen.
