### ISSUE TITLE
Absatzformat für space[@unit = 'lines'][@quantity]

### ISSUE THREAD

**Issue by pglatza** [faustedition/faust-gen-html#272]
In der InDesign-Vorlagendatei stehen verschiedene Formate zur Auswahl (bspw. Viertel, Halb, Ganz). Welches soll hier zugewiesen werden?

Ich würde die IDML-Synthese darauf einrichten, dass entsprechend dem Wert in @quantity genauso viele Absätze (Zeilen) generiert und dem Absatzformat zugewiesen werden?

**Comment by gerritbruening** [comment]
> welches

Ganz!
> entsprechend dem Wert in @quantity genauso viele Absätze (Zeilen) 

Ja, das wäre genau richtig!

**Comment by gerritbruening** [comment]
Siehe auch https://github.com/faustedition/faust-gen-html/issues/269.

**Comment by pglatza** [comment]
Ist in der IDML-Synthese nun auch so umgesetzt.
