### ISSUE TITLE
Unvollständige Note (before_12045_b)

### ISSUE THREAD

**Issue by pglatza** [faustedition/faust-gen-html#273]
Fehlt der note 'before_12045_b' eine schließende runde Klammer?

`  <note n="before_12045_b">(St. Joh. IV.</note>`

**Comment by pglatza** [comment]
Wem sollen Issues, welche XML betreffen zugewiesen werden?

**Comment by gerritbruening** [comment]
mir!

**Comment by gerritbruening** [comment]
> Fehlt der note 'before_12045_b' eine schließende runde Klammer?

Ja, das ist richtig. Bei Interesse kannst du mal einen Blick auf die Handschrift werfen:
http://beta.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=383&view=facsimile#lbefore_12045_a
(unter Hälfte)

**Comment by gerritbruening** [comment]
Ich nehme das mal als Anstoß, hier doch eine Änderung des ursprünglichen Textes vorzunehmen.
