### ISSUE TITLE
non-textcrit notes in reading text

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#274]
![grafik](https://user-images.githubusercontent.com/10358005/35976680-2e6ac542-0ce1-11e8-9661-6bd3ee108f05.png)

Idealerweise würden diese `note`s in derselben Zeile landen wie der `speaker`, da `rend="inline"`. Auch eine eigene Zeile wäre schonmal ein Fortschritt (so wie jetzt denkt man, die Anmerkung stünde hinter dem Vers).

**Comment by thvitt** [comment]
* wieso ham die ein n wenn sie inline sind?
* das rend='inline' kommt im Lesetext nicht an, irgendwo wird das wohl weggeräumt
* ist die Semantik von <note rend="inline">, dass die note in das vorhergehende Element hineingehört?
* der Screenshot ist gar nicht aus dem Lesetext. Da steht eine Seitenzahl drin.

**Comment by gerritbruening** [comment]
> * wieso ham die ein n wenn sie inline sind?

Aus demselben Grund wie `stage` (direkt im Anschluss in derselben Zeile).
> * ist die Semantik von `<note rend="inline">`, dass die note in das vorhergehende Element hineingehört?

s. vorige Antwort
> * der Screenshot ist gar nicht aus dem Lesetext. Da steht eine Seitenzahl drin.

Richtig, korrigiere ich sofort.

**Comment by thvitt** [comment]
für `<stage rend="inline">` haben wir auch keine andere Behandlung als für andere `<stage>`. Sollte das anders sein?

Ein Problem ist, dass der durch das `@n` getriggerte Aufklappmechanismus nicht funktioniert, wenn die zugehörigen HTML-Elemente etwas anderes als eigene Zeilen sind.

**Comment by gerritbruening** [comment]
> Ein Problem ist, dass der durch das `@n` getriggerte Aufklappmechanismus nicht funktioniert, wenn die zugehörigen HTML-Elemente etwas anderes als eigene Zeilen sind.

Ja, richtig. Dann bleiben alle `@n`-Elemente online hübsch eigene Zeilen. Und `@rend` wird nur für das idml mitgeschleppt.

**Comment by thvitt** [comment]
https://github.com/faustedition/faust-web/commit/d56b903dfba1ac513a64d0d040cb3d56ff5a047f
