### ISSUE TITLE
 Ersatz für Caret^

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#275]
(steht für fehlende Interpunktion Apparateinträgen)

Evtl. dasselbe Zeichen auf Höhe der Grundlinie möglich?

**Comment by markusciupke** [comment]
In InDesign können wir das ^ über ein Zeichenformat in jeder beliebigen Größe auf jede beliebige Höhe setzen. Auch auf die Grundlinie.

**Comment by thvitt** [comment]
Sagt mal, es ist vllt am einfachsten für alles, dieses ^ gleich beim Prozessieren des Apparats (app2xml.py) zu TEIcodieren – es kommt ja nur aus dem Apparat vor. Und es kann natürlich online auch irgendwie hoch/tief/sonstwie gestellt werden, von mir aus sogar blinken, das kann Indesign nicht :P 

`<c>`? `<g>`?

**Comment by gerritbruening** [comment]
<pc> punctuation character

**Comment by gerritbruening** [comment]
< pc >

**Comment by thvitt** [comment]
Achja, dieses Unicodezeichen gibt's noch:

U+2038 CARET
UTF-8: e2 80 b8 UTF-16BE: 2038 Decimal: &#8248; Octal: \020070
‸
Category: Po (Punctuation, Other)
Unicode block: 2000..206F; General Punctuation
Bidi: ON (Other Neutrals)

Bsp.  _4877_ Ich?] _H_   Ich‸ _I H.0a (II aa)_

**Comment by gerritbruening** [comment]
Sieht gut aus!

**Comment by thvitt** [comment]
(Muss in Ubuntu auch ergänzt werden)

**Comment by thvitt** [comment]
Hab das jetzt mal im Apparat eingesetzt, ihr könnt ja mal schauen, was die Schriften für den Druck dazu sagen. Ich habe auch mal ein provisorisches Zeichen in die Ubuntu Faust gebastelt für die Webausgabe, Feedback welcome. Vermutlich musses noch dünner werden oder so.

**Comment by gerritbruening** [comment]
Sieht für mich sehr gut aus!
Manchmal scheint für mich ein Abstand davor zu stehen, besonders offenbar wenn es ein `speaker` ist. Ist das Absicht so?

**Comment by thvitt** [comment]
ich habe keine besonderen kerning pairs definiert, d.h. wenn irgendwo ein Abstand ist, ist das entweder eine optische Täuschung oder ein Effekt des Schriftwechsels oder ein Bug. Wo denn?

**Comment by gerritbruening** [comment]
`lbefore_2429_b`

![grafik](https://user-images.githubusercontent.com/10358005/36097356-ebd6768c-0ffa-11e8-8646-ef2dd9ea55bc.png)

**Comment by thvitt** [comment]
Da ist extrawhitespace, siehe extrabug.

**Comment by gerritbruening** [comment]
Gut. Solange es InDesign auch darstellen kann.

**Comment by markusciupke** [comment]
Wenn ich es richtig sehe, habe ich dieses Zeichen noch nicht in meiner Datei. Kann auch daran liegen, dass die Apparat-Texte bislang nur unvollständig rübergekommen sind. Verstehe ich richtig, dass bei Varianten wie vor 2256 »ALTMAYER leise. S  ALTMAYER leise A« hinter das zweite leise ein tiefgestelltes »^« soll?

**Comment by pglatza** [comment]
Richtig, die Behandlung der Apparat-Text hatte ich zwischenzeitlich wieder hinten angestellt. Deshalb ist das Zeichen neben anderen (XML-)Elementen momentan noch nicht sichtbar.

**Comment by pglatza** [comment]
Das Caret-Zeichen, also U+2038 wird von der gewählten Schrift in InDesign nicht unterstützt und deshalb als Viereck mit Kreutz dargestellt.
In der kommend bereitgestellten Version der IDML-Synthese wird dieses Zeichens nun erstmal durch Circumflex Accent, also U+005E ersetzt.

**Comment by gerritbruening** [comment]
Scheint mir das praktikabelste.
@markusciupke, könntest du dann schauen, ob du ein tiefgestelltes Caret daraus machen kannst?
Vgl.
![grafik](https://user-images.githubusercontent.com/10358005/40608857-2e2200be-626d-11e8-8e3d-de48a7faab30.png)

**Comment by markusciupke** [comment]
Hab ich in der Datei, die ich gestern abend an euch drei gemailt habe, bereits gemacht. Allerdings habe ich das Caret auf die Grundlinie gestellt. Der obigen Ansicht zufolge soll die Spitze des Carets von unten an die Standlinie stoßen? Wenn ja, richte ich das im nächsten Gang so ein.

**Comment by gerritbruening** [comment]
> auf die Grundlinie gestellt ... von unten an die Standlinie

Scheint mir beides möglich, müsste man sich anschauen.
Was ich meinte, war eher das Zeichen selbst (Strichstärkenunterschied, optischer Grad des Winkels). So sieht es sehr nach dem Akzent aus, und das ist eine Assoziation, die idealerweise vermieden werden sollte.

**Comment by markusciupke** [comment]
In Ordnung. Varianten folgen beim nächsten Gang.

**Comment by gerritbruening** [comment]
JFTR:
> Das Caret-Zeichen, also U+2038 wird von der Schrift nicht unterstützt und deshalb als Viereck mit Kreutz dargestellt. Ich habe es wie in Issue 275 geschrieben durch das ^-Zeichen ersetzt und das Zeichenformat Tiefgestellt zugewiesen. Hier müsste noch etwas an der Gestaltung gewerkelt werden.

**Comment by markusciupke** [comment]
> Hier müsste noch etwas an der Gestaltung gewerkelt werden.

Hab ich ja bereits gemacht, und weitere Varianten folgen beim nächsten Gang.

**Comment by gerritbruening** [comment]
Ich weiß, deswegen "JFTR" (hieß hier so viel wie zu Archivierungszwecken)

**Comment by markusciupke** [comment]
Ich kann es so aussehen lassen wir oben: also Winkel (kein Akzent)
1.  mit der Spitze von unten an die Grundlinie stoßend
2. auf halber Höhe der Grundlinie
3. mit den Enden auf der Grundlinie stehend
[Caret.pdf](https://github.com/faustedition/faust-gen-html/files/2062868/Caret.pdf)
Mein Caret ist aus der verwendeten Schrift. Wenn der Winkel oder die abgeflachte Spitze nicht gefallen, kann ich auch ein anderes aus einer anderen Garamond nehmen
[Caret spitz.pdf](https://github.com/faustedition/faust-gen-html/files/2062886/Caret.spitz.pdf)
Wenn euch die Größe des Caret nicht gefällt, sagt mir ob größer oder kleiner.
Könnt ihr euch schon entscheiden?

**Comment by gerritbruening** [comment]
@dietmarpravida, hast du eine Tendenz?

**Comment by dietmarpravida** [comment]
Caret spitz, den ersten Kandidaten (mit der Spitze an der Grundlinie, wenn ich recht sehe?)

**Comment by markusciupke** [comment]
In Ordnung. Caret spitz, obere Variante, mit der Spitze an der Grundlinie.
Sind die Proportionen so recht, oder soll das Zeichen etwas größer oder kleiner?

**Comment by dietmarpravida** [comment]
dazu würde ich gern ein realistisches Beispiel sehen, an diesem pdf ist das nicht leicht zu entscheiden

**Comment by markusciupke** [comment]
Die Apparatschrift ist 8 pt groß. Ich habe von einer Beispielseite fünf Varianten gemacht: 6 pt, 7 pt, 8 pt, 9 pt und 10 pt.
Sucht euch eine aus.
[Caret spitz 6 pt.pdf](https://github.com/faustedition/faust-gen-html/files/2077848/Caret.spitz.6.pt.pdf)
[Caret spitz 7 pt.pdf](https://github.com/faustedition/faust-gen-html/files/2077849/Caret.spitz.7.pt.pdf)
[Caret spitz 8 pt.pdf](https://github.com/faustedition/faust-gen-html/files/2077850/Caret.spitz.8.pt.pdf)
[Caret spitz 9 pt.pdf](https://github.com/faustedition/faust-gen-html/files/2077851/Caret.spitz.9.pt.pdf)
[Caret spitz 10 pt.pdf](https://github.com/faustedition/faust-gen-html/files/2077852/Caret.spitz.10.pt.pdf)

**Comment by dietmarpravida** [comment]
ich bin eigentlich für 6 pt

**Comment by markusciupke** [comment]
im App zu  260 fehlt zwischen dem Caret und »bis« das LZ.

**Comment by gerritbruening** [comment]
Das scheint glücklicherweise nur beim ersten Carat passiert zu sein.
Ich zähle 94x ^. Könntest du mal zählen, wie oft `^`+` ` vorkommt? Hoffentlich zumindest 93 mal.

**Comment by markusciupke** [comment]
Caret  + LZ kommt 80 mal vor. Abzüglich der von mir korrigierten Stelle sind also 79 von 94 korrekt.

**Comment by gerritbruening** [comment]
> Caret + LZ kommt 80 mal vor.

Das ist mit Blick auf #246 kein gutes Zeichen.
Im IDML sieht das so aus:

```xml
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
                     <Content>auf’s Land</Content>
                  </CharacterStyleRange>
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Tiefgestellt">
                     <Content>^</Content>
                  </CharacterStyleRange>
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
                     <Content> </Content>
                  </CharacterStyleRange>
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Kursiv">
                     <Content>bis</Content>
                  </CharacterStyleRange>
```
D.h., `^`, dann ` `, dann `bis`, so wie es sein soll. Wenn der bei dir auch nicht rüberkommt, mache ich mir langsam Gedanken.

**Comment by gerritbruening** [comment]
Ich würde nun sowohl was dieses als auch das Issue #387 betrifft, @pglatza bitten, die Verluste von Inhalten auf einer eigenen ID-Instanz zu reproduzieren.
@markusciupke würde ich bitten, die weiteren Vorkommen verlorener Leerzeichen zu notieren.
