### ISSUE TITLE
Apparateintrag Zusatzverse nach 4334

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#276]
Der wird im Moment nicht geparst.
Außerdem muss der innere Aufbau geklärt werden. Statt `<br/>Wie jeder doch die Beine lupft!<br/>` wäre Formatvorlage `l` gut, oder halt wie von @thvitt vorgeschlagen gleich richtige XML-Tags.

**Comment by gerritbruening** [comment]
Wenn das gemacht ist, label:idml ergänzen.

**Comment by dietmarpravida** [comment]
wo soll Formtvorage l hin, über die ganze Zeile? Und was ist mit den speakern?

TANZMEISTER. 
Wie jeder doch die Beine lupft! 
Sich wie er kann herauszieht! 
Der Krumme springt, der Plumpe hupft
Und fragt nicht wie es aussieht. 

FIDELER. 
Das haßt sich schwer das Lumpenpack
Und gäb sich gern das Restchen; 
Es eint sie hier der Dudelsack
Wie Orpheus Leyer die Bestjen.

**Comment by gerritbruening** [comment]
Ja, ganze Zeile markieren und Formatvorlage `l` zuweisen, ebenso mit `Tanzmeister.` verfahren. Was du mit Formatvorlage nicht unterbringst, sind Verszahlen. Wenn du direkt an den Anfang `n="..."` reinschreibst, kann ich das hinschubsen.

**Comment by dietmarpravida** [comment]
Ich gebe H.1 wieder. 

Sollen die `n="..."` in Verkehrshütchen, oder wie?

**Comment by gerritbruening** [comment]
Ist vielleicht erstmal eine Frage an @thvitt: Brauchen wir die saubere Zählung in den Apparateinträgen?

**Comment by thvitt** [comment]
Was soll denn überhaupt mit den Apparateinträgen geschehen? Wenn die nur angezeigt werden sollen, brauchen wir da gar keine Zählung. Wenn irgendwas mehr passieren soll (Versnummern anzeigen, Synopse …) muss man nochmal über Details nachdenken, aber dann sollte eine Zählung in n schon sein. (Verkehrshütchen?)

**Comment by gerritbruening** [comment]
> Verkehrshütchen?

auf die Seite gelegte: `<`, `>`

**Comment by gerritbruening** [comment]
Kodiere ich direkt in XML.

**Comment by dietmarpravida** [comment]
das dürfte abgeschlossen sein, oder?

**Comment by gerritbruening** [comment]
Nach https://github.com/faustedition/faust-gen-html/commit/daa418fda8ed34e23653ffe465b2bb5847ceaede könnte es funktionieren. @dietmarpravida, bitte morgen prüfen und im Gelingensfall closen.
