### ISSUE TITLE
Apparateinträge für Antilaben

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#277]
Pensum wie #276.

Wenn die Struktur geklärt ist, label:idml hinzufügen.

**Comment by dietmarpravida** [comment]
gehts ein bisschen genauer?

**Comment by gerritbruening** [comment]
Ja. Wir müssen erstmal die gewünschte Darstellung klären. Also, ob alles in einer Zeile erscheinen soll, abgetrennt mit Schrägstrichen oder so, oder ob Verse und Sprecher auf eigene Zeilen sollen.

**Comment by dietmarpravida** [comment]
Es handet sich in Faust I wohl nur um "3550–3551] In H5 bilden 3550–3551 einen antilabischen Vers: GRETGEN Ach / LIESGEN Ja so ist’s ihr endlich gangen. [Typ 2d*]". Da wir für Versgrenzern einen | nehmen, wäre hier vielleicht ein gebrochener vertikaler Strich und inine-Text am besten, wenn es sowas gibt? Wenn nicht, dann vielleicht wie Verse auf zwei Zeilen .setzen

**Comment by gerritbruening** [comment]
Siehe https://github.com/faustedition/faust-gen-html/blob/master/text/app12norm_special-cases.xml#L74.

Der Text steht in `quote`, würde also wie vorgeschlagen behandelt werden. Wäre es hier aber nicht gerade wichtig, die Antilabizi... typographisch sichtbar zu machen.
Vielleicht kann @markusciupke sich dieses Falls probeweise annehmen.

**Comment by markusciupke** [comment]
Das wäre mal ein erster Versuch:
[App zu 3550 f.pdf](https://github.com/faustedition/faust-gen-html/files/2002725/App.zu.3550.f.pdf)
Vielleicht könnt ihr von da aus eure Vorstellungen beschreiben und mitteilen.

**Comment by gerritbruening** [comment]
Scheint mir gut, abgesehen vom Replikenabstand. Den würde ich in Apparateinträgen evtl. der Kompaktheit zuliebe einsparen.

**Comment by markusciupke** [comment]
Das sieht dann so aus:
[App 3550-3551.pdf](https://github.com/faustedition/faust-gen-html/files/2004159/App.3550-3551.pdf)

**Comment by dietmarpravida** [comment]
finde ich okay. Muss es eigens kodiert werden und wie?

**Comment by gerritbruening** [comment]
Kodiert ist es schon, behandelt nach Ausnahmeregel #454.

**Comment by dietmarpravida** [comment]
[Typ 2d*]

**Comment by markusciupke** [comment]
Hier noch mal mit 2 LZ nach der Versangabe und mit Typ. Online sind die Typen römisch gezählt, und so habe ich das in den bisherigen Beispielen auch übernommen. Sollen die arabisch gezählt werden?
Zwischen II und d ist ein Vierundzwanzigstelgeviert.
[App 3550-3551 mit Typ.pdf](https://github.com/faustedition/faust-gen-html/files/2005182/App.3550-3551.mit.Typ.pdf)

**Comment by markusciupke** [comment]
Und noch was: mit eckigen Klammern wie oben oder mit runden, wie ich es bisher gemacht habe? – Letztlich müsst ihr das natürlich richtig einrichten. Ich frage nur für die Probelayouts.

**Comment by dietmarpravida** [comment]
Soll (IId*) (ja, so) alinea links stehen? Vielleicht eher auf der Zeile 3551 rechts (ungefähr auf der Höhe von "Vers")?

**Comment by markusciupke** [comment]
Ich dachte halt, dass nur die zitierten Absätze auf neuer Zeile und eingerückt sind (mit Tab um 6mm), und dass ansonsten der Apparat-Text linksbündig steht.
Habe die Typ-Angabe jetzt hinter den zitierten Vers 3551 gesetzt und 5 Gevierte eingefügt, um sie auf die Höhe von »Vers« zu bringen. Aber das ist ja ziemlich beliebig und zufällig. Wäre die erste Zeile länger oder kürzer, würde dann die Typ-Angabe entsprechend weiter rechts oder links stehen? Das wäre ein sehr untypisches Prinzip für die Ausgabe.
[App 3550-3551 mit Typ rechts.pdf](https://github.com/faustedition/faust-gen-html/files/2005320/App.3550-3551.mit.Typ.rechts.pdf)

**Comment by markusciupke** [comment]
Habe mir das noch mal angeschaut und mit dem Apparat zu 4335-4342 verglichen. Hier steht die Typ-Angabe vor dem Zitat. Auch ist hier kein Doppelpunkt gesetzt. Ich hab mal den Apparat zu 3550-3551 entsprechend umgesetzt. Ist vielleicht die eleganteste Lösung.
[App 4335-4342 mit Typ vor Zitat.pdf](https://github.com/faustedition/faust-gen-html/files/2005379/App.4335-4342.mit.Typ.vor.Zitat.pdf)
[App 3550-3551 mit Typ vor Zitat.pdf](https://github.com/faustedition/faust-gen-html/files/2005382/App.3550-3551.mit.Typ.vor.Zitat.pdf)

**Comment by dietmarpravida** [comment]
Stimmt, finde ich auch besser so und würde das so machen wie vorgeschlagen.  @gerritbruening Wo sind denn die Doppelpunkte abgeblieben?

**Comment by gerritbruening** [comment]
Wo fehlen die? Online und im XML nicht.

**Comment by markusciupke** [comment]
Das kann nach meinem Dafürhalten geschlossen werden.
