### ISSUE TITLE
Sprecher / Figur / Auftritt

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#278]
Wir die Formate `Sprecher`, `Auftritt` und `Figur` nochmals diskutieren.

Zu erhöhter Transparenz des idml-Outputs schlage ich vor:

# Zusätzliches Zeichenformat `Sprecher in BA`
Sprecherbezeichnungen, die zusammen mit anschließender (`inline`) BA in einer `BA zentr. …` landen, bekommen nicht das Zeichenformat `Figur`, sondern `Sprecher in BA` (bei nach jetzigem Stand gleicher Formatierung wie `Figur`).
So können die drei dahinterstehenden Phänomene im idml-Ergebnis gefunden werden:
* Sprecherbezeichnungen
* Figurennennungen in BA
* Auftrittsbezeichnungen

# Zusätzliches Zeichenformat `Sprecher in BA (Auftritt)`
Sprecherbezeichnungen, die zusammen mit anschließender (`inline`) BA in einer `BA zentr. …` landen, können mit einer Auftrittsbezeichnung zusammenfallen (`move/following-sibling::*[1][self::sp]/speaker[following-sibling::*[1][self::stage[@rend[contains(.,'inline')]]]]`).

                            <move type="entrance"/>
                            <sp>
                                <speaker n="before_602_a">Faust</speaker>
                                <stage n="before_602_b" rend="inline small">allein.</stage>

Für diese sollte das Zeichenformat `Sprecher in BA (Auftritt)` eingeführt werden.

# Zusätzliches Absatzformat `Sprecher (Auftritt)`
Auf einer Zeile für sich allein stehende Sprecherbezeichnungen können ebenfalls mit einer Auftrittsbezeichnung zusammenfallen (`move/following-sibling::*[1][self::sp]/speaker[not(following-sibling::*[1][self::stage[@rend[contains(.,'inline')]]])]`).

                            <move type="entrance"/>
                            <sp>
                                <speaker n="before_1322_a">Mephistopheles</speaker>
                                <stage n="before_1322_a">tritt, indem der

Für diese sollte das Absatzformat `Sprecher (Auftritt)` eingeführt werden.

# Formatierung
Außerdem ist über die Formatierung neu nachzudenken.
1. Auftrittsbezeichnung und Sprecherbezeichnung müssen sich unterscheiden. Sonst sind Auftrittsbezeichnungen nicht erkennbar, wenn Auftrittsbezeichnung und Sprecherbezeichnung zusammenfallen.
2. Sie müssen so ähnlich sein, dass Auftrittsbezeichnungen für Sprecherbezeichnungen eintreten können, wo keine gesonderte Sprecherbezeichnung steht (22 Fälle im Faust I).
3. Figurennennungen und Sprecherbezeichnungen sollten am besten identisch erscheinen, damit “DIE HEXE / mit vielen Ceremonien ...” als Quasi-Replik erscheint.

In A wurde das um den Preis stark unterschiedlicher Schriftgrößen erreicht.
Vorschlag für die Ausgabe ist stärkerer Sperrsatz.

|                  | Sprecherbezeichnung | Figurennennung in BA | Auftrittsbezeichnung |
|------------------|---------------------|----------------------|----------------------|
| aktuelle Vorlage | VERKLEINERTE VERSALIEN | VERSALIEN so groß wie SPRECHER | Kapitälchen  in größerer Schrift als die übrige BA | 
| Vorschlag        | dasselbe | dasselbe                     | V&nbsp;E&nbsp;R&nbsp;S&nbsp;A&nbsp;L&nbsp;I&nbsp;E&nbsp;N&nbsp; so groß wie&nbsp; S&nbsp;P&nbsp;R&nbsp;E&nbsp;C&nbsp;H&nbsp;E&nbsp;R&nbsp; mit stärkerer Sperrung | 
|                  |                     |                      |                      |

**Comment by gerritbruening** [comment]
Mit @dietmarpravida ist dies bereits diskutiert. Als nächstes brauchten wir eine Stellungnahme von @markusciupke.

**Comment by gerritbruening** [comment]
Ich zeige noch, was der Stein des Anstoßes war:
![grafik](https://user-images.githubusercontent.com/10358005/36000008-e6d80abe-0d21-11e8-9a93-1e9e880901dc.png)

"F<sub>AUST</sub>" ist Sprecherbezeichnung, sieht aber nicht so aus (siehe "WAGNER")

**Comment by markusciupke** [comment]
Das hatten wir seinerzeit in Göttingen so besproche. Wir haben uns dabei an A orientiert und die Sperrung als Kapitälchen umgesetzt. Das finde ich weiterhin gut. Was wäre die Alternative? Weiter gesperrte Versalien?

> "FAUST" ist Sprecherbezeichnung, sieht aber nicht so aus (siehe "WAGNER")

»Faust« ist Sprecher, und es ist gleichzeitig ein »Auftritt« weil sich die Figurenkonstellation mit dem Abtritt von Wagner geändert hat. Vielleicht sollte das Zeichenformat nicht »Auftritt« sondern »Neue Figur/Figurenkonstellation« heißen. Das würde die Funktion genauer beschreiben.

**Comment by gerritbruening** [comment]
> Was wäre die Alternative? Weiter gesperrte Versalien?

Ja, s.o. die Tabelle 2. Zeile.

> »Faust« ist Sprecher, und es ist gleichzeitig ein »Auftritt« 

Das ist richtig, das hatte ich oben im Abschnitt Formatierung Punkt 1 und 2 in verallgemeinerter Form zum Ausdruck zu bringen versucht.
Das Problem ist, dass Kapitälchen unserer Meinung nach den Sprecher-Versalien nicht ähnlich genug sind, wenn man die Ähnlichkeits-Beziehungen in A zugrundelegt.

> »ein »Auftritt« weil sich die Figurenkonstellation mit dem Abtritt von Wagner geändert hat.

Das würde ich anders formulieren. Bei uns liegt dann ein Auftritt vor, wenn die entsprechende typografische Markierung in A das indiziert.

> Vielleicht sollte das Zeichenformat nicht »Auftritt« sondern »Neue Figur/Figurenkonstellation« heißen. Das würde die Funktion genauer beschreiben.

Der Name des Zeichenformats ist hier glaube ich nicht der Punkt, unsere Logik ist auch nicht so sehr an der Funktion orientiert. Siehe die vorige Bemerkung.

**Comment by gerritbruening** [comment]
Formatierung ist mittlerweile geklärt.

**Comment by gerritbruening** [comment]
> Sprecher-BA-Unterscheidung bleibt

(Göttingen, 8.3., mdl.)

Soll heißen, es bleibt dabei, dass `speaker`-Inhalte mal in `Sprecher`-Absätzen, mal in `BA-Absätzen` landen, im Absatz- und Zeichenformat also nicht mehr unmittelbar erkennbar sind. Es ergibt sich aber bislang kein praktisches Problem daraus. Die o.g. Vorschläge in Richtung Transparenz haben sich damit erübrigt.
