### ISSUE TITLE
Render html app entries as appendix to the reading text

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#279]
Following #219.

This list should be sorted by types of decisions.
Ideally, it would link to the original app entries in the text so that readers can explore each decision in its context.

We would need headings for the types as we need short descriptions for the tooltips (there's another issues for this).

**Comment by gerritbruening** [comment]
Man könnte auch überlegen, im Anschluss an jeden einzelnen Typ eine Liste mit Stellenreferenzen zu geben. So würde man allzuviel Dopplung vermeiden.

**Comment by thvitt** [comment]
Brauchen eh die Expansionen für die Typen. Dann wird jeder Typ ein Link auf den entsprechenden Eintrag oder Abschnitt in der Liste und linkt zurück an die entsprechende Stelle.

**Comment by gerritbruening** [comment]
Ja, finde ich gut!

**Comment by thvitt** [comment]
Eine [entsprechende vorläufige Liste samt Links existiert nun in der Webansicht](http://dev.faustedition.net/print/app). Offensichtlich fehlen dieser Liste noch die Überschriften, die IIRC @dietmarpravida liefern wollte. 

Ich habe dies bewusst nicht in die `faust.xml` geschrieben, da es daraus einerseits leicht (siehe [text-applist.xsl](https://github.com/faustedition/faust-gen-html/blob/master/xslt/text-applist.xsl)) erzeugt ist und andererseits das Rendering für die Druckausgabe sicher anders läuft.

Ich unassigne mich erstmal, bitte reassignen, wenn die Liste der Typ-Überschriften da ist.

**Comment by gerritbruening** [comment]
Sehr gut, danke!

**Comment by gerritbruening** [comment]
> Ich unassigne mich erstmal, bitte reassignen, wenn die Liste der Typ-Überschriften da ist.

Die ist jetzt da. Wo nochmal, @dietmarpravida?

**Comment by dietmarpravida** [comment]
Steht bei #184
