### ISSUE TITLE
Appendix of notes on app entries & textual issues

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#280]
These notes will contain additional information about app entries as well as textual issues which are not reflected in any apparatus entry. The former would point to app entries, the latter to any text passage.

We will also make use of this appendix in the printed volume.

**Comment by thvitt** [comment]
Schreibt Ihr das in ein TEI-File und assignt mich dann wieder?

**Comment by gerritbruening** [comment]
Machen wir!

**Comment by dietmarpravida** [comment]
Ich hätte da jetzt gern eine Konvention dazu.

**Comment by gerritbruening** [comment]
OK, @thvitt, worauf dürfen die `note`-Elemente, z.B. mit `@target`, pointen?
Ich denke an
* `@n`-Werte von Textteilen
* `@xml:id`s von Lemmas (gemeint wäre dabei der darauf bezügliche Apparateintrag)

**Comment by thvitt** [comment]
hm, ach es geht schon um Einzelstellen mit Kreuzverlinkung …

`@target` sieht grundsätzlich URLs vor, also #xmlid. Allerdings muss ich über die XML-IDs der Apparateinträge nochmal nachdenken, im Zusammenhang mit #191 und dem gleichzeitigen Highlighten. Im Prinzip könnten die IDs für den Apparat der Systematik `app.〈n〉.〈f:ins〉` folgen bzw `app.〈n〉`, falls [] leer ist. f:ins wird dabei normalisiert, dh nicht-buchstaben weg, wie jetzt bei den seg-IDs.

**Comment by gerritbruening** [comment]
Wir müssen jetzt glaube ich sowieso erstmal für den Content sorgen, und das tun wir vorerst außerhalb von TEI.

**Comment by thvitt** [comment]
in #294 habe ich ja IDs definiert und auch schon (an den note type=textcrit) in faust.xml eingetragen.

**Comment by gerritbruening** [comment]
Okay gut, dann schreiben wir die an den Anfang des jeweiligen Absatzes.

**Comment by gerritbruening** [comment]
Nach dem 30. holen wir uns die Daten vom Verlag und arbeiten damit weiter.

**Comment by dietmarpravida** [comment]
Siehe auch #592

**Comment by gerritbruening** [comment]
@thvitt, sollen wir das hier zugunsten von https://github.com/faustedition/faust-web/issues/552 closen?
