### ISSUE TITLE
render space in reading text

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#283]
Depending on value of `@quantity` the text should have a series of empty lines, analogous to https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#leerzeile.

Ideally, these empty space would have some tooltip explaining the phaenomenon, e.g. 

> Lücke von ... Zeilen

**Comment by thvitt** [comment]
Should we do this _only_ for the reading text or also for manuscripts?

**Comment by gerritbruening** [comment]
I asked myself the same question. What we now have is `***` which is less intuitive, I think. Real space with tooltip may be more complicated, though, when it comes to inline `space`, not so well-defined `space`, `space` at the end of lines or of the text ...
If you think that we should be consistent, we may provisionally keep the `***`.
I'm not even totally sure what we will do in the printed edition, see https://github.com/faustedition/faust-gen-html/issues/272.

**Comment by gerritbruening** [comment]
Right now I see no rendering, no `***`s either.

**Comment by thvitt** [comment]
there is no `<space>` in faust.xml …

**Comment by thvitt** [comment]
Nun mal zur Ansicht: Leerzeilen (gerundet) für `unit=lines`, *** für alles andere.

**Comment by gerritbruening** [comment]
OK!

**Comment by thvitt** [comment]
ok heißt schließen, nehme ich mal an.

**Comment by gerritbruening** [comment]
Ist so noch nicht ganz optimal, weil der gelbe Balken ebenfalls eine Lücke hat. Jetzt sieht es aus wie eine Szenengrenze, oder?
