### ISSUE TITLE
Yellow bar in space rendering

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#288]
See https://github.com/faustedition/faust-gen-html/issues/283#issuecomment-365076735.

**Comment by thvitt** [comment]
Balken und Hintergrund haben eine Lücke, weil das `<space>` kein `@n` hat, von daher gibt's da auch keine Belegdichte und Variantenzahl, die man visualisieren könnte. Ist ja nicht zur Deko da.

**Comment by gerritbruening** [comment]
OK, und wenn man sagt: Dieses Dings gibt es einmal und es gibt eine Variante? Wenn nötig könnte man könnte man auch irgendeine `after_...`-Nummer vergeben.

**Comment by thvitt** [comment]
das ist vermutlich die saubere Lösung, auch wenn sie jetzt noch nicht so ohne weiteres eine Änderung bringt, da die Sonderbehandlung für `<space>` die Behandlung für den Variantenapparat überschreibt.

Ggf. ist es eine gute Idee, das Variantenapparathandling zu zerlegen in einen Teil, der den Apparat- und Einfärbeteil macht und einen, der das Element rendert. Ggf. auch in Verbindung mit einer Markupänderung, der nochmal ein Extra-`<div>` einführt; damit könnte man vielleicht auch die diversen sich aus dem gegenwärtigen Handling ergebenden Probleme (n als float, fehlende Einrückung bei Umbruch, Unterbrechungen des Hintergrunds) angehen.

Müsste ich mal sauber konzipieren in Bezug auf die diversen Aspekte, aber es schadet sicher nix, wenn Du den beiden Spaces in _2 H_ ein `n` verpasst.

**Comment by thvitt** [comment]
die telefonisch besprochene überlegung hier ist, bereits in H zu codieren als
```xml
<ab n="…">
   <space unit="lines" …/>
</ab>
```
was den Charme hat, dass der Apparat in dem `<ab>` eingefügt wird (`space` ist ein leeres Element) und nicht allzuviel Sonderbehandlung für `<space>` nötig ist

**Comment by gerritbruening** [comment]
Habe das in 391098 entsprechend geändert.

**Comment by thvitt** [comment]
Was ist [hier](http://dev.faustedition.net/document?sigil=2_H&page=80&view=print#lafter_6062) noch offen?

**Comment by thvitt** [comment]
nehme mal an nix
