### ISSUE TITLE
Emend full stop after hi

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#291]
Unemended version:

                            <stage n="before_4728_f">
                                <hi>Der <hi>Kaiser</hi>
                                </hi>.

In the emended version, the full stop after the parent `hi` would be deleted.
@thvitt, is this covered by our current procedures (how)? Do we need some workaround?

**Comment by thvitt** [comment]
a) there's a whitespace error between the `</hi>`s, introduced by the transformation. :bug:
b) there's no rule for that.

Is this an individual decision (i.e., a case for app2norm.txt, urgs) or a general rule – remove all `.` in `<stage>` immediately preceded by a `</hi>`?

**Comment by gerritbruening** [comment]
> Is this an individual decision (i.e., a case for app2norm.txt, urgs) or a general rule –

Danke fürs Anschalten meines Gehirns, das sich momentan im Sieb-Zustand befindet: https://github.com/faustedition/faust-gen-html/issues/248
Heißt "general rule", keine individuelle Textentscheidung mit Apparateintrag.

**Comment by gerritbruening** [comment]
So this issue should rather be "Trim whitespace in `hi[hi]`"?
