### ISSUE TITLE
AF Sprecher mit ZF Sprecher und nicht-Sprecher

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#293]
Bsp.:

![grafik](https://user-images.githubusercontent.com/10358005/36201915-ffbd4c88-1181-11e8-9273-210aebbb23f1.png)

Hier habe ich jetzt festgelegt:
https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#sprecher

(d.h., "und" als Nichtversalien, aber auch nicht verkleinert)
So verständlich und akzeptabel, @markusciupke?

**Comment by markusciupke** [comment]
Verständlich und nicht nur akzeptabel sondern auch korrekt, wenn wir das gleiche meinen.
Ich fasse einmal ausführlich zusammen:
Verse haben eine Schriftgröße von 10 pt.
Bühnenanweisungen haben eine Größe von 8,5 pt. 
Die Versalien in der Bühnenanweisung haben also eine Schriftgröße von 8,5 pt und sind angesperrt. Die normalen Sprecher haben auch eine Schriftgröße von 8,5 pt und sind angesperrt. 
Verkleinert sind die Figuren und Sprecher **nur** in Relation zur Grundschrift (»Tropf«).
Das »und« hat ebenfalls eine Schriftgröße von 8,5 pt und ist **nicht** angesperrt.
Erreicht wird das über die Zuweisung des Absatzformates C BA zentr. 1,5 / 0,0 für den Absatz, sowie über die Zuweisung des Zeichenformats »Figur« an die Zeichen »Kater « bzw. » Kätzinn«.
Würde man das Zeichenformat »Figur« weglassen, wären »Kater« sowie »Kätzinn« nicht angesperrt.
Würde man das Absatzformat »Sprecher« dem Absatz zuweisen, wäre das »und« mitgesperrt.
Damit die gesperrten Figuren nicht zu eng am »und« stehen, sollen die Leerzeichen vor und nach »und« mitgesperrt werden.
Mitsperrung betrifft grundsätzlich alle Zeichen vor und nach Zeichen mit Sperrungen nach Dudenregeln. Also alles außer Anführungszeichen und Punkt (siehe #242).

**Comment by gerritbruening** [comment]
> Erreicht wird das über die Zuweisung des Absatzformates C BA zentr. 1,5 / 0,0 für den Absatz, sowie über die Zuweisung des Zeichenformats »Figur« an die Zeichen »Kater « bzw. » Kätzinn«.

Die `A` usw.-Formate bedürfen aus meiner Sicht noch der Diskussion, die oben verlinkte Dokumentation beruht noch auf den alten Formatnamen mit provisorischen Ergänzungen von mir. Ich würde gern Klarheit schaffen, bevor das alles geändert wird.
`BA` finde ich in diesem Fall komisch, denn bislang wäre es Absatzformat `Sprecher` gewesen.
Ich beharre nicht auf den Namen, aber wenn wir weiterkommen, müssen wir die Bezeichnungen im Rahmen der Doku https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md regeln. Dass das bisherige Absatzformat `Sprecher` zwingend VERSALIEN vorsieht, stand da z.B. noch nicht, und es wäre evtl. sinnvoll, dafür das via Zeichenformat statt Absatzformat zu regeln. Auch die Schriftgrößen sollten ergänzt werden. Du kannst dieses Dokument übrigens auch editieren!

**Comment by markusciupke** [comment]
Wenn hier nur »Kater« stünde wäre das Absatzformat Sprecher. Schon durch den Punkt danach wird der Absatz eine BA, denn der Punkt wird nach Dudenregeln nicht mitgesperrt. Das Absatzformat Sprecher ist aber zwingend gesperrt. 
Durch »und« wird der Absatz erst recht zur BA. Nämlich zu einer BA mit Figur. Figur unterscheidet sich in nichts von Sprecher, außer dass noch weiterer Text im gleichen Absatz steht. Sobald ein Absatz einen Sprecher oder eine Figur enthält, erhält er einen Abstand nach oben von 1,5. Der Name ist völlig egal. Bei dir heißt es »BA zentr. 1,5« bei mir »C BA zentr. 1,5 / 0,0«. Der Inhalt ist aber der gleiche. Schriftgröße 8,5, Abstand 1,5 nach oben und 0,0 nach unten. Bei Sprecher und bei BA.
Aber du hast recht, wir brauchen das Absatzformat Sprecher nicht. Wir können es durch das Format ersetzen, das im Moment bei dir »BA zentr. 1,5« und bei mir »C BA zentr. 1,5 / 0,0« heißt. Zusätzlich müsste der Sprecher (plus Leerzeichen und Interpunktion) das Zeichenformat »Figur« erhalten. Es würde sich am Schriftbild überhaupt nichts ändern. Der Name ist tatsächlich völlig egal, wir können es auch »Sprecher oder Figur mit oder ohne weiteren Text im Absatz« nennen. Jedenfalls hätten wir dadurch ein Format eingespart und müssten nur das Zeichenformat Figur häufiger vergeben. Was ist für euch einfacher oder aus XML heraus logischer?
Das Absatzformat »Sprecher« sieht nicht zwingend Versalien vor. Nur das Zeichenformat »Figur« sieht zwingend Versalien (und Sperrung) vor. Das Absatzformat erzeugt aber wie gesagt zwingend eine Sperrung. 
Im übrigen ist »Kater und Kätzinn« in den beiden zuletzt gesandten PDF-Dateien (11.2. und 13.2.) im (falschen?) Format »Sprecher« angelegt. Das heißt, hier ist »und« mitgesperrt. Das kommt wohl aus der Online-Ausgabe. Dort ist »Kater und Kätzinn« durchgehend in Versalien geschrieben. In D1, der WA und der FA ist »und« allerdings anders ausgezeichnet als die Worte »Kater« bzw. »Kätzinn«. Ich habe da keine Vorliebe, fände es aber logisch, wenn wir uns nach dem Erstdruck richten.
Konkrete Frage: soll ich generell das Absatzformat »Sprecher« löschen und durch ein Absatzformat »BA … 1,5/0,0« ersetzen und dem Speaker das Zeichenformat »Figur« zuweisen?

**Comment by gerritbruening** [comment]
Unsere Daten sehen eine klare Trennung zwischen Sprechern und Bühnenanweisungen vor. Diese Trennung wird schon dadurch eingerissen, dass, wenn beide in einer Zeile stehen, sie in eine BA kommen. Was du zuletzt geschrieben hast, läuft für mich darauf hinaus, im Grunde alles in einem Format aufgehen zu lassen, das man auch NT (für Nebentext) nennen könnte.
Das entspricht natürlich nicht der Logik unserer Daten, aber das wäre für mich kein zwingendes Gegenargument. Man kann danach halt nicht mehr die Sprecherbezeichnungen anfassen, ohne zugleich auch alle Bühnenanweisungen zu modifizieren. Die Formate müssten also sitzen.

**Comment by markusciupke** [comment]
Ich verstehe gerade nicht, wo das Problem liegt. »eingerissen« klingt so destruktiv und negativ. Dass wir Sprecher zusammen mit Bühnenanweisungen in einer Zeile und also in einem Absatz haben, ist doch klar. Und es ist nun einmal so, dass ich in InDesign **jedem** Absatz ein Absatzformat zuordnen **muss**. Befinden sich also zwei in XML klar getrennte Textelemente in **einem** Absatz, **muss** ich diesem ein Absatzformat zuweisen. 
Bei Zeichenformaten sieht es anders aus. Hier haben alle Zeichen ersteinmal kein Zeichenformat bzw., sie haben ein Zeichenformat, das heißt »ohne«. Nun kann ich einzelnen oder mehreren aufeinanderfolgenden Zeichen Zeichenformate zuweisen, muss aber nicht. Das gute ist, diese sind stärker als die Absatzformate. Steht also im Absatzformat »Sperrrung« im Zeichenformat aber »keine Sperrung«, dann wird die Sperrung in diesem Absatz trotz des Absatzformats wieder aufgehoben. Insofern haben wir auf diese Art weiterhin eine klare Trennung zwischen Sprechern (gesperrt) und Bühnenanweisungen (normal). Allerdings wohl anders als in XML. Das kann ich nicht beurteilen. Nur, es gibt für InDesign keinen anderen Weg. 
Ob man alles, was nicht Vers oder Prosa ist, nun NT oder BA nennt ist unerheblich. Für mich gibt es mehrere Arten von Nebentext. Es gibt Nebentext, der zum Faust-Text gehört (Überschriften und Bühnenanweisungen und »Finis«, und solchen, der nicht Faust-Text von Goethe ist, aber dennoch dazu gehört (Kolumnen, Vers- und Zeilenzähler, Seitenzahlen). Im übrigen steht in jedem 5. Vers Nebentext, der nicht zum Faust-Text von Goethe gehört: der Verszähler. Der ist Bestandteil eines Absatzes mit dem Absatzformat »Vers« und hat das Zeichenformat »Verszahl«. Auch hier gibt es vermutlich keine so klare Trennung wie in XML, oder eben eine auf eine andere Weise.
Nun kann man also über das Zeichenformat »Figur« (wir können es auch anders nennen) durchaus alle Sprecher anfassen und ändern, ohne dass davon der Rest des Absatzformates, also die Bühnenanweisung berührt werden würde.

**Comment by markusciupke** [comment]
Kleine Ergänzung, ist mir noch eingefallen: Wir können natürlich auch **jedem** Zeichen ein Zeichenformat (NT, BA, Teil, Akt, Szene usw.) zuweisen, auch wenn wir es gar nicht müssen, weil es dem Grundformat des Absatzformates entspricht. So wären aber alle Texteinheiten über das Zeichenformat definiert und klar von einander getrennt. 
Bestimmte Dinge, wie Abstände nach oben und unten lassen sich aber nur über ein Absatzformat generieren. 
Hilft das weiter?

**Comment by gerritbruening** [comment]
Das habe ich soweit verstanden.
Als nächstes sollten wir https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md durchsprechen, am besten telefonisch.

**Comment by gerritbruening** [comment]
>müsste hier das Absatzformat »C BA zentr. 2,3 / 0,0« vergeben werden

In Ordnung. @pglatza, siehe dazu den referencing commit https://github.com/faustedition/faust-gen-html/commit/0602b892d650e227d10bb3254ac53072c66e61aa.

**Comment by gerritbruening** [comment]
> für »Kater« bzw. »Kätzinn« das Zeichenformat »Figur«. Das »und« hat dann das Zeichenformat »ohne«.

Scheint mir richtig. @pglatza, siehe das Update https://github.com/faustedition/faust-gen-html/commit/c8eba8b760cf6353733554999cfd9dd7a1d0b4c4.

**Comment by markusciupke** [comment]
Ich bin da nicht sicher. Anbei eine PDF-Datei mit beiden Varianten. Erste Seite »und« in 10 Punkt wie die Verse, 2. Seite »und« in 8,5 Punkt wie BA-Texte. Für mich wird dieser Absatz durch das »und« zu einer BA, und daher finde ich 8,5 Punkt für das »und« richtig. Außerdem fügt es sich nach meinem Geschmack besser ein.
[K und K.pdf](https://github.com/faustedition/faust-gen-html/files/1896517/K.und.K.pdf)
Wenn ihr euch für »und« in 10 Punkt entscheidet, brauchen wir hierfür ein weiteres Zeichenformat (z.B. »Grundschrift«) das allen Zeichen die Schriftgröße 10 Punkt zuweist. Das würde ich dann noch einrichten.

**Comment by gerritbruening** [comment]
Für mich ist das eine Sprecherbezeichnung, aber ich sehe den ästhetischen Punkt: Normale Schriftgröße passt nicht gut zu den verkleinerten Versalien.

**Comment by gerritbruening** [comment]
> Tatsächlich ist das »und« im Erstdruck größer als sonst der Schriftgrad von BAs. Die Frage ist, ob es einen vergleichbaren Fall im Ersten Teil gibt und wie es da aussieht?

Ähnlich ist noch 4315 "Ci-devant".

> könnte man die Größe auch als ein Setzerversehen betrachten?

Nein, das ist bei Sprecherbezeichnungen systematisch so. Nur Bühnenanweisungen im eigentlichen Sinn haben kleinere Schrift.
Auch die Auftrittsbezeichnungen haben nichtverkleinerte Schrift, siehe "Glockenklang und Chorgesang".

> auch im Erstdruck sieht das »und«, wie ich finde, etwas unproportional aus.

![grafik](https://user-images.githubusercontent.com/10358005/38606017-414f69be-3d75-11e8-9428-1fb48fa72648.png)

Sieht für mich OK aus.
Bei uns aber nicht, weil wir links und rechts vom "und" verkleinerte Schrift haben. Deswegen wäre zu überlegen, auf diese Differenzierung zu verzichten und alle drei in Versalien erscheinen zu lassen. Denn von mir aus soll es hauptsächlich so aussehen wie eine Sprecherbezeichnung. Mir würde das die Sache einfacher machen, denn der Faust II ist inkonsistent und manchmal auch unklar.

**Comment by gerritbruening** [comment]
Ich assigne jetzt mal DP und mich, und wenn wir fertig überlegt haben, verweisen wir den Fall zurück.
Für die Online-Darstellung ist dasselbe zu überlegen.

**Comment by markusciupke** [comment]
Alle drei in Versalien erscheint mir als die schlechteste Variante, weil die Differenzierung des Erstdrucks da natürlich verloren geht. Wahrscheinlich stört mich vor allem der Unterschied zur Schriftfgröße des »sich dem Feuer nähernd.« unmittelbar darüber. Aber wie wäre es mit 10 Punkt und manuell leicht vergrößerten Abständen vor und nach »und«?
Natürlich verstehe ich, dass wir im Zweiten Teil noch mehr Probleme bekommen werden und deswegen eine einfache Lösung pragmatisch ist. 
Ich warte jetzt gerne ab.

**Comment by dietmarpravida** [comment]
warum nicht nichtversale normale Schrift in unverkleinerter Schriftgröße, wie Text in Auftritten? Ich vermute, dass die betr. Elemente in den Hss meist nicht unterstrichen sind, oder?

**Comment by gerritbruening** [comment]
Hier nochmal die erwähnte Datei: [K und K.pdf](https://github.com/faustedition/faust-gen-html/files/1896517/K.und.K.pdf)

**Comment by markusciupke** [comment]
Ich habe jetzt beim Blättern in D4 mindestens drei Fälle gefunden, die parallel zu K und K laufen (ich habe nicht systematisch gesucht, das könnt ihr in XML besser): 
1. vor 1178 »Faust mit dem Pudel hereintretend.« 
»Faust« und »Pudel« sind groß und gesperrt (Auftritt)
»mit dem« ist wie das »und« bei K und K, also groß und nicht gesperrt (Grundschrift)
»hereintretend.« ist klein (BA)
2. vor 2158: »Faust und Mephistopheles«
»Faust« und »Mephistopheles«: Auftritt
»und«: Grundschrift
3. vor 903: »Faust und Wagner«
wie 2.

Die WA setzt nach meinem Eindruck das »und« in den Fällen 2 und 3 sowie bei K und K größer als die anderen BAs. Im Fall 1 differenziert sie aber nicht.
Die  FA setzt das »und« in den Fällen 2 und 3 sowie bei K und K recte (BAs sind im Unterschied dazu kursiv). Im Fall 1 differenziert sie aber nicht, sondern setzt alles kursiv.

Mir scheint es vernünftig, für die Fälle 2, 3 und K und K das Zeichenformat »Grundschrift« (groß, klein, ungesperrt, 10 Punkt) zu verwenden – ebenso für »mit dem« in Fall 1 –, um so die Differenzierung des Erstdrucks zu erhalten (vorausgesetzt mein D4-Faksimile entspricht dem Befund in A8).

**Comment by markusciupke** [comment]
Entschuldigt: »vernünftig« ist hier keine vernünftige Kategorie. Es ist vielmehr eine gangbare Möglichkeit, wenn man die Differenzierung erhalten will. Was das für den Zweiten Teil bedeutet, kann ich nicht überblicken.
Die andere Möglichkeit ist Vereinheitlichung in BA-Größe für diese Fälle. Damit würde die Differenzierung des Erstdrucks aufgegeben. Aber was trägt diese eigentlich aus? Auch bei Szenenüberschriften nehmen wir ja eine Vereinheitlichung gegen den Erstdruck vor (Vorspiel auf dem Theater, Prolog im Himmel). Es ist ein Lesetext und unterschiedliche Schriftgrößen, die nach meinem Verständnis nicht wirklich etwas austragen, können auch die Lesebequemlichkeit beeinträchtigen.
Also: Was entscheidet ihr?

**Comment by markusciupke** [comment]
Ich habe keinen klaren Favoriten, auch weil ich nicht überblicke, welche Konsequenzen für den Zweiten Teil daraus erwachsen. Seite 1 entspricht der gangbaren Lösung mit Differenzierung. Was mir gar nicht gefällt und was ich auch für falsch halte, wäre das »und« oder das »mit dem« bei Fall 1 ebenfalls in Versalien zu setzen.
Seite 2 ist nach meiner Meinung ästhetisch ansprechender. Sie vereinheitlicht aber. Das kann man im Rahmen der Lesefassung vertreten. Ich denke, dass man Seite 2 wählen kann, wenn die Differenzierung nichts austrägt.

**Comment by dietmarpravida** [comment]
Ich habe auch keinen klaren Favoriten, aber nur alles in Versalien (wie von Gerrit oben proponiert) fände ich vielleicht auch nicht so toll.

**Comment by markusciupke** [comment]
Ich habe die Frage übers Wochenende noch einmal sacken lassen und kann mich nun doch eindeutig positionieren: Ich empfinde gerade eine Stelle wie »FAUST mit dem PUDEL _hereintretend_« als überdifferenziert. Das löst beim Leser eher Fragen oder Verwirrung aus, als es Orientierung schafft. Und für Orientierung und vernünftige Differenzierung ist Typographie doch da. Eine solche sehr genaue Differenzierung, die die Verhältnisse der Erstausgabe abbildet, sollte man nach meiner Meinung diplomatischen historisch-kritischen Editionen überlassen. Für einen Lesetext, der auf der historisch-kritischen Arbeit der digitalen Edition beruht, genügt es nach meiner Ansicht die Sprecher bzw. Figuren auszuzeichnen. Der andere Text sollte klein bleiben, also eine Schriftgröße von 8,5 Punkt erhalten. Das macht dann hoffentlich auch die typographische Bearbeitung des Zweiten Teils einfacher. – Ich würde mich freuen, wenn euch meine Einschätzung bei eurer Entscheidungsfindung hilft.

**Comment by gerritbruening** [comment]
Gut; nach den Wortmeldungen wären die betreffenden Phänomene ("und") wie normaler BA-Text zu behandeln.
Dafür brauchen wir kein besonderes Zeichenformat, weil dafür schon das Absatzformat `C BA zentr. 2,3 / 0,0` sorgt, richtig @markusciupke? 
Für KATER und KÄTZIN und dgl. brauchen wir auch nichts besonderes, weil dafür schon das Zeichenformat `Figur` sorgt, richtig @markusciupke?
