### ISSUE TITLE
proper IDs for apparatus parts

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#294]
* one unique ID per `<app>`
* unique IDs per referenced `<seg>` to allow for parallel highlighting
* IDs should be predictable and stable since they are also needed for #280 
* duplicates could be eliminated #191

**Comment by thvitt** [comment]
Calculation an ID base for an f:ins (from app*norm.xml) works as follows:
- value of n attribute of that ins
- `.`
- the first non-empty of:
    - the text value of the f:ins, converted to lower case, removing everything that is neither a letter, a digit or `_`
    - the value of the place attribute
    - the number of the app element in its source (absolute fallback, shouldn't happen)

For `<app>` elements, we take the base ID of the first f:ins in the app and prefix it with `app.`. For `<seg>` elements, we take the base id of the f:ins corresponding to the `<seg>` and prefix it with `seg.`.

**Comment by gerritbruening** [comment]
Confused the repos in commit message, sorry.

**Comment by thvitt** [comment]
I guess you didn't want to reopen this?

**Comment by gerritbruening** [comment]
Ah, now I see that this was legitimatly closed before, sorry!
