### ISSUE TITLE
Trim whitespace at end of stage before adding full stop

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#297]
Example:

                     </sp><stage n="after_10832" rend="inline">
                           ab
                        .</stage>

(2018-02-14T23:31:41.908+01:00)

Note that there was markup dropped in the course of "emend" at some stage:

                        <stage n="after_10832">
                           <add f:revType="late">(ab)</add>
                        </stage>

`@rend` has been removed in the XML source.

**Comment by thvitt** [comment]
I absolutely hate the idea of text manipulation in the stage directions, it causes a neverending plethora of special cases …

**Comment by gerritbruening** [comment]
That is, deletion of parentheses, addition of dots is not feasible?

**Comment by thvitt** [comment]
its feasible, but my impression is that every solution for a special case causes another even more special case to face.

**Comment by thvitt** [comment]
#216

**Comment by gerritbruening** [comment]
💐  (._.)

**Comment by thvitt** [comment]
Now, don't look to close at the _other_ cases :-)

**Comment by gerritbruening** [comment]
You already know them?
