### ISSUE TITLE
BA 'prominent' / 'normal'

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#298]
@markusciupke schlägt vor, zwischen prominenten und normalen BAs zu unterscheiden. Bevor wir hier an die Implementierung gehen, sollten wir einige daran hängende Fragen klären.

# prominent
'prominent' wird beschrieben als
> Bühnenanweisung vor   dem 1. Vers einer Szene oder Unterszene

- [ ] was bedeutet das?
- [ ] entspricht das editorisch relevanten Textmerkmalen? 
- [ ] wie werden die genannten Beispiele editorisch eingeschätzt?

# normal
'normal' zerfällt realiter in drei Gruppen
> * BA normal mit A/F   vor BA mit F / Sp / V"
> * BA normal ohne A/F   vor BA ohne F
> * BA normal ohne A/F   vor BA mit F / Sp / V

- [ ] inwieweit deckt das die editorisch relevanten Textmerkmale ab? (wie oben)
- [ ] ist die Einteilung richtig und vollständig, auch mit Blick auf die Beispiele?

# Durcharbeitung
Siehe https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#b%C3%BChnenanweisungenxlsx

# Gedanken dazu

Ich bin noch dabei, mir über die Bedeutung von 'prominent' zu erschließen (auch weil 5 verschiedene Arten davon ausgemacht werden). Ich bin aber verhalten skeptisch, was die editorische Tragfähigkeit dieses Konzepts betrifft. Ich würde das vorerst ruhen lassen und mich den sog. 'normalen' BAs zuwenden.

Was diese angeht, so scheinen die aufgeführten Merkmale der drei realen Gruppen bereits auf der "plattgeklopften" (Imsieke / Krätke) Struktur von IDML zu basieren, nicht auf der XML-Hierarchie. Indiz: Es fehlt der Bezug auf Strukturen wie Repliken und Versgruppen. Die gibt es in IDML nicht mehr, wohl aber in XML, und sie könnten es m.E. erleichtern, die Merkmalserkennung etwas geradliniger zu gestalten (vgl. z.B. https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#ba-in-replik).

Für ein teilweises Aufsetzen auf der "plattgeklopften" Struktur von IDML bin ich grundsätzlich zu haben, wenn man da z.B. die Aufeinanderfolge von Absatzformaten mit Abständen über die sibling-Achse direkt abfragen und unerwünschte Aufaddierungen dadurch identifizieren kann. Dazu kann evtl. @pglatza Auskunft geben. Vor IDML kommt aber logisch XML, deswegen müssen wir sowieso erstmal den XML-Baum abfragen.

**Comment by gerritbruening** [comment]
Teil von #299.

**Comment by pglatza** [comment]
Ich glaube dieses Ticket kann geschlossen werden!?
Inzwischen sind die BA-Absätze und deren Formatvorlagen umgesetzt und die Unterscheidung in prominent und normal ist technisch hinfällig geworden.
