### ISSUE TITLE
Abstände vor / nach

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#299]
Die nichtvergrößerten Abstände lasse ich hier erstmal beiseite.

Ich gehe von den kleinsten vergrößerten Abständen zu den größten:

# zwischen Repliken und daran anschließenden BAs ohne Figur
(z.B. "Ab.", "Ungeheures Getöse ...")
Weder die Überlieferung noch die XML-Struktur liefert einen Anhaltspunkt, solche BAs je nach Gehalt unterschiedlich zu behandeln. Der Abstand sollte daher so sein, dass "Ab"-Vermerke nicht von der Replik isoliert werden und zugleich die inhaltlich selbständigen BAs (z.B. "Ungeheures Getöse ...") nicht zu dicht an ihr kleben (in diesem Sinne schon https://github.com/faustedition/faust-gen-html/issues/286#issue-296420262). Möglichkeit: Abstand kleiner als der Replikenabstand.

# vor Repliken
(Replik reicht von Sprecherbezeichnung bis zum letzten Vers oder Prosa-Absatz)

## vor Quasi-Repliken
(BAs mit Hervorhebung einer Figur, die dann aber nichts sagt, z.B. "Die Hexe mit seltsamen Geberden ...", siehe https://github.com/faustedition/faust-gen-html/issues/239)
Sollte analog zu Replik behandelt werden.

# vor erstem Vers / erstem Prosaabsatz einer Replik
kein Abstand erforderlich, hätte jedenfalls kleiner zu sein als Replikenabstand

# zwischen BAs
(mal mit, mal ohne Figur, z.B. [vor 4613](https://github.com/faustedition/faust-gen-html/issues/255))

# zwischen Versgruppen

## vor und nach BA zwischen Versgruppen
Sollte analog zum Abstand zwischen Versgruppen sein.

# Abstand vor und nach Auftritt

# zwischen Haupt- und Unterüberschrift
(z.B. "Dom." / "Amt ...")
Die Titel können wir hier erstmal beiseitelassen.

# zwischen Über- / Unterüberschrift und Text

# Anmerkungen
@markusciupke, mit verschiedenen Punkten will ich hier nicht festlegen, dass die Abstände unterschiedlich groß sein müssen, dass also der Versgruppenabstand größer sein muss als der Replikenabstand. Je mehr gleichartige Abstände, desto einfacher. Die Abstände müssen auch nicht gleich ganz präzisiere sein, für die Diskussion sind vllt. Angaben wie halbzeilig, einzeilig, zweizeilig etc. förderlicher.

Dabei auch daran denken, dass Phänomene kombiniert vorkommen, also z.B. Versgruppen und BAs im Anschluss an die Replik. Eine BA folgt dann auf eine Versgruppe und zugleich auf eine Replik. Da wäre dann zu entscheiden, ob der Versgruppenabstand genommen wird oder der Abstand von BAs nach Repliken (ich wäre für das letztere).

Auf unerwünschte Aufaddierungen von Abständen > 0,0 (https://github.com/faustedition/faust-gen-html/issues/251#issuecomment-364690608) ist zu achten.

Der Kommentar https://github.com/faustedition/faust-gen-html/issues/255#issuecomment-364702186 ist zu beherzigen.

Die Detailbemerkungen zu @markusciupke|s Vorschlag stehen jetzt auf einer [eigenen Seite](https://github.com/faustedition/faust-gen-html/blob/master/idml/ba-diskussion.md).

**Comment by dietmarpravida** [comment]
Ich mch einmal einen pauschalen Vorschlag:
* Abstand zwischen Repliken únd daran anschließenden BAs: ich bin eigentlich nicht dafür, mit Abständen semantische Beziehungen zu symbolisieren, aber es scheint hier doch sinnvoll; warum nicht einfach halber Replikenabstand zwischen BA und vorangehendem Sprechtext? Danach normaler Replikenabstand. (Das gilt für alle Fälle ausnahmslos, ohne semantische Rücksichten.) Vorschlag: 0.25 Z, mit Replikensabstand 0.5 Z
** wie groß ist eigentlich der Abstand zwischen Sprecherangabe und Sprechtext? gar keiner? 0.25 Z?
* Versgruppen innerhalb einer Replik: dieser Abstand sollte allerdings kleiner sein als der Replikenabstand Vorschlag: ebenso halber Replikenabstand (0.25 Z)
* Abstand vor und nach Auftritt: eineinhalb Replikenabstände (jeweils geich großer Abstand nach oben und unten) (0.75 Z)
* Abstand zwischen Haupt- und Unterüberschrift: dazu habe ich im Augenblick keine klare Vorstellung, aber warum nicht 1.0 Z? 
* Abstand zwischen Über- / Unterüberschrift und Text: vielleicht 1.5 Z?

0.25-, 0.5-, 1.0-, etc.-Abstände hätten vielleicht den Vorteil, dass sie sich leichter zu ganzen Zeilen summieren, während es sonst leicht zu unrhythmischen Seitenbildern kommt, besonders wenn man linke und rechte Seiten nebeneinanderlegt; aber wenn das kein Problem sein sollte, wäre ich auch nicht gegen andere Schritte.

**Comment by dietmarpravida** [comment]
Ich mache einmal einen pauschalen Vorschlag:
* Abstand zwischen Repliken únd daran anschließenden BAs: ich bin eigentlich nicht dafür, mit Abständen semantische Beziehungen zu symbolisieren, aber es scheint hier doch sinnvoll; warum nicht einfach halber Replikenabstand zwischen BA und vorangehendem Sprechtext? Danach normaler Replikenabstand. (Das gilt für alle Fälle ausnahmslos, ohne semantische Rücksichten.) Vorschlag: 0.25 Z, mit Replikenabstand 0.5 Z
   * wie groß ist eigentlich der Abstand zwischen Sprecherangabe und Sprechtext? gar keiner? 0.25 Z?
* Versgruppen innerhalb einer Replik: dieser Abstand sollte allerdings kleiner sein als der Replikenabstand Vorschlag: ebenso halber Replikenabstand (0.25 Z)
* Abstand vor und nach Auftritt: eineinhalb Replikenabstände (jeweils geich großer Abstand nach oben und unten) (0.75 Z)
* Abstand zwischen Haupt- und Unterüberschrift: dazu habe ich im Augenblick keine klare Vorstellung, aber warum nicht 1.0 Z?
* Abstand zwischen Über- / Unterüberschrift und Text: vielleicht 1.5 Z?

0.25-, 0.5-, 1.0-, etc.-Abstände hätten vielleicht den Vorteil, dass sie sich leichter zu ganzen Zeilen summieren, während es sonst leicht zu unrhythmischen Seitenbildern kommt, besonders wenn man linke und rechte Seiten nebeneinanderlegt; aber wenn das kein Problem sein sollte, wäre ich auch nicht gegen andere Schritte.

**Comment by gerritbruening** [comment]
Ich versuche im folgenden, Markus' off-Issue-Mail und diesen Kommentar auf einander beziehen:

BAs nach Repliken:
* MC & DP: halber Replikenabstand (1/6 ggü. 2/6 oder 1/4 ggü. 1/2)

vor Repliken
* MC: 1/3 Z
* DP: 1/2 Z

Quasi-Repliken
* MC: 0,5, d.h. nicht derselbe Abstand wie Repliken (= 3 Replikenabstände). Grund: wie Auftritt.
* DP: wie Repliken

zwischen Versgruppen
* MC: 0,5 Z (= 3 Replikenabstände) https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#vers-abstand
* DP: 0,25 Z (= ½ Replikenabstand); Replik sollte Einheit bilden.

Abstand vor und nach Auftritt:
* MC: davor 0,5 Z (= 3 Replikenabstände)  / danach entweder 1,5 (= 9 Replikenabstände) oder 1,0 (= 6 Replikenabstände) (vielleicht, weil bei normaler BA ein 1,5er Abstand zu groß wäre?)
* DP: davor und danach 1 ½ Replikenabstände d.h. 0,75 Z

Überschriften
* nach Aktüberschriften
  * MC: 2,5 (= 15 Replikenabstände) 
  * DP: -- (kein Vorschlag)
* Nach Szenenüberschriften und Unterszenenüberschriften (zwischen diesem und nachfogendem Text)
   * MC 1,5 Zeilen (= 9 Replikenabstände)
   * DP 1,5 Zeilen (= 3 Replikenabstände)
* zwischen Über- / Unterüberschrift 
  * MC: ?
  * DP: vielleicht 1.0 Z? (sollte kleiner sein als der Abstand zum Text, z.B. 1,0 zu 1,5)

BAs im sog. Kopfteil
> Nach Bühnenanweisungen mit Auftritt darin:         0,5 Zeilen

* Was heißt das? Soll 0,5 zu dem Abstand addiert werden, den Auftritte ohnehin haben sollen? Oder sollen solche Auftritte “nur” 0,5 Z Abstand haben, statt 1,0 oder gar 1,5 wie die anderen Auftritte?

> “Nach Bühnenanweisungen mit Figur darin”

* Was ist damit gemeint? Hier wäre vielleicht ein Verweis auf eine konkrete BA hilfreich.

> Nach Bühnenanweisungen ohne Akt Auftritt und Figur 0,166 Zeilen (1/6) (nicht innerhalb einer Replik)
* Was ist damit gemeint? Auch hier wäre vielleicht ein Verweis auf eine konkrete BA hilfreich.

> Hier kann es zu Aufaddierungen kommen, je nachdem was für ein Textelement folgt.

* d.h., die genannten Abstände unter "Kopfbereich" verstehen sich als Bonus-Abstände?

**Comment by gerritbruening** [comment]
Der nächste Schritt wäre jetzt denke ich, gemeinsam einen Blick auf den letzten Probesatz zu werfen. Inwieweit spiegelt der dieses System wider? Ganz oder teilweise?

**Comment by gerritbruening** [comment]
Die genannten Fragen sind in diesem Dokument geregelt:
https://docs.google.com/document/d/15upTDCnYM0Dya5_hFqrng8sYl1clXq1xJeQeBJkBezI/edit
