### ISSUE TITLE
before_4412 (er ergreift ... Es singt inwendig)

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#300]
@dietmarpravida, bei folgender Stelle

![grafik](https://user-images.githubusercontent.com/10358005/36384552-f6d79c10-158f-11e8-9014-fc4251050508.png)

müsste ich wissen, ob 
> er ergreift das Schloß. Es singt inwendig.

sozusagen kompress erscheinen soll oder ob, da BA im Anschluss an eine Replik, gemäß allgemeiner Regel ein Abstand zwischen letztem Faust-Vers und BA stehen soll. 

Die Kodierung sieht salvo meliore so aus:

                        <l n="4411">Fort! dein Zagen zögert den Tod heran.</l>
                    </sp>
                    <stage n="before_4412">er ergreift das Schloß. Es singt inwendig.</stage>
                    <sp>
                        <lg rend="indented">
                            <l n="4412">Meine Mutter, die Hur,</l>

**Comment by dietmarpravida** [comment]
mit Abstand

**Comment by gerritbruening** [comment]
Danke!
