### ISSUE TITLE
head/lb --> Zeilenumbruch

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#301]
@pglatza, die [Umsetzung von `lb` in Zeilenumbruch](https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#%C3%9Cberschriften) scheint noch nicht zu funktionieren.

Bsp., ursprüngliche Kodierung:

                        <head n="before_33_a" rend="centered big letter-spaced">Vorspiel<lb/>auf dem
                            Theater</head>

Ergebnis:

      <ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/Teil / Akt">
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Content>Vorspielauf dem Theater</Content>
         </CharacterStyleRange>
         <Br/>
      </ParagraphStyleRange>

**Comment by pglatza** [comment]
Der Zeilenumbruch ist nun mit der aktuellen Konverterversion in jeder IDML-Datei vorhanden.
Hinweis: es muss nicht immer das Element <Br/> sein. InDesign erstellt auch Zeilenumbrüche beim Einfügen des Line-Separator Unicode-Zeichens U+2018 (wie in unserer IDML-Synthese verwendet).

**Comment by gerritbruening** [comment]
> Hinweis: es muss nicht immer das Element `<Br/>` sein. 

Frage dazu: beschließt `<Br/>` nicht immer einen Absatz, ist also etwas anderes als ein Zeilenumbruch?

In der neuen Datei sehe ich jetzt wie erwartet `&#x2028;`.

**Comment by pglatza** [comment]
Doch, ja, das stimmt mit dem Verhalten von Br.
Und nur `&#x2028;` erzeugt den Zeilenumbruch.
