### ISSUE TITLE
Vers Abstand

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#303]
@pglatza, ist das schon umgesetzt?

Im IDML sieht der erste Vers, auf den das zutrifft, wie jeder andere aus:

      <ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/Vers">
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Content> </Content>
         </CharacterStyleRange>
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Content> </Content>
         </CharacterStyleRange>
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Content>Ihr bringt mit euch die Bilder froher Tage,</Content>
         </CharacterStyleRange>
         <Br/>
      </ParagraphStyleRange>

**Comment by gerritbruening** [comment]
XPath-match: https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#vers-abstand

**Comment by pglatza** [comment]
Ja, ist bereits umgesetzt und seit Freitag beim Upload-Formular verfügbar.
