### ISSUE TITLE
Absätze zusammenhalten?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#304]
Man sehe eine Stelle wie diese:

![grafik](https://user-images.githubusercontent.com/10358005/36398018-5f003a06-15c5-11e8-8c5b-6ca983dc38df.png)

@pglatza, in Word könnte man bei DIRECTOR jetzt im Absatzformat sagen: "Nicht vom nächsten Absatz trennen". Das wäre hier ein sehr sinnvoller Grundsatz. Ist das ohne großen Aufwand möglich?
(Ich würde dann dafür sorgen, dass Absatzformate entstehen, die klarmachen, dass hier eine Sprecherbezeichnung steht.)

**Comment by pglatza** [comment]
Ja, das geht. Das müsste @markusciupke im Template bereits für die Sprecher-Absatzformate hinterlegen.

Die Einstellung unter den Absatzformatoptionen findet sich im Unterpunkt Umbruchoptionen, "Nicht trennen von nächsten: [Wert]" Zeilen. Dort müsste die Zahl 1 eingetragen werden.

**Comment by markusciupke** [comment]
Ich möchte das gerne ohne diese Einstellung machen. Ich würde gern zunächst sehen wollen, wie sich die Seite auf natürliche Weise füllt. Wenn dann der Sprecher vom 1. Vers getrennt ist, sehe ich das sofort und werde je nachdem wie die Doppelseite gefüllt ist und was das für Auswirkungen auf die Folge(doppel)seiten hat, entscheiden, ob ich noch zwei Verse zum Sprecher auf diese Seite ziehe oder den Sprecher auf die nächste Seite schiebe. Eventuell ändere ich, wenn etwas blöd läuft, sogar ein paar Seiten vorher den Seitenumbruch. – Also bitte hier nichts machen! 
Letztlich wird mein Bemühen natürlich sein, möglichst gleichmäßig gleichlange Kolumnen auf den Seiten zu machen. Aber das ist bei Dramensatz natürlich nur begrenzt möglich, es sei denn man arbeitet am Abstand zwischen Repliken und Sprecher und den anderen Abständen. Das möchte ich aber nicht tun.

**Comment by gerritbruening** [comment]
War nur so eine Idee, könnt ihr unter euch ausmachen.

**Comment by pglatza** [comment]
Als erste Näherung zu einem Grobumbruch sehe ich die Einstellung als Verbesserung  – wenn nicht sogar als notwendig – an.
Ich kann allerdings auch Markus seine Arbeitsweise beim Feinumbruch verstehen.

Als Kompromiss sehe ich aktuell nur, dass man zwei IDML-Dateien erstellt:

- eine für den Feinumbruch und 
- eine weitere um schnell eine PDF zur Voransicht der Synthese zu erstellen.

Gibt es Stimmen für/gegen eine zweite IDML-Datei? @gerritbruening, @markusciupke 

Nachteile: doppelte Laufzeit bei der IDML-Synthese (können wir vernachlässigen) und die potenzielle Gefahr beim Feinumbruch die falsche Datei zu verwenden.

**Comment by markusciupke** [comment]
Ich habe nichts gegen zwei IDML-Läufe. Die Gefahr einer Verwechslung halte ich für gering. Das würde ich mit Sicherheit merken.

**Comment by gerritbruening** [comment]
Das Problem ist evtl., das Leute wie ich dann auf den Geschmack kommen :-), z.B.
* ersten Vers einer Replik (`sp/l[1]`) nicht vom nächsten Absatz trennen
* ersten Vers einer Versgruppe (`lg/l[1]`) nicht vom nächsten Absatz trennen

Oder was halt für Regeln gelten sollen. Das hätte m.E. sehr viel Sinn; aber es ist nichts, worum ich kämpfen würde.

Bei der Gelegenheit, hast du, @markusciupke, irgendeine Sammlung von Textelementen, die unbedingt oder möglichst zusammenbleiben sollen oder nicht? Würde uns interessieren.

**Comment by markusciupke** [comment]
Natürlich! Immer mindestens zwei Verse zusammen mit dem Sprecher bzw. immer mindestens die letzten beiden Verse einer Replik zusammen auf einer Seite. Ebenso Versgruppen. Aber ich würde auch noch auf den Reim achten und Reimpaare nicht auseinanderreißen wollen. Und BAs, die inhaltlich eng zum Vorangehenden gehören, sollen nicht auf eine neue Seite. Das betrifft nicht nur »ab.«. Im Grunde könnt ihr das in den gestern (heute morgen) gesandten PDFs bereits sehen. So würde ich das machen. Hier kommt noch mal der Vorschlag breit und weit.
[Vorschlag breit und weit.pdf](https://github.com/faustedition/faust-gen-html/files/1759253/Vorschlag.breit.und.weit.pdf)

**Comment by gerritbruening** [comment]
Habs mir notiert.
Ja, das würde schon Spaß machen. Aber wenn die Aussicht wäre, dass das nur zu Preview-Zwecken erzeugt und nicht weiter damit gearbeitet wird, wüsste ich nicht, obs die Mühe wert ist.

**Comment by markusciupke** [comment]
Ich glaube, es hat keinen Sinn, in parallelen Versionen zu arbeiten. Sinn hat diese Einstellung momentan nur für Umbrüche, die auf andere Fragen hin geprüft werden, und noch nicht an mich für den Feinsatz gegeben werden sollen. Für diese Versionen könnte Philipp die Einstellung ins Format eingeben und später für diejenige, die zum Feinsatz gehen soll, wieder rausnehmen.

**Comment by markusciupke** [comment]
Dieses Issue kann dann wohl geschlossen werden. Ich werde die Absätze im Satz nach den oben beschriebenen Kriterien so gut es geht manuell zusammenhalten.

**Comment by pglatza** [comment]
Damit bin ich auch einverstanden. Die Mühe sparen wir uns.
Es gab auch keine weiteren Fälle für den Bedarf zweier IDML-Läufe.
