### ISSUE TITLE
Tabs vor Vers Antilabe

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#305]
Bsp.:

![grafik](https://user-images.githubusercontent.com/10358005/36398237-66a05b14-15c6-11e8-8586-74db84e04e72.png)

Für mich sieht es hier so aus, als würde die Einrückung perfekt funktionieren, aber als müssten bei den beiden `Vers Antilabe` Absätzen auch noch die Tabulatoren ergänzt werden, die sonst vor den Versen stehen:

So sieht es normalerweise aus:

      <ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/Vers">
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Content> </Content>
         </CharacterStyleRange>
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Content> </Content>
         </CharacterStyleRange>
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Content>Kennst du den Faust?</Content>
         </CharacterStyleRange>
         <Br/>
      </ParagraphStyleRange>

Und so bei den Antilaben-Versen:

      <ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/Vers Antilabe">
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Antilabe transparent">
            <ZF_Antilabe_transparent AppliedCharacterStyle="CharacterStyle/Antilabe transparent">
               <Content>Kennst du den Faust?</Content>
            </ZF_Antilabe_transparent>
         </CharacterStyleRange>
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Content>Den Doctor?</Content>
         </CharacterStyleRange>
         <Br/>
      </ParagraphStyleRange>

**Comment by gerritbruening** [comment]
> zwei Tabs. Der erste setzt einen möglichen Verszähler rechtsbündig 14 mm vom linken Blattrand bzw. 4 mm vor den Satzspiegelrand, 

Darf ich bei dieser Gelegenheit mal etwas fragen: Wie wird es eigentlich erreicht, dass bei diesen nach links verlängerten Zeilen zentrierter Text zentriert erscheint? Er müsste doch weiter links stehen, da die Zeile unsichtbar weiter links beginnt als die Verse? Oder wird da auch mit Tabs bei gearbeitet?

**Comment by markusciupke** [comment]
Ich habe auf 18 mm von links sozusagen einen virtuellen Satzspiegel eingerichtet. Zentrierte Absatzformate haben keine Tabs dafür einen Einzug von 18 mm. So erscheinen Sprecher sowie zentrierte BAs zentriert zur Kolumnenzeile und dem virtuellen Satzspiegel. Der faktische Satzspiegel beginnt auf linken Seiten links am Blattrand  und auf rechten Seiten links im Bund.

**Comment by pglatza** [comment]
Die beiden fehlenden Tabs bei der Antilabe habe ich nun ergänzt.
