### ISSUE TITLE
Vers Einrückung --> zentriert

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#306]
Wo das Format `Vers Einrückung` ist, sehen die Verse jetzt zentriert aus. Auf welcher Ebene geschieht das? Auf der Ebene der Formatdefinition in ID oder vorher bei der Synthese?

**Comment by markusciupke** [comment]
Ich habe das Absatzformat »Vers Einrückung« zentriert formatiert, um schon einmal einen ungefähren Eindruck der optischen Zentrierung zu erhalten. Im Feinsatz werde ich das Format wieder auf  linksbündig setzen und die optische Mitte individuell einrichten.
Mir ist recht, wenn die entsprechenden Absätze zentriert bei mir ankommen.

**Comment by gerritbruening** [comment]
Okay, danke!
