### ISSUE TITLE
Auftrittsbezeichnungen ohne Namen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#307]
Sowas wie 

> Zeche lustiger Gesellen.
> Harzgebirg.
> Ein kleines reinliches Zimmer.
> Straße vor Gretchens Thüre.

Muss man da nach einer abweichenden Lösung für die Auftrittsmarkierung suchen, z.B. ohne Versalien, aber dafür in normalgroßer Schrift statt verkleinert?

**Comment by dietmarpravida** [comment]
In A ist, wenn ich recht sehe, kein Unterschied zu Auftrittsmarkierungen (gelegentlich leicht unterschiedliche Sperrungen scheinen ohne Bedeutung). Müssen wir da unterscheiden? (Ja, vermute ich. Dann im Sinn deines Vorschlags) Wie wird denn die "Gegend von Schirke und Elend" wiedergegeben? (In A genauso wie "Walpurgisnacht" oder "Ein Gartenhäuschen", was bei uns gar nicht geht.)

**Comment by gerritbruening** [comment]
> In A ist, wenn ich recht sehe, kein Unterschied zu Auftrittsmarkierungen

(d.h. zwischen "Harzgebirg" und anderen Auftrittsmarkierungen) 
Jetzt wo ich darauf achte, erscheint mir "Harzgebirg" doch deutlich weniger gesperrt als Auftritte. Wo gibt es denn schwächer gesperrte Auftritte? 

"Gegend von Schirke und Elend." ist momentan eine BA (`stage`), was angesichts der deutlichen Sperrung vielleicht nicht ganz sauber ist. Alternative wäre eine Aufeinanderfolge mehrerer Überschriften (`head`), von denen "Gegend von Schirke und Elend." dann die letzte wäre.

**Comment by markusciupke** [comment]
Ich hab mal die vier Szenenanfänge im Vorschlag breit und weit gesetzt und den vier oben genannten Zeilen ein eigenes Format gegeben (Überschrift). Dieses Format habe ich nach deinem (@gerritbruening) Vorschlag eingerichtet (Normalschrift, 10/13,2, Abstand nach unten 1 LZ). Ausnahme »Harzgebirg«, wo ich vor »Gegend von Schirke und Elend.« keinen Abstand eingefügt habe. »Gegend von Schirke und Elend.« ist in BA-Größe gesetzt (8,5/13,2) mit Sperrung. Abstand zum Auftritt »Faust. Mephistopheles« 1 LZ. Was meint ihr dazu?
[Auftrittsbezeichnungen ohne Namen.pdf](https://github.com/faustedition/faust-gen-html/files/1764775/Auftrittsbezeichnungen.ohne.Namen.pdf)

**Comment by gerritbruening** [comment]
"Harzgebirg" jetzt unter #331.
Die übrigen sind Auftrittsbezeichnungen, das sollte sich m.E. sowohl in der Gestaltung als auch im Namen des Absatzformats widerspiegeln.
Von mir aus also
* gleiche Sperrung wie bei Auftritten
* gleiche vertikale Abstände wie bei Auftritten (d.h. ohne Extra-Abstand, das folgende Element hat wie sonst 0,5 Zeilen Abstand)
* normale Schriftgröße statt Versalien in BA-Schriftgröße (wie von Markus vorgeschlagen)

Ein eigenes Absatzformat vorausgesetzt, können den Rest evtl. tatsächlich später regeln.

**Comment by dietmarpravida** [comment]
okay

**Comment by dietmarpravida** [comment]
ist das noch aktuell?

**Comment by gerritbruening** [comment]
Ich weiß nicht, ob @markusciupke das Absatzformat (s.o.) schon eingerichtet hat.

**Comment by markusciupke** [comment]
Nein, das hatte ich gestern noch nicht berücksichtigt. Habe ich jetzt gemacht.
[Auftrittsbezeichnungen.ohne.Namen.pdf](https://github.com/faustedition/faust-gen-html/files/1985691/Auftrittsbezeichnungen.ohne.Namen.pdf)

Das neue Absatzformat heißt »Auftritt o.N.« und hat die oben beschriebenen Spezifikationen:
– gleiche Sperrung wie bei Auftritten
– gleiche vertikale Abstände wie bei Auftritten (d.h. ohne Extra-Abstand, das folgende Element hat wie sonst 0,5 Zeilen Abstand)
– normale Schriftgröße statt Versalien in BA-Schriftgröße

Allerdings ist »Harzgebirg. | Gegend von Schicke und Elend.« ein Sonderfall, weil danach im Unterschied zu den ersten drei Auftritten ohne Namen nicht ein Sprecher folgt, sondern ein Auftritt (mit Namen). Dieser hat aber das Absatzformat »H BA zentr. 0,0 / 0,0 mit A/F« und damit keinen Abstand nach oben wie die Sprecher. Ausweg ist, dem Absatz »Faust. Mephistopheles.« hier das Absatzformat »C BA zentr. 2,3 / 0,0« zuzuweisen. Dann kann »Harzgebirg. | Gegend von Schicke und Elend.« ebenfalls das Format »Auftritt o.N.« erhalten und das nur für diese Stelle eingerichtete Sonderformat »Szenenunter (Harzgebirg)« kann ersatzlos gestrichen werden. Diese Lösung würde ich vorziehen. Einverstanden?

**Comment by markusciupke** [comment]
Hier steht noch die Antwort aus, ob die Einrichtung dieser vier Fälle wie oben beschrieben (bzw. in der Datei »Auftrittsbezeichnungen.ohne.Namen.pdf«) so in Ordnung ist.

**Comment by gerritbruening** [comment]
Ich würde jetzt doch darauf verzichten, ein eigenes Zeichenformat zu nehmen, sondern würde mit dem Arbeiten, was aus der Pipeline kommt, und dann auf dem Weg zur bzw. anhand der ersten Fahne (mit @dietmarpravida) weiterreden.

**Comment by markusciupke** [comment]
Aus GBs E-Mail und meiner Antwort:
> Ich persönlich finde die Lösung in Auftrittsbezeichnungen.ohne.Namen.pdf
> noch nicht so ganz überzeugend. Für mich ist da nicht mehr erkennbar, dass
> es sich in der Vorlage um eine Auftrittsbezeichnung handelt.

Das verstehe ich im Prinzip, nur dass es sich in meinen Augen inhaltlich gar nicht in jedem Fall um Auftrittsbezeichnungen handelt. Zeche lustiger Gesellen kann man wohl so betrachten, aber Ein kleines reinliches Zimmer, Straße vor Gretchens Thüre und Harzgebirg sind doch Ortsbezeichnungen, wie sie sonst allerdings im ersten Teil nicht vorkommen. Typographisch entsprechen sie in A Auftritten wie Director, Theaterdichter, lustige Person (was immer Cottas Setzer dazu veranlasst hat). Aber die treten dann im Anschluss ja auch tatsächlich auf. Das kann man für die Zeche lustiger Gesellen auch noch gelten lassen, aber für die anderen drei ja nicht. Hier (gesperrte) Versalien zu verwenden, die den Leser auf auftretendes Personal hinweisen, halte ich für irreführend. In einer Leseausgabe, in der auch sonst Schriftgrößen und Groß/Kleinschreibung nicht streng nach der Vorlage gehandhabt sind, ist es nach meiner Ansicht legitim hier eine andere typographische Lösung zu suchen. Es muss ja nicht die von mir zuletzt vorgeschlagene sein. Das können wir wie gesagt dann auch bei der Korrektur der 1. Fahne besprechen.

**Comment by markusciupke** [comment]
> gerritbruening commented on 12 Mar
"Harzgebirg" jetzt unter #331.
Die übrigen sind Auftrittsbezeichnungen, das sollte sich m.E. sowohl in der Gestaltung als auch im Namen des Absatzformats widerspiegeln.
Von mir aus also
gleiche Sperrung wie bei Auftritten
gleiche vertikale Abstände wie bei Auftritten (d.h. ohne Extra-Abstand, das folgende Element hat wie sonst 0,5 Zeilen Abstand)
normale Schriftgröße statt Versalien in BA-Schriftgröße (wie von Markus vorgeschlagen)
Ein eigenes Absatzformat vorausgesetzt, können den Rest evtl. tatsächlich später regeln.
 @dietmarpravida
  Member
dietmarpravida commented on 11 Apr
okay

Ich vergebe bei den genannten Stellen nun entsprechend der oben festgelegten Gestaltung das Absatzformat »Auftritt o.N.«.

**Comment by dietmarpravida** [comment]
im Satz sind alle Passagen gleich und so jetzt für immer; soweit ich und der Druck betroffen sind, kann geschlossen werden. Wenn es noch Formatsachen und Kodierungssschen geben sollte, bitte wieder öffnen

**Comment by gerritbruening** [comment]
Gut!
