### ISSUE TITLE
Punkt vor head/lb entfernen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#308]
Betrifft

                    <head rend="centered small letter-spaced" n="before_ttf_1_a">Trüber
                        Tag.<lb/>Feld</head>

Da hier ein Zeilenumbruch entsteht ([idml.md#%C3%9Cberschriften](https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#%C3%9Cberschriften)), soll der Punkt `.` vor `lb` entfernt werden. @pglatza, kannst du das machen?

**Comment by pglatza** [comment]
Ja, das geht. Habe es umgesetzt, steht beim nächsten Konverter-Update zur Verfügung.

**Comment by gerritbruening** [comment]
Punkt ist weg.
