### ISSUE TITLE
Keep soft hyphen in reading text's TTF

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#309]
See #268.
Must be https://github.com/faustedition/faust-gen-html/blob/master/xslt/utils.xsl#L406 but I'm not sure whether this may be restricted without affecting the web interface.

**Comment by gerritbruening** [comment]
I still don't see it in the output file. Did I use the wrong character then?

**Comment by thvitt** [comment]
:rage: I swear it was there yesterday, on my computer

**Comment by thvitt** [comment]
Recent pushs have failed to trigger the build for some unknown reason, probably an API change. I've triggered it manually now and will try to resolve the issue with the build system.
