### ISSUE TITLE
apply-edits: Normalize whitespace around punctuation marks

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#31]
XML example:

    (<del>zurückkommend</del> von 

Intented result:

    (von

**Comment by thvitt** [comment]
@gerritbruening, please point me to a place where this actually occurs in the live data

**Comment by gerritbruening** [comment]
Just before http://beta.faustedition.net/print/faust2.24.html#l10547

> ( von oben herunterkommend)

**Comment by thvitt** [comment]
I fear this cannot be done without additional damage. The space character is actually in the original transcript XML, and it is significant:

    <stage n="before_10547_b">(<del f:revType="instant"
          ge:stage="#change_stage_vor_l10547">zurückkom̄end</del> von oben
                                                                ↑

Since we have `<del>`s inside words as well as around words, eliminating space characters there seems to introduce a risk of eliminating whitespace elsewhere that should be kept.

Shouldn't this have been encoded as follows?

    <stage n="before_10547_b">(<del f:revType="instant"
          ge:stage="#change_stage_vor_l10547">zurückkom̄end </del>von oben

**Comment by thvitt** [comment]
Although, since this is the “cleaned” state anyway, we could probably think of a post-processing step that eliminates all whitespace after opening and before closing punctuation … if you really want this …

**Comment by gerritbruening** [comment]
I would like that, admittedly.

There are some issues with

    <stage n="before_10547_b">(<del f:revType="instant"
          ge:stage="#change_stage_vor_l10547">zurückkom̄end </del>von oben

1. It is words that are deleted in the manuscripts; the kind of whitespace we are struggling with was probably alien to the people revising them.
2. For the purposes of the "Einblendungsapparat", the present encoding is preferable.
3. After loosing many significant whitespace in the course of a whitespace normalisation we have become quite sensitive. For example, we have tried to avoid text nodes starting or ending with significant (but leading or trailing) whitespace.
--- Sigh!
