### ISSUE TITLE
Zensurzeichenmixup —

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#312]
[in den Apparaten zu 4139ff](http://dev.faustedition.net/print/faust.24#app.4139) stehen — als Zensurstriche, wir haben aber per #151 — aus der Vorlage in – gewandelt.

**Comment by gerritbruening** [comment]
@dietmarpravida, was willst du das im Lesetext haben?

**Comment by dietmarpravida** [comment]
Geviertstriche

**Comment by gerritbruening** [comment]
Was haben wir denn jetzt generell?
Siehe
http://dev.faustedition.net/print/faust.23#l3790
wo sich Geviertstriche und Halbgeviertstriche abwechseln.

**Comment by gerritbruening** [comment]
Das folgende scheint mir widersprüchlich:

                        <l n="4139">So <seg type="lem" xml:id="seg.4139">–</seg> es war, gefiel
                            mir’s doch.<note type="textcrit" xml:id="app.4139"><ref>4139</ref><app
                                    from="#seg.4139">
                                    <lem
                                        wit="faust://document/faustedition/A faust://document/faustedition/B faust://document/faustedition/B.a"
                                        >— <note>

Im Text steht –, im Lemma steht —.

**Comment by thvitt** [comment]
Im Text und in der Endstufe stehen Halbgeviertstriche, weil die auf euren bereits länger her seienden Wunsch so normalisiert werden.

Im Apparat wird nix herumnormalisiert, sondern alles so übernommen, wie ihr’s da hineingeschrieben habt. In der Praxis heißt das, dass Ihr entscheiden müsst, ob ich die Normalisierung Halbgeviert- → Geviertstrich 

a) im Lesetext
b) in den Drucken und der Endstufe der Handschriften

entfernen soll. Außerdem müsstet Ihr entscheiden, ob wir (wenn nicht nach Halbgeviertstrich normalisiert wird) nach bereits in den Quellen codierten Halbgeviertstrichen gesucht und diese zu Geviertstrichen normalisiert werden sollen.

**Comment by gerritbruening** [comment]
Gut, dann schlage ich vor:
* Die Normalisierung des Grundtextes bleibt, wie sie ist.
* @dietmarpravida, du sagst mir, wo im Grundtext Zensurstriche vorkommen.
* Ich kennzeichne diese Geviertstriche `<pc type="censorship">` oder so.
* @thvitt, du schließt die `<pc type="censorship">`-Geviertstriche von der Normalisierung aus.

Könnte das passen?

**Comment by dietmarpravida** [comment]
Zensurstriche:
3961
4139
4142
4143

**Comment by gerritbruening** [comment]
Habe jetzt an den bewussten Stellen `<pc type="censorship">—</pc>` eingefügt.
Komischerweise sind die gemäß Schema nicht erlaubt.

**Comment by thvitt** [comment]
Das ist vllt. auch ganz gut so, denn ich sehe gerade, was ich vorher übersehen habe – das Einsetzen des Apparats funktioniert natürlich nicht mehr, wenn da `<pc>` drumrumsteht. Muss also vor `text-insert-app.xsl` wieder raus.

**Comment by dietmarpravida** [comment]
1821

**Comment by thvitt** [comment]
apparateinfügen klappt immernoch nicht

**Comment by thvitt** [comment]
so jetzt schon.

Ich habe die Normalisierung der Zeichen aus dem []{} im Apparat herausgenommen, so dass jetzt einzelne neue Abweichungen aufgetaucht sind, die vorher toleriert wurden, die müsst ihr im Apparat noch anpassen.

http://dev.digital-humanities.de/ci/view/Faust/job/faust-gen-fast/lastSuccessfulBuild/artifact/target/lesetext/app-validation.html#dangling

**Comment by dietmarpravida** [comment]
Wir könnten das nur im Satz machen und in der Edition darauf verzichten. Allerdings haben die Striche eine klare Bedeutung: je ein Strich steht für je ein zensiertes Wort, daher sollte die Zahl der Striche schon irgendwie erkennbar bleiben.

**Comment by thvitt** [comment]
hä? Ich seh grad das Problem nicht? Es muss auch kein Wort sein für's Apparateinsetzen

Die Zensurstrichfälle sollten doch jetzt alle erschlagen sein. Bei dem hier:
> 2814 | — | — | Den hat ein Pfaff hinweggerafft! –
ist einfach in Apparat und Text ein unterschiedlicher Strich, d.h. entweder im Text `<pc type="censorship">—</pc>` (aber das ist hier nicht der fall?) oder im Apparat `–`.

**Comment by dietmarpravida** [comment]
ich sehe das problem auch nicht wirklich

**Comment by gerritbruening** [comment]
Nein, das war ein bisschen off topic. Sub specie apparatus ist alles OK.

**Comment by gerritbruening** [comment]
http://dev.faustedition.net/print/faust.12#app.2814 ist jetzt noch komisch, sonst könnte das geclosed werden, oder?

**Comment by dietmarpravida** [comment]
Wie ist das komisch?

**Comment by gerritbruening** [comment]
Wegen
![grafik](https://user-images.githubusercontent.com/10358005/39779061-53b8e71c-5308-11e8-9cf4-6b6c377e7cac.png)
mal Geviertstrich, mal Halbgeviertstrich.
Man beachte auch den Unterschied zwischen Text und Lemma.

**Comment by thvitt** [comment]
Der Strich muss im XML für A als `<pc type="censorship">—</pc>` codiert werden, sonst wird er wegnormalisiert.

**Comment by dietmarpravida** [comment]
Geht es bei 2184 um Zensurstriche? Oder um gewöhnliche Gedankenstriche?

**Comment by thvitt** [comment]
wenn’s gedankenstriche sind, musst du halt im Apparat auch welche setzren und nicht geviertstriche, weil wir gedankenstriche im Lesetext normalisieren … oder @gerritbruening ?

**Comment by dietmarpravida** [comment]
Meine Frage war, ob es sich um Gedankenstriche handelt, oder nicht vielleicht eben doch Zensurstriche. Pampige Bemerkungen sind hier ausnahmweise nicht am Platz.

**Comment by gerritbruening** [comment]
> Der Strich muss im XML für A als <pc type="censorship">—</pc> codiert werden, sonst wird er wegnormalisiert.

Da es kein Zensurstrich ist, kann und soll er normalisiert werden.

> wenn’s gedankenstriche sind, musst du halt im Apparat auch welche setzren und nicht geviertstriche, weil wir gedankenstriche im Lesetext normalisieren … oder @gerritbruening ?

Ja, @dietmarpravida, das scheint mir genau das Problem zu sein. Im Apparateintrage stehen Geviertstriche (—), es müssten aber Halbgeviertstriche stehen.

**Comment by gerritbruening** [comment]
Wenn das so ist.
Wenn das nicht so ist, kodiere ich brav `<pc type="censorship">—</pc>`, und dann müssen die Geviertstriche auch im Apparateintrag bleiben.
