### ISSUE TITLE
Apparat zu before_2603

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#314]
Hier entsteht ein zweimaliger Punkt in `<seg type="lem" xml:id="seg.before_2603.leise">Leise.</seg>.`

Dieses XML kommt raus:

                        <stage n="before_2603"><seg type="lem" xml:id="seg.before_2603.leise"
                                >Leise.</seg>.<note type="textcrit" xml:id="app.before_2603.leise"
                                    ><ref>vor 2603</ref><app from="#seg.before_2603.leise">
                                    <lem wit="faust://document/faustedition/S">Leise. <wit
                                            wit="faust://document/faustedition/S">S</wit></lem>
                                    <rdg
                                        wit="faust://document/faustedition/A faust://document/faustedition/D.1"
                                            >Leise<pc>‸</pc>
                                        <wit f:is-base="true" wit="faust://document/faustedition/A"
                                            >A</wit>
                                        <wit wit="faust://document/faustedition/D.1">D<hi
                                                rend="superscript">1</hi></wit></rdg>
                                    <rdg wit="faust://document/faustedition/B">Leise. <wit
                                            wit="faust://document/faustedition/B">B</wit></rdg>
                                    <rdg wit="faust://document/faustedition/B.a" type="type_1c"
                                        >(Leise.) <wit wit="faust://document/faustedition/B.a">B<hi
                                                rend="superscript">a</hi></wit></rdg>
                                </app></note></stage>

**Comment by thvitt** [comment]
Wie der `without-app.xml` entnommen werden kann, lautet before_2603 vor der Anwendung des Einzelstellenapparats:

```xml
<stage n="before_2603">Leise.</stage>
```

Die Textform des Apparateintrags:

```
before_2603[Leise]{Leise.} <i>vor 2603</i> Leise. <i>S</i>]   Leise^ <i>A D.1</i> Leise. <i>B</i> (Leise.) <i>B.a [type=1c]</i>
```

Wenn im endgültigen Text ein . stehen soll, muss das hier mit `before_2603[Leise.]{Leise.}` beginnen, andernfalls mit `before_2603[Leise.]{Leise}`. Die Normalisierungen (Punkt und Klammern in BA) erfolgen bevor der Einzelstellenapparat angewandt wird.
