### ISSUE TITLE
Amb rule matches for "Vers ..." & "Vers Antilabe"?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#319]
Don't know at the moment if these may interfere.

**Comment by pglatza** [comment]
There are no ambiguous rule matches, during idml synthesis, at the moment.

The current mapping rules for `l` are:
priority="1" for 'Vers Abstand' (`*:lg[preceding-sibling::*[1]/self::*:lg]/*:l[1]`)
priority="2" for 'Vers Einrückung' (`*:lg[@rend eq 'indented']/*:l`)
priority="3" for 'Vers Antilabe' (`*:l[@part = ('M', 'F')]`)
priority="3" for 'Vers Einrückung Abstand' (`*:lg[@rend eq 'indented'][preceding-sibling::*[1]/self::*:lg[@rend eq 'indented']]/*:l[1]`)
'Vers' as default paragraph style for `l`

**Comment by gerritbruening** [comment]
Thanks!

As Wagner puts it:

                        <l n="524">In dieser Kunst möcht’ ich <seg type="lem" xml:id="seg.524.was"
                                >’was</seg> profitiren,

Will compare your list with my XPath expressions in the docu.
