### ISSUE TITLE
before_949_c Tanz und Gesang

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#323]
@dietmarpravida, kein Abstand davor, aber halbzeiliger Abstand danach? (dazu tendieren @markusciupke und ich). Bitte festlegen.

**Comment by markusciupke** [comment]
Ich habe mir die Stelle noch mal angeschaut und bin unsicher. Verse folgen sonst immer ohne Abstand auf Sprecher oder Bühnenanweisungen mit Figur (= Sprecher). Hier sind das die Bauern. Also dürfte hier kein Abstand zwischen der BA und dem Vers sein. Man könnte sonst meinen, der Text gehöre zu Wagner.
Zum Anschauen hänge ich mal beide Varianten an:
[Bauern unter der Linde mit Abstand.pdf](https://github.com/faustedition/faust-gen-html/files/1799384/Bauern.unter.der.Linde.mit.Abstand.pdf)
[Bauern unter der Linde ohne Abstand.pdf](https://github.com/faustedition/faust-gen-html/files/1799385/Bauern.unter.der.Linde.ohne.Abstand.pdf)

**Comment by dietmarpravida** [comment]
Wie wäre es mit Abstand davor und danach?

**Comment by pglatza** [comment]
@markusciupke, welches wäre das treffende Absatzformat hierfür, wenn wir Abstand davor und danach vorsehen?

**Comment by markusciupke** [comment]
Abstand davor und danach hat die obere Variante zum Anschauen (Bauern unter der Linde mit Abstand.pdf).
Die untere Variante hat nur Abstand nach oben.
Abstand davor und danach würde folgende Absatzformate erfordern:
»Bauern unter der Linde.«: C BA zentr. 2,3 / 0,0
»Tanz und Gesang.«: A BA zentr. 2,3 / 0,0
Vers 949: Vers Abstand (das sind 2,3 mm nach oben

Man kann ein Absatzformat sparen, wenn zwischen »Bauern unter der Linde.« und »Tanz und Gesang.« nicht ein Absatz sondern ein Zeilenumbruch ist (weicher Absatz). Dann muss der Absatz das Format C BA zentr. 2,3 / 0,0 haben.

Aber wie gesagt: da Verstext sonst immer ohne Abstand auf den Sprecher folgt, dürfte hier nach meiner Ansicht zwischen den Bauern und Vers 949 kein Abstand sein.

**Comment by pglatza** [comment]
Also dann würde ich die aktuelle Mapping-Konfiguration einfach unangetastet lassen:
C BA zentr. 2,3 / 0,0 (Bauern unter der Linde.)
A BA zentr. 0,0 / 0,0 (Tanz und Gesang.)
Darstellung eben in InDesign kontrolliert: wie in [Bauern unter der Linde ohne Abstand.pdf](https://github.com/faustedition/faust-gen-html/files/1799385/Bauern.unter.der.Linde.ohne.Abstand.pdf)

Ich persönlich empfinde die Variante mit Abstand auch als weniger passend.

**Comment by dietmarpravida** [comment]
Editorisch ist die Frage nicht so sehr die Simmigkeit, sondern ob der Originalddruck möglicherweise einen signifikanten Befund der (nicht erhaltenen) Handschrift wiedergibt, dessen Spuren nicht verdeckt werden dürften. Das scheint hier tatsächlich so sein, daher sollte die Stelle m.E. vielleicht  nicht einfach als normale Replik behandelt werden.

**Comment by dietmarpravida** [comment]
ist das noch aktuell

**Comment by gerritbruening** [comment]
Ich habs jetzt mal aus idml rausgenommen und auf die erste Fahne verschoben.

**Comment by markusciupke** [comment]
Ja, das ist noch aktuell. Ihr müsst jetzt oder in der ersten Fahne eine Entscheidung treffen, wie die Abstände geregelt sein sollen.

**Comment by gerritbruening** [comment]
@pglatza 
> welche Mapping-Regeln für bspw. `<stage n="before_949_c">Tanz und Gesang</stage>`? Hier müsste ich die IDML-Synthese einstellen, dass auch bei Nicht-Vorhandensein des hi-Elementes eine Sperrung stattfindet?

@pglatza, hier habe ich für die IDML-Synthese kapituliert und das (zumindest für mich selbst) auf die erste Fahne verschoben und aus  `label:idml` rausgenommen. Mein Vorschlag: einfach normale Regeln anwenden.

**Comment by markusciupke** [comment]
Wenn ich es richtig sehe, haben wir bislang nur über die Abstände diskutiert. Die sind geklärt. 
Jetzt noch die Frage: Soll »Tanz und Gesang« vor 949 gesperrt werden? Gesperrt und vor einer Linie ist die Zeile in D1. So auch in A? – Die Zeile erscheint damit stark herausgehoben, weswegen mir eine Sperrung im konstituierten Text plausibel erscheint. – Bitte entscheidet.

**Comment by dietmarpravida** [comment]
Wenn die Schriftgröße gleich der der BA ("unter der Linde") ist, dann leicht sperren

**Comment by markusciupke** [comment]
Es ist der gleiche Schriftgrad. Wird gemacht.

**Comment by dietmarpravida** [comment]
@markusciupke Bitte verzeichne **alle** Eingriffe, die du machst auf einer Seite. Dafür ist #521 vorgesehen, wenn dieser Issue inzwischen auch schon ganz zerschossen ist. Aber vielleicht klappt es doch noch damit. Viellleicht schreibst du **alles**, was du änderst (inkl Formatzuweisungen, Leerzeichen etc:)  **nach Verszahlen geordnet** in **einen einzigen** comment, den du über diese Schaltfläche rechts oben zweite von links:

![edit](https://user-images.githubusercontent.com/26788529/41232281-28277364-6d86-11e8-8bc0-002acf8ed7c3.JPG)

nachbearbeiten kannst.

**Comment by markusciupke** [comment]
In Ordnung, das wusste ich nicht.

**Comment by gerritbruening** [comment]
Hat seine eigene Behandlung erfahren.
