### ISSUE TITLE
Word index for reading text, ordered by frequency

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#324]
We already have something similar, see
* #154
* http://dev.faustedition.net/word-index

It would be helpful to confine this to the reading text. May uncover some tokens which are suspicious.

**Comment by thvitt** [comment]
Wird unter <http://dev.faustedition.net/print/faust.wordlist> erscheinen

**Comment by gerritbruening** [comment]
Alles klar, danke, schaue ich mir morgen an!

**Comment by gerritbruening** [comment]
Firefox hört nicht auf zu laden, und zeigt nur dies:
![grafik](https://user-images.githubusercontent.com/10358005/37565984-47cbac96-2ab3-11e8-9ef9-8c3ebfee77fc.png)

In Chrome sieht das genauso aus, aber ohne Laden.

**Comment by thvitt** [comment]
ach kack, bei mir gings, was hab ich denn nun falsch gemacht :(
