### ISSUE TITLE
Achtelgeviertabstand in InDesign verloren

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#325]
Zwischen Auslassungspunkten steht im XML ein

> NARROW NO-BREAK SPACE in Achtelgeviertbreite

Zur Zeichenkodierung in der XML-Quelle siehe @thvitt|s https://github.com/faustedition/faust-gen-html/issues/196#issuecomment-363948288.

Dieses Zeichen wird aber von InDesign offenbar nicht respektiert:

> die Leerräume zwischen Auslassungspunkten, die normal groß waren

(@markusciupke per Mail)

**Comment by pglatza** [comment]
@markusciupke, ist dieses Unicode-Zeichen (U+202F) als Glyphe überhaupt in der Schrift WSVgara vorhanden? Bzw. kommt dieses Zeichen in bestimmten Schriftschnitten dieser Schrift nicht vor?

 char, hex: 202F
 char, dec: 8239
  name: NARROW NO-BREAK SPACE
  general-category: Zs (Separator, Space)

**Comment by markusciupke** [comment]
InDesign gibt mir bei den Glyphen folgende Info:
GID 351
Unicode 2009
THIN SPACE

Der Leerraum heißt Achtelgeviert und wird bei mir mit cmd-alt-shift-m erzeugt.
Ich hoffe, die Angaben helfen dir weiter?

Wie dieses Zeichen in unseren Font gekommen ist, kann ich nicht sagen. 
Am Ende wäre es natürlich kein Problem, wenn ich die Achtelgevierte durch Suchen & Ersetzen einsetze.

**Comment by pglatza** [comment]
Ich kann das nicht reproduzieren. Bei mir steht zwischen den Punkten ein U+202F, auch in InDesign.
Im gesamten XML-Dokument kommt kein Thin Space (U+2009) vor.

Allerdings habe ich die Schrift WSVgara auch nicht installiert. Deshalb habe ich die Vermutung, dass die Schrift dieses Zeichen gar nicht unterstützt?!

Oder wolltest du fragen, ob alle U+202F im Element `g` zu U+2009 geändert werden könnten?

**Comment by markusciupke** [comment]
Ich komme ja nicht von der technischen Seite und kenne mich da leider nicht so gut aus. Was ich  sagen will ist, dass da nur ein eindeutiges Zeichen stehen muss. Im Moment ist das wohl U+202F. Bei mit erscheint das als ein Leerzeichen mit fester Breite, welche aber breiter ist als die eines Achtelgevierts. Ich kann dann am Ende unser Zeichen mit der richtigen Breite eintauschen. Das ist dann für mich eine Sache von weniger als eine Minute, so dass wir hier darauf keine Zeit mehr verwenden müssen.
