### ISSUE TITLE
BA Blocks. immer mit halbzeiligem Abstand nach oben?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#327]
evtl. alle einen halbzeiligen Abstand nach oben?

(betrifft die ohne Figur, auch wenn diese auf eine Replik folgen und von daher nur 1/4 Zeile Abstand bekämen)

Muss ich mir mal überlegen.

**Comment by gerritbruening** [comment]
Tendiere sehr zu einheitlicher Behandlung, d.h. auch lange BAs ohne Figur in Anschluss an Repliken sollten 1/4 Zeile Abstand haben.

**Comment by gerritbruening** [comment]
Bei Gelegenheit des Probesatzes S. 234f.: Die Nacht- und Grabdichter sind so ein Fall.
Der Abstand im Probesatz scheint minimal, vllt. einen halben Millimeter geringer. Ist das schon die Viertelzeile, @markusciupke, oder hat das mit den unterschiedlichen Schriftgrößen zu tun?

**Comment by markusciupke** [comment]
Ich habe hier eine halbe Leerzeile Abstand nach oben (2,3 mm) und finde es sieht gut aus. Ich mache es morgen mal mit einer einer viertel Leerzeile (1,15 mm) nach oben.
Ich verstehe nicht, was du mit dem halben Millimeter meinst. Zwischen welchen Elementen ist der Abstand vielleicht einen halben Millimeter geringer als welcher andere Abstand?

**Comment by gerritbruening** [comment]
> Ich verstehe nicht, was du mit dem halben Millimeter meinst. Zwischen welchen Elementen ist der Abstand vielleicht einen halben Millimeter geringer als welcher andere Abstand?

Ich habe mit einem Lineal jeweils von Grundlinie bis Grundlinie gemessen. Wahrscheinlich rührt das Unterschiedliche Messergebnis wieder von einer Anhebungen her.

Stand jetzt würde ich ungern an der Regel rühren oder neue Kriterien wie "Inhalt" und dgl. einführen. Für den jetzt gerade anstehenden Zweck habe ich kein Problem, einen halbzeiligen Abstand zu setzen, denn der Viertelzeilige ist ohne Kontext und ohne Erläuterungen zur Einrichtung des Drucks nicht verständlich. Als "endgültig" sehe ich heute weder die eine noch die andere Entscheidung an.

**Comment by markusciupke** [comment]
In Ordnung, das betrifft ja ohnehin nur drei Blocksatzstellen. Wieviele zentrierte Stellen es sein könnten, wird man sehen, wenn ich den Umbruch mache.

Für die Antrags-Anlage nehme ich den schmalen Satzspiegel.

**Comment by gerritbruening** [comment]
Ich bin momentan dafür, die allgemeine Regel anzuwenden. Dass einige BAs eine bessere Lobby haben als andere, scheint mir als Prinzip nicht gut vertretbar zu sein, inhaltliche Selbständig ist schwer einzugrenzen. Sprechen wir anhand der ersten Fahne darüber.

**Comment by dietmarpravida** [comment]
dürfte erledigt sein?

**Comment by markusciupke** [comment]
Ja, ich hab’ aufgegeben.
