### ISSUE TITLE
Darstellung von wit/hi

### ISSUE THREAD

**Issue by pglatza** [faustedition/faust-gen-html#329]
`wit/hi[@rend='superscript']` ist für die IDML-Synthese [dokumentiert.](https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#siglenziffer) Doch wie steht es um `hi` ohne Attribute innerhalb eines `wit`-Elementes einer textcrit-note?

Beispiel in n="21".

**Comment by thvitt** [comment]
In der faust.xml [aus dem Build](http://dev.digital-humanities.de/ci/job/faust-gen-fast/) kommt das nicht vor. Wäre wohl auch ein Bug

**Comment by pglatza** [comment]
Nein, habe mich verguckt. Hatte einen Zwischenstand offen und nicht noch einmal nachkontrolliert.
