### ISSUE TITLE
Text-Hochstellung

### ISSUE THREAD

**Issue by pglatza** [faustedition/faust-gen-html#330]
Im Fußnotentext sollen Inhalte [hochgestellt](https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#siglenziffer) werden.
Wie wollen wir das realisieren? Mit InDesign-Boardmittel oder Zeichenformat?
Letzteres wäre mein favorisierte Lösung, würde allerdings eine Anpassung und erneute Bereitstellung der InDesign-Template-Datei bedeuten.

**Comment by markusciupke** [comment]
Mit Zeichenformat! – @gerritbruening will mir Probedateien des Apparats und Vorschläge für die Auszeichnungen senden. Das sehe ich mir dann an und erstelle entsprechende Zeichenformate.
Im übrigen brauchst du sowieso eine neue ID-Datei, weil wir ja am 8. März die BA-Formate geändert haben (es sind jetzt nur noch vier statt sieben) und neue Formate für Überschriten eingeführt haben.

**Comment by pglatza** [comment]
In Ordnung. Mir fiel gerade auf, dass es an dieser Stelle ja bereits auch das Format 'Kursiv (Apparat)' gibt. Da die Hochstellung innerhalb dieser Auszeichnung vorkommt, müsste als Variante für das Zeichenformat Hochstellung dann auch mit 'Kursiv' geben.

**Comment by gerritbruening** [comment]
> Mir fiel gerade auf, dass es an dieser Stelle ja bereits auch das Format 'Kursiv (Apparat)' gibt.

Das habe ich soeben als deprecated markiert: https://github.com/faustedition/faust-gen-html/commit/efcc7b94d4feb81234f34d2b8e88423b1fc131e7

**Comment by markusciupke** [comment]
Das müsste doch geklärt sein. Alle benötigten Auszeichnungen im Apparat werden über Zeichenformate erzeugt.

**Comment by gerritbruening** [comment]
Ja, muss in die https://github.com/faustedition/faust-gen-html/issues/374#issuecomment-389103877 erwähnte Liste.
