### ISSUE TITLE
non-indented version of faust.xml

### ISSUE THREAD

**Issue by pglatza** [faustedition/faust-gen-html#333]
Currently, I can get a readable version of the faust.xml file via http://dev.digital-humanities.de/ci/view/Faust/job/faust-gen-fast/lastSuccessfulBuild/artifact/target/lesetext/faust.xml

Is there a location available, where the non-indented document can be downloaded? All xml nodes in one line (after xml declaration)?

**Comment by thvitt** [comment]
We don't have a non-indented version (the original sources are indented, and we never explicitely remove wsp). 

If there's a use case, we can probably build something using f:normalize-text, I remember some older approach targeted at indesign …

**Comment by pglatza** [comment]
The use case is easier whitespace-handling for the InDesign character style 'Sperrung'.
I think I`ve finished this step in idml synthesis preprocessing, so the issue is obsolete.
