### ISSUE TITLE
9165–9164 stärker eingerückt

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#337]
Grundsätzliches pattern ist `lg[@rend='indented']/l[@rend='indented']`.

Weiß nicht, ob man das in der Generierung berücksichtigen kann, da nun Zentrierung erzeugt wird (was ich für den Grobsatz irritierend finde).
Wäre es nicht nett, einen Grobsatz zu haben, wo normal eingerückte `l` soundso viele tabs davor bekommen und die extra eingerückten noch ein paar mehr?

**Comment by markusciupke** [comment]
Das kann man so machen. Dann ändere ich das Absatzformat und setze einen linksbündigen Tab auf 18 mm vom linken Satzspiegelrand (das scheint mir eine gute durchschnittliche Einrückung für die 1. Ebene zu sein) und einen auf 28 mm (2. Ebene). Dann richtet sich alles aus. Ihr müsstet nur wie gehabt vor die Einrückung der 1. Ebene einen Tab und vor denen der 2. Ebene zwei Tabs setzen. Im Feinsatz werde ich dann die »genaue« optische Mitte nacharbeiten.

**Comment by gerritbruening** [comment]
Okay, danke für dein Entgegenkommen! Die spätere Suche nach der optischen Mitte soll natürlich unbenommen sein.

**Comment by markusciupke** [comment]
Das ist doch kein Entgegenkommen! Ich hatte nur nach einer schnellen Lösung gesucht, und da hab ich dann die Zentrierung genommen. So sieht es wahrscheinlich sogar gleich besser aus. Und der Vorteil ist wohl auch, dass die zweite Ebene in der XML-Datei schon vorbereitet wird.

**Comment by pglatza** [comment]
In Ordnung. Dann muss auch bei der Synthese nichts weiter angepasst werden.

**Comment by gerritbruening** [comment]
Wir brauchen aber dann noch den Namen des Absatzformats und die neue Formatinfo für die Styles.xml, oder?

**Comment by markusciupke** [comment]
Die Absatzformatnamen »Vers Einrückung« und »Vers Einrückung Abstand«bleiben. Ich habe nur die Definitionen innerhalb der Formate geändert. Ihr oder Philipp müssen wie gehabt vor eingerückten Versen der 1. Ebene einen zusätzlichen Tab vor dem 1. Zeichen des Verses einfügen. Für die 2. Ebene müssen zwei zusätzliche Tabs vor dem 1. Zeichen des Verses eingefügt werden.

> Übrigens, die stärkere Einrückung bedeutet nicht, dass eine neue Versgruppe beginnt im Sinne von Vers Abstand. Also kein halbzeiliger Abstand nach oben.

Ist in Ordnung. Aber die Zuweisung der Absatzformate erfolgt ja sowieso bei euch. Möglicherweise ist an irgendeiner Stelle sowohl die Einrückung auf die 2. Ebene als auch ein Abstand nach oben erwünscht? Wenn nicht, weist ihr dem ersten eingerückten Vers der 2. Ebene eben nicht das Absatzformat »Vers Einrückung Abstand« zu, sondern einfach »Vers Einrückung«. Auf jeden Fall müssen aber 2 Tabs vor dem 1. Zeichen des Verses stehen.

**Comment by gerritbruening** [comment]
Ja, jetzt verstehe ich.
Habe das entsprechend dokumentiert [(idml.md)](https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#vers-einr%C3%BCckung).

**Comment by gerritbruening** [comment]
> Möglicherweise ist an irgendeiner Stelle sowohl die Einrückung auf die 2. Ebene als auch ein Abstand nach oben erwünscht?

Erwarte ich momentan nicht.
