### ISSUE TITLE
stage/hi nicht immer Auftritt

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#339]
> Es wurden von mir nur stage-Elemente mit der hi-Auszeichnung berücksichtigt. Die hi-Auszeichnungen werden in später zu Auftritt (Zeichenformat).

(https://github.com/faustedition/faust-gen-html/issues/242#issuecomment-373304643)
Das hört sich so an, als würde `stage/hi` zu `Auftritt`, auch wenn kein `move` vorhergeht (dementsprechend ist auch der Output). 
Das `move` wird aber immer verlangt, wenn es ein `Auftritt` werden soll, siehe https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#auftritt.

Zu normalem `stage/hi` ohne `move` siehe https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#figur.

**Comment by pglatza** [comment]
Das stimmt. Die Anpassungen stammen aus einer frühen Phase der IDML-Synthese, mit noch nicht 100%-ig definierten Mapping-Regeln bei den move-/stage- und hi-Elementen.
Upload-Konverter noch nicht aktualisiert.

**Comment by pglatza** [comment]
Die IDML-Synthese berücksichtigt nun das `move`-Element bei der Zuweisung des Zeichenformates Auftritt. Das Upload-Formular ist aktuell.

**Comment by gerritbruening** [comment]
Hierzu muss ich noch einmal rückfragen:

```xml
      <ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/A BA zentr. 0,0 / 0,0">
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Content>Director, Theaterdichter, lustige Person.</Content>
         </CharacterStyleRange>
         <Br/>
      </ParagraphStyleRange>
```

Da vermisse ich jetzt noch `CharacterStyle/Auftritt`.
Nach meiner Erwartung hätte hier der Ausdruck `move/following-sibling::*[1][self::stage[not(hi)]]` greifen sollen.
@pglatza, hast du eine Erklärung dafür, was hier passiert oder nicht passiert?

**Comment by pglatza** [comment]
Diesen Fall habe ich zusammen mit 4 anderen korrigiert.

Resultat nun: 
```xml
         <ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/A BA zentr. 0,0 / 0,0">
            <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Auftritt">
               <Content>Director, Theaterdichter, lustige Person</Content>
            </CharacterStyleRange>
            <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
               <Content>.</Content>
            </CharacterStyleRange>
            <Br/>
         </ParagraphStyleRange>
```

**Comment by gerritbruening** [comment]
OK, vielen Dank!
