### ISSUE TITLE
Scheinbares Verschwinden von Text in InDesign

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#340]
Hinweis von MC auf

![grafik](https://user-images.githubusercontent.com/10358005/37515585-898d97ec-290b-11e8-92cc-94d249a470c6.png)

(16.3.2018)

Das IDML sieht für mich in Ordnung aus:

      <ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/B BA zentr. 0,0 / 2,3">
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Auftritt">
            <hi AppliedCharacterStyle="CharacterStyle/Auftritt">
               <Content>Faust</Content>
            </hi>
         </CharacterStyleRange>
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Content>. </Content>
         </CharacterStyleRange>
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Auftritt">
            <hi AppliedCharacterStyle="CharacterStyle/Auftritt">
               <Content> Mephistopheles</Content>
            </hi>
         </CharacterStyleRange>
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Content>.</Content>
         </CharacterStyleRange>
         <Br/>
      </ParagraphStyleRange>

**Comment by pglatza** [comment]
Das war noch ein Fehler in der IDML-Synthese, der mit aktuellem Stand behoben wurde.

**Comment by gerritbruening** [comment]
Danke!
