### ISSUE TITLE
Bibelstellen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#341]
Siehe https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#bibelstelle.

Die kommen im IDML noch nicht an.

**Comment by pglatza** [comment]
Sind nun mit aktuellen Stand des Konverters in IDML drin. Upload-Formular aktualisiert.

**Comment by gerritbruening** [comment]
Ich finde dreimal `CharacterStyle/Bibelstelle`.
Theoretisch müssten es sieben sein (werden in der md auch aufgezählt).
Schöne wäre auch noch der `1 em` Abstand davor.

**Comment by gerritbruening** [comment]
Sind jetzt 7.
