### ISSUE TITLE
BA vor 350

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#342]
Hier gibt es eine Individualregel, die im IDML noch nicht greift:
https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#bas-vor-350

Habe die Formatnamen aktualisiert und die beiden Alternativen noch einmal formuliert.

**Comment by pglatza** [comment]
Ist nun umgesetzt und via Upload-Formular verfügbar.

**Comment by gerritbruening** [comment]
Sehe es, sehr gut, danke!
