### ISSUE TITLE
ß --> ss in Versalien

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#343]
Betrifft

                        <div f:n="1.1.11" f:label="Straße" type="scene">

                        <speaker n="before_10903">
                           Erztruchseß
                        </speaker>

STRASSE, ERZTRUCHSESS -- richtig?

**Comment by markusciupke** [comment]
Bis einschließlich 3. April 2018 bin ich nicht im Büro. In dringenden Fällen wenden Sie sich bitte an meine Kollegin Lynn van Leewen (lvanleewen@wallstein-verlag.de).

Mit freundlichen Grüßen
Markus Ciupke

**Comment by thvitt** [comment]
Nicht ẞ? :-)

**Comment by gerritbruening** [comment]
Bitte nicht :-)

**Comment by markusciupke** [comment]
Wir haben für die auch für Faust verwendete Schrift letztens ein Versal-ß bekommen. Ich habe die Schrift aber noch nicht installiert und das Versal-ß noch nicht ausprobiert. Lasst uns doch mal  nach Ostern anschauen wie STRASSE in der Kolumnenzeile mit Versal-ß aussieht. Ich bin selbst gespannt.

**Comment by markusciupke** [comment]
Ich habe das inzwischen ausprobiert und ich finde es sieht **SCHEI**ẞ**E** aus mit großem ẞ. Seht selbst:
[Straße mit großem ß.pdf](https://github.com/faustedition/faust-gen-html/files/2009383/Strasse.mit.grossem.ss.pdf)
[Erztruchseß mit großem ß.pdf](https://github.com/faustedition/faust-gen-html/files/2009384/Erztruchsess.mit.grossem.ss.pdf)
Was mich betrifft kann es bei SS für ß bleiben und das Issue geschlossen werden.

**Comment by gerritbruening** [comment]
Dann hinfort

**Comment by gerritbruening** [comment]
Ach so, es muss ja noch umgesetzt werden.

**Comment by markusciupke** [comment]
Was meinst du damit? Das muss doch ich umsetzen, indem ich den Schriftfont ohne großem ß auswähle.

**Comment by markusciupke** [comment]
Nein, im Szenentitel bleibt es doch bei groß/klein »Straße«.
[Seite 114-115.pdf](https://github.com/faustedition/faust-gen-html/files/2009735/Seite.114-115.pdf)

**Comment by gerritbruening** [comment]
Scheint kein Problem zu sein.
