### ISSUE TITLE
Einrückungen 5441ff., 5484

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#346]
Hier scheint grundsätzlich etwas faul zu sein:

```
ERROR:parse_app2norm: No match: 5441|5445|5449|5452[@lg|@lg|@lg|@lg]{rend="indented"|rend="indented"|rend="indented"|rend="indented"} <i>5441–5456 Die Verse sind in I_H.0a nicht eingerückt [type=1c]</i>

ERROR:parse_app2norm: No match: 5484[^]{<milestone unit="lg" rend="indented"/>} <i>5484–5493 Die Verse sind in I_H.0a nicht eingerückt [type=1c]</i>
```

@thvitt, kann es sein, dass ich hier die Regel missverstanden habe?

Diese Kommentar scheint einschlägig zu sein: https://github.com/faustedition/faust-gen-html/issues/119#issuecomment-357749252

**Comment by thvitt** [comment]
`</i>` nach der Stellenangabe ist zwingend

**Comment by gerritbruening** [comment]
Danke!
Ich schaue beim nächsten Update, dass `... 5441–5456</i> <i>Die Verse ...` dasteht.

**Comment by gerritbruening** [comment]
Korrigiere: Ich sage jetzt
_5441–5456_] _Die Verse ..._ 
und
_5484–5493] _Die Verse ..._ 
wegen https://github.com/faustedition/faust-gen-html/issues/238#issuecomment-362556312
