### ISSUE TITLE
Apostrophe in faust.wordlist

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#347]
Z.B. http://dev.faustedition.net/print/faust.9#l2520

Hier wird "ält" indexiert, es müsste aber " ält’ste" indexiert werden. Ist das möglich?
Apostrophe am Ende von Wörtern sind auch noch Teil des Wortkörpers.

**Comment by thvitt** [comment]
a6f8f91bd1fc5890ea35af39817e7537f2a9ed33

**Comment by gerritbruening** [comment]
Danke, schaue ich mir morgen an!
