### ISSUE TITLE
app after_6358

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#349]
Folgender Eintrag in app2norm.txt:
`after_6358[]{} <i>nach 6358</i> <speaker>Page.</speaker> <l>Ich bin verliebt, man hält mich nicht für voll.</l> <speaker>Meph.</speaker> <stage>(bey Seite)</stage> <l>Ich weiß nicht mehr wohin ich hören soll.</l> <i>in Lücke erg Ec 2_H [type=6]</i>`
sieht erstmal unkaputt aus.

Da ist wahrscheinlich was illegal?

**Comment by thvitt** [comment]
Die Lemmaklammer fehlt. Dadurch wird die Klammer nach `type=6` als Lemma-Ende interpretiert, und die einzelnen Teile sind dann wg. dem `<i>` nicht wohlgeformt.

**Comment by gerritbruening** [comment]
Alles klar, habe jetzt
_nach 6358_] PAGE ...
