### ISSUE TITLE
Include 1 H.1 within list of manuscripts

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#35]
So that //print/metadata documents appear on archive_manuscripts.php when they are supplied with an 

    //idno[@type="faustedition_ms"]

**Comment by thvitt** [comment]
whatever you do, please don't remove `<idno type="faustedition">`, these are expected to be in _every_ document.

(Maybe rather tell me what you attempt to achieve?)

**Comment by gerritbruening** [comment]
That is a good point.
What we want to achieve is this: a print-like object, 1 H.1, should appear among the manuscripts.

**Comment by thvitt** [comment]
Only this single one or all that have a repository?

**Comment by gerritbruening** [comment]
For the moment only this one I'd think.

**Comment by gerritbruening** [comment]
@thvitt , ABR has just stumbled over that again, is this still beta or post-beta?

**Comment by thvitt** [comment]
`faust://xml/document/archival/dla_marbach/Cotta_Ms_Goethe_AlH_C-1-12_Faust_I.xml`
