### ISSUE TITLE
Handling of <corr> in text generation

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#351]
391098 has

                           <l n="6126">Und<corr> d</corr>as Papier

In faust.xml this is

                           <l n="6126">Und das Papier

Consequently, the app entry which has `Undas` as replacement-string, is not inserted. I could easily remove this `corr`, but it is safer to look after the `corr` processing, I think.

**Comment by thvitt** [comment]
[text-cleanup.xsl](https://github.com/faustedition/faust-gen-html/blob/2ff18c72636672eb3facf03b8492e4dabf8c45ff/xslt/text-cleanup.xsl#L25) has `corr` under _These elements are replaced with their respective content_, which is exactly what happens – so what `corr` handling would you expect?

**Comment by gerritbruening** [comment]
Thanks for this hint!
