### ISSUE TITLE
Add faust.xml to prepare-reading-text

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#353]
@thvitt, I would like to resume work with prepare-reading-text.xpl.
Can I add the faust.xml to this pipeline, or is this incompatible with the current `<base>http://dev.faustedition.net/xml</base>`?

**Comment by thvitt** [comment]
I haven't looked at `prepare-reading-text.xpl` for quite some time, but the steps in there should already have been applied to faust.xml, so it doesn't really make sense to pass this through the pipeline.

**Comment by gerritbruening** [comment]
OK, so if I wish to condense faust.xml even a bit more (remove attributes from `<div xmlns:f="http://www.faustedition.net/ns" f:n="1.0.1" f:label="Zueignung">`, `seg` etc., I best do this in a separate xsl that runs directly on the locally saved faust.xml?

**Comment by thvitt** [comment]
1. namespace declaration in divs is a mistake, I'll move this into the TEI element
2. `f:n` should really be `n` … I'll fix this
3. I haven't touched prepare-reading-text.xpl for a while, but the additional attributes are added by text-postprocess.xsl which will probably need to be included.

I have never attempted to make the adjustments in the reading text idempotent, so I can't guarantee that running faust.xml through the pipeline again works flawlessly.

**Comment by gerritbruening** [comment]
Never heard of idempotency before.
Anyway, as I don't oversee the implications, I will will wait for the steps you mention and will work with faust.xml in the current form.
