### ISSUE TITLE
app f:replace processing requires wsp-normalized text

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#354]
**Parsed**
`INFO:parse_app2norm: Parsed: before_5987_c[anständig, nicht auffallend, nach Sitte gekleidet, beyde knieen.]{=} <i>vor 5987</i> anständig <gap reason="ellipsis"/> knieen. <i>2_I_H.0a</i>] anständig nicht auffallend <gap reason="ellipsis"/> knieen. <i>2_H :</i> (anständig <gap reason="ellipsis"/> knieen.) <i>Ec [type=6]</i>`
but it sill appears under the heading
> Bei 4 Einträgen hat das Einfügen nicht geklappt:

My suspicion is that the linebreak before "knien"

                            <stage n="before_5987_c">Der <hi>Kayser</hi>, <hi>Hofleute</hi>; <hi>Faust</hi>, <hi>Mephistopheles</hi>, anständig, nicht auffallend, nach Sitte gekleidet, beyde
                                knieen.<note type="textcrit" xml:id="app.before_5987_c.anständignichtauffallendnachsittegekleidetbeydeknieen"><ref>vor 5987</ref><app from="#seg.before_5987_c.anständignichtauffallendnachsittegekleidetbeydeknieen"><lem wit="faust://document/faustedition/2_I_H.0a">anständig <gap reason="ellipsis"/> knieen.  <wit f:is-base="true" wit="faust://document/faustedition/2_I_H.0a">I H<hi rend="superscript">0a</hi></wit></lem><rdg wit="faust://document/faustedition/2_H">anständig nicht auffallend <gap reason="ellipsis"/> knieen.  <wit wit="faust://document/faustedition/2_H">H</wit></rdg><rdg wit="faust://document/faustedition/2_H" type="type_6">(anständig <gap reason="ellipsis"/> knieen.) <note>Ec</note>  <wit wit="faust://document/faustedition/2_H">H</wit></rdg></app></note></stage>

prevents the search-string from being found.

**Comment by thvitt** [comment]
yes. we _might_ try to normalize whitespace everywhere, would also deal with #333, but I guarantee for nothing.

**Comment by gerritbruening** [comment]
Thanks
Since you could fix this without general whitespace normalization, we can leave it like this, I think.

**Comment by gerritbruening** [comment]
I still don't see the `seg`.

**Comment by thvitt** [comment]
f:normalize-space seems to not work in this line :(

I hate whitespace.
