### ISSUE TITLE
BAs in Apparaten

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#359]
Auch hier müssen u.U. die Abstandsregelungen greifen, abhängig davon, wie die Apparateinträge insgesamt aussehen.
Die bisherigen Regeln für die BAs setzen voraus, dass es sich um normale BAs (im Text) handelt, d.h. es immer zusätzlich die Bedingung `not(ancestor::note[@type='textcrit'])`. Evtl. kann das sicherheitshalber in die IDML Pipeline eingebaut werden?

**Comment by pglatza** [comment]
Welches Absatzformat soll standardmäßig BAs in Apparaten zugewiesen werden?
Hattet ihr euch schon Regelungen und Formate hierfür überlegt?

**Comment by gerritbruening** [comment]
Mir ist nicht ganz klar: Gibt es in Fußnoten wiederum Absätze? Ist die Fußnote selbst ein Absatz?

**Comment by gerritbruening** [comment]
> Welches Absatzformat soll standardmäßig BAs in Apparaten zugewiesen werden?
Hattet ihr euch schon Regelungen und Formate hierfür überlegt?

Darüber haben wir noch nicht diskutiert. Ich würde sagen, dass hier vorläufig analog zum Text verfahren werden sollte. Im Moment gibt es aber nur neun `stage`-Elemente; in den Apparateinträgen zum Faust&nsp;I fehlen offenbar noch welche. Das kann ich erst nach Ostern klären und korrigieren.

**Comment by gerritbruening** [comment]
Diskutieren wir genügend unter anderen Issues.
