### ISSUE TITLE
Link on the GSA's archive database

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#36]
- [X] generate list of shelfmark
- [x] get match on "Ident-Nummern"
- [x] define links (see below https://github.com/faustedition/faust-gen-html/issues/36#issuecomment-247279202)
- [x] define place of link
- [ ] integrate Ident-Nummern as idno into the metadata
- [x] generate links

**Comment by gerritbruening** [comment]
Here is the List of archival shelfmarks and "Ident-Nummern":
[Faust-Signaturen.xlsx](https://github.com/faustedition/faust-gen-html/files/474240/Faust-Signaturen.xlsx)

> Wenn ich es richtig verstehe, muss man vor die Nummer die Adresse http://ora-web.swkk.de/archiv_online/gsa.Vollanzeige?u_id=1663579&id=
setzen.
Beim ersten Eintrag (312226) erhält man dann:
http://ora-web.swkk.de/archiv_online/gsa.Vollanzeige?u_id=1663579&id=312226
Dieser Link funktioniert, aber man gelangt auf eine Seite das übliche "Drumherum".
Wenn ich mich durch die Archivdatenbank klicke, gelange ich zu einer Seite mit dem üblichen "Drumherum" (im Anhang).
Diese hat aber den Nachteil, dass ihre Adresse nicht eindeutig ist. Sie heißt:
http://ora-web.swkk.de/archiv_online/gsa.entry?u_id=1663579&b=13&source=gsa.bestaende2
Gibt es einen Weg, einen genauen Link für die übliche Ansicht der Archivdatenbank mit Rahmenelementen zu erhalten?

(an SH, 15.9.16)

**Comment by gerritbruening** [comment]
The correct link would have the following structure:

    http://ora-web.swkk.de/archiv_online/gsa.entry?p_id=312226&source=gsa.vollanzeige

So all we have to do is to concatenate the following strings:
 1. `http://ora-web.swkk.de/archiv_online/gsa.entry?p_id=`
 2. {Ident-Nummer, e.g. `312226`}
 3. `&source=gsa.vollanzeige`

**Comment by thvitt** [comment]
Is that ident nr somewhere in our metadata? If not, it should probably be there?

**Comment by gerritbruening** [comment]
Yes, we could insert it into our metadata as a special type of `idno`.

**Comment by gerritbruening** [comment]
Were could the link be placed on the page?
* after the shelfmark?
* among "Bibliographische Nachweise" (better "Nachweise")?

I have just asked SH for her preference.

In any case, the link should be rendered as an **external** link, shouldn't it?

**Comment by thvitt** [comment]
I'd think the obvious solution is to make the shelfmark a link.

Do we have separate styling for external links?

**Comment by gerritbruening** [comment]
ad 1: agree!

ad 2: no, not yet. Maybe something similar as in the Wikipedia?

**Comment by gerritbruening** [comment]
Ad https://github.com/faustedition/faust-gen-html/issues/36#issuecomment-247299184: SH agrees to integrate Ident-Nummern into the metadata. However, they are not to be displayed publicly.

**Comment by thvitt** [comment]
Ah, ich soll das eintragen …

**Comment by gerritbruening** [comment]
Wenn das aufgrund der Excel automatisch geht.

**Comment by thvitt** [comment]
Für die folgenden Einträge habe ich keine passende Metadatendatei:

```
No file found for signature 13/33,5
No file found for signature 25/W 1362
No file found for signature 25/W 1768
No file found for signature 25/XIX,3 = 25/W 1804
No file found for signature 29/411,II
No file found for signature 30/319
No file found for signature 30/320
```

Die anderen bekämen `<idno type="gsa_ident">…</idno>`.

**Comment by gerritbruening** [comment]
```
No file found for signature 13/33,5 --> xml/document/archival/gsa/GSA_13-33-5_St_22.xml
No file found for signature 25/W 1362 --> xml/document/verschiedenes/gsa_390489.xml
No file found for signature 25/W 1768 --> xml/document/kunst_und_alterthum/gsa_390821.xml
No file found for signature 25/XIX,3 = 25/W 1804 --> xml/document/faust/2/gsa_391098.xml 
No file found for signature 29/411,II --> xml/document/archival/gsa/GSA_29-411-II_Bl_74-75.xml
No file found for signature 30/319 --> xml/document/archival/gsa/GSA_30-319_Bl_82-83.xml and xml/document/archival/gsa/GSA_30-319_Bl_85-88.xml and xml/document/archival/gsa/GSA_30-319_Bl_44-45.xml
No file found for signature 30/320
```

**Comment by thvitt** [comment]
missing Idents should be assigned in the metadata by adding
```xml
<idno type="gsa_ident">4711</idno>
```
after the `idno/@type="gsa_2"` element.

**Comment by gerritbruening** [comment]
Updated schema and added idnos.
