### ISSUE TITLE
before_10811_b

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#360]
in 391098.xml:
```xml
                        <stage n="before_10811_b" rend="inline">
                           <add f:revType="late"><g ref="#parenthesis_left"/>kauert nieder.<g
                                 ref="#parenthesis_right"/></add>
                        </stage>
```
in app2norm.xml:
```xml
  <!--FIXED: before_10811_a[$]{<stage n="before_10811_b" rend="inline">kauert nieder.</stage>} <i>vor 10811</i> <stage>kauert nieder</stage> <i>2_IV_H.8</i>] <i>erg Ec 2_H [type=2aa] [type=6]</i>-->
  <app n="before_10811_a">
    <f:ins n="before_10811_a" place="after"><stage n="before_10811_b" rend="inline">kauert nieder.</stage></f:ins>
    <ref>vor 10811</ref>
    <!--<stage>kauert nieder</stage> <i>2_IV_H.8</i>-->
    <lem wit="2_IV_H.8"><stage>kauert nieder</stage> <note><wit wit="2_IV_H.8">2_IV_H.8</wit></note></lem>
    <!-- <i>erg Ec 2_H [type=2aa] [type=6]</i>-->
    <rdg wit="2_H" type="type_6"> <note>erg Ec <wit wit="2_H">2_H</wit> [type=2aa]</note></rdg>
  </app>
```

Wenn ich das so ausführe, bekomme ich im entstehenden Lesetext die BA _kauert nieder_ doppelt.

**Comment by gerritbruening** [comment]
Habe kürzlich `ge:stage="#posthumous"` hinzugefügt. Dann sollt es rausfliegen und darf wieder eingefügt werden, oder?

                        <stage n="before_10811_b" rend="inline">
                           <add f:revType="late" ge:stage="#posthumous"><g ref="#parenthesis_left"/>kauert nieder.<g
                                 ref="#parenthesis_right"/></add>
                        </stage>

**Comment by thvitt** [comment]
Ja, sorry, ist [in der dev](http://dev.faustedition.net/print/faust.39#lbefore_10811_b) schon korrekt – ich hatte wohl etwas veraltete XML-Daten lokal.
