### ISSUE TITLE
Trüber Tag / Feld

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#362]
@dietmarpravida, in Göttingen war noch die Frage aufgekommen, ob die TTF-Überschrift in einer oder in zwei Zeilen stehen soll. Ich dachte, in zweien. Richtig?
Wenn doch in einer, würde ich hierfür eine Individualregel schreiben.

**Comment by dietmarpravida** [comment]
Zwei Zeilen ist einfacher, sonst könnte man sich noch veranlasst sehen, in Analogie zu "Nacht, offen Feld" ein Komma setzen zu wollen, außerdem sieht "Trüber Tag. Feld" ohne Punkt nach "Feld" komisch aus, so  aber brauchen wir gar keinen Punkt, auch nicht nach "Tag" (also ganz wie in AA). Die Frege stellt sich dann allerdings beim Kolumnentitel: hier muss dann der Punkt hin?

**Comment by gerritbruening** [comment]
>  so aber brauchen wir gar keinen Punkt, auch nicht nach "Tag" (also ganz wie in AA)

Ja, siehe #401.

> Kolumnentitel: hier muss dann der Punkt hin?

Ja, deswegen

                        <div f:label="Trüber Tag. Feld" type="scene" n="1.1.23">
