### ISSUE TITLE
Siglen in Apparat zu nach 3409

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#364]
B.a und C.1_12 werden nicht als Siglen erkannt. Vielleicht, weil Interpunktionszeichen folgen?

**Comment by thvitt** [comment]
Ja. Der Code zerlegt an Leerraum in Tokens und prüft jedes Token, ob es Sigle etc. ist.

**Comment by gerritbruening** [comment]
Könntest du @dietmarpravida sagen, wie das gehandhabt werden soll?
(falls da nicht auch das direkte XML her muss)

**Comment by thvitt** [comment]
Wenn auf eine Sigle ein Punkt folgt, bitte vor dem Punkt ein ZERO WIDTH SPACE oder ZERO WIDTH NON-JOINER einfügen (Kopiervorlage: »​«). Kommas, Semikolon etc. sind unproblematisch (d.h. nur die letzte Sigle wird hier jetzt noch nicht erkannt)

**Comment by dietmarpravida** [comment]
@thvitt Es müsste auch mit `&#x200b;'` funktionieren, oder?

**Comment by thvitt** [comment]
ja

```
U+200B ZERO WIDTH SPACE
UTF-8: e2 80 8b UTF-16BE: 200b Decimal: &#8203; Octal: \020013

Category: Cf (Other, Format)
Unicode block: 2000..206F; General Punctuation
Bidi: BN (Boundary Neutral)
```

**Comment by gerritbruening** [comment]
Sieht komisch aus,

`INFO:parse_app2norm: Parsed: 3409[]{} <i>nach 3409</i> <i>Die Strophengrenze nach Vers 3409 wird in 1_H.5 durch eine Leerzeile markiert, keine Leerzeile findet sich in S A B B.a</i>] <HTML-Code>&#x200b;</HTML-Code><i>; Leerzeile in 1_H.1 vorschl. Gö bill. G; Leerzeile in C.1_12 C.3_12</i><HTML-Code>&#x200b;</HTML-Code><i>. [type=2b]</i>`

kann aber geparst werden.

**Comment by thvitt** [comment]
hu? Nein, das ist so nicht ok:

1. Das `<HTML-Code>` und `</HTML-Code>` hat da nichts zu suchen, das käme so ins TEI!
2. Die Kursivierung ist da unterbrochen → wird als neues Reading geparst

Der Apparat sieht nach dem Übersetzen in XML dann so aus:

```xml
  <app>
    <f:ins n="3409" place="only-app"/>
    <ref>nach 3409</ref>
    <!--<i>Die Strophengrenze nach Vers 3409 wird in 1_H.5 durch eine Leerzeile markiert, keine Leerzeile findet sich in S A B B.a</i>-->
    <lem wit="1_H.5 S A B B.a"> <note>Die Strophengrenze nach Vers 3409 wird in <wit>1_H.5</wit> durch eine Leerzeile markiert, keine Leerzeile findet sich in <wit>S</wit> <wit>A</wit> <wit>B</wit> <wit>B.a</wit></note></lem>
    <!-- <HTML-Code>&#x200b;</HTML-Code><i>; Leerzeile in 1_H.1 vorschl. Gö bill. G; Leerzeile in C.1_12 C.3_12</i>-->
    <rdg wit="1_H.1 C.1_12 C.3_12" hand="Gö G"><HTML-Code>​</HTML-Code> <note>; Leerzeile in <wit>1_H.1</wit> vorschl. <seg type="hand">Gö</seg> bill. <seg type="hand">G</seg>; Leerzeile in <wit>C.1_12</wit> <wit>C.3_12</wit></note></rdg>
    <!--<HTML-Code>&#x200b;</HTML-Code><i>. [type=2b]</i>-->
    <rdg type="type_2b"><HTML-Code>​</HTML-Code> <note>.</note></rdg>
  </app>
```

**Comment by gerritbruening** [comment]
OK, wenn ich das direkt in XML kodieren solle, bitte mich assignen.

**Comment by gerritbruening** [comment]
@dietmarpravida, kannst du es nochmal mit dem Unicode-Zeichen probieren?:
`​`
Das verbatim html bereitet mir Probleme.

**Comment by dietmarpravida** [comment]
ich meinte eigentlich, es mit unicode und ohne html gemacht zu haben, kucke aber nochmal nach

**Comment by gerritbruening** [comment]
![grafik](https://user-images.githubusercontent.com/10358005/38750833-797f5d84-3f56-11e8-89e6-618b285ac285.png)

Sieht so aus, als sei die Kursivierung wirklich unterbrochen und nicht das import-Makro oder mein Skript würde das erst tun.

**Comment by thvitt** [comment]
Ich tippe auf ein Zeichenformat "HTML-Code". Wenn Du einfach in der normalen kursiven schrift &#x200b; hineingeschrieben hättest, hätt’s wohl funktioniert

**Comment by dietmarpravida** [comment]
hat sich durch Wegfall der Interpunktionszeichen wohl erledigt
