### ISSUE TITLE
Nachteiliges spacing in Apparateinträgen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#365]
before_5357_b:

![grafik](https://user-images.githubusercontent.com/10358005/37801629-94611268-2e27-11e8-9234-0662a7d09e78.png)

Is the space after _erg. G_ intended?

**Comment by gerritbruening** [comment]
Ach so, nach jeder Lesart folgt wohl extra Spacing.
Betrifft auch die letzte Angabe in

![grafik](https://user-images.githubusercontent.com/10358005/37802190-b03b16a8-2e29-11e8-9066-f901dda22bf0.png)

Betrifft auch 3550--3551 nach "Vers:"

**Comment by thvitt** [comment]
Dass nach jeder Lesart ein größerer Abstand kommt, war doch explizit Dein Wunsch. Im Text haben wir da mittlerweile einen Umbruch, aber das wäre in der Listendarstellung zu unübersichtlich.

Der Parser hat den Eintrag _vor 5357_ anhand der Kursiv/Aufrecht-Wechsel so zerlegt, wie [in der app2norm.xml zu sehen ist](http://dev.digital-humanities.de/ci/job/faust-gen-fast/). 

```xml
  <!--FIXED: before_5357_b[]{} <i>vor 5357</i> <speaker>Alecto</speaker> <i>2_I_H.0a</i>] ⟨<stage>Die Furien</stage> <i>erg G</i>⟩ <speaker>Alecto.</speaker> <i>2_H [type=2c*]</i>-->
  <app n="before_5357_b">
    <f:ins n="before_5357_b" place="only-app"/>
    <ref>vor 5357</ref>
    <!--<speaker>Alecto</speaker> <i>2_I_H.0a</i>-->
    <lem wit="2_I_H.0a"><speaker>Alecto</speaker> <note><wit wit="2_I_H.0a">2_I_H.0a</wit></note></lem>
    <!-- ⟨<stage>Die Furien</stage> <i>erg G</i>-->
    <rdg hand="G">⟨<stage>Die Furien</stage> <note>erg <seg type="hand">G</seg></note></rdg>
    <!--⟩ <speaker>Alecto.</speaker> <i>2_H [type=2c*]</i>-->
    <rdg wit="2_H" type="type_2c*">⟩ <speaker>Alecto.</speaker> <note><wit wit="2_H">2_H</wit></note></rdg>
  </app>
```

Das Problem ist also im Apparat.

**Comment by gerritbruening** [comment]
OK, was uns hier auf die Füße fällt, ist der Einblendungsapparat: Variante innerhalb einer Variante.
Entweder wir untersagen das, oder ich muss im Vorwege so etwas wie `<add>` reinbauen, oder ich muss etwas ummantelndes bauen.

**Comment by thvitt** [comment]
Oder ihr müsst endlich das Word kicken und mit app?norm.xml arbeiten.

**Comment by gerritbruening** [comment]
Das wäre für solche Fälle bestimmt das beste.
Wäre es möglich, für einzelne Apparateinträge einen sicheren XML-Hafen einzurichten, der nicht wie jetzt überschrieben wird?
Dann könnte man die von der jetzigen Routine abkoppeln und da sauberes XML schreiben. Die Routine ganz loswerden geht vermutlich erst in der ersten Aprilhälfte.

**Comment by thvitt** [comment]
ja, committe analog zu der Testdatei eine saubere Datei mit nur diesen Einträgen (die muss nur an zwei Stellen (text-insert-app.xsl und text-app-validation.xsl) aufgelistet werden), und entferne die entsprecheden Einträge aus der app2norm.txt oder mache sie unparsbar (z.B. durch präfigieren der Zeile mit irgendeinem Zeichen wie ✘).

Ein [kommentiertes Relax-NG-Schema zu den app*norm.xml-Dateien liegt im Git](‌https://github.com/faustedition/faust-gen-html/blob/master/text/appxnorm.rnc)

**Comment by thvitt** [comment]
Neben app[12]norm.txt, also in faust-gen-html/text

app[12]norm.xml ist nicht im Git, solange es automatisch generiert wird. Die Dateien können [auf der Seite des letzten erfolgreichen Builds oben unter Build-Artefakte](http://dev.digital-humanities.de/ci/view/Faust/job/faust-gen-fast/lastSuccessfulBuild/) eingesehen / heruntergeladen werden. (Die Kommentare mit dem Ausschnitt aus app[12]norm.txt stehen da natürlich nur zum Debugging drin und ich kann die auch rausnehmen, wenn sie stören)

**Comment by gerritbruening** [comment]
OK, danke.
Habe jetzt
`<?xml-model href="https://github.com/faustedition/faust-gen-html/blob/master/text/appxnorm.rnc" type="application/relax-ng-compact-syntax"?>`
eingefügt.
Das ist wohl nicht ganz richtig?

**Comment by gerritbruening** [comment]
Ich push sie erstmal kurz.

**Comment by gerritbruening** [comment]
> Die Kommentare mit dem Ausschnitt aus app[12]norm.txt stehen da natürlich nur zum Debugging drin und ich kann die auch rausnehmen, wenn sie stören

Bitte gern so lassen, die sind hilfreich!

> ausgecheckt

ach so, dann gehts, danke!

**Comment by gerritbruening** [comment]
Habe jetzt mal einen Apparat kodiert:
https://github.com/faustedition/faust-gen-html/blob/bb1826d556f46632c26f8eec636cb248a4ff5a6c/text/app2norm_special-cases.xml#L24
Valide ist er schon mal.

**Comment by gerritbruening** [comment]
Habe die entsprechende Zeile in app2norm.txt jetzt unterdrückt.
Kann ich so dann weiterwursteln?

**Comment by thvitt** [comment]
Ja, sieht m.E. gut aus (und nicht von https://github.com/faustedition/faust-web/issues/379 irritieren lassen …)

**Comment by gerritbruening** [comment]
Ich habe die beiden hier diskutierten Fälle jetzt in `special-cases` behandelt.
Einziger Punkt: Ich habe für Verweise auf Faust-Text, der keine gleichrangige Lesart bildet, `quote` verwendet:
https://github.com/faustedition/faust-gen-html/blob/6941eb99ef99890ffa239f9ee918911638e6c0ad/text/app12norm_special-cases.xml#L50
https://github.com/faustedition/faust-gen-html/blob/6941eb99ef99890ffa239f9ee918911638e6c0ad/text/app12norm_special-cases.xml#L87

Mit dem Hintergedanken, dass dieser Text wie der von Lesarten aufrecht, nicht kursiv, erscheint, aber eben anders als diese kein extra spacing erhält.
@thvitt, ist das so in Ordnung?

**Comment by thvitt** [comment]
Erfordert noch CSS-Anpassung
