### ISSUE TITLE
Siglenwiederholung bei _:_

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#366]
Hier gibt es zwei Punkte.

Einmal ganz konkret:

![grafik](https://user-images.githubusercontent.com/10358005/37801772-213b3ea2-2e28-11e8-8c21-0b12816006e6.png)

Die letzte Lesart steht nicht in H.3a, sondern nur in H. Da scheint der Doppelpunkt zu weitgehend interpretiert worden zu sein.

Und allgemein: Der Doppelpunkt wird ja gedropped zugunsten der Wiederholung der Siglen. Für den Druck wäre es aber gut, ihn noch zu haben und dafür dann auf die eingefügte Siglenwiederholung zu verzichten.

**Comment by thvitt** [comment]
```xml
 <!--       9076[In tiefem]{=} <i>9076</i> In tiefem <i>C.1_4</i>] Im tiefen <i>2_III_H.2:1</i> In tiefen <i>2_III_H.3a:1 2_H :</i> In tiefem <i>G [type=2d]</i>-->
  <app n="9076">
    <f:replace n="9076">In tiefem</f:replace>
    <f:ins n="9076">In tiefem</f:ins>
    <ref>9076</ref>
    <!--In tiefem <i>C.1_4</i>-->
    <lem wit="C.1_4">In tiefem <note><wit wit="C.1_4">C.1_4</wit></note></lem>
    <!-- Im tiefen <i>2_III_H.2:1</i>-->
    <rdg wit="2_III_H.2:1">Im tiefen <note><wit wit="2_III_H.2:1">2_III_H.2:1</wit></note></rdg>
    <!-- In tiefen <i>2_III_H.3a:1 2_H :</i>-->
    <rdg wit="2_III_H.3a:1 2_H">In tiefen <note><wit wit="2_III_H.3a:1">2_III_H.3a:1</wit> <wit wit="2_H">2_H</wit></note></rdg>
    <!-- In tiefem <i>G [type=2d]</i>-->
    <rdg wit="2_III_H.3a:1 2_H" hand="G" type="type_2d">In tiefem <note><seg type="hand">G</seg></note></rdg>
  </app>
```

Was genau bedeutet der Doppelpunkt? Finde den völlig verwirrend in diesem Apparat

**Comment by gerritbruening** [comment]
Am Anfang und im Hintergrund steht dieses hier:
![grafik](https://user-images.githubusercontent.com/10358005/37821044-cf13749a-2e82-11e8-9cbf-f9ab65c663ee.png)
Das bedeutet, der _:_  steht für "abc _wird ersetzt durch_ def", so wie sonst auch in den Apparaten. Nur hier halt in Kombination mit Angaben zu verschiedenen Handschriften. Der Doppelpunkt sagt: Was jetzt kommt, ist eine geänderte Lesart in derselben Handschrift, die zuletzt genannt wurde. Damit man nicht denkt, jetzt käme eine Lesart aus einem anderen Zeugen.

**Comment by gerritbruening** [comment]
> stehen lassen – kann mir nicht vorstellen, wie das im TEI aussehen soll? 

Gilt da nicht dasselbe wie beiden angle brackets:
https://github.com/faustedition/faust-gen-html/blob/d41a1c38743a720d315111579969f6432e1b21e2/text/app2norm_special-cases.xml#L24
Auch die sind eigentlich ein Fremdkörper im TEI.

**Comment by gerritbruening** [comment]
Was man probieren könnte wäre folgendes:
https://github.com/faustedition/faust-gen-html/blob/66bf819e079fa0bc563b4470578c065a93ecbc9d/text/app2norm_special-cases.xml#L48
Kein Doppelpunkt, stattdessen `subst` (das bedeutet er ja).
Für das Rendering (und den Druck) würden wir das Zeichen wieder gebrauchen können. Ich weiß aber nicht, ob es nötig ist, das drin zu behalten. Vielleicht reicht die `subst` info wie im inline-Apparat auch?

**Comment by thvitt** [comment]
hm, ich bin nicht so sicher, ob wir wirklich hier den ganzen Inlineapparat im Apparat auffahren wollen (technisch ist das z.Z. ein eigener Pfad, ließe sich aber wohl mit mittlerem Aufwand umbauen). Codierung ist hier allerdings anders als sonst? (f:proposedBy etc)

Könnte man hier einfach so codieren (bzw. das Pythonskript codieren lassen), ggf. mit einem durch das : getriggerten `type="subst"` an dem `rdg` oder so?

```xml
<lem wit="2_H"><speaker>Marschalck</speaker></lem>
<rdg wit="2_H"><speaker>Schatzmeister</speaker> <note><wit>2_H</wit></note></rdg>
<rdg wit="2_H" hand="G"><note>: </note><speaker>Marschalck</speaker> <note>(<quote>Schatzmeister</quote> ungestrichen) <seg type="hand">G</hand></note></rdg>
```

(wobei ich das mit dem _ungestrichen_ nicht verstehe – heißt das etwas anderes als _die streichung aufgehoben_? Wieso habt Ihr dann _Marschalck_ ausgewählt?)

**Comment by gerritbruening** [comment]
Ja, wir können gern bei zwei `rdg` bleiben.
Bei `<note>: </note>` hätte ich spontan gesagt, `: ` könnte eher in das vorhergehende `<note><wit>2_H</wit></note>` noch mit rein.

> (wobei ich das mit dem _ungestrichen_ nicht verstehe – heißt das etwas anderes als _die streichung aufgehoben_? Wieso habt Ihr dann _Marschalck_ ausgewählt?)

Ja, man hätte auch umgekehrt entscheiden können, das widerspräche aber dem Usus:

> Enthält die Handschrift Korrekturvorschläge Goethes, die von ihm nicht verworfen wurden, werden sie in den Edierten Text aufgenommen. (Grundlagen der Goethe-Ausgabe)

Etwas anderes wäre eine aufgehobene Streichung: Da wird erst gestrichen und dann wieder zurückgeändert.

**Comment by thvitt** [comment]
@gerritbruening , du hattest erwähnt, dass es hier eine neue Entscheidung gibt, magst Du das noch ergänzen und dann wieder mich zuweisen zum implementieren?

**Comment by gerritbruening** [comment]
Danke für die Erinnerung!
Also, es wurde folgendes überlegt:
![grafik](https://user-images.githubusercontent.com/10358005/39956936-99bb64a8-55ea-11e8-8f60-81ba29180418.png)
Wobei wir jetzt sagen: Typenziffern alle gesammelt am Schluss, also "(IIb, VI)".
Vor "Lust" ist weniger Abstand als sonst vor Lesarten. Um diesen Effekt zu erreichen, wäre vielleicht doch die Frage, ob solche Sachen mit `rdg/subst` besser verarbeitbar ausgedrückt werden als mit `rdg`, `rdg`.
Das "in" müsste man evtl. schon in der Quelldatei einfügen, es sei denn, solchen Text verwertest du nicht.

**Comment by gerritbruening** [comment]
https://github.com/faustedition/faust-gen-html/blob/ff724e8a3ac00cdca797223164de4666c8ac8cde/text/app12norm_special-cases.xml#L120

```xml
    <app>
        <f:replace n="5265">Luft</f:replace>
        <f:ins n="5265">Lust</f:ins>
        <ref>5265</ref>
        <lem wit="2_I_H.15b">Lust <note><wit>2_I_H.15b</wit></note></lem>
        <rdg wit="2_I_H.15b">Luft <note><wit>2_I_H.15b</wit>
            </note></rdg>
        <rdg wit="2_I_H.15b" hand="G">Lust <note><seg type="hand">G</seg></note></rdg>
        <rdg wit="2_H 2_I_H.0a" type="type_2b">Luft <note><wit>2_H</wit>
                <wit>2_I_H.0a</wit></note></rdg>
        <rdg wit="2_I_H.0a 2_H" type="type_6">Lust <note>Sc <wit>2_H</wit></note></rdg>
    </app>
```

Hatte schon einen ziemlichen Schreck bekommen.

**Comment by thvitt** [comment]
ah, ich hatte natürlich nur in den Textdaten geschaut weil da ja der _:_ steht. Ich bin jetzt aber hinreichend verworren. Wieso ist das manuell codiert? Wie sähe die Textcodierung aus und wieso? Sollen die Fälle alle manuell codiert werden? Soll das _:_ aus der Textdatei so oder anders in faust.xml umgesetzt werden?


Wir können das vermutlich schon rein im text-insert-app.xsl auflösen nach der folgenden Regel:

> Wenn auf ein `<rdg>`¹ ein weiteres `<rdg>`² folgt und beide rdg denselben Wert³ für `@wit` haben, dann ist in `<rdg>`¹ das `<wit>` mit Wert³ durch `<pc type="subst">:</subst>` zu ersetzen. 

ach nee, weil ja die zweite Sigle fehlt. Das ist echt verwirrend, v.a. in der Ausgangscodierung.

**Comment by gerritbruening** [comment]
> Wieso ist das manuell codiert?

Schien mir im Zweifel sicherer.
> Wie sähe die Textcodierung aus und wieso?

Vielleicht doch so ähnlich wie https://github.com/faustedition/faust-gen-html/issues/366#issuecomment-375807962 vorgeschlagen? Nur mit der Sigle am Schluss statt nach dem `del`?

> Sollen die Fälle alle manuell codiert werden? ...

Wenn die Textdatei zu opak ist, wäre es wahrscheinlich einfacher, als die zurechtzubiegen und Processing-Verrenkungen zu betreiben.
Der _:_ würde dann aber durch Processing entstehen, so wie beim Inline-Apparat auch. Wäre das nicht sauberer und nervenschonender? Ja, ist sehr verwirrend.

**Comment by thvitt** [comment]
Nagut, ich baue das Pythonscript um, sodass im Apparat für beide Fälle nur ein Reading mit `<subst><del/><add/></subst>`. Effektiv wird die Codierung so aussehen, dass das, was im ersten rdg steht, ins del kommt, und der inhalt des zweiten rdg ins add. Da in subst neben breaks nur add und del stehen dürfen, kommen da also keine notes rein! Schaff ich aber erst am Abend.

Effektiv heißt das, das @pglatza fürs IDML und ich fürs HTML jeweils zwischen die Kinder des subst im rdg ein _:_ mit entsprechendem Spacing setzen müssen (normales Leerzeichen?)

**Comment by pglatza** [comment]
Ok, habe das auf dem Schirm.

**Comment by gerritbruening** [comment]
> jeweils zwischen die Kinder des subst im rdg ein _:_ mit entsprechendem Spacing setzen müssen (normales Leerzeichen?)

Ja genau!

**Comment by thvitt** [comment]
So, @gerritbruening, jetzt guck mal ob das so deinen Wünschen entspricht.

**Comment by gerritbruening** [comment]
Das ist ja luxuriös, danke!
Ich nehme an, dass es einen guten Grund gibt, frage aber trotzdem:

    <rdg wit="2_II_H.74">
      <subst>
        <del>kreisenden <note> </note></del>
        <add wit="2_II_H.74" hand="G">Kreisenden <note><seg type="hand">G</seg> <wit>2_II_H.74</wit></note></add>
      </subst>
    </rdg>

`wit="2_II_H.74" hand="G"` ans `subst`?
`<note><seg type="hand">G</seg> <wit>2_II_H.74</wit></note>` hinter das `subst`?
