### ISSUE TITLE
Doppelte Typenzuweisung

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#367]
z.B. in http://dev.faustedition.net/print/faust.39#app.before_10811_a.kauertnieder
wo im txt am Ende `[type=2aa] [type=6]</i>` steht.

Das ist wohl nicht so ohne weiteres umsetzbar?

Siehe auch https://github.com/faustedition/xml/issues/288.

**Comment by thvitt** [comment]
Das müsste wohl schon implementierbar sein; codierung wäre dann `<rdg type="type_2aa type_6">`

**Comment by gerritbruening** [comment]
Gut, soll ich das dann auch in `special-cases` behandeln? Dann müsstest du das komische `[type=2aa] [type=6]</i>` nicht parsen.

**Comment by thvitt** [comment]
au ja
codierung als `<rdg type="type_2aa type_6">…</rdg>`

**Comment by gerritbruening** [comment]
OK, habe ich.
