### ISSUE TITLE
4a bei Abweichungen zwischen B und B.a

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#368]
Betrifft folgende Stellen:
* 859 (B und B.a teilweise übereinstimmend)
* 1187 (nicht übereinstimmend)
* 1574 (teilweise)
* 3134 (teilweise)
* 3908 (teilweise)
* 4278 (teilweise)
* 4503 (teilweise)
* 4608 (teilweise)

Hier ist mir nicht klar, ob sie unter 4a gelistet werden können. Ich verzeichne Abweichungen von C.1 4 in unterschiedliche Richtungen bis jetzt nicht.

**Comment by dietmarpravida** [comment]
1574 "Lorber(')n" ist zumindest teilweise übereinstimmend.

Beim Rest würde ich doch sagen, dass sie beide von A abweichen, wenn sie auch nicht ganz genau übereinstimmen. Ich hatte gezögert, hier viel Aufhebens zu machen, aber es handelt sich etwa bei "schnobern schnopern schnoppern" natürlich gerade um die interessanten Fälle halb-konvergenter Änderungen.

**Comment by gerritbruening** [comment]
Wenn die Fälle irgendwie von "konvergent" noch abgedeckt sind, habe ich kein Problem.
Ich würde mich im dritten Akt aber weiter auf die Übereinstimmungen im engen Sinn beschränken, welchen Unterschied hoffentlich niemand bemerken wird.

**Comment by dietmarpravida** [comment]
scheint mir geklärt
