### ISSUE TITLE
Smooth output for watermarkId etc

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#37]
@thvitt, please supply me with a table which has as its first column:
* distinct values of watermarkId,
* distinct values of patchWatermarkId
* d. v. of countermarkId
* d. v. of patchCountermarkId
It would be nice to have the occurances of each distinct value in the second column.

In the third column I would fill in what should appear in the metadata rendering.

**Comment by thvitt** [comment]
[Here you are](https://github.com/faustedition/faust-gen-html/files/103520/watermark-summary.xlsx). Add a new column for the label as you please, but don't edit _Watermark_ column.

**Comment by gerritbruening** [comment]
Great! Thanks a lot.

**Comment by gerritbruening** [comment]
Done!
[watermark-summary.xlsx](https://github.com/faustedition/faust-gen-html/files/186104/watermark-summary.xlsx)

**Comment by gerritbruening** [comment]
Great, thanks!
