### ISSUE TITLE
Komische lem/note

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#375]
Sogar `lem` gefolgt von `lem` kommt vor.

**Comment by thvitt** [comment]
macht lem gefolgt von lem irgendeinen Sinn? Im Schema hab ich's verboten, in app2norm.xml kommt's trotzdem einmal vor, :bug: in app2xml.py vllt

**Comment by gerritbruening** [comment]
> macht lem gefolgt von lem irgendeinen Sinn?

Nein, natürlich nicht. Eine unsichtbare Word-Formatierung war schuld. Ist jetzt weg.

**Comment by gerritbruening** [comment]
Was ich meinte, war `lem`, wo nur eine `note` drinsteht:

                                         <lem
                                            wit="faust://document/faustedition/1_H.5 faust://document/faustedition/S faust://document/faustedition/A">
                                            <note>Die Vershälften bilden in <wit
                                                  wit="faust://document/faustedition/1_H.5">H<hi
                                                  rend="superscript">5</hi></wit> und <wit
                                                  wit="faust://document/faustedition/S">S</wit>
                                                einen antilabischen Vers, in <wit f:is-base="true"
                                                  wit="faust://document/faustedition/A"
                                                >A</wit></note></lem>

Diese Fall ist ja erledigt (#372).
Kannst du mal abfragen, wo außer whitespace nur `note` in `lem` vorkommt? Ich habe gerade nicht im Kopf, wie das mit `not(normalize-space)` oder so ähnlich war.

**Comment by thvitt** [comment]
//lem[note and normalize-space(string-join(text(), '')) = '']/../../ref

* vor 2392
* vor 2429
* vor 2450
* 3550–3551
