### ISSUE TITLE
B.a not recognized as idno sometimes

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#377]
Gründe
- [x] fehlendes Leerzeichen (https://github.com/faustedition/xml/issues/297)
- [x] Interpunktion danach
- [x] `<lem>&lt;i&gt;In 1_H.5 S A B B.a handelt es sich` (und ähnliche Fälle)

**Comment by thvitt** [comment]
https://github.com/faustedition/faust-gen-html/commit/79db3aa8aef3bdcbf8c2a4a94574e50c5038ecc5 sollte die interpunktionsbedingten Fälle lösen, der Rest ist dann wohl Handarbeit

**Comment by gerritbruening** [comment]
https://github.com/faustedition/faust-gen-html/issues/374#issuecomment-376458714

**Comment by gerritbruening** [comment]
Vermute, dass mein Skript hier was nicht richtig macht.

**Comment by gerritbruening** [comment]
Letzter task gefixt zusammen mit https://github.com/faustedition/xml/issues/307.
