### ISSUE TITLE
Spacing before rdg when there is no lem

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#378]
Cases
* 2709
* 3356ff.
* nach 3409
* maybe some others

Would it be helpful to introduce empty `lem` elements as I have seen elsewhere in the apparatus entries generated by the Python script?

**Comment by thvitt** [comment]
at least 2709 _has_ an empty lem, the schema prescribes it IIRC.

**Comment by thvitt** [comment]
in the web, the extra linebreak is caused by a `rdg::before` rule.

**Comment by gerritbruening** [comment]
Yes, now I remember that I added the lem because schema told me to.
