### ISSUE TITLE
app//speaker & app//stage

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#379]
Encoding might be sloppy and inconsistent.
Check if `inline` is needed.
Necessary for #359.

**Comment by gerritbruening** [comment]
@dietmarpravida, nach https://github.com/faustedition/faust-gen-html/commit/56187c1c6df8d273ff8c6858436a1dd2d1364b2f sieht es für mich so aus, als sollte BA-Text in Apparaten immer als solcher gekennzeichnet sein, auch wenn der Apparateintrag nur BA-Text und nichts anderes enthält, eine typographische Differenzierung also nicht erforderlich ist. Wollen wir das so?
Wir würden doch z.B. Überschriftstext im Apparateintrag nicht anders erscheinen lassen.

**Comment by dietmarpravida** [comment]
ja, ich dachte mir auch schon, dass das jetzt keine gute Idee war. Ich setze es morgen wieder zurück.

**Comment by gerritbruening** [comment]
Für Faust II muss ich nochmal drauf achten.

**Comment by gerritbruening** [comment]
Faust II geklärt, Faust I wäre für die 1.0 nochmals anzusehen.

**Comment by gerritbruening** [comment]
Habe mal geschaut, sieht für mich alles OK aus.
