### ISSUE TITLE
redundant id 'l3184'

### ISSUE THREAD

**Issue by pglatza** [faustedition/faust-gen-html#380]
There are two xml:id-attributes with the value "l3184" in the current state of 'lesetext'-xml.

Is there are specific reason (the xml can't get valid).

**Comment by gerritbruening** [comment]
<l xml:id="l3184" n="3184">Er liebt mich!<note type="textcrit" xml:id="app.3184.only-app"><ref>3184</ref><app from="#l3184"><lem>&lt;i&gt;In 1_H.5 S A B B.a handelt es sich um zwei Verse, sie wurden erst von Düntzer und dann in WA zu einem antilabischen Vers zusammengefasst. [type=3*</lem></app></note></l>
                            </sp>
                            <sp>
                                <speaker n="before_3184f">Faust</speaker>
                                <l xml:id="l3184" n="3184">Ja, mein Kind! Laß dieses Blumenwort</l>

These `xml:id`s are added with the apparatus entry, aren't they, @thvitt?

**Comment by thvitt** [comment]
It is. It is yet another special case: the apparatus entry refers to `<f:ins place="only-app" n="3184"/>`, but there are _two_ verses 3184. The cleanup phase removes the second `<note>`, but it doesn't touch the xml-id.

I think we'll have to use auto-generated IDs here and iterate over matching `@n`s to generate the app’s `from` attribute …
