### ISSUE TITLE
app on space[@n='after_6358']

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#382]
Link is
http://dev.faustedition.net/print/faust.30#app.after_6358.only-app
which brings me to the beginning of "Kaiserliche Pfalz" scene.
Second, app entry is not inserted.

app-validation says `WARNING:parse_readings: Failed to parse »« as lem`
What does that mean?

**Comment by thvitt** [comment]
the underlying problem is that `<space n="…" unit="lines">` should be trreated like a line that has variants etc. but it isn’t

**Comment by gerritbruening** [comment]
Thanks!
space element must not have children, though.

**Comment by gerritbruening** [comment]
I have noticed that the rendered apparatus entry drops down so that it appears on roughly the same level as before_6360_a. I think this is not intended, is it?

**Comment by thvitt** [comment]
it’s a logical consequence of the fact that the space is rendered using a bunch of `<br/>` elements and the textcrit note is inserted behind it. oh my, how do we fix this in a sensible way? Probably swap the stuff in print2html.xsl

**Comment by thvitt** [comment]
is there a problem in faust.xml? the display issue is HTML only, so I don’t understand the msfaustii milestone

**Comment by gerritbruening** [comment]
You are right. I have no idea why I added this to the msfaustii milestone.
