### ISSUE TITLE
Fehlende WNT-Formate

### ISSUE THREAD

**Issue by pglatza** [faustedition/faust-gen-html#387]
Im aktuellen Stand der [idml.md](https://github.com/faustedition/faust-gen-html/blob/e1224942d8b9c2ce79e6642ee46c9b5017beff13/idml/idml.md) wurde für die WNT-Überschrift folgendes definiert:

> (WNT-Titel)
> 
> XML: head[@n="before_4223_a"]/hi[1].
> Zwischenzeile (WNT)
> 
> (für das "oder")
> 
> XML: head[@n="before_4223_a"]/hi[2][text()[contains(.,'oder')]].
> Szene nach Zwischenzeile (WNT)
> 
> für "Oberons ..."

Hierfür fehlen noch die Formate in der InDesign-Templatedatei. Für WNT-Titel weise ich aktuell "Teil (WNT)" zu.
Siehe auch #328

**Comment by markusciupke** [comment]
Was meine InDesign-Dateien betrifft, so ist ja die Datei Faust KT 18.03.14 leer.indd, die ich am 15. März um 0:06 Uhr gesandt habe, die aktuelle mit den aktuellen Zeichen- und Absatz-Formaten.
Dort findet sich für die Zeile »Walpurgisnachtstraum« das einmalige Absatzformat »Teil (WNT)«
Für »oder« das einmalige Format »Unterszene nach Szene«
Für »Oberons und Titanias goldne Hochzeit« das einmalige Format »Szene (OuTgH)«
Für »Intermezzo« das allgemeine Format »Szene«
Das alles sind meine Vorschläge zur typographischen Gestaltung. Diese müssen von @gerritbruening und @dietmarpravida noch abgesegnet werden.

**Comment by pglatza** [comment]
@markusciupke, erhalten die `hi`-XML-Elemente noch extra Zeichenformat-Zuweisungen? Konnte dazu nichts in der Datei 'Faust KT 18.03.14 leer.indd' finden – sie ist nicht nur vom Namen, sondern auch inhaltlich leer.

**Comment by markusciupke** [comment]
Was sind  hi-XML-Elemente? Ich kann dazu nichts sagen. @gerritbruening: Brauchen wir weitere Zeichenformate? Wenn ja, welche?
Die Datei hat absichtlich nur leere Rahmen, damit die konvertierte XML-Datei da hineinimportiert werden kann. Und der Inhalt, also die XML-Datei, kommt doch von @gerritbruening.

**Comment by markusciupke** [comment]
> Es reicht, wenn der Textinhalt rüber kommt, alles weitere dann im Satz.

Ausgerechnet der Textinhalt dieser paar Zeilen ist nicht rüber gekommen! Ich habe ihn jetzt  abgetippt. Das muss von euch geprüft werden.

**Comment by gerritbruening** [comment]
Nicht rübergekommen?
So sieht das IDML aus:

```xml
      <ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/Teil (WNT)">
         <head AppliedParagraphStyle="ParagraphStyle/Teil (WNT)">
            <hi>
               <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
                  <Content>Walpurgisnachtstraum</Content>
               </CharacterStyleRange>
            </hi>
         </head>
         <Br/>
      </ParagraphStyleRange>
      <ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/Unterszene nach Szene">
         <head AppliedParagraphStyle="ParagraphStyle/Unterszene nach Szene">
            <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
               <Content>oder</Content>
            </CharacterStyleRange>
         </head>
         <Br/>
      </ParagraphStyleRange>
      <ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/Szene (OuTgH)">
         <head AppliedParagraphStyle="ParagraphStyle/Szene (OuTgH)">
            <hi>
               <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
                  <Content>Oberons</Content>
               </CharacterStyleRange>
            </hi>
            <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
               <Content> und </Content>
            </CharacterStyleRange>
            <hi>
               <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
                  <Content>Titanias goldne Hochzeit</Content>
               </CharacterStyleRange>
            </hi>
         </head>
         <Br/>
      </ParagraphStyleRange>
      <ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/Szene">
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Content>&#x2028;</Content>
         </CharacterStyleRange>
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Content>&#x2028;</Content>
         </CharacterStyleRange>
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Content>&#x2028;</Content>
         </CharacterStyleRange>
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Content>Intermezzo</Content>
         </CharacterStyleRange>
         <Br/>
      </ParagraphStyleRange>
```

Der Textinhalt ist jedenfalls da.
Wenn der nicht erscheint, kann der Text von hier kopiert werden:
http://dev.faustedition.net/print/faust.25#lbefore_4223_a

**Comment by markusciupke** [comment]
Der Text ist da. Nur die Überschrift von Walpurgisnachtsraum bis Hochzeit fehlt. Das ist also nicht schlimm, aber ich wollte euch natürlich darauf hinweisen. Das müsst ihr ja wissen.

**Comment by gerritbruening** [comment]
> Nur die Überschrift von Walpurgisnachtsraum bis Hochzeit fehlt.

Die ist doch da, siehe obigen Snippet?

**Comment by gerritbruening** [comment]
Ich assigne doch @pglatza vorsichtshalber, weil er vielleicht erraten könnte, was die Ursache ist.

**Comment by markusciupke** [comment]
Ist das in der PDF-Datei von heute Nachmittag da? Die habe ich nicht hier zu Hause. Wenn ja, dann könnte es an meinem MiniMac-Rechner liegen, dass der die IDML-Datei nicht richtig aufruft. Dann darf ich nicht mehr zu Hause arbeiten.

**Comment by gerritbruening** [comment]
Da ist freier Raum:
![grafik](https://user-images.githubusercontent.com/10358005/41126677-a01b4a20-6aa8-11e8-856e-e8c3386a0ad6.png)

> Ich habe ihn jetzt abgetippt.

Abtippen würde ich wirklich nur, wenn ich absolut sicher sein will, dass es am Ende Fehler gibt.

Zweitens brauchen wir eine Analyse des Phänomens. Sonst ist unklar, wo es unbemerkterweise noch auftauchen könnte. An der Stelle darf wirklich kein Kind zurückgelassen werden.

**Comment by markusciupke** [comment]
Deswegen hab ichs ja hier mitgeteilt. Ich hab jetzt ein neues Issue für solche Sachen, die ich bemerke, aufgemacht. Zuordnen kann man die im Zweifelsfall später.
Also liegt der Fehler schon früher und nicht an meinem Rechner zu Hause? Da bin ich beruhigt!

**Comment by gerritbruening** [comment]
Es wäre wirklich beruhigender, wenn es an deinem Rechner läge ...

**Comment by markusciupke** [comment]
Ha, ha, ha. Oder wie man heute sagt: Lol!

**Comment by pglatza** [comment]
Die Ursache muss nicht erraten werden. Die kann ich sagen: das Mapping dieser drei Absätze habe ich fix hinterlegt ohne die Namensräume der XML-Elemente korrekt anzugeben. Dadurch kam es nicht zur ordentlichen späteren Auflösung zu IDML-Markup.

Ich habe die Mapping-Regeln einmal komplett durchgesehen und keine weitere solcher Stellen gefunden.

**Comment by gerritbruening** [comment]
Danke, @pglatza, jetzt glaube ich deine Antwort erst zu verstehen: Die eingeschmuggelten TEI-Elemente `head` und `hi` wie in 
```xml
      <ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/Teil (WNT)">
         <head AppliedParagraphStyle="ParagraphStyle/Teil (WNT)">
            <hi>
               <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
                  <Content>Walpurgisnachtstraum</Content>
```
waren die Ursache für die Nichtanzeige in ID, richtig?

**Comment by pglatza** [comment]
> waren die Ursache für die Nichtanzeige in ID, richtig?
Ja, das ist korrekt.
