### ISSUE TITLE
Element ab

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#388]
@pglatza, als Ergebnis von https://github.com/faustedition/faust-gen-html/issues/288#issuecomment-379799317 entsteht in `faust.xml` ein `ab/space`. Das kann eigentlich ignoriert werden. Was wichtig ist, steht in `space` und in der folgenden `note`. Falls es Probleme oder Dokumentationsbedarf gibt, sag mir bescheid.

**Comment by pglatza** [comment]
Es gibt mit aktuellen Stand der Faust-XML genau zwei `space`-Elemente. Diese wurden wie [hier](https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#leerzeile) beschrieben umgesetzt.

Gut, dann werden nun keine Leerzeilen mehr eingefügt? Sonst wäre bei `space` nichts weiter wichtiges auszuwerten?

**Comment by gerritbruening** [comment]
> Gut, dann werden nun keine Leerzeilen mehr eingefügt? Sonst wäre bei `space` nichts weiter wichtiges auszuwerten?

Doch, bitte entschuldige die mangelnde Präzision: Das `ab` kann ignoriert, nicht aber `ab/space` im Sinne von `space` (`space` bleibt relevant und ist so zu behandeln wie bisher).

**Comment by pglatza** [comment]
Ok. Habe ich so belassen bzw. wird `ab` ignoriert.
Upload-Formular ist aktualisiert.

**Comment by gerritbruening** [comment]
Danke!

**Comment by pglatza** [comment]
Habe mit der Revision 70 (gerade live geschalteten) noch einmal eine Korrektur vorgenommen. Hier sollte nun auch alles passen.
