### ISSUE TITLE
Remove dot at end of speaker/hi and head/hi

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#389]
Examples:

    <speaker n="before_2423"><hi>Kater</hi> und <hi>Kätzinn.</hi></speaker>

and

    <hi>Oberons</hi> und <hi>Titanias goldne Hochzeit.</hi></head>

**Comment by thvitt** [comment]
(see also #204 )

no additional constraints?

**Comment by gerritbruening** [comment]
No, I think that's it.
