### ISSUE TITLE
Replace some bibliographical URIs

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#39]
faust://bibliography/inventare2000 --> faust://bibliography/inventare_2_1 

faust://bibliography/inventare2011 --> faust://bibliography/inventare_2_2

**Comment by thvitt** [comment]
Who will do this when and where?

There seem to be 26 matches in faust://xml/document and 86 in overall faust://xml/ ? Should I mass-replace this in the source files?

**Comment by gerritbruening** [comment]
Yes, a mass-replacement in the source files would be ideal.
