### ISSUE TITLE
2 III H.3a:1 kein dok. Tr.

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#392]
http://dev.faustedition.net/document?sigil=2_III_H.3a:1&page=1&view=document_text

> Kein dokumentarisches Transkript verfügbar Error: Failed to load transcript/diplomatic/2_III_H.3a:1/page_1.svg, error: Not Found

**Comment by thvitt** [comment]
`:`

**Comment by gerritbruening** [comment]
Bei mir erscheint das Dokument (noch) nicht. strg-F5 habe ich gemacht. Oder folgt da noch ein Update der Seite?

**Comment by thvitt** [comment]
ja, wo hast du denn den link her? er müsste <http://dev.faustedition.net/document?sigil=2_III_H.3a_1&page=1&view=document_text>

**Comment by gerritbruening** [comment]
Ach so, jetzt verstehe ich. Der Link kam aus einem Zustand der Edition, der jetzt überwunden ist.
