### ISSUE TITLE
rendering of app before_4613_c

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#395]
@thvitt, der Eintrag
http://dev.faustedition.net/print/faust.29#app.before_4613_c.only-app
sieht sehr "bold" aus, was vmtl am `head` liegt.
Ist das perspektivisch beeinflussbar?

**Comment by thvitt** [comment]
ja, grundsätzlich sollten wir mal für die diversen `<l>`, `<head>`, `<speaker>` etc. im Apparat überlegen, wie die dargestellt werden. Lässt sich dann aber über entsprechende CSS-Regeln machen. (à la

```css
.type-textcrit .head { color: green; }
```

— wenn es knallgrün ist, fällt das Fette vielleicht weniger auf)

**Comment by gerritbruening** [comment]
Kann das sein, dass hier wieder die repos verwechselt wurden?

**Comment by gerritbruening** [comment]
Ja, sehr schön.
