### ISSUE TITLE
Zeilenumbrüche in div[@n="1.1.23"]

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#399]
Zur vorausgegangenen Diskussion siehe #268.

- [ ] aus den `milestone/@n` wie aus `l/@n` die Fünferschritte rausziehen, in diesem Fall `ttf_5` usw.
- [ ] `ttf_5` zu `5` verkürzen (oder erst dies und dann den vorherigen Schritt)
- [ ] `milestone` kann in der Folge ignoriert werden
- [ ] Bei jedem `lb` einen Zeilenumbruch einfügen

@pglatza, ich habe noch im Kopf, dass es für die Fünferschritte schon eine Lösung gab, an der @thvitt beteiligt war oder zu der er sich geäußert hat.

**Comment by gerritbruening** [comment]
Ist das hier wirklich geclosed?
`faust.xml` sieht für mich unverändert aus. Die `lb` werden konserviert, aber die Fünferschritte plus Verkürzung usw. fehlen noch.

**Comment by thvitt** [comment]
nein, der Commit schließt faustedition/faust-web#399. Danke fürs Aufpassen.

Die Fünferschritte und die Verkürzung sind eine Sache für die IDML- und Webdarstellung, in der faust.xml muss das so bleiben wie es ist.

**Comment by gerritbruening** [comment]
OK, gut.
> Die Fünferschritte und die Verkürzung sind eine Sache für die IDML- und Webdarstellung

@pglatza, da hast du schon eine Lösung für, oder?

**Comment by pglatza** [comment]
Ja, die Lösung ist da. Diese refline-Absätze müssen ganz anders behandelt werden als sie aktuell in XML kodiert werden. Aus dem Absatz mit Zeilenumbrüchen müssen eigenständige Absätze in IDML werden, damit die Zeilennummerierung korrekt dargestellt werden kann.

**Comment by gerritbruening** [comment]
Kann man hier nicht mit verankerten Textrahmen oder so arbeiten? Ich hätte sowieso gedacht, dass etwas in der Art die Standardlösung für Zeilenzählungen darstellt.

**Comment by thvitt** [comment]
ansonsten ist das so ähnlich in xslt/prose-to-lines.xsl implementiert; allerdings mit Absatzumbruch bei `milestone` statt bei `lb` (da für die Onlineversion alle Zeugen nach der Referenzzählung umbrochen werden)

**Comment by gerritbruening** [comment]
Danke für die Rückmeldung, dann überlasse ich euch das weitere Verfahren.

**Comment by markusciupke** [comment]
Hier kommt nun ein Umbruch von TTF entsprechend der in #268 geführten Diskussion: Umbruch möglichst eng an A8 bzw. der Online-Version, aber nicht sklavisch, wenn das Vorteile für Trennungen hat (mehrfach) oder für Wortabstände (einmal: Zeile 21/22). Auch nach den Trennungen von B9 habe ich mich, wo möglich, gerichtet:
[TTF.pdf](https://github.com/faustedition/faust-gen-html/files/1968954/TTF.pdf)

Technisch habe ich folgendes gemacht:
– Der Satzspiegel ist rechts und links um jeweils 2mm schmaler gemacht (113 mm statt 117 mm)
– Die Pagina ist entsprechend um 2 mm nach innen gerückt
– Hinter jede Sprechzeile habe ich einen Absatz eingefügt (harter Absatz)
– Liegt eine Trennung am Ende einer Zeile, habe ich einen Trennungsstrich (= Bindestrich) eingefügt.
– Ein neues Absatzformat mit dem Namen Prosa EB ist definiert (EB = Erzwungener Absatz)
– Ein neues Absatzformat mit dem Namen Prosa LB ist definiert (LB = Linksbündig)
– Alle Sprechzeilen einer Replik, außer der letzten, haben das Format Prosa EB erhalten
– Die letzte Sprechzeile einer Replik hat das Format Prosa LB erhalten
– Hat eine Replik nur eine Zeile ist das die letzte Sprechzeile mit dem Format Prosa LB
– Vor jeden Absatz (= Sprechzeile) habe ich zwei Tabs eingefügt (wie bei Vers auf 19mm und 23 mm)
– In jede fünfte Zeile habe ich nach dem ersten, rechtsbündigen Tab den Zeilenzähler eingefügt

Das Ergebnis seht ihr in der beigegebenen PDF-Datei.

Wenn ihr diesen Umbruch gutheißt, müssen in XML praktisch nur die Absätze, die Trennungsstriche und der Zeilenzähler vorbereitet werden. Dann müssen die richtigen Absatzformate zugewiesen werden (die beiden neuen Absatzformate ersetzen das alte Absatzformat Prosa). Ich muss dann nach der Konvertierung in IDML nur noch den Satzspiegel um 4 mm schmaler machen und die Pagina um 2mm nach innen rücken, und TTF sieht aus wie die obige PDF-Datei.

Ich bitte um Rückmeldung.

**Comment by markusciupke** [comment]
@pglatza 

> benötigen wir hier noch ein zusätzliches Absatzformat, welches analog zu Vers formatiert ist? Soll das Zeichenformat Verszahl dem Fünferschrittzähler zugewiesen werden?

Du siehst, ich habe deinen Vorschlag ziemlich genau aufgegriffen. Das ist sicher die einfachste Lösung für das Problem. Und ja, dem Fünferschrittzähler soll auch das Zeichenformat Verszahl zugewiesen werden.

**Comment by pglatza** [comment]
Von meiner Seite aus lesen sich die technischen Anpassungen (https://github.com/faustedition/faust-gen-html/issues/399#issuecomment-386125284) als genau passend.

**Comment by pglatza** [comment]
Ist soweit umgesetzt. Vor Aktualisierung des Upload-Formulars bräuchte ich noch die aktuelle Version des IDML-Templates (Absatzformate 'Prosa EB' und 'Prosa LB').

**Comment by markusciupke** [comment]
Es hat neben diesen beiden neuen Absatzformaten in den letzten Wochen noch weitere Änderungen und/oder Ergänzungen bei den Absatz- und Zeichenformaten gegeben. Es erscheint mir sinnvoll, dass ich meine Aufstellung der Absatz- und Zeichenformate entsprechend aktualisiere und @gerritbruening mitteile, damit er wiederum die XML-Datei entsprechend aktualisieren kann. Dazu komme ich aber voraussichtlich erst heute abend.

**Comment by markusciupke** [comment]
Ich habe jetzt die Liste der Absatz- und Zeichenformate aktualisiert. Bei den Absatzformaten ersetzen die neuen Formate Prosa EB und Prosa LB das alte Format Prosa. Ansonsten gibt es kein neues Absatzformat, sondern nur zwei kleine Änderungen. Das Absatzformat Apparat hat jetzt immer einen Abstand von 1/4 Zeile nach unten zum nächsten Apparat-Eintrag und die Schriftgröße der Kolumne ist von 9,5 auf 8,5 verkleinert.
Die 7 Zeichenformate aus der Liste vom 14.03.2018 sind unverändert, aber es gibt 8 weitere Zeichenformate:
Kursiv, Hochgestellt, Kursiv Hochgestellt, Typ (für die römischen Typ-Bezeichnungen im Apparat), Versalziffer recte (für Ziffern bei Sprechern u.ä.), Versalziffer kursiv hoch (für den Apparat), Dot (für den Punkt in der Kolumnenzeile) und Transparent. 
Hier ist die Excel-Datei (im Querformat):
[Formate.xlsx](https://github.com/faustedition/faust-gen-html/files/1981531/Formate.xlsx)

Und hier ist das entsprechende leere IDML-Template mit den aktualisierten Absatz- und Zeichenformaten und leeren Rahmen auf knapp 500 Seiten:
[Faust Template 2018.05.07.idml.zip](https://github.com/faustedition/faust-gen-html/files/1981546/Faust.Template.2018.05.07.idml.zip)

**Comment by markusciupke** [comment]
@pglatza: gestern Abend habe ich noch ein weiteres Absatzformat definiert: Auftritt o.N. (siehe #307).
Deshalb lade ich hier eine aktualisierte Formatliste und eine aktualisierte Template-Datei hoch:
[Formate.xlsx](https://github.com/faustedition/faust-gen-html/files/1986579/Formate.xlsx)
[Faust Template 2018.05.09.zip](https://github.com/faustedition/faust-gen-html/files/1986584/Faust.Template.2018.05.09.zip)

**Comment by pglatza** [comment]
Bitte die IDML-Datei immer beilegen, @markusciupke. Habe sie nun selbst erstellt, sollte allerdings keine Probleme/Unterschiede mit sich bringen. Wird auch schon aktuell im Upload-Formular verwendet.

**Comment by markusciupke** [comment]
Meinst du PDF-Datei? – Ja, entschuldige. Das habe ich heute morgen zu Hause gemacht, und da wird keine PDF-Datei automatisch erstellt wie hier im Verlag.

**Comment by pglatza** [comment]
In der ZIP-Datei lag eine `.indd`-Datei, jedoch keine `.idml`-Datei. Die PDF-Datei benötige ich im Normalfall nicht, mach Dir da keine Umstände.

**Comment by markusciupke** [comment]
In Ordnung. Nächstes mal mit idml-Datei.

**Comment by markusciupke** [comment]
Hier richte ich mich nach den von euch gemachten Absätzen. In der letzten IDML-Datei waren hier noch die Trennungen nach A drin (unendli-cher). Das kann ich aber auch im Satz schön machen, und ihr kontrolliert in der 1. Fahne.
Von mir aus kann das geschlossen werden.

**Comment by gerritbruening** [comment]
Dann sind die Zeilenumbrüche ja rübergekommen, also zu.
