### ISSUE TITLE
korrekter Text in Tooltips

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#4]
Für den Text in Tooltips müssten add, del, etc. korrekt ausgewertet werden.

**Comment by thvitt** [comment]
auch <gap> etc

**Comment by gerritbruening** [comment]
Was heißt "auch etc"?

**Comment by thvitt** [comment]
On 20.07.2015 14:26, gerritbruening wrote:
> Was heißt "auch etc"?

auch `gap` etc., die spitzen Klammern hat Github wohl gefuttert
