### ISSUE TITLE
Render <gap> with precision="medium" as ×...×

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#40]

**Comment by thvitt** [comment]
Only in the Einblendungsapparat? The other `<gap>` rules are in all representations

**Comment by thvitt** [comment]
Need more info here. The current solution is:

* `unit="chars"` → *Rendering:* as many `×` as missing chars, *Tooltip:* [ungefähr ]_n_ unlesbare Zeichen (_ungefähr_ iff `@cert='medium'`, this should obviously be changed to `@precision='medium'`)
* `unit="words"` → *Rendering:* as many `×···× ` as missing words, *Tooltip:* _n_ unlesbare Wörter

So you'll need to specify both rendering and tooltip for each unit when precision=medium.

**Comment by gerritbruening** [comment]
I have corrected the XML sources, there is no `unit="words"` together with `precision="medium"` left.

**Comment by gerritbruening** [comment]
As for https://github.com/faustedition/faust-gen-html/issues/40#issuecomment-233274163: I agree with the current solution. @thvitt, given that there is no "words" in combination with "medium": Is there anything left to be specified?

**Comment by gerritbruening** [comment]
As for https://github.com/faustedition/faust-gen-html/issues/40#issuecomment-233264983: Yes, this applies to all representations, not for the Einblendungsapparat exclusively.
