### ISSUE TITLE
Rendering of rdg with multiple @type values

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#400]
See https://github.com/faustedition/faust-gen-html/issues/397.

@thvitt, how are these rendered?

**Comment by thvitt** [comment]
[(II a, II c)](http://dev.faustedition.net/print/faust.9#l2348)

**Comment by gerritbruening** [comment]
Thanks.
@dietmarpravida, please have look on the example linked by @thvitt. Do you agree o this rendering?

**Comment by dietmarpravida** [comment]
i do
