### ISSUE TITLE
insert vertical space before 4412

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#402]
For previous discussion, see #320.

It seems as if only `speaker` gets some space before it. In this case, the `l` would need some space before it.

**Comment by thvitt** [comment]
I don’t get it. What should I add to faust.xml here? And according to what rule?

**Comment by gerritbruening** [comment]
Nothing to be added to faust.xml, only to the current rendering which _seems_ to have vertical spacing between `sp`s. However, this is triggered by the `speaker` element at each normal  `sp`'s start. What we need here is spacing despite that there is no `speaker`, only a new `sp`

**Comment by thvitt** [comment]
`.sp` cannot get padding (would cause a gap in background in border), so its probably
```css
.sp .hasvars:first-child { padding-top: 1.5ex; }
```

**Comment by gerritbruening** [comment]
Danke!
