### ISSUE TITLE
stage/emph wie stage/hi zu behandeln

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#403]
Betrifft z.B. before_12032_a Mater Gloriosa
müsste Replikenabstand noch oben bekommen; dass die BA den nicht bekommt, liegt wohl an `emph` statt `hi`

**Comment by gerritbruening** [comment]
@markusciupke, haben 
> ERDBEBEN

und
> MATER GLORIOSA schwebt einher

einen halbzeiligen Abstand nach oben? Wenn ja, closen.

**Comment by markusciupke** [comment]
»Erdbeben« hat 0,5 Zeilen Abstand nach oben.

»MATER GLORIOSA« schwebt einher steht oben am Seitenbeginn, hätte aber 0,5 Zeilen Abstand nach oben, wenn es mitten auf der Seite stünde.

Kann geschlossen werden.
