### ISSUE TITLE
app zu 2490-92

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#408]
> ich finde ja, dass der Apparat zu 2490-92 seltsam aussieht. Niemand versteht vermutlich, was hier geschehen ist, oder? (Es könnte auch nur an dem "bis" liegen?)

![grafik](https://user-images.githubusercontent.com/10358005/38736202-99d4ccf2-3f2b-11e8-934d-71c790e4062d.png)

**Comment by dietmarpravida** [comment]
hm ja, war auch nur so ein Gefühl, dass der gewöhnliche User sich hier nicht zurechtfinden wird
