### ISSUE TITLE
before_2270_a

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-gen-html#409]
Kein Leerzeichen zwischen "Mephistopheles" und "bohrt"?

![before_2270_a](https://user-images.githubusercontent.com/26788529/38741161-8e7c1eba-3f39-11e8-9fb4-ea9d356e30ff.JPG)

**Comment by thvitt** [comment]
#396

**Comment by thvitt** [comment]
btw ihr macht es mir einfacher, wenn ihr den Link zur Stelle ins Github kopiert, habt ihr ja eh im browser wenn ihr das seht
