### ISSUE TITLE
Variant detection error

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#41]
[Here below verse 7039](http://beta.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2.2/gsa_391089.xml&page=1&view=print#l7039) and also in the heading on that page we have _0 variants in 0 witnesses_ – at least the latter cannot be true.

**Comment by gerritbruening** [comment]
Interesting. Maybe the n attribute is missing or empty or has multiple values?

**Comment by thvitt** [comment]
Multiple values ;-(

```xml
<stage n="after_7039 before_7040_a">(Entfernt ſich<del f:revType="soon-or-late">;
       die Luftfahrer oben</del>)</stage>
```

The other case on that page is similar. Does this encoding make any sense?

**Comment by thvitt** [comment]
OK, encoding doesn't make sense. Support for multiple `n` values will be discussed at next f2f meeting.

**Comment by thvitt** [comment]
@gerritbruening, has this the same semantics as the multiple values in #51? If not, the encoding should be fixed in the original sources.

**Comment by gerritbruening** [comment]
Ah, only now I see that unfortunately the current encoding indeed does make perfect sense.

In general we have to prepare for cases where the division of stage direction or heading varies in the whitnesses.
