### ISSUE TITLE
hi per app entfernen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#411]
@thvitt, an den hier zu sehenden beiden Fällen
https://github.com/faustedition/faust-gen-html/commit/fcc9bf68b165505c9b9d6c3be6f7cf77e723e9fd#diff-a48138172ec406b07f08b2d419608958R153
wäre es richtig, wenn im XML ein `hi` da wäre (genau um die betreffenden Phrasen herum, und das dann weg-emendiert würde. Gibt es dazu schon eine Möglichkeit?

**Comment by thvitt** [comment]
noch nicht. Die Codierung würde ähnlich zu #321 erfolgen, d.h. xml:id am zu löschenden `<hi>`, ich pushe gleich eine Schemaänderung.

**Comment by thvitt** [comment]
hm. Ich würde das jetzt so ändern, dass man beliebige Elemente durch neuen Inhalt ersetzen kann, also quasi eine All-in-one-Lösung für #321 und dies hier.

**Comment by thvitt** [comment]
@gerritbruening, bitte analog folgendem codieren (vgl. schema) und dann gucken, ob’s geklappt hat und ggf. dies wieder aufmachen
```xml
<app>
  <f:replace n="4711" element-id="someid"/>
  <f:ins n="4711">und die</f:ins>
  <!-- … -->
</app>
```
Ersetzt in Vers 4711 das Element mit der XML-ID `someid` (ob nun anchor oder hi) und dessen Inhalt durch den Inhalt des `f:ins`-Element, wie üblich in ein `<seg>` verpackt.

**Comment by gerritbruening** [comment]
Danke, mache ich, und erstatte Bericht.

**Comment by dietmarpravida** [comment]
muss ich da für app on 359 etwas machen? oder fällt das in Gerrits Bereich?

**Comment by gerritbruening** [comment]
Scheint so, jedenfalls bin ich bei #321 momentan assignt.

**Comment by gerritbruening** [comment]
An den beiden betreffenden Stellen (siehe referencing commit oben) wurde letztlich nicht emendiert.
359 ist ein anderer Punkt.
