### ISSUE TITLE
Go to next app entry

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#412]
It would be nice to have a button in app entry that brings me the next or previous app entry. Would enable to read the text along the app entries. `print/app` does not replace this since it is based on types, not on textual order.
What do you think, @thvitt?

**Comment by thvitt** [comment]
(wonder whether we should split the c:text label into stuff that is required for a proper `faust.xml` (i.e. print deadline) and features re visualisation in the web)

**Comment by gerritbruening** [comment]
Yes, stuff relevant for the printed edition could get the idml label provisionally.

**Comment by gerritbruening** [comment]
This is nice, thanks!
