### ISSUE TITLE
Add Siglenverzeichnis

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#413]
Das Siglenverzeichnis sollten wir auch online haben, nicht nur im Druck.

Welche Einträge das Siglenverzeichnis hat, ergibt sich aus der `faust.xml`.
Im header (`listWit`) stehen alle Zeugensiglen, die vorkommen.
Dazu brauchen wir eine Kurzbeschreibung, ich denke jenseits der jetzigen `headNote`. Die gehorcht v.a. bei den Handschriften einem ziemlich rigiden Schema, das für eine Kurzbeschreibung im textkritischen Kontext nicht so ganz passt, oder, @dietmarpravida?
In @thvitt|s Sinne wäre es wohl, wenn die textkritische Charakterisierung direkt in den document-Dateien abgelegt und von dorther bezogen wird, richtig?

**Comment by thvitt** [comment]
ja. – Bei der Gelegenheit: Wir verwenden an verschiedenen Stellen (Handschriftentabelle, vor allem aber Links in der Edition) eine Kurzbeschreibung im Tooltip, die m.W. im Augenblick classification + headNote ist. Wenn es jetzt eine zusätzliche Kurzbeschreibung gibt, sollte die vermutlich möglichst überall, zumindest aber in den Links verwendet werden

**Comment by gerritbruening** [comment]
Das sollen wir nochmal überlegen, wenn wir wissen, wie die inhaltlich aussehen.
@dietmarpravida, ich habe mal ein paar Ansätze an der betreffenden Stelle des Googledoc eingefügt, tu du das doch auch mal, und dann sehen wir weiter.

**Comment by gerritbruening** [comment]
Könntest du ein paar davon mit Inhalt füllen? Damit wir sehen, welche Form die haben könnten und wie wir das am Ende in die Daten schreiben.

**Comment by thvitt** [comment]
Wo ist das jetzt? Wenn das Material da ist bzw. konkret etwas zu tun für mich, dann bitte zurückzuweisen

**Comment by dietmarpravida** [comment]
ich würde das hier am liebsten schließen und den Vorschlag nicht weiterverfolgen

**Comment by gerritbruening** [comment]
Ja OK, dann ist das Siglenverzeichnes nur für den Druck, um dessen Verständlichkeit zu gewährleisten. Von mir aus.

**Comment by dietmarpravida** [comment]
Siehe  #538
