### ISSUE TITLE
Check wordlist for strange tokens

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#415]
http://dev.faustedition.net/print/faust.wordlist

from the wordlist.

- [x] b
- [x] ben
- [x] betrubende
- [x] bez (nicht mehr vorhanden)
- [x] Bimm (schreibt Jo so)
- [x] Bischen
- [x] cher
- [x] Ci
- [x] Comando
- [x] Dacktyl (bei der Abschrift Apostroph weggelassen)

**Comment by gerritbruening** [comment]
Heute nicht mehr.

**Comment by dietmarpravida** [comment]
erledigt?
