### ISSUE TITLE
Generate Grundschicht

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#416]
Aspekte
* Grundschicht ohne Sofortkorrekturen
* Grundschicht mit Sofortkorrekturen
* TEI-Regeln für die chronologische Interpretation von Verschachtelungreihenfolgen
* gleich an Zwischenstufen denken
* Richtung vorwärts oder rückwärts

**Comment by gerritbruening** [comment]
Ein Hack wäre auch schon sehr hilfreich, dann könnte ich die Arbeit am Text noch rechtzeitig abschließen. Wäre da etwas möglich, @thvitt?

**Comment by thvitt** [comment]
Wirklich nur Grundschicht ist vermutlich im wesentlichen 
- del → child::node()
- add → ()
- subst → del/node()
- restore, transpose ignorieren

@gerritbruening, was ist mit
- supplied[@evidence = 'internal']
- supplied[@reason = 'typesetting-error']
- choice / orig / abbr / sic / lem

**Comment by thvitt** [comment]
Ergebnisse erscheinen [hier im Build](http://dev.digital-humanities.de/ci/view/Faust/job/faust-gen-fast/ws/target/grundschicht)

**Comment by gerritbruening** [comment]
Super, danke, ich gehe die obigen Fragen durch und notiere, was mir so auffällt:

                        <l n="8495">Der Rückkehr <subst f:revType="late">
                              <del>
                                 <unclear cert="high">S</unclear>
                              </del>
                              <add>ſ</add>
                           </subst>amt den tapferſten ſeiner Krieger ſich.</l>

Hier wäre in `del` der leading und trailing whitespace (Juhu!) zu entfernen.

**Comment by thvitt** [comment]
wsp: der ist da m.E. schon in der Quelle nicht angebracht

**Comment by thvitt** [comment]
Ich habe jetzt mal einen radikaleren Ansatz gepusht: Der unnötige Whitespace kommt vorm Prozessieren weg und hinterher wird einfach mit Einrückung gespeichert. Damit ist auch das o.g. Whitespaceproblem gelöst. Wenn’s zu Problemen führt, sag bescheid.

**Comment by gerritbruening** [comment]
> wsp: der ist da m.E. schon in der Quelle nicht angebracht

Das finde ich auch, ich vermute dass er maschinell durch irgendeine Datenbankmigration in alten Zeiten oder durch disfunktionales Format & Indent in Oxygen verursacht wurde. Händisch kodiert haben wir so nicht. Könnte daher auch immer mal wieder enstehen, ohne dass wir das wollen.
Umso besser, wenn das nicht händisch entfernt werden muss.

**Comment by thvitt** [comment]
* [ ] Grundschicht _mit_ Sofortkorrekturen

**Comment by gerritbruening** [comment]
Kann ich das schon testen?

**Comment by thvitt** [comment]
ja, das liegt [hier neben der anderen Grundschicht](http://dev.digital-humanities.de/ci/job/faust-gen-fast/ws/target/grundschicht-instant/)

**Comment by gerritbruening** [comment]
OK, danke!

**Comment by gerritbruening** [comment]
Getestet und für sehr gut befunden. Ein paar Aufräumschritte habe ich noch appliziert, muss aber nicht un die Pipeline, sonst sage ich noch bescheid.

**Comment by thvitt** [comment]
dann mach ich das jetzt zu, kannst ja bei bedarf reopenenn

**Comment by gerritbruening** [comment]
Ja!
