### ISSUE TITLE
Siglen in wit in faust.xml

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#417]
- [x] wo in welcher Form?
- [x] wo erst expandiert und dann ggf. wieder verkürzt?

**Comment by gerritbruening** [comment]
Weil vorhin die Rede darauf kam -- was ich tue, ist folgendes:
* Ich verwandele Hochstellungen in die Form `.5` etc. (https://github.com/faustedition/faust-gen-html/blob/master/text/app.xml#L742).
* Ich expandiere @dietmarpravida|s H.5 etc. und C.1 / C.3 so, dass eindeutige IDs herauskommen (https://github.com/faustedition/faust-gen-html/blob/master/text/app.xml#L762)

Das tue ich unabhängig davon, ob und wie deren spätere Textform im Apparat wieder hochgestellt oder verkürzt wird.
Im Faust II ziehe ich meinen Wildwuchs in der Word-Datei auf diese Weise glatt, wo ich mal Punkt mal Hochstellung und mal "H" und mal "2_H" und alle möglichen anderen Inkonsistenzen habe, die vom informellen Charakter der Datei herrühren.
Anders wollte ich das dir, @thvitt, nicht zumuten.

**Comment by gerritbruening** [comment]
Das ist gut zu wissen, klingt sehr vernünftig. 
Dann brauchen wir soweit erstmal nichts ändern, denke ich.
Ich habe das Issue umbenannt, so dass es sich jetzt vorläufig nur noch auf den Inhalt von `wit` in der `faust.xml` bezieht.
Es wird am besten sein, das von dem am Montag zur Sprache gekommenen Siglenverzeichnis her zu überlegen.
Deswegen sollten wir uns jetzt erstmal um faust-gen-html/issues/413 kümmern.

**Comment by gerritbruening** [comment]
Ich würde sagen, @dietmarpravida, du triffst zunächst die Festlegung für Faust I. Danach assignst du @thvitt wieder für die Umsetzung.

**Comment by dietmarpravida** [comment]
was für eine Festlegung?

**Comment by gerritbruening** [comment]
Vor allem C.1 und C.3 mit oder ohne 12 (C 4 und C 12 auch im Faust II zu bedenken). Hilfreich wäre zu wissen, wie das Siglenverzeichnis aussehen solle, ob es hierarchische Einträge gibt z.B.

**Comment by dietmarpravida** [comment]
- Bei Band 12 von C1 und C3 steht nie die Bandzahl (kommt nur in Faust I vor)

- Bei Band 4 (und falls vorkommend Band 41) von C1 und C3 steht immer die Bandzahl (nur in Faust II)
 

Die Zitierweise wird im Siglenverzeichnis erläutert

**Comment by gerritbruening** [comment]
> Bei Band 12 von C1 und C3 steht nie die Bandzahl (kommt nur in Faust I vor)

Beschreibt, was am Ende sein soll. Im Manuskript steht die Bandziffer noch. Die werde dann durch Suchen und Ersetzen entfernt.

**Comment by thvitt** [comment]
also, um mal klare Ersetzungsregeln zu definieren:

* `C.1 12` → _C¹_
* `C.3 12` → _C³_
* `C.1 4` → _C¹ 4_
* `C.3 4` → _C³ 4_

alle anderen Siglen folgen den in #205 ausgeführten und implementierten Regeln? Soll ich das so implementieren?

**Comment by thvitt** [comment]
Ich habe ein paar Ersetzungsregeln als Preprocessingschritt hier hingeschrieben:

https://github.com/faustedition/faust-gen-html/blob/2d78caaedc9fcd3213c08f646e8cfab01475fce0/xslt/text-insert-app.xsl#L189-L195

Könnt ihr ja bearbeiten, wenn sich die Meinungen noch ändern. orig="Sigle in der Webedition"

**Comment by dietmarpravida** [comment]
Nach neuestem Stand:

* `C.1 4` → _C¹_

@gerritbruening, passt du das an?

**Comment by thvitt** [comment]
war mal so frei

**Comment by gerritbruening** [comment]
Dann close ich das jetzt mal, bei Bedarf bitte reopen.
