### ISSUE TITLE
Middle dot in Kolumnentiteln

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#418]
![grafik](https://user-images.githubusercontent.com/10358005/38932563-e3ff0e16-4316-11e8-8fa6-e6cffe54b163.png)

Der Punkt auf halber Höhe im rechten Kolumnentitel erscheint in meinen Augen auffällig dicker als die Strichstärke der sonstigen Zeichen.
Hat das eher mit dem Schriftzeichen oder mit der Schriftart zu tun?

**Comment by markusciupke** [comment]
Da hast du recht. Das habe ich zu schnell gemacht und nicht noch mal auf einem Ausdruck geprüft. Der Dot ist verkleinert, aber nicht genug. Das mache ich morgen nochmal besser und lade es hier hoch.

**Comment by gerritbruening** [comment]
Sie Kommentar in https://github.com/faustedition/faust-gen-html/issues/374#issuecomment-382695777, scheint uns OK so.

**Comment by dietmarpravida** [comment]
ich schließe das hier mal, da es erledigt zu sein scheint, nicht?
