### ISSUE TITLE
No match for 9393[^], 9401[^]

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#423]
```
ERROR:parse_app2norm: No match: 9393[^]{<milestone unit="lg" rend="indented"/>} <i>vor 9393 Spatium H fehlt C.1_4 [type=2aa]</i>

ERROR:parse_app2norm: No match: 9401[^]{<milestone unit="lg" rend="indented"/>} <i>vor 9401 Spatium H fehlt C.1_4 [type=2aa]</i>
```

@thvitt, I am searching for the infringement of the rules, but I don't find it.
The `5484[^]{<milestone unit="lg" rend="indented"/>} ...` further above does work.

**Comment by thvitt** [comment]
`[…]<i>vor 9393</i>] <i>Spatium H fehlt C.1_4 [type=2aa]</i>`

**Comment by thvitt** [comment]
Dieser _no match_ ausdruck schaut nicht wirklich in [replace] und {insert} hinein, die probleme sind meist danach zu finden

**Comment by gerritbruening** [comment]
Ah, wer weiter liest ist klar im Vorteil.
