### ISSUE TITLE
Duplicates in trailing section of 2_H

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#425]
See
http://dev.faustedition.net/document?sigil=2_H&page=375&view=print#l12111

**Comment by thvitt** [comment]
wieso c:text?

**Comment by thvitt** [comment]
Ist möglicherweise gar keine Regression, es sind neue `<div type="stueck">` in den Daten hinzugekommen.

In `{prepared/textTranscript,emended}/2_H.xml` sind die Duplikate noch nicht vorhanden, von daher tippe ich auf den Trailereinsammelcode in split.xsl

**Comment by gerritbruening** [comment]
> wieso c:text?

War Quatsch

**Comment by gerritbruening** [comment]
Äh, blödes Smartphone!

**Comment by thvitt** [comment]
/me nimmt [ForkHub](https://play.google.com/store/apps/details?id=jp.forkhub), aber es gibt eine ganze Reihe passabler Clients

**Comment by gerritbruening** [comment]
((ForkHub probiere ich grad mal aus.))
