### ISSUE TITLE
∞ character in trailing section of 2 H

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#427]
![grafik](https://user-images.githubusercontent.com/10358005/45181652-5daab900-b21f-11e8-92b9-2c5d49cc3943.png)

http://dev.faustedition.net/document?sigil=2_H&page=1&view=text&section=2_H.all#l5931

Possibly associated with #425.

**Comment by gerritbruening** [comment]
Sorry for the uncropped image, now it's cropped.

**Comment by thvitt** [comment]
is this still an issue?

**Comment by gerritbruening** [comment]
Yes, ∞ character is still there, look at the new picture in the first comment.

**Comment by thvitt** [comment]
faustedition/faust-web#351
