### ISSUE TITLE
Fußnoten haben Ausdehnung

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#428]
verlängern u.U. die Zeile, bei Zentrierung (betrifft **alle Einträge in Sprecher und BA**) und langen Zeilen ein Problem (sehr langer Vers könnte umgebrochen werden)

Idee MC: Fußnote an den Zeilenanfang (vor Tab / Verszahl) setzen.

**Comment by pglatza** [comment]
Veranlasse in der IDML-Synthese die Umplatzierung der Fußnoten an den Anfang des Absatzes.
Änderung noch nicht beim Upload-Formular verfügbar.

**Comment by pglatza** [comment]
Habe das Upload-Formular aktualisiert.

**Comment by gerritbruening** [comment]
Ich füge mal ein Beispiel ein, dass [in anderem Zusammenhang](https://github.com/faustedition/faust-gen-html/issues/374#issuecomment-388606961) zur Diskussion steht:

```xml
      <ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/C BA zentr. 2,3 / 0,0">
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Footnote>
               <ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/$ID/NormalParagraphStyle">
                  <Content>Wachspfropfen </Content>
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Kursiv">
                     <Content>S</Content>
                  </CharacterStyleRange>
               </ParagraphStyleRange>
            </Footnote>
         </CharacterStyleRange>
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Footnote>
               <ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/Sprecher">
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
                     <Content>Mephistopheles</Content>
                  </CharacterStyleRange>
               </ParagraphStyleRange>
               <Content> / bohrt, </Content>
               <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Kursiv">
                  <Content>bis</Content>
               </CharacterStyleRange>
               <Content> verstopft</Content>
            </Footnote>
         </CharacterStyleRange>
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Figur">
            <Content>Mephistopheles</Content>
         </CharacterStyleRange>
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Content>&#x2028;</Content>
         </CharacterStyleRange>
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Content>bohrt, einer hat indessen die Wachspfropfen gemacht und verstopft.</Content>
         </CharacterStyleRange>
         <Br/>
      </ParagraphStyleRange>
```

Hierzu die Frage von @markusciupke (ebd.):
> > Das Problem mit den Fußnoten löst @pglatza in #428 oder hat es schon gelöst.

> Auch das Problem mit den BAs, die mit der Fußnotenmarke zwei statt einer Zeile benötigen würde?

@pglatza, kannst du hierzu etwas sagen?

**Comment by pglatza** [comment]
Ja, der IDML-Schnipsel zeigt das neue Verhalten der IDML-Synthese: alle Fußnoten werden an den Anfang der des Absatzes verschoben.
Das Verschieben vor die Verszahl bzw. vor einem Tabulator trifft bei einem zentriertem Absatz natürlich nur bedingt zu, da es hier keine solchen optischen Elemente gibt.

**Comment by gerritbruening** [comment]
OK, und führt das zu Problemen bei der Zentrierung,
* weil die Zeile von der Mitte weg nach rechts verschoben wird,
* und weil die Zeile evtl. früher umbricht?

**Comment by pglatza** [comment]
Ja, das trifft zu, für die beiden negativen Punkte.
Wenn wir es nicht über das Absatzformat lösen können (z.B. mit bestimmten Abständen, Einzügen, Tabulatoren o.ä., @markusciupke?), dann sehe ich nur eine funktionierende Umsetzung via InDesign-Skript. Dabei wird die Fußnoteziffer aus dem Fließtext / Absatz gelöst, in einen eigenen Textrahmen gepackt und dieser am Anfang des zentrierten Absatzes verankert.
Das Skript müsste einmalig von Markus ausgeführt werden.

**Comment by markusciupke** [comment]
Ich kenne mich leider mit Skript-Schreiben nicht aus. Aber ich werde mich kundig machen. Auf jeden Fall kann ich die Fälle, die das betrifft, so aufbereiten, dass es funktioniert. Es wird nicht die letzte manuelle Nacharbeit sein. Insofern können von meiner Seite her Fußnotenmarken die in bzw. nach zentrierten Absätzen stehen von euch ignoriert werden.
Wenn bei allen anderen Absätzen die Fußnotenmarke am Anfang des Absatzes steht, stellen zumindest diese kein Problem mehr dar.
Dieses Issue kann also von meiner Seite her geschlossen werden.

**Comment by gerritbruening** [comment]
Dann gehe ich mal davon aus, dass das hier gelöst ist.
