### ISSUE TITLE
rdg/@type an den Schluss

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#429]
@dietmarpravida and I have discussed this recently.
In most cases, type information applies to the whole app entry.
In some cases it applies only to the reading after which it is placed in the app[12]norm.txt files.

**Comment by gerritbruening** [comment]
Mehrfache in der Form

> (X, XX)

**Comment by thvitt** [comment]
ach, das soll in’s XML? Dann muss ich wieder umbauen

**Comment by gerritbruening** [comment]
Wenn das zu nervig ist, könnte @pglatza, die `rdg/@type` einsammeln und in Klammern an den Schluss setzen. Ich würde es davon abhängig machen, ob wir das online auch so haben wollen. Die Typ-Angabe direkt hinter dem betreffenden `rdg`-Inhalt hat ihr Vor- und Nachteile.

**Comment by thvitt** [comment]
Es wär ja nicht damit getan, da ich wg. Links bei mehreren sowas bräuchte wie 

```xml
<note type="type">(<ref target="#type_2a">II a</ref>, <ref target="#type_7">VII</ref>)</note>
```
Im Augenblick geschieht das erst bei der HTML-Wandlung. Da die Zeit knapp wird: Ich kann nicht versprechen, dass ich das noch rechtzeitig bis morgen schaffe.

**Comment by pglatza** [comment]
Ich werde voraussichtlich bis morgen auch noch nicht liefern können.
Also von meiner Seite gibt es keinen Druck, diese XML-Anpassung diese Woche noch umzusetzen.

**Comment by gerritbruening** [comment]
Vielen Dank @thvitt und schöne Pfingsten!
@pglatza, ich habe die IDML-Doku entsprechen aktualisiert.
