### ISSUE TITLE
app list doesn’t suppress (,) for multiple types

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#430]
stimmt noch etwas nicht in der Typenliste:
http://dev.faustedition.net/print/faust.39#app.before_10811_a.kauertnieder

![grafik](https://user-images.githubusercontent.com/10358005/39187868-af664356-47ce-11e8-9f84-52339f46043f.png)

Der Eintrag im Text ist OK

**Comment by thvitt** [comment]
@gerritbruening Die Typenliste ist ja rein web, wieso ist das im msfausti milestone?

**Comment by gerritbruening** [comment]
Ach so, ich dachte das würde sich bis in faust.xml fortpflanzen.

**Comment by thvitt** [comment]
nein. Wenn sowas benötigt wird, müsste man mir die Anforderungen präziser formulieren (und eine andere Deadline als Freitag)

**Comment by thvitt** [comment]
#429

**Comment by thvitt** [comment]
This is obsolete with the resolution of #429
