### ISSUE TITLE
Styling for trailer

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#431]
http://dev.faustedition.net/document?sigil=2_H&page=375&view=print#l12111

After 
> Finis

there should be some visible break.
Don't we have some spacing at end of `text` elements?

See also #425.

**Comment by gerritbruening** [comment]
What I see now (Gesamtansicht) is this:

![grafik](https://user-images.githubusercontent.com/10358005/41436579-679a4af0-7022-11e8-8777-c1fb8eae454d.png)


Intuitively I would say. the spacing after "Finis" should be stronger than before it.
Secondly I ask myself whether "Finis" should be indented, maybe even more than the verse lines are.
What are the thoughts behind the current solution, @thvitt?

**Comment by thvitt** [comment]
I’ve only looked at the text and not considered that there is a witnes with contents after the Finis.

We could also center it, make it bold or red etc., just tell me what you want …

**Comment by gerritbruening** [comment]
Centered would be nice, I think.

**Comment by thvitt** [comment]
faustedition/faust-web@b0030d0bb679894ce89f64f143d80d242eac3397

**Comment by gerritbruening** [comment]
Fine!
