### ISSUE TITLE
Two periods in 10524

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#432]
See #422.

Also, only "fort" is underlined. Would be good to underline the whole of v. 10524.

**Comment by thvitt** [comment]
Die zwei Punkte kommen zustande, weil zunächst Vers 10524 mit `fort.` eingefügt wird;

```xml
  <app>
    <f:ins n="10523" place="after"><l n="10524">Er ist behend, reist alles mit sich fort.</l></f:ins>
  <!-- ... -->
  </app>
```
… und dann das `fort` durch `fort.` ersetzt wird:

```xml
  <!--       10524[fort]{fort.} <i>10524</i> fort. <i>none</i>] fort^ <i>2_IV_H.18 [type=1b]</i>-->
  <app>
    <f:replace n="10524">fort</f:replace>
    <f:ins n="10524">fort.</f:ins>
    <!-- ... -->
  </app>
```
⇒ im Apparat zu nach 10523 den . entfernen.

Das Highlighting für ganze eingefügte Zeilen müssen wir nochmal überlegen.
