### ISSUE TITLE
Editorial text in app entries should appear grey

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#434]
Current solution unsatisfying, see
http://dev.faustedition.net/print/faust.30#app.before_6150_b.gleichfals
(both editorial text and `stage` text black and in italics)

**Comment by thvitt** [comment]
* [x] Notes
* [x] Typen, Links
* [ ] gap
* [ ] Lemmaklammer

**Comment by gerritbruening** [comment]
Great, thanks!
