### ISSUE TITLE
(a) in Typenbeschreibungen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#435]
Betrifft
* II aa: Emendation einer Störung im Grundtext (a)
* II aa*: Emendation einer Störung im Grundtext (a*)

Verstehe ich das "(a)" nicht so richtig. Soll es einfach sagen: etwas anderes als Typ IIa, @dietmarpravida?

**Comment by thvitt** [comment]
Da steht im als Typ `2aa`. Dafür gibt's keine Expansion in der [Liste](https://github.com/faustedition/faust-gen-html/blob/master/text/apptypes.xml), drum.

**Comment by dietmarpravida** [comment]
Kommt das 2aa irgendwo vor? In F-I anscheinend nicht.

**Comment by thvitt** [comment]
60× in Faust II

**Comment by gerritbruening** [comment]
Zur Erinnerung, 2aa bedeutet dasselbe wie 2a, aber zusätzlich "gegen die unmittelbare Vorlage". Vielleicht also "Emendation einer Störung im Grundtext gegen die unmittelbare Vorlage"?

**Comment by dietmarpravida** [comment]
Was ist denn eigentlich die Frage?

**Comment by gerritbruening** [comment]
IIaa und IIaa* werden nicht so erklärt, dass der Unterschied zu IIa und IIa* klar wird.
Wärst du mit der Kurzerklärung "Emendation einer Störung im Grundtext gegen die unmittelbare Vorlage" und dem Zusatz "(nicht übernommen)" einverstanden?

**Comment by dietmarpravida** [comment]
ja
