### ISSUE TITLE
Sort bibliography

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#44]
We need a detailed sort spec that works _for all_ citations. 

Problem: volume numbers such as
WA I 1
WA I 10
WA I 13
WA I 15,1
WA I 15,2
WA I 2

Also applies to the GJB volumes.

**Comment by gerritbruening** [comment]
@thvitt, do you want me to specify the how the bibliography headings (WA I 13 etc.) are to be parsed? For example:

| 1 (alphab) | 2 (alphab) | 3 (num) | 4 (sep) | 5 (num) |
|------------|------------|---------|---------|---------|
| WA         | I          | 15      | ,       | 1       |
| WA         | IV          |  39 | -- | -- |

**Comment by thvitt** [comment]
The bibliography seems to use at least three different systems for the citation keys (Author/Year, WA, GJb). To sort properly, we need a rule that covers them all. 

I'm now splitting the case-normalized citation keys into four groups that form the sort keys, in order:

1. sequence of non-digits, sorted alphabetically
2. following sequence of digits, interpreted as number
3. sequence of non-digits, sorted alphabetically
4. sequence of digits, interpreted as number

I hope this covers all cases, if not, either come up with a better rule or use a more consistent scheme for the citation keys …

**Comment by gerritbruening** [comment]
Seems to be a good solution to me! I will have a look on the result when it's online.

**Comment by gerritbruening** [comment]
Great! Thanks
