### ISSUE TITLE
Update schema for reading text

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#443]
For example, `witness/@corresp` causes many validation errors.
Didn't we have an issue for this already? I vaguely remember.

**Comment by thvitt** [comment]
Sounds familiar to me.

There’s already a branch in the faust-schema project called _fix-text_ …

**Comment by thvitt** [comment]
Fixed by https://github.com/faustedition/faust-schema/commit/ab719e6f4520d3be78a10ba998a7df109dd56fdc

**Comment by thvitt** [comment]
witStart is still missing. Check if it isn’t easier to allow witStart immediately instead of allowing app in those places where we only need it for witStart
