### ISSUE TITLE
Drop supplied reason="typesetting-error" in text view of prints

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#444]
See
http://dev.faustedition.net/document?sigil=A&page=35&view=structure&section=4#l359

XML:

                                    <l n="359">Und <supplied reason="typesetting-error"
                                            >bin</supplied> ſo klug als wie zuvor;</l>

**Comment by thvitt** [comment]
A’s textual transcript reads

> Und so klug als wie zuvor; 

so it already is dropped?

**Comment by thvitt** [comment]
ah, I read _print_ view

**Comment by gerritbruening** [comment]
Thanks!
