### ISSUE TITLE
Lesarten in Apparat zu nach 3409 voneinander trennen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#445]
Die Vorgeschichte #364.

Jetzt folgen die Lesarten in einem Rutsch hintereinander:
```
3409[]{} <i>nach 3409</i>] <i>Strophenabstand 1_H.5 kein Strophenabstand S A B B Strophenabstand vorschl. Gö mark. G 1_H.6 kein Strophenabstand 1_H.1 Strophenabstand C.1_12 C.3_12 [type=2b]</i>
```
Es müsste so sein:
```
<i>Strophenabstand 1_H.5</i> <i>kein Strophenabstand ...
```
Erreichen lässt sich das durch unkursive geschützte Leerzeichen zwischen den Lesarten.

**Comment by dietmarpravida** [comment]
müsste beim ncäshtenmal gehen

**Comment by gerritbruening** [comment]
Ja, in https://github.com/faustedition/faust-gen-html/commit/be47caef3c93f1c027c68fb9a1cc0139f4cc5aaa#diff-86da7489d035aef254aa3eb175b90d8fR254.
