### ISSUE TITLE
Fälschlich im Inhaltsverzeichnis gelandet, dortige Links kaputt

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#446]
Wenn ich z.B. diesen Link klicke
http://dev.faustedition.net/print/faust#l6062
(vom Text in 2_H aus),
lande ich in einer Gesamtansich. Das ist wohl nicht beabsichtigt?

**Comment by gerritbruening** [comment]
Wenn ich von hier aus die Szene Lustgarten aufsuche, land ich hier:
http://dev.faustedition.net/print/faustyes
(Fehler 404)

**Comment by thvitt** [comment]
arglarglargl … ja, ist’n bug, auswirkung dieser print-link-sache
