### ISSUE TITLE
correct target for "]" after </i> in 852, 988, 2322 and 4343

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-gen-html#447]
- [x] +852[]{} <i>852–859</i> <i>Die Verse sind in allen Drucken nicht eingerückt; in</i>**]** <i>faust://bibliography/Q wurden sie entsprechend den Versen 949–980 eingerückt. [type=1c*]</i>

- [x] INFO:parse_app2norm: Parsed: 988[stillt;]{=} <i>988</i> stillt; <i>Das Semikolon fehlt in manchen Exemplaren von A. [type=7]</i>**]** 

- [x] ERROR:parse_app2norm: No match: <i>2322</i> <i>In S A D.1 B 1_H.1 ist der mittlere Teil des antilabischen Verses (</i>**]**  Wie?<i>) nicht korrekt unterhalb des vorangehenden Teils (</i>Was giebt’s<i>) plaziert; korrigiert in B.a und in C.1_12 C.3_12. [type=1c]</i> --> #450

- [x] before_4343[]{} <i>vor 4343</i> <i>In 1_H.1 C.1_12 C.3_12 folgen die (ganz oder teilweise auch in 1_H.16 und 1_H.17 enthaltenen) Verse 4335–4342 (hier wiedergegeben nach 1_H.1) [type=5*]:</i>**]**  <sp><speaker>Tanzmeister.</speaker><l n="4335">Wie jeder doch die Beine lupft! </l> <l n="4336">Sich wie er kann herauszieht!</l> <l n="4337">Der Krumme springt, der Plumpe hupft</l> <l n="4338">Und fragt nicht wie es aussieht.</l><sp><sp></speaker>Fideler.</speaker><l n="4339">Das haßt sich schwer das Lumpenpack</l> <l n="4340">Und gäb sich gern das Restchen;</l> <l n="4341">Es eint sie hier der Dudelsack</l> <l n="4342">Wie Orpheus Leyer die Bestjen.</l><sp> --> #276.

**Comment by gerritbruening** [comment]
Wenn das geschehen ist, kannst du mich wieder assignen, und dann erledige ich den Rest.

**Comment by dietmarpravida** [comment]
sollte klappen

**Comment by gerritbruening** [comment]
Fixed in https://github.com/faustedition/faust-gen-html/commit/536d91754eb22d745a2f3ced0badd743a81c6dc4#diff-86da7489d035aef254aa3eb175b90d8fR62.
