### ISSUE TITLE
Encoding before2540_c

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-gen-html#448]
Jetzt steht da `before_2540_c[@stage]{rend=} vor 2540] In S ist Die Hexe nicht hervorgehoben. [Typ 1c*]` und wird nicht eingefügt. Es ist das einzigemal, dass `[@stage]{rend=}` bei mir vorkommt. Was ist hier zu tun?

**Comment by gerritbruening** [comment]
Es geht doch um 

                                <speaker n="before_2540_b">Die
                                    Hexe</speaker>

oder?
Also müsste stehn `before_2540_b[Die Hexe]{=} ...`, oder?

**Comment by thvitt** [comment]
Dieses `[@stage]` haben wir nie vereinbart, es gibt nur `[@lg]`, da die lgs keine eigenen ns haben. Falls von `<stage n="before_2540_c">` das rend-Attribute entfernt werden soll, könnte man das im XML-Apparat so codieren:

```xml
<f:ins n="before_2540_c" place="attributes">
    <stage rend=""/>
</f:ins>
```

Eine Textform habe ich für diesen Sonderfall IIRC nicht vorgesehen.

**Comment by dietmarpravida** [comment]
versuchen wirs mit `before_2540_b[Die Hexe]{=} ...`

**Comment by dietmarpravida** [comment]
Hat das ] dort was zu suchen?

**Comment by gerritbruening** [comment]
Wo?

**Comment by dietmarpravida** [comment]
Hier (fett): 

-before_2540_c[Die Hexe]{=} <i>vor 2540</i> <i>In S ist</i>**]**  Die Hexe <i>nicht hervorgehoben. [type=1c*]</i>

**Comment by gerritbruening** [comment]
Ach so. Der Eintrag ist in `app1norm.txt` entfallen, stattdessen jetzt
https://github.com/faustedition/faust-gen-html/blob/master/text/app12norm_special-cases.xml#L53

Ich bitte um (zumal inhaltliche) Prüfung.

**Comment by gerritbruening** [comment]
> keine Replik

Wie, nicht? http://dev.faustedition.net/print/faust.9#lbefore_2540_b

**Comment by gerritbruening** [comment]
@thvitt, dieser Link
http://dev.faustedition.net/print/faust.9#app.before_2540_c.diehexe
führt nicht ganz zum Ziel, sondern zum Szenenanfang.

**Comment by dietmarpravida** [comment]
Ich, ich mein, es ist ja keine typische Sprecherangabe. Ich möchte bitte bei meinem alten Text bleiben.

**Comment by thvitt** [comment]
Gerrit:
> @thvitt, dieser Link
> http://dev.faustedition.net/print/faust.9#app.before_2540_c.diehexe
> führt nicht ganz zum Ziel, sondern zum Szenenanfang.

Der Apparat hat überraschenderweise keine ID. Schau ich mir an.

Ist sonst noch was zu tun hier?

**Comment by gerritbruening** [comment]
> keine typische Sprecherangabe

Das verstehe ich nicht, aber hier kannst du das herstellen, was du haben willst:
https://github.com/faustedition/faust-gen-html/edit/master/text/app12norm_special-cases.xml

**Comment by dietmarpravida** [comment]
Ich rede hier immer von S. Und da handelt es sich nicht um eine typische Sprecherangabe, aus welchem Grund auch immer. Daher soll es heißen:

`In S ist Die Hexe nicht hervorgehoben. [Typ 1c*]`

**Comment by dietmarpravida** [comment]
ach egal, lassen wir es, wie es vor meinem Einspruch war.
