### ISSUE TITLE
Encoding of before2293_a

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-gen-html#449]
`before_2293_a[(Sie trinken wiederholt.)]{Sie trinken wiederholt.} vor 2293 Sie trinken wiederholt.]` wird nicht eingefügt. Liegts an Klammern und Punkt in den geschweiften Klammern?

**Comment by gerritbruening** [comment]
Für mich sieht der Eintrag
https://github.com/faustedition/faust-gen-html/blob/master/text/app1norm.txt#L140
im Prinzip OK aus.
Du müsstest bei den Bühnenanweisungen noch Formatvorlagen ergänzen.
@thvitt, hast du noch etwas zu beanstanden, weswegen der Apparateintrag nicht eingefügt wird?

**Comment by thvitt** [comment]
In without-app.xml steht
```xml
                            <stage type="sentence" n="before_2293_a">Sie trinken
                                wiederholt.</stage>
```
also ohne Klammern.

**Comment by dietmarpravida** [comment]
ok

**Comment by gerritbruening** [comment]
Läuft jetzt durch.
Aber, @dietmarpravida, bitte noch die Bühnenanweisungstexte mit der Formatvorlage `stage` versehen.

**Comment by dietmarpravida** [comment]
> Aber, @dietmarpravida, bitte noch die Bühnenanweisungstexte mit der Formatvorlage `stage` versehen.

Vermutlich war das heir die Quelle dafür, dass ich gestern fast meine ganze Datei korrumpiert habe. Was war damit eigentlich gemeint?

**Comment by gerritbruening** [comment]
Es war nur auf diesen einen Fall bezog und hier falsch. Ich war so an die `speaker`-`stage`-Folge gewöhnt, dass ich auch hier `stage` erwartet habe.
