### ISSUE TITLE
Fehlendes Zeichenformat stage

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#453]
` / ` gefolgt von Buchstaben, ` / ` gefolgt von `(`:

- [x] `before^_2260^_b[]{} <i>vor 2260</i> <speaker>Mephistopheles</speaker> / <stage>nimmt den Bohrer</stage> / <stage>zu Frosch</stage> <i>none</i>]<br/><speaker>Mephistopheles</speaker> / nimmt den Bohrer. / Zu Frosch. <i>S</i><br/><speaker>Mephistopheles</speaker> / nimmt den Bohrer / zu Frosch ^^ <i>A</i><br/><speaker>Mephistopheles</speaker> / nimmt den Bohrer. / zu Frosch ^^ <i>D.1</i><br/><speaker>Mephistopheles</speaker> / nimmt den Bohrer. / Zu Frosch. <i>B</i><br/><speaker>Mephistopheles</speaker> / (nimmt den Bohrer, zu Frosch). <i>B.a [type=8]</i>`
- [x] `before^_2263^_b[Frosch]{=} <i>vor 2263</i> <speaker>Altmayer</speaker> / <stage>zu Frosch</stage> <i>none</i>]<br/><speaker>Altmayer</speaker> / zu Frosch. <i>S_</i><br/><speaker>Altmayer</speaker> / zu Frosch^^ <i>A</i><br/><speaker>Altmayer</speaker> / zu Frosch. <i>D.1</i><br/><speaker>Altmayer</speaker> / zu Frosch. <i>B</i><br/><speaker>Altmayer</speaker> / (zu Frosch). <i>B.a [type=8]</i>`
- [x] `before^_2266^_a []{} <i>vor 2266</i> <speaker>Mephistopheles</speaker> / <stage>indem #[2026] bohrt</stage> <i>none</i>]<br/><speaker>Mephistopheles</speaker> / indem <i>#[2026]</i> bohrt. <i>S_</i><br/><speaker>Mephistopheles</speaker>. / (indem <i>#[2026]</i> bohrt.) <i>A</i><br/><speaker>Mephistopheles</speaker> / indem <i>#[2026]</i> bohrt. <i>D.1</i><br/><speaker>Mephistopheles,</speaker> / indem <i>#[2026]</i> bohrt. <i>B</i><br/><speaker>Mephistopheles</speaker> (indem <i>#[2026]</i> bohrt). <i>B.a [type=8]</i>`
- [x] `before^_2270^_a[]{} <i>nach 2269</i> <speaker>Mephistopheles</speaker> / <stage>bohrt, #[2026] verstopft</stage> <i>none</i>]<br/><speaker>Mephistopheles</speaker> / bohrt, <i>#[2026]</i> verstopft. <i>S</i><br/><speaker>Mephistopheles</speaker>. / (bohrt, <i>#[2026]</i> verstopft.) <i>A</i><br/><speaker>Mephistopheles</speaker> / bohrt, <i>#[2026]</i> verstopft. <i>D.1_</i><br/><speaker>Mephistopheles</speaker> / bohrt, <i>#[2026]</i> verstopft. <i>B</i><br/><speaker>Mephistopheles</speaker> / (bohrt, <i>#[2026]</i> verstopft). <i>B.a [type=8]</i>`
- [x] `before^_2274^_a|before^_2274^_b[Siebel|indem sich Mephistopheles seinem Platze nähert]{=} <i>vor 2274</i> <speaker>Siebel</speaker> / <stage>indem #[2026] nähert</stage> <i>none</i>]<br/><speaker>Siebel</speaker> / indem <i>#[2026]</i> nähert. <i>S</i><br/><speaker>Siebel</speaker>. / (indem <i>#[2026]</i> nähert.) <i>A</i><br/><speaker>Siebel</speaker>. / indem <i>#[2026]</i> nähert. <i>D.1</i><br/><speaker>Siebel,</speaker> / indem <i>#[2026]</i> nähert. <i>B</i><br/><speaker>Siebel</speaker> / (indem <i>#[2026]</i> nähert). <i>B.a [type=8]</i>`
- [x] `before^_2291^_a[]{} <i>vor 2291</i> <speaker>Alle</speaker> / <stage>indem #[2026] läuft</stage> <i>none</i>]<br/><speaker>Alle</speaker> / indem <i>#[2026]</i> läuft. <i>S_</i><br/><speaker>Alle</speaker>. / (indem <i>#[2026]</i> läuft)^^  <i>A</i><br/><speaker>Alle</speaker>. / indem <i>#[2026]</i> läuft. <i>D.1</i><br/><speaker>Alle</speaker> / indem <i>#[2026]</i> läuft. <i>B</i><br/><speaker>Alle</speaker> / (indem <i>#[2026]</i> läuft).  <i>B.a [type=8]</i>`
- [x] `before^_2299^_b[]{} <i>vor 2299</i> <speaker>Siebel</speaker> / <stage>trinkt #[2026] Flamme.</stage> <i>S_</i>] <br/><speaker>Siebel</speaker>. / trinkt <i>#[2026]</i> Flamme. <i>A_D.1</i><br/><speaker>Siebel</speaker> / trinkt <i>#[2026]</i> Flamme. <i>B</i><br/><speaker>Siebel</speaker> / (trinkt <i>#[2026]</i> Flamme). <i>B.a [type=8]</i>`
- [x] `before^_2311i^_b[]{} <i>vor 2311</i> <speaker>Altmayer</speaker> / <stage>zieht #[2026] entgegen.</stage> <i>S</i>] <br/><speaker>Altmayer</speaker>. / zieht <i>#[2026]</i> entgegen^^ <i>A_</i><br/><speaker>Altmayer</speaker>. / zieht <i>#[2026]</i> entgegen. <i>D.1</i><br/><speaker>Altmayer</speaker> / zieht <i>#[2026]</i> entgegen. <i>B</i><br/><speaker>Altmayer</speaker> / (zieht <i>#[2026]</i> entgegen). <i>B.a [type=8]</i>`

@dietmarpravida, an Stellen wie diesen:
`<speaker>Mephistopheles</speaker> / nimmt den Bohrer. / Zu Frosch.`
brauchen wir das Zeichenformat `stage` im docx. Die Schrägstriche stören erstmal nicht, wenn fehlender Schrägstrich bedeutet, dass die BA auf derselben Zeile beginnt? So scheint es mir, deswegen bitte
- [x] https://github.com/faustedition/faust-gen-html/commit/560f7255b088de3eabd23634faefe565fae95c62#diff-86da7489d035aef254aa3eb175b90d8fR121 die Hinzufügung von `rend="inline"` prüfen.

**Comment by gerritbruening** [comment]
Für mich später zum Kontrollieren:
*  `/ {&a}`
*  `/ (`
*  `/ <i>`

**Comment by dietmarpravida** [comment]
ich habe auch alle übrigen Passagen aus BAs im Apparat als stage formatiert

**Comment by dietmarpravida** [comment]
> ich habe auch alle übrigen Passagen aus BAs im Apparat als stage formatiert

Das war ein Fehler...

**Comment by gerritbruening** [comment]
Es scheint jetzt noch ein paar Stellen ohne Zeichenformat zu geben:
`before^_2260^_b[]{} <i>vor 2260</i> <speaker>Mephistopheles</speaker> <stage rend="inline">nimmt den Bohrer</stage> / <stage>zu Frosch</stage> <i>none</i>]<br/><speaker>Mephistopheles</speaker> nimmt den Bohrer. / Zu Frosch. <i>S</i><br/><speaker>Mephistopheles</speaker> nimmt den Bohrer^^ / zu Frosch^^ <i>A</i><br/><speaker>Mephistopheles</speaker> nimmt den Bohrer. / zu Frosch^^ <i>D.1</i><br/><speaker>Mephistopheles</speaker> nimmt den Bohrer. / Zu Frosch. <i>B</i><br/><speaker>Mephistopheles</speaker> / (nimmt den Bohrer, zu Frosch). <i>B.a [type=8]</i>`

`before^_2263^_b[Frosch]{=} <i>vor 2263</i> <speaker>Altmayer</speaker> <stage rend="inline">zu Frosch</stage> <i>none</i>]<br/><speaker>Altmayer</speaker> / zu Frosch. <i>S_</i><br/><speaker>Altmayer</speaker> zu Frosch^^ <i>A</i><br/><speaker>Altmayer</speaker> zu Frosch. <i>D.1</i><br/><speaker>Altmayer</speaker> zu Frosch. <i>B</i><br/><speaker>Altmayer</speaker> (zu Frosch). <i>B.a [type=8]</i>`

`before^_2266^_a []{} <i>vor 2266</i> <speaker>Mephistopheles</speaker> <stage rend="inline">indem #[2026] bohrt</stage> <i>none</i>]<br/><speaker>Mephistopheles</speaker> / indem <i>#[2026]</i> bohrt. <i>S_</i><br/><speaker>Mephistopheles</speaker>. / (indem <i>#[2026]</i> bohrt.) <i>A</i><br/><speaker>Mephistopheles.</speaker> / indem <i>#[2026]</i> bohrt. <i>D.1</i><br/><speaker>Mephistopheles,</speaker> / indem <i>#[2026]</i> bohrt. <i>B</i><br/><speaker>Mephistopheles</speaker> / (indem <i>#[2026]</i> bohrt). <i>B.a [type=8]</i>`

**Comment by dietmarpravida** [comment]
erledigt; die Word-Anzeige der Formatvorlagen ist ziemlich missverständlich, wie ich gerade feststelle: Es genügt nicht, dass das Feld bunt umrandet ist, es muss auch intensiv leuchten

**Comment by dietmarpravida** [comment]
Sol eigentlich so kodiert werden:

MEPHIſTOPHELES `<speaker>`nimmt den Bohrer.`</speaker>` / `<speaker>`Zu Froſch.`</speaker>`

Oder so: 

MEPHIſTOPHELES `<speaker>`nimmt den Bohrer. / Zu Froſch.`</speaker>`

**Comment by dietmarpravida** [comment]
> ich habe auch alle übrigen Passagen aus BAs im Apparat als stage formatiert

zurückgenommen

**Comment by dietmarpravida** [comment]
@gerritbruening ?

**Comment by gerritbruening** [comment]
Ja?

**Comment by dietmarpravida** [comment]
let me repeat the question for you

(quote:)

@gerritbruening Soll eigentlich so kodiert werden:

MEPHIſTOPHELES `<stage>`nimmt den Bohrer.`</stage>` / `<stage>`Zu Froſch.`</stage>`

Oder so: 

MEPHIſTOPHELES `<stage>`nimmt den Bohrer. / Zu Froſch.`</stage>`

(close quote)

**Comment by gerritbruening** [comment]
Mit zweimaligem Format stage, und dazwischen dann der Schrägstrich. Denn ich war bislang davon ausgegangen, dass es zwei Bühnenanweisungen sind, und nicht nur eine.

**Comment by dietmarpravida** [comment]
oaky, so müsste es auch in der Datei sein. Testen wirs bei nächster Pushung.

**Comment by gerritbruening** [comment]
@dietmarpravida, kann das hier geclosed werden?
