### ISSUE TITLE
Lesetext validieren

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#455]
Muss kurz vor Übergabe noch mal drübergeschaut werden.

**Comment by dietmarpravida** [comment]
Ich sehe da (bei F-I) nur noch Meldungen, denen ich mit meinen Mitteln nicht mehr abhelfen zu können glaube

**Comment by gerritbruening** [comment]
@dietmarpravida, ich sehe jetzt noch das hier:

<table><th>@n</th><th>[replace]</th><th>{insert}</th><th>Vers</th><tr data-case="dangling"><td>l2709a</td><td></td><td></td><td>Und hier!</td></tr><tr data-case="dangling"><td>l2709b</td><td></td><td></td><td>Und hier!</td></tr><tr data-case="dangling"><td>before_11350_a</td><td>und die</td><td>und die</td><td></td></tr></table>

(also den oberen Fall)
Wenn du nicht weiterweißt, @thvitt fragen.

**Comment by dietmarpravida** [comment]
Ist das nicht auch in der Sonderdatei, wo war die nochmal?

11350 ist F-II

**Comment by gerritbruening** [comment]
OK, das hieße:
https://github.com/faustedition/faust-gen-html/commit/ab269ea3486cc86e1e7fbd61d6cc7e641a9ed443
Die lange Version steht noch im grünen Kommentar.

**Comment by dietmarpravida** [comment]
danke, ich möchte im Apparat auf langen Text generell gern verzichten, wie ist das bei Faust II? (Nebenbei: Kann ich diesen Text eigentlich auch mal sehen?)

**Comment by gerritbruening** [comment]
Welchen Text? Den der Apparateinträge zum Faust II?
Der steht in der letzten PDF, zumindest so halbwegs.

**Comment by gerritbruening** [comment]
@dietmarpravida, die Lesetextvalidierung gibt einige Meldungen des Typs
`WARNING:parse_readings: Failed to parse »Zimmer,« as lem`
aus.
Da fehlt IMHO das _none_.

**Comment by dietmarpravida** [comment]
soll auch bei 

`852[]{} 852–859] Die Verse sind in allen Drucken nicht eingerückt; in faust://bibliography/Q wurden sie ebenso wie die Verse 949–980 eingerückt. [Typ 7]`

ein _none_ hin?

**Comment by dietmarpravida** [comment]
Bei

`INFO:parse_app2norm: Parsed: 3620[ich]{ich so} <i>3620</i>] so <i>1_H.5 1_H.12 fehlt A D.1</i>  so <i>B B.a [type=2a Typ 4b]</i> 
WARNING:parse_readings: Failed to parse »« as lem`

muss es eine andere Feherquelle sein?

Kodiert ist

`3620[ich]{ich so} 3620 ſo] H5 H12	fehlt A D1 	ſo B Ba [Typ 2a Typ 4b] `

**Comment by thvitt** [comment]
- `WARNING:parse_readings: Failed to parse »« as lem` ist genau dann kein Problem, wenn der vorherige Eintrag (wie z.B. 852) kein Lemma hat.
- Fälle wie dieser hier müssen mit der artifiziellen Lemmasigle _none_ vor der Lemmaklammer codiert werden. Falsch:
```
INFO:parse_app2norm: Parsed: 3567[Ward’]{Ward} <i>3567</i> Ward] Ward <i>1_H.5 S</i>  Ward’ <i>A B B.a 1_H.1</i> Ward <i>C.1_12 C.3_12 [type=1b]</i>
WARNING:parse_readings: Failed to parse »Ward« as lem
``` 
Richtig:
```
INFO:parse_app2norm: Parsed: before_3544_b[Lieschen]{=} <i>vor 3544</i> <speaker>Lieschen</speaker> <i>none</i>] <speaker>Lieschen^</speaker> <i>S</i> <speaker>Liesgen^</speaker> <i>1_H.5</i> <speaker>Lieschen.</speaker> <i>A D.1</i> <speaker>Lieschen^</speaker> <i>B B.a [type=8]</i>
```
- zu 3620: du schreibst, codiert sei:
`3620[ich]{ich so} 3620 ſo] H5 H12 fehlt A D1 ſo B Ba [Typ 2a Typ 4b]`
das ist aber nicht bei Dateien der Fall, die ich zu gesicht bekomme, da steht 
`3620[ich]{ich so} <i>3620</i>] so <i>1_H.5 1_H.12 fehlt A D.1</i>  so <i>B B.a [type=2a Typ 4b]</i>`
was in mehrerley hinsicht falsch ist (mindestens fehlendes _none_, `so` nach statt vor der Lemmaklammer und doppelte Typzuweisung)

**Comment by dietmarpravida** [comment]
danke, dann habe ich zwischenzeitlich getan, was in diesem Fall zu tun war

**Comment by dietmarpravida** [comment]
fehlendes _none_ wohl nicht, es kommt hier ja keins; wohl ein Sonderfall, @gerritbruening

**Comment by gerritbruening** [comment]
Ich würde sagen, dem Restbestand an Problemen wenden wir uns nach der baldigen Umstellung auf XML zu.

**Comment by gerritbruening** [comment]
Bleibt einzig noch das hier:

@n | [replace] | {insert} | Vers
-- | -- | -- | --
l2709a |   |   | Und hier!
l2709b |   |   | Und hier!

Ist hier was im XML zu fixen, @thvitt?

**Comment by thvitt** [comment]
Sieht [das](http://dev.faustedition.net/print/faust.11#l2709) so aus wie es sollte? Dann ist das wohl ok und nur ein Artefakt der validierung

**Comment by dietmarpravida** [comment]
ja, sieht so aus, wie es sich gehört
