### ISSUE TITLE
Prosa EB, Prosa LB

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#457]
Was ist das?

**Comment by markusciupke** [comment]
Vgl. #399 :

Hier kommt nun ein Umbruch von TTF entsprechend der in #268 geführten Diskussion: Umbruch möglichst eng an A8 bzw. der Online-Version, aber nicht sklavisch, wenn das Vorteile für Trennungen hat (mehrfach) oder für Wortabstände (einmal: Zeile 21/22). Auch nach den Trennungen von B9 habe ich mich, wo möglich, gerichtet:
TTF.pdf

Technisch habe ich folgendes gemacht:
– Der Satzspiegel ist rechts und links um jeweils 2mm schmaler gemacht (113 mm statt 117 mm)
– Die Pagina ist entsprechend um 2 mm nach innen gerückt
– Hinter jede Sprechzeile habe ich einen Absatz eingefügt (harter Absatz)
– Liegt eine Trennung am Ende einer Zeile, habe ich einen Trennungsstrich (= Bindestrich) eingefügt.
**– Ein neues Absatzformat mit dem Namen Prosa EB ist definiert (EB = Erzwungener Absatz)
– Ein neues Absatzformat mit dem Namen Prosa LB ist definiert (LB = Linksbündig)
– Alle Sprechzeilen einer Replik, außer der letzten, haben das Format Prosa EB erhalten
– Die letzte Sprechzeile einer Replik hat das Format Prosa LB erhalten
– Hat eine Replik nur eine Zeile ist das die letzte Sprechzeile mit dem Format Prosa LB**
– Vor jeden Absatz (= Sprechzeile) habe ich zwei Tabs eingefügt (wie bei Vers auf 19mm und 23 mm)
– In jede fünfte Zeile habe ich nach dem ersten, rechtsbündigen Tab den Zeilenzähler eingefügt

Das Ergebnis seht ihr in der beigegebenen PDF-Datei.

Wenn ihr diesen Umbruch gutheißt, müssen in XML praktisch nur die Absätze, die Trennungsstriche und der Zeilenzähler vorbereitet werden. Dann müssen die richtigen Absatzformate zugewiesen werden (die beiden neuen Absatzformate ersetzen das alte Absatzformat Prosa). Ich muss dann nach der Konvertierung in IDML nur noch den Satzspiegel um 4 mm schmaler machen und die Pagina um 2mm nach innen rücken, und TTF sieht aus wie die obige PDF-Datei.

Ich bitte um Rückmeldung.

**Comment by gerritbruening** [comment]
Alles klar, danke!
