### ISSUE TITLE
App Strich mit umgebenden Leerzeichen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#458]
Eins der Zeichenformate im Apparat.

Wo soll der | nun eigentlich hin?

Betroffen sind für allem die Typ VIIIer, aber sollen die nicht mit Zeilenumbrüchen gesetzt werden?

**Comment by markusciupke** [comment]
Immer dort, wo Zitate im Apparat nicht umbrochen werden. Ich hatte da ja schon verschiedene Tests zum Vergleich gemacht. Bei Typ VIII würde ein Zeilenumbruch sehr viel Platz benötigen, zumal im Anhang. Hier scheint es mir richtig, die Zeilenumbrüche durch » | « wiederzugeben.

Und: Stellt euch vor, eine Szene passt nur wegen eines umbrochenen Zitats im Apparat so gerade nicht auf eine Seite und endet so, dass lediglich 3 bis 4 Verse oder eine BA auf einer neuen Seite zu stehen kommen. Dann könntet ihr euch aus gestalterischen Gründen dafür entscheiden, dieses Zitat im Apparat nicht zu umbrechen, sondern die » | « zu nutzen. Dann wäre das richtige Zeichenformat dafür schon da und die Szene würde schön auf einer gefüllten Seite enden. – Nur gesetzt den Fall.

**Comment by dietmarpravida** [comment]
Dasa Problem ist, dass man den Apparat ohne Zeilenumbruch nicht leicht versteht, während er bei Zeilenumbruch sogleich einleuchtet. Ohne ihn schaffen wir eine gute alte Variantenhalde. In diesem Fall sollten dann die ganzen Apparateinträge aber lieber gleich ganz anders formuliert werden.

**Comment by markusciupke** [comment]
Typ VIII muss man mal als ganzes ausprobieren, aber das hat ja noch etwas Zeit. Im Apparat auf den Textseiten empfinde ich das jedenfalls nicht so. Da würde nach meiner Ansicht auch die Variante mit » | « gut aussehen.
[App 3787-3788.pdf](https://github.com/faustedition/faust-gen-html/files/2005563/App.3787-3788.pdf)

**Comment by markusciupke** [comment]
Inwiefern  funktioniert die erste Seite überhaupt nicht? So ist der Apparat jedenfalls in der Apparateliste angeordnet. – Was soll ich wie ändern? Ich probiere gerne Alternativen aus.

**Comment by dietmarpravida** [comment]
Ich verstehe die Frage nicht so recht. Der Apparat ist so für den Leser unverständlich. Und die Sigle darf nicht so einfach vor der Lesart stehen, schon gar nicht, wenn sie ganz allein und ohne begleitenden motivierenden Text ist. Seite 2 ist okay, warum können wir es nicht so lassen? Andernfalls müsste Editortext generiert werden, der die abweichende Anordnung irgendiwe motiviert, und das möchte ich vermeiden.

**Comment by markusciupke** [comment]
Ich bin ja auch für Seite 2, deswegen habe ich sie ja gemacht. Für Seite 1 habe ich den Text aus der Online-Apparat-Liste kopiert und mit den richtigen Formaten versehen. Das ist ja für mich die Vorgabe, an der ich erstmal nichts ändern soll/darf. Aber gefallen tut mir das auch nicht.

**Comment by dietmarpravida** [comment]
Was ist denn eigentlich die Frage? War Seite 2 kein Vorschlag?

**Comment by markusciupke** [comment]
Doch klar. Hab ich doch gerade geschrieben!
> Ich bin ja auch für Seite 2, deswegen habe ich sie ja gemacht.

**Comment by markusciupke** [comment]
Was meinst du mit »über Bande«? Das ist doch das Prinzip von GitHub, oder? Inwiefern ist 3787 f. ein Sonderfall? Und was meinst du mit negativem Apparat? Ist es vielleicht gut, kurz mal zu telefonieren? Ich bin an meinem Platz.

**Comment by dietmarpravida** [comment]
3787-3788 ist firstproof

Die Typ 8-Bühnenanweisungen-Lesarten, die in die pdf geraten sind, fand ich tatsächllich auch bei inline-Satz lesbar, wir können das also eventuell doch so machen.

**Comment by dietmarpravida** [comment]
nein

**Comment by markusciupke** [comment]
Vielleicht ein, zwei Sätze mehr? Was bedeutet »firstproof«? Was meinst du dann mit

> Die Typ 8-Bühnenanweisungen-Lesarten, die in die pdf geraten sind, fand ich tatsächllich auch bei inline-Satz lesbar, wir können das also eventuell doch so machen.

?

**Comment by dietmarpravida** [comment]
firstproof heißt in diesem Zusammenhang, glaube ich, Feinsatz

Typ 8 sollen am Ende stehen, aber nicht notwendig mit so großzügiger Typographie wie ursprünglich vorgesehen, sondern eventuell auch etwas platzsparender

**Comment by markusciupke** [comment]
Danke! – Mache ich. – Kann das dann hier geschlossen werden?

**Comment by dietmarpravida** [comment]
es ist anscheinend noch offen, wie App Strich mit umgebenden Leerzeichen prozessiert wird, lassen wirs vorläufig noch offen

**Comment by gerritbruening** [comment]
Ich verschiebe das mal auf firstproof.

**Comment by markusciupke** [comment]
@dietmarpravida schrieb:
> Seite 2 ist okay, warum können wir es nicht so lassen?

Ich habe den Apparat zu 3787-3788 nun so eingerichtet wie auf Seite 2 meines Vorschlags. Die Einrichtung in der IDML-Datei habe ich ignoriert.

**Comment by markusciupke** [comment]
Alle | sind jetzt korrekt formatiert. Kann geschlossen werden.
