### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#459]
first bad commit: [6b81fd7ec392432d98fa7d38de31b2f445cfe013] Update special-cases (before_2465_a)

> ERROR: file:/var/www/faust-gen/target/xproc/xslt/text-insert-app.xsl:262:err:XTTE0570:An empty sequence is not allowed as the value of variable $current-replace

**Comment by thvitt** [comment]
@gerritbruening, was möchtest Du uns hiermit sagen?

https://github.com/faustedition/faust-gen-html/blob/6b81fd7ec392432d98fa7d38de31b2f445cfe013/text/app12norm_special-cases.xml#L26-L29

**Comment by gerritbruening** [comment]
> @gerritbruening, was möchtest Du uns hiermit sagen?

https://github.com/faustedition/xml/issues/346#issuecomment-389127819
