### ISSUE TITLE
Zeichenformate Hochgestellt, Versalziffer ...

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#460]
Die Zeichenformate 
* Hochgestellt
* Versalziffer recte

puzzeln mich.

In welchen Kontexten können diese Zeichenformate vorkommen? Warum wird nicht alles von `Versalziffer kursiv hoch` abgedeckt?

**Comment by markusciupke** [comment]
Bislang kommt es gar nicht vor. Ich hab es wohl eingerichtet, als ich noch nicht wusste, dass die hochgestellten Ziffern bei Siglen kursiv hochgestellt sein würden.

**Comment by gerritbruening** [comment]
> es 

also beide?

**Comment by markusciupke** [comment]
Versalziffern werden z.B. bei den Greifen und den Choretiden vorkommen.
Wofür stehen die drei Pünktchen?

**Comment by gerritbruening** [comment]
Warum sollen die eben genannten Fälle nicht mit mediävalziffern gesetzt werden?

**Comment by markusciupke** [comment]
Ich habe in Erinnerung, dass du dort die Medievalziffern nicht schön findest. Jedenfalls finde ich sie nicht schön. Das können wir uns noch im Vergleich ansehen und dann entscheiden, ob wir dieses Zeichenformat brauchen oder nicht.

**Comment by gerritbruening** [comment]
> dass du **dort** die Medievalziffern nicht schön findest

dort heißt für mich: als hochgestellte Siglenziffern. Da fand ich Mediävalziffern nicht optimal. Aber bei Vers-, Seiten- und sonstigen Zahlen habe ich nichts gegen sie.
