### ISSUE TITLE
correct target for ] after </i> in 3978

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-gen-html#462]
`INFO:parse_app2norm: Parsed: before_3978[Halbes]{halbes} <i>vor 3978</i> <speaker>Hexenmeister</speaker> <stage rend="inline">halbes Chor.</stage> <i>none</i> <i>1_H.14</i>]   <speaker>Hexenmeister.</speaker> <stage rend="inline">Halbes Chor.</stage>  <i>A B 1_H.1 C.1_12 C.3_12</i> <speaker>Hexenmeister.</speaker> <stage rend="inline">(Halbes Chor.)</stage> <i>B.a [type=8]</i>`

`ERROR:parse_app2norm: Lemma section »<speaker>Hexenmeister</speaker> <stage rend="inline">halbes Chor.</stage> <i>none</i> <i>1_H.14</i>« parses to 2 lemmas instead of one`

Seems to be an new kind of error, can't recall having hit upon it before. It had better read `<i>none</i>] <i>1_H.14</i>`

**Comment by gerritbruening** [comment]
`<i>none</i> <i>1_H.14</i>]`
`<i>none</i>] <i>1_H.14</i>`
@thvitt, ist eins davon erlaubt? Sieht für mich beides problematisch aus.

**Comment by thvitt** [comment]
Der aufrechte Teil ist der Trenner → `<i>none 1_H.14</i>]`.

**Comment by dietmarpravida** [comment]
das heißt, es wäre richtig so, wie es ist. Woher aber die Fehermeldung?

**Comment by thvitt** [comment]
Nein, der Fehlermeldung zufolge steht da jetzt `<i>none</i> <i>1_H.14</i>]` und nicht `<i>none 1_H.14</i>]`. Da der Wechsel zwischen kursiv und aufrecht bei euch Feldtrenner ist, führt das aufrechte Leerzeichen zum Fehler

**Comment by dietmarpravida** [comment]
Hm, dann ist das kein Probem, das ich lösen kann.

**Comment by gerritbruening** [comment]
Was soll denn nun geschehen?

**Comment by dietmarpravida** [comment]
Was für ein txt?

`<i>vor 3978</i> HEXENMEISTER halbes Chor] <i>H14</i>  HEXENMEISTER. Halbes Chor.  <i>A B H1 C1 C3</i> 	HEXENMEISTER. (Halbes Chor.) <i>Ba</i> <i>[Typ 8]</i>`
