### ISSUE TITLE
app zu 359

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#463]
http://dev.faustedition.net/print/faust.4#l359

_A fehlt_ müsste doch ein eigenes Reading sein? Falls ja ließe sich das vermutlich durch einfügen eines aufrechten Leerzeichens vor dem _fehlt_ erreichen.

**Comment by gerritbruening** [comment]
Das recte Leerzeichen muss ein geschütztes sein.

**Comment by dietmarpravida** [comment]
ok

**Comment by gerritbruening** [comment]
Jetzt scheint hier ein aufrechtes Lz zu viel zu sein:
`<i>fehlt</i> <i>A</i>`
