### ISSUE TITLE
Handling of C.2α_4 and witnesses with : 

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#464]
Example:

                                        <rdg wit="faust://document/faustedition/C.3_4"
                                            type="type_4a">nannt’ <note>C.2α_4 <wit
                                                  wit="faust://document/faustedition/C.3_4">C<hi
                                                  rend="superscript">3</hi> 4</wit></note></rdg>

Or is there something wrong in the input data?

Same applies to idnos like `2_III_H.3a:1`.

**Comment by thvitt** [comment]
C.2alpha_4
2_III_H.3a_1

1. Griechische Buchstaben werden ausgeschrieben.
2. Alles, was weder A-Z a-z 0-9 noch `.` oder `-` ist, wird durch `_` ersetzt.

**Comment by gerritbruening** [comment]
Und das soll schon im txt-Input so sein?

**Comment by thvitt** [comment]
ich glaube, im txt wird auch α und : akzeptiert, zumindest habe ich grad Normalisierungscode im Python gesehen.

**Comment by gerritbruening** [comment]
OK, assigne mich, wenn ich im txt-Input was beheben soll.

**Comment by thvitt** [comment]
hast du jetzt irgendwo ein Problem gesehen oder ist das eine theoretische Diskussion?

**Comment by thvitt** [comment]
Das ist hier, oder?
```xml
  <!--       9009[nannt]{=} <i>9009</i> nannt <i>C.1_4</i>] nannt’ <i>C.2α_4 C.3_4 [type=4a]</i>-->
  <app>
    <f:replace n="9009">nannt</f:replace>
    <f:ins n="9009">nannt</f:ins>
    <ref>9009</ref>
    <lem wit="C.1_4">nannt <note><wit>C.1_4</wit></note></lem>
    <rdg wit="C.2alpha_4 C.3_4" type="type_4a">nannt’ <note><wit>C.2alpha_4</wit> <wit>C.3_4</wit></note></rdg>
  </app>
```
Wird mittlerweile erkannt.

**Comment by gerritbruening** [comment]
Auch schon in der aktuellen faust.xml, oder dauert das noch ein paar Minuten?

**Comment by thvitt** [comment]
build ist schon länger durch. Du siehst [auf der Build-Seite](http://dev.digital-humanities.de/ci/view/Faust/job/faust-gen-fast/) links unten unter Build-Verlauf ob da grade noch was läuft und wann der letzte Build war.

**Comment by thvitt** [comment]
wieso nur im Build und nicht bei mir? Das macht kein Sinn
