### ISSUE TITLE
quote/sp

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#465]
`quote/sp` führt zu einzelnen Absätzen für `speaker` und `l`, obwohl `quote`-Inhalt sonst fortlaufend gesetzt wird.

**Comment by dietmarpravida** [comment]
nixverstehn

**Comment by gerritbruening** [comment]
Wenn du Oxygen hast, faust.xml öffnest und oben links //quote/sp einträgst, kriegst du die Fälle.

**Comment by dietmarpravida** [comment]
Und was wäre hier dann zu tun? Manuell?

**Comment by gerritbruening** [comment]
Betrifft nur 3550 / 3551. Das ist ja wohl geklärt, nicht? Sonst reopen.
