### ISSUE TITLE
Verszahl in Apparaten

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#466]
Die soll wohl manchmal, aber nicht immer mit ausgegeben werden.
Könntet ihr für Faust I da eine Regel ersinnen?

**Comment by dietmarpravida** [comment]
In Frage kommen (sauf omission) maximal die folgenden Fälle:
- ((2709)): 

> `2709] Die Vershälften bilden in H5 und S einen umbrochenen Vers, in A B Ba sind es zwei Verse; wie bei 3994–3995 (zwei Verse in B H1 C1 C3, ein Vers in H14 A Ba) ist von einem Satzfehler auszugehen. [Typ 2a]`

- ((3184)): 

> `3184] In H5 S A B Ba handelt es sich um zwei Verse, sie wurden erst von faust://bibliography/duentzer1882a#Düntzer und dann von faust://bibliography/wa_I_14#Erich Schmidt zu einem antilabischen Vers zusammengefasst. [Typ 3*]`

- 3356–3357:

> `3356–3357] In H5 handelt es sich um zwei Verse, in S wurde daraus durch Versehen des Abschreibers oder des Setzers nur ein Vers: Und ich, der Gottverhaßte, hatte nicht genug, (…). [Typ 2b] `

- 3550–3551:

> `3550–3551] In H5 bilden 3550–3551 einen antilabischen Vers: GRETGEN Ach / LIESGEN Ja so ist’s ihr endlich gangen. [Typ 2d*]`

 
- 3787–3788:

> `3787–3788] <l>Beteſt du für deiner Mutter Seel</l> <l>Die durch dich sich in die Pein hinüberschlief.</l> H5 [Typ 2b*] `

- 4051:

> `4051] <sp><speaker>Faust.</speaker><l n=4051_I>Verflucht Geſchnarr!</l></sp><sp><speaker>Mephistopheles.</l></speaker><l n=4051_F>Man muß ſich dran gewöhnen.</l></sp> konj faust://bibliography/resenhoefft1975 #Resenhöfft [Typ 3*] `

- 4335–4342:

> `vor 4343] In H1 C1 C3 folgen die (ganz oder teilweise auch in H16 und H17 enthaltenen) Verse 4335–4342 (hier wiedergegeben nach H1) [Typ 5*]: <sp><speaker>Tanzmeister.</speaker><l n="4335">Wie jeder doch die Beine lupft! </l> <l n="4336">Sich wie er kann herauszieht!</l> <l n="4337">Der Krumme springt, der Plumpe hupft</l> <l n="4338">Und fragt nicht wie es aussieht.</l><sp><sp></speaker>Fideler.</speaker><l n="4339">Das haßt sich schwer das Lumpenpack</l> <l n="4340">Und gäb sich gern das Restchen;</l> <l n="4341">Es eint sie hier der Dudelsack</l> <l n="4342">Wie Orpheus Leyer die Bestjen.</l><sp>`

 
Wozu bedarf es da einer Regel? Kann man das nicht in den einzelenen Fällen vorgeben? Wirklich nötig sind die Verszahlen wohl nur bei 4335-4342.

**Comment by markusciupke** [comment]
Ich unterwerfe mich dem Votum von @dietmarpravida

**Comment by dietmarpravida** [comment]
@gerritbruening Gibt es dafür Fälle in Fust II, die ich berücksichtigen muss?

(Übrigens: der nächste, der "Ich unterwerfe mich dem Votum von @dp*" schreibt, muss fünf Euro  ins Sparschwein einzahlen.)

**Comment by gerritbruening** [comment]
Nein, zum Faust II denke ich mir dann was aus.

**Comment by dietmarpravida** [comment]
Machen wir in der ersten Fahne

**Comment by markusciupke** [comment]
Ist nach meiner Ansicht alles gemacht.

**Comment by gerritbruening** [comment]
@dietmarpravida, auch für dich erledigt? Dann closen.
