### ISSUE TITLE
statt T_5_H.1 steht im app1norm.txt T_5_1_H.1

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-gen-html#471]
zu 759 wird die Handschrift T_5_H.1 aufgeführt. Soweit ich weiß gibt es dazu noch keine Umsetzung, damit sie im Apparat online in einer Form wie die anderen Sigle as T 5 H1 (mit hochgestelllter 1) dargestellt wird.

**Comment by thvitt** [comment]
Müsste eigentlich. Allerdings steht im Apparat (fälschlich?) `T_5_1_H.1`, das wird gar nicht als Sigle erkannt.

**Comment by dietmarpravida** [comment]
taatsächlich? weißt du, warum, @gerritbruening 

http://dev.faustedition.net/document?sigil=T_5_H.1&page=1&view=structure
