### ISSUE TITLE
Typennummer

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#476]
https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#typ

**Comment by thvitt** [comment]
ist im faust.xml bereits direkt umsetzbar codiert:

```xml
<note type="type"><ref target="faust://app/type_2c">(II c)</ref></note>
```

Zwischen `II` und `c` steht z.Z. ein U+202F NARROW NO-BREAK SPACE, wenn da was anderes hineinsoll möge man mir das sagen

**Comment by gerritbruening** [comment]
> Zwischen `II` und `c` steht z.Z. ein U+202F NARROW NO-BREAK SPACE

Da scheint mir für online gut, wenn auch vielleicht nicht unbedingt nötig. Es behindert ein bisschen das Suchen von Typen mit strg-f.
Im IDML-Ergebnis wird ein 24stel-Geviert gewünscht.

**Comment by thvitt** [comment]
[Es scheint so zu sein](http://www.absatzsetzer.de/downloads/Zeichen.pdf), dass dies in Indesign dem U+200A HAIR SPACE entspricht. Wieder was gelernt …

**Comment by gerritbruening** [comment]
Findest du denn, dass wir online so feine Abstände dieser Art brauchen?
Ich hatte daran gar nicht gedacht und stattdessen Philipp erklärt, wo ein 24stelgeviert einzufügen wäre.

**Comment by thvitt** [comment]
Wenn du mich so fragst, denke ich, wenn wir die Typnummer eh schon formatiert ins faust.xml schreiben, statt das nur in der HTML-Generierung zu machen (#429), dann können wir auch gleich das richtige Leerzeichen reinpappen und müssen’s nicht in den Folgetransformationen doch noch mal umschrauben.

(Praktisch war mir als Typografielaie nicht klar, dass ein 1/24-Geviert ein stehender Begriff ist: bei der geringen Breite hätte ich eher einen Bindehemmer erwartet oder so)

**Comment by markusciupke** [comment]
Das 1/24-Geviert ist zwar klein, aber es macht doch einen Unterschied. Er gibt den Typen mit a, b, c-Zählung eine kleine, aber feine Struktur, die sichtbar ist. Und ich finde es so besser als ohne.

**Comment by pglatza** [comment]
Gut, ich sehe, dass das 1/24-Geviert in der aktuellen Lesetext-XML-Datei eingesetzt worden ist.
Sollen dennoch vor einer schließenden runden Klammer diese haarfeinen Abstände stehen? Es findet sich z.B.:  `<ref target="faust://app/type_7">(VII )</ref>`

**Comment by gerritbruening** [comment]
Das ist ein Fehler.
Der Abstand wird offenbar eingefügt ohne Rücksicht darauf, ob ein Buchstabe folgt, der dadurch abgetrennt werden soll. Vor der Klammer kann der Abstand einfach entfallen.

**Comment by thvitt** [comment]
so, überflüssiger vorklammerhairspace is wech in faust.xml

**Comment by gerritbruening** [comment]
Umso besser, danke!
Bei dieser Gelegenheit bemerke ich, dass **vor** der öffnenden Klammer `(III*` der whitespace fehlt, z.B. http://dev.faustedition.net/print/faust.all#l719.

**Comment by gerritbruening** [comment]
Nehme das aus label:idml raus, verbleibendes Problem besteht nur online.

**Comment by thvitt** [comment]
ich sehe das Problem online nicht mehr, dürfte der Effekt von #495 sein
