### ISSUE TITLE
Mehrfache Lemmaklammern

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#477]
Bsp.:
![grafik](https://user-images.githubusercontent.com/10358005/40610191-abd7bb1c-6271-11e8-8afa-f5658a132a65.png)

Scheinen zu entstehen, wenn `lem` außer `text()`- noch element content hat (hier `pc` bzw. `gap`).

**Comment by pglatza** [comment]
Setze mich gleich dran. Das könnte voraussichtlich meine letzte Anpassung für `milestone:msfausti` sein. Danach könnte @markusciupke eigenständig arbeiten?!

**Comment by gerritbruening** [comment]
> soll nach dem Ende des `lem`-Elementes oder nach dem Lemma selbst sein (sprich nur das allererste Wort im Element `lem`)?

Danke, jetzt verstehe ich das Problem.
```xml
<lem wit="faust://document/faustedition/A">Schaaren<pc>‸</pc> <wit f:is-base="true" wit="faust://document/faustedition/A">A</wit></lem>
                                           ******************
```

Zum Lemma in diesem Sinne gehört alles _bis vor das_ `wit` Element. Das `wit` Element selbst gehört nicht mehr dazu. Die Klammer müsste also zwischen dem vorherigen `lem` Inhalt und dem nachfolgen `wit` zu stehen kommen:
> Schaaren‸] _A_

**Comment by pglatza** [comment]
Ist `wit` immer die Begrenzung oder gibt es noch andere Elemente?
Für `lem` ohne Kindelemente bleibt alles beim alten: hier würde die eckige Klammer stets am Ende/danach eingefügt.

**Comment by gerritbruening** [comment]
Danke für die Nachfrage, ich habe jetzt nochmal [deine Doku abgerufen](https://transpect.le-tex.de/data/docxml/gui/faust.xml/out/faust.docxml.xhtml#ei_lem).
Es gibt noch `lem/note/wit` statt einfach `lem/wit`, aber in `note` steht dann nur `wit`, also dürfte (oder müsste) `note` für die Lemmaklammer ignoriert werden.
HTH.

**Comment by pglatza** [comment]
Ok, danke. Habe das Upload-Formular aktualisiert (ich gebe ab nun zur Sicherheit Revisionsnummern dazu, hätte ich durchgehend machen können: _r66_).

**Comment by pglatza** [comment]
Nachbesserung hierzu in r67 (ist live). Die `note[wit]` wurde noch nicht richtig berücksichtigt, hatte https://github.com/faustedition/faust-gen-html/issues/477#issuecomment-393784877 missverstanden.

**Comment by gerritbruening** [comment]
![grafik](https://user-images.githubusercontent.com/10358005/40828794-e3817e3c-6581-11e8-9a4a-6e146d6d11a4.png)

Kann man irgendwie abfragen, ob sowas hier noch öfter stehen geblieben ist?

**Comment by gerritbruening** [comment]
Oder ist das genau das?

**Comment by pglatza** [comment]
Korrekt. Das wurde mit r67 behoben.
