### ISSUE TITLE
Spurious &#x2028;

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#479]
Example:
![grafik](https://user-images.githubusercontent.com/10358005/40610831-26d11e10-6274-11e8-8a48-a8187fd892c5.png)

In the IDML result I see

```xml
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Kursiv">
                     <Content>H</Content>
                  </CharacterStyleRange>
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
                     <Content> </Content>
                  </CharacterStyleRange>
                  <CharacterStyleRange>
                     <Content>&#x2028;</Content>
                  </CharacterStyleRange>
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/(Ohne) Teil">
                     <Content>Faust.</Content>
                  </CharacterStyleRange>
```

Where does this `&#x2028;` come from?

**Comment by pglatza** [comment]
The line-break (`&#x2028;`) is inserted for every `head`-element in a textcrit-note.
I am sorry for asking late: how should the `head` element formatted? No line-break? Whitespace before/after?

**Comment by gerritbruening** [comment]
I am sorry that I did not look into the source data before creating this issue. Now fixed in the data, no `head` anymore.
