### ISSUE TITLE
Leerzeichen nach caret

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#480]
![grafik](https://user-images.githubusercontent.com/10358005/40611976-ea6aa608-6278-11e8-8bc8-2d19de6cc08c.png)

@markusciupke, der Abstand zwischen dem `Ich^` und dem folgenden `I&nbsp;H0a` sieht irgendwie schmal aus. Im IDML output sehe ich keinen Unterschied.
Ist das Leerzeichen hier schmaler oder sieht das nur für mich so aus?

**Comment by markusciupke** [comment]
Es ist ein ganz normales Leerzeichen. Wenn der Abstand nach Caret generell zu eng sein sollte, könnte ich immer ein Achtelgeviert eintauschen. Ich probiers im nächsten Gang mal aus.

**Comment by markusciupke** [comment]
Ich glaube das hier kann geschlossen werden, weil wir das Caret in #275 weiter diskutieren.
