### ISSUE TITLE
subst/del and subst/add handling

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#481]
`subst/*` is handled almost perfectly, although I forgot to mention it in the `idml.md`. Thanks for this, @pglatza!
However,
* `subst/del` seems to be dropped
* the _:_ should have spacing after it
* _:_ should not be inserted after _bis_
* `subst/wit` seems to be dropped

**Comment by gerritbruening** [comment]
Note that this relevant vor Faust&nbsp;II only (`milestone:msfaustii`), so there is no reason to hurry.

**Comment by gerritbruening** [comment]
Didn't forgot to mention it, but forgot _that_ I have mentioned it (https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#apparateintr%C3%A4ge-mit-subst) :-)

**Comment by pglatza** [comment]
'Un'dropping contents is much easier than whitespace handling. Needed the full content of a note right now, so I decided to just solve this Issue in `milestone:msfausti`.
The online converter is up to date.

**Comment by gerritbruening** [comment]
01.06.2018 07:50:31 I still don't see the `del` content.

**Comment by pglatza** [comment]
Fixed. Upload conversion updated.

**Comment by gerritbruening** [comment]
Ja, danke!
