### ISSUE TITLE
"Anpassung der IDML-Synthese bei der Sperrung"

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#483]
JFTR, weil ich gerade die Mails durchgehe.

> > Wenn ich die Kommentare ab Zeile 20 Deiner Excel-Datei genauer 
> studiere, dann komme ich zu dem Fazit, dass bspw. eine Anpassung der 
> IDML-Synthese bei der Sperrung Dir sehr zuträglich wäre?

> Ich weiß nicht genau, was du meinst. Wenn du die fehlenden Sperrungen bei Auftritten meinst, so ist das ja kein Problem der Sperrung, sondern eines der korrekten Zuweisung von Zeichenformaten bereits in der XML-Datei, wenn ich das richtig verstehe. Ebenso z.B. die Zuweisung des ZF »Figur« dem »mit dem« vor 1178 (Zeile 30 in Excel): ich weiß nicht, ob das so Absicht ist oder eine falsche Zuweisung bereits in XML oder ein Fehler bei der Konvertierung zu IDML. So auch bei den anderen in meinen Augen fehlerhaften Zuweisungen von ZF (Zeilen 21-36 in der Excel-Datei).

@pglatza, @markusciupke, wenn das geklärt ist, einfach closen.

**Comment by markusciupke** [comment]
Ich weiß nicht ob, das geschlossen werden kann, weil ich 1. nicht weiß was hier Absicht, und was hier ein Fehler ist. 2. Weiß ich nicht wo oder wann dieser Fehler in die Datei gekommen ist. Schon in Frankfurt oder erst in Leipzig? Ihr müsst euch bitte zum einen die Einzelstellen anschauen und dann zum zweiten analysieren, ob es manuelle Fehler sind oder systematische.

**Comment by gerritbruening** [comment]
Danke für die Rückmeldung. 
Wenn das so ist würde ich sagen, das ist durch die anderen von mir angelegten Issues abgedeckt.
@pglatza, wenn du doch noch etwas anderes meintest, kannst du ja reopen.
