### ISSUE TITLE
rdg/wit lost when multiple wit

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#484]
MC: 

> Textbestand, der mir teilweise falsch vorkommt (z.B. Der Apparat zu Vers 260 [Zeile 21]), 

> Was bedeutet: »Am ] An Am B

Seems as if rdg/wit is not always lost but only when there is more than one wit.

**Comment by gerritbruening** [comment]
https://github.com/faustedition/faust-gen-html/issues/478#issuecomment-393413788

Dies hier dürfte damit ebenfalls gefixt sein, oder?

**Comment by pglatza** [comment]
Ja, so sehe ich es auch. Bitte kommende PDF abwarten.

**Comment by gerritbruening** [comment]
Scheinen jetzt alle da zu sein.
