### ISSUE TITLE
vor 1530  zwei Lz zwischen "Faust." und "Mephistopheles"

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#486]
@pglatza, dass hattest du schon aufgeklärt und beseitigt, oder?

**Comment by pglatza** [comment]
Solche Fälle hatte ich geklärt, doch dieser blieb aufgrund einer besonderen Bedingung für die Sperrung-Formatfindung noch übrig. Man lernt nie aus (und hätte von Anfang den Whitespace vor der IDML-Synthese normalisieren sollen).
Upload-Formular habe ich soeben erneut aktualisiert.

**Comment by gerritbruening** [comment]
Gut, danke, dann verschiebe ich das für eine sicherheitshalbere Kontrolle auf die 1. Fahne.
