### ISSUE TITLE
Proof Faust I title content in scenes.xml

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#488]
@dietmarpravida, hier:
https://github.com/faustedition/faust-gen-html/blob/master/xslt/scenes.xml
stehen die Szenen-Kurztitel, die in den Kolumnentiteln landen würden.
Es wäre gut, diese vor Manuskriptabschluss zu prüfen.

**Comment by dietmarpravida** [comment]
okay
