### ISSUE TITLE
Szene nach Akt

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#489]
@markusciupke, soll es dieses Format nicht mehr geben?
(so verstehe ich
> Absatzformat   »Szene nach Akt« ist noch im Text. Kommt 3 mal vor. Alle 3 sollen stattdessen   das Absatzformat »Szene« erhalten.

in der excel-Liste)

**Comment by markusciupke** [comment]
Ja. Der Abstand nach »Teil« wird durch das Absatzformat »Teil« bestimmt. »Szene« hat genau wie »Sprecher nach Überschrift« 0,0 Abstand nach oben. Das Format is nach unserem Treffen in Göttingen überflüssig geworden.

**Comment by gerritbruening** [comment]
Danke, dann war das ein Missverständnis von mir.
@pglatza, ich habe das von @markusciupke abgeschaffte Format jetzt auch aus der Doku rausgenommen (https://github.com/faustedition/faust-gen-html/commit/f146b5e6fd4f684ccd06c91d86aa527a6c5f40d5).

**Comment by gerritbruening** [comment]
(Ich denke mal, das Format wäre schon sinnvoll gewesen, wenn wir bei der jeweils ersten Szene eines Akts den Beginn einer neuen Seite hätten verhindern wollen. Aber nun haben wir ja keine automatisch eingefügten Seitenanfänge.)

**Comment by markusciupke** [comment]
Stimmt. Da hast du recht, und das hatte ich nicht mehr auf dem Schirm.
