### ISSUE TITLE
Lz vor Lemma

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#491]
Im heutigen IDML-Output sehe ich:

```xml
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Kursiv">
                     <Content>260</Content>
                  </CharacterStyleRange>
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Kursiv">
                     <Content> </Content>
                  </CharacterStyleRange>
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
                     <Content> </Content>
                  </CharacterStyleRange>
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
                     <Content> </Content>
                  </CharacterStyleRange>
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
                     <Content>aufs </Content>
                  </CharacterStyleRange>
```

So als würde ein Abstand mit `Kursiv` und drei Lz danach folgen. Ist das Absicht? Veraltet?

**Comment by gerritbruening** [comment]
Nach https://github.com/gerritbruening/faust-data/commit/730b11d68078381f2b36082547d46889852d1d29 ist eins davon verschwunden.

**Comment by pglatza** [comment]
Das ist inzwischen veraltet. Mit dem aktuellen Stand (Upload-Formular) nach `260` nur noch ein Leerzeichen.

**Comment by gerritbruening** [comment]
Im Moment sehe ich
```xml
               <ParagraphStyleRange AppliedParagraphStyle="ParagraphStyle/Apparat">
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Kursiv">
                     <Content>260</Content>
                  </CharacterStyleRange>
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Kursiv">
                     <Content> </Content>
                  </CharacterStyleRange>
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
                     <Content> </Content>
                  </CharacterStyleRange>
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
                     <Content>aufs </Content>
                  </CharacterStyleRange>
```

Wäre für mich aber OK, wenn @markusciupke das ohne Schwierigkeiten durch Suchen und Ersetzen beseitigen kann.

**Comment by gerritbruening** [comment]
Ich sehe jetzt die Ursache:

````xml
                            Land vom Land aufs</seg> Meer,<note type="textcrit"
                            xml:id="app.260.aufslandvomlandaufs"><ref>260</ref><app
                                from="#seg.260.aufslandvomlandaufs">
                                <lem wit="faust://document/faustedition/A">aufs <gap

```

Vor dem Lemma wird ein Lz eingefügt, obwohl schon whitespace da ist (zwischen `app` und `lem`). Habe die Hinzufügung des Lz aus der Doku rausgenommen. Es sei denn, du hast `app` in einem `xsl:strip-space`, dann sähe die Sache natürlich wieder anders aus ... dieser whitespace 😱

**Comment by gerritbruening** [comment]
> Es sei denn, du hast `app` in einem `xsl:strip-space`

Wahrscheinlich wäre das sogar die bessere Lösung, um dann die gewünschte Anzahl von Lz einzufügen.
@pglatza, das ist mir zu hoch. @markusciupke signalisiert, dass er dieses und verwandte Probleme durch Suchen und Ersetzen ... Entscheidet ihr das unter euch? Je nachdem kann das hier ein `label:wontfix` bekommen.

**Comment by gerritbruening** [comment]
(Ich füge @thvitt zu diesem thread hinzu, für den Fall, dass ich völligen Unsinn geredet habe und er das schon für faust.xml geregelt hat.)

**Comment by markusciupke** [comment]
Hier noch mal das Ergebnis meiner schnellen Durchsicht der neuen IDML-Datei für alle. Beachtet bitte auch die Frage ganz am Schluss, ob die luftigere Typographie mit 1 LZ mehr nicht die bessere ist. Dann entfiele ein Großteil der Tauschvorgänge und ihr könntet euch auf das inhaltliche konzentrieren.
Außerdem ist mir noch aufgefallen, dass der Typ VIII immer noch im Apparat ist.

Eine schnelle Durchsicht der neuen IDML-Datei hat für mich ergeben, dass das sehr gut aussieht. Mit dem Textteil kann ich auf alle Fälle arbeiten. Auch der Apparatteil sieht in meinen Augen sehr gut aus, aber das kann ich vor allem inhaltlich nicht wirklich beurteilen. 

Formal ist mir im Apparat folgendes aufgefallen:

Beispiel: 21  Lied  ]  H2   Leid  A  B  Ba   Lied   (II c) 

1. zwichen Versangabe und Lemma sind 2 LZ --> kann ich durch Suchen & Ersetzen zu 1 LZ korrigieren.

2. vor der Lemmaklammer ist 1 LZ + 1/8-Geviert --> kann ich durch Suchen & Ersetzen zu 1/8-Geviert korrigieren.

3. 2 LZ hinter der Lemmaklammer sind korrekt.

4. zwischen der Sigle und der Variante sind 3 LZ --> eigentlich sind 2 LZ vorgesehen, aber mir gefällt das so besser. Ansonsten kann ich es durch Suchen & Ersetzen zu 2 LZ korrigieren.

5. Zwischen Variante und Sigle sind 2 LZ --> eigentlich ist 1 LZ vorgesehen, aber mir gefällt das so besser. Ansonsten kann ich es durch Suchen & Ersetzen zu 1 LZ korrigieren.

6. Zwischen den Varianten sind 1 geschütztes LZ + 1 LZ --> eigentlich ist 1 geschütztes LZ vorgesehen, aber mir gefällt das so besser. Ansonsten kann ich es durch Suchen & Ersetzen zu 1 geschütztem LZ korrigieren.

7. Zwischen Variante und Typ sind 3 LZ --> eigentlich sind 2 LZ vorgesehen, aber mir gefällt das so besser. Ansonsten kann ich es durch Suchen & Ersetzen zu 2 LZ korrigieren.

8. Die Typenbezeichnungen sind nicht das ZF »Typ« zugewiesen, was eine Verkleinerung des Schriftgrades um 1 Punkt bewirkt. Das kann ich durch Suchen & Ersetzen korrigieren.

9. Das 1/24-Geviert zwischen römischer Typenbezeichnung und alphabetischer Zählung ist korrekt.

Das luftigere im Apparat gefällt mir gut, außer vor der Lemmaklammer. Überlegt mal, ob wir es so lassen.

**Comment by gerritbruening** [comment]
> ob die luftigere Typographie mit 1 LZ mehr nicht die bessere ist

Mir persönlich scheint sie etwas zu luftig zu sein.

> dass der Typ VIII immer noch im Apparat 

Ja, #496.

> 2 LZ hinter der Lemmaklammer sind korrekt.

Das scheint mir präzisierungsbedürftig. Wenn eine Sigle folgt, sollte zwischen ] und Sigle nur _ein_ Lz stehen (sonst würde deren Zugehörigkeit zum Lemma unklar). Nur wenn nach ] direkt eine Lesart folgt, sollten _zwei_ Lz eingefügt werden (https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#lesart) -- durch wen und wie auch immer.

**Comment by markusciupke** [comment]
> Mir persönlich scheint sie etwas zu luftig zu sein.

Ihr seid die Bosse, ihr müsst **jetzt** entscheiden. Hier ist S. 12 mit einer Sigle nach der Lemmaklammer und 1 Lesart nach der Lemmaklammer einmal luftig und einmal normal:
[Seite 12 luftig.pdf](https://github.com/faustedition/faust-gen-html/files/2057472/Seite.12.luftig.pdf)
[Seite 12 normal.pdf](https://github.com/faustedition/faust-gen-html/files/2057473/Seite.12.normal.pdf)

Im übrigen sind momentan tatsächlich 4 LZ hinter der Lemmaklammer, wenn eine Lesart folgt. Das hatte ich bei meiner schnellen Durchsicht übersehen. Sind möglicherweise LZ konsequent verdoppelt worden?
Wenn man genauer einsteigt finden sich weitere Unregelmäßigkeiten bei der Anzahl der LZ.
Im übrigen sind die Apparareinträge der Szene Nacht weiterhin fehlerhaft.

**Comment by gerritbruening** [comment]
Danke! Finde `normal` immer noch besser. "Jetzt" ist Feiertag in Hessen, deswegen sind wir nicht permanent am Platz.
Zu
> momentan tatsächlich 4 LZ 

_e tutti quanti_ sagt am besten @pglatza, ob er sich diese ganzen Whitespacegeschichten jetzt noch antun will.

**Comment by markusciupke** [comment]
> "Jetzt" ist Feiertag in Hessen

Ja, die Straßen Göttingens sind voll mit Hessen, die endlich mal in Ruhe einkaufen wollen. Wahrscheinlich vor allem die berühmten Göttinger Würste, die schon Heine so geschätzt hat. Toll, dass ihr trotzdem am Platz seid.

**Comment by markusciupke** [comment]
Kann das geschlossen werden? – Ich gehe davon aus, dass ich die diversen horizontalen Abstände im Apparat mit Leerzeichen und Festabständen manuell bzw. durch Suchen & Ersetzen zu prüfen habe.
