### ISSUE TITLE
Auftritte

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#492]
Z.B. sollten 
Spaziergänger aller Art / Faust mit dem Pudel 
gleich behandelt werden, sie kommen aber im heutigen PDF unterschiedlich heraus.

**Comment by gerritbruening** [comment]
Die weiteren Einträge der Excel-Liste deuten darauf hin, dass man sich die Auftritte noch mal anschauen könnte. (Wenn ihr dafür noch die Zeit findet)

**Comment by gerritbruening** [comment]
Siehe auch #483, was hiervon vmtl mut abgedeckt wird.

**Comment by markusciupke** [comment]
Nochmal zur Verdeutlichung was meine Frage ist bzw. wo mein Problem liegt. Für mich ist das nicht unbedingt eine Frage von Auftritten, sondern eine Frage des Zusammentreffens von Auftritten oder Figuren mit anderem Text. Wir haben anhand von »Kater und Kätzinn« festgestellt, dass in A das »und« größer gesetzt ist als die BAs, nämlich so groß wie Verstext. Es ist auch so groß wie Kater bzw. Kätzinn, aber nicht gesperrt. In unserem Druck wollen wir die Sperrung (im zweiten Teil die Unterstreichung) von Sprechern durch Versalien umsetzen. Mein letzter Stand ist, dass das »und« nicht ebenfalls in Versalien gesetzt werden soll. Es soll aber auch nicht in der Schriftgröße der Verse gesetzt werden, weil die Versalien verkleinert sind, damit diese wiederum harmonisch zu den Versen und den BAs passen. Da würde das »und« in Grundschrift zu groß wirken. Daher haben wir beschlossen, die unterschiedliche Schriftgröße von »und« und BA-Text zu ignorieren und das »und« ebenfalls in BA-Größe zu setzen, so dass alles harmonisch zusammenwirkt. Gleiches muss nun nach meiner Auffassung auch für »Faust mit dem Pudel hereintretend« gelten oder für »Spaziergänger aller Art ziehen hinaus.«: »Faust« bzw. »Pudel« versal, »mit dem« sowie »hereintretend« groß/klein und einheitlich in BA-Schriftgröße. Im zweiten Teil ist »Hofgesinde aller Art prächtig gekleidet tritt vor« ein paralleler Fall.

**Comment by gerritbruening** [comment]
> Kater und Kätzinn

Alles klar, habe ich jetzt begriffen (#493). Scheint mir wichtig genug, das wenn möglich noch zu beheben.

**Comment by gerritbruening** [comment]
> Faust mit dem Pudel hereintretend ... Spaziergänger aller Art ziehen hinaus

Das war meine Schuld. Mit dem Nachvollzug der kleinen Änderung https://github.com/faustedition/faust-gen-html/commit/ef252368773232bb1ee07eb51e32afe210fd1c76 behoben werden können.

Falls das für @pglatza zuviel klein klein ist, nenne ich euch für die erste Fahne die einschlägigen Stellen:
* vor 808
* vor 1178 (beide oben genannt)
* vor 3544 (Gretchen und Lieschen mit Krügen)

**Comment by markusciupke** [comment]
Ich werde sowieso auch weiterhin genau hinschauen, so dass alle Stellen gefunden werden sollten. Allerdings könnte es sich hier auch um Zuweisungen handeln, die Herausgeberentscheidungen sind. Insofern wäre es gut, solche Stellen vor Satzabgabe in die richtige Form zu bringen. Zu den drei genannten Stellen gehört als vierte auch vor 2423 (Kater und Kätzinn).

**Comment by dietmarpravida** [comment]
für den Druck von F-I erledigt; falls es Nachkodierungsbedarf gibt, bitte wieder öffnen
