### ISSUE TITLE
Handling of speaker[hi]

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#493]
Right now, `speaker[hi]` is transformed to `ParagraphStyle/Sprecher`.
The result is that all its content is rendered as all-caps which is not intended.
For an improved handling see https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#ba-aus-speaker.

Only `speaker/hi` is to be rendered as all-caps, see https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#figur.

**Comment by pglatza** [comment]
Corrected. The online converter is up to date.

**Comment by gerritbruening** [comment]
Confirm.
