### ISSUE TITLE
Ignore seg

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#494]
@pglatza, in faust.xml there are `seg` elements that undermine your rules, for example

```xml
                        <speaker n="before_2195i_b"><seg type="lem"
                                xml:id="seg.before_2195i_b.altmayer">Altmayer</seg><note
```

has the effect that "Altmayer" receives `No character style` instead of `Figur`.
To avoid this you may just drop `seg` in a preprocessing step (but keep the content, of course).

Examples:
* Vor 2195: Altmayer ist ohne ZF --> Figur
* Vor 2276: Mephistopheles ist ohne ZF --> Figur
* Vor 2540: Die Hexe ist ohne ZF --> Figur
* Vor 3183: Soll Margarete hier kein ZF Figur erhalten, obwohl sie danach spricht (siehe auch Lemma im Apparat) oder ist das ein Versehen?

**Comment by pglatza** [comment]
That`s true! Now dissolved earlier.
Fortunately, there are is another positive change:

Before:
```
            <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Bibelstelle">
               <Content>(St. Joh. </Content>
            </CharacterStyleRange>
            <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
               <Content>IV.)</Content>
            </CharacterStyleRange>
```

After:
```
            <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Bibelstelle">
               <Content>(St. Joh. IV.)</Content>
            </CharacterStyleRange>
```

Planning to update the online converter soon.

**Comment by gerritbruening** [comment]
Great, thanks!
