### ISSUE TITLE
Abstand vor note/ref-Element

### ISSUE THREAD

**Issue by pglatza** [faustedition/faust-gen-html#495]
Welcher Abstand soll gewöhnlich vor dem ref-Element stehen? Ein einfaches Leerzeichen?
Beispiel, welcher eine Definition für einen Abstand notwendig macht ist in `<l n="58">`: das hochgestellte 'a' steht momentan direkt am Text-Teil `(IV a)` des ref-Elementes.

**Comment by gerritbruening** [comment]
Habe die Doku entsprechend aktualisiert: https://github.com/faustedition/faust-gen-html/commit/f44a3bdd59f5f2cedd369418f45b353db4038f89.

**Comment by pglatza** [comment]
@gerritbruening:
Leere ref-Elemente können entfallen, z.B. `<note><ref target="faust://bibliography/D.4alpha"/></note>`? Oder müssen gesonderte Regeln beachtet werden? Momentane Einstellung: immer Leerzeichen für die jeweiligen Elemente einfügen, auch wenn sie keine Inhalte tragen.

**Comment by gerritbruening** [comment]
Oh, da scheint tatsächlich text content zu fehlen. @thvitt, ist das Absicht so, weil die `ref` auf `...bibliography...` zeigen?

**Comment by gerritbruening** [comment]
> Leerzeichen für die jeweiligen Elemente einfügen

Eigentlich sollte davor und danach ein Lz stehen. Text content vorausgesetzt, wäre nichts weiter als die normale Zuweisung der Zeichenformate Kursiv und ggf. hochgestellt anzuwenden

**Comment by thvitt** [comment]
»Absicht« ist eine diplomatische Beschreibung für »nicht an den Druckfall gedacht«. Bzw. ich habe nur an den `#Erich_Schmidt`-Fall gedacht.

**Comment by thvitt** [comment]
Den haben bestimmt die Meerkatzen geklaut. Ich füg den doch extra ein. Menno.

**Comment by thvitt** [comment]
sieht jetzt so aus `<note type="type">␣␣<ref target="…">(IV a)</ref></note>`

**Comment by pglatza** [comment]
Ich habe mit XML-Datenstand von eben die Leerzeichen angetroffen und die IDML-Synthese an dieser Stelle leicht zurückgebaut. Die beiden Leerzeichen werden nur eingefügt, wenn noch kein Whitespace vorhanden ist.

**Comment by pglatza** [comment]
Upload-Formular aktualisiert.

**Comment by gerritbruening** [comment]
OK, für mich sieht es jetzt so aus, als ergeben sich insgesamt drei Lz:

```xml
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
                     <Content> </Content>
                  </CharacterStyleRange>
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Kursiv">
                     <Content>  (IV a)</Content>
                  </CharacterStyleRange>
```

Aber das belassen wir jetzt, ich nehme das aus label:idml raus und verschiebe es auf die erste Fahne.
