### ISSUE TITLE
Lz in Auftritten

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#499]
(ich weiß ...)
@pglatza, bitte entschuldige die Nachfrage.
Kannst du das hier sehen?:
https://github.com/gerritbruening/faust-data/commit/407bab5b43ebbd30ea2b7f8928bb7790ae5b4432#diff-99a218ab63e473355cd2194861dbbed9R5820
Für mich sieht das seltsam aus.
Eine Änderung dieser Art kommt auch da vor, wo kein Komma vorhergeht:
https://github.com/gerritbruening/faust-data/commit/407bab5b43ebbd30ea2b7f8928bb7790ae5b4432#diff-99a218ab63e473355cd2194861dbbed9R65810

Mir scheint, dadurch müsste eine asymmetrische Sperrung der Leerzeichen entstehen. Ich weiß nicht, ob Markus das per Suchen und Ersetzen finden und begradigen kann.

**Comment by pglatza** [comment]
Ja, kann ich sehen. Stimmt.
Dann verschiebe ich diese Whitespace-Anpassung zum nachfolgenden xslt-mode.

**Comment by pglatza** [comment]
#486

**Comment by gerritbruening** [comment]
Ist jetzt in Ordnung.
