### ISSUE TITLE
] missing when lem has only speaker as element content

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#500]
Applies to `lem[speaker and not(*[not(self::speaker)])]`.
Seems to apply to 12 passages in the text.

**Comment by pglatza** [comment]
Lösung vorhanden, warte aber noch auf Antwort zu https://github.com/faustedition/faust-gen-html/issues/477#issuecomment-393761322.

**Comment by gerritbruening** [comment]
Antwort soeben gegeben.

**Comment by pglatza** [comment]
Ist live und mit r66 behoben.
