### ISSUE TITLE
note[@n] is lost

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#501]
See https://github.com/faustedition/faust-gen-html/blob/master/idml/idml.md#bibelstelle.

As @thvitt [has observed](https://github.com/faustedition/faust-gen-html/issues/497#issuecomment-393578216), these are lost.
Interestingly, those which happen to appear right after `speaker` make it into the idml.

**Comment by gerritbruening** [comment]
Note that this is relevant for Faust II only, no need to hurry.

**Comment by pglatza** [comment]
Ist behoben, in r70 und live.

**Comment by gerritbruening** [comment]
Ja, sind da, danke!
