### ISSUE TITLE
? lost after Sperrung

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#502]
@thvitt [has first observed this](https://github.com/faustedition/faust-gen-html/issues/497#issuecomment-393578216).

This is brand new, as I still see the question mark in the newest PDF I got:
![grafik](https://user-images.githubusercontent.com/10358005/40801553-770c44e4-6513-11e8-9a00-0902b72586a5.png)

```xml
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Sperrung">
            <Content> Was</Content>
         </CharacterStyleRange>
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/$ID/[No character style]">
            <Content> und nicht ums </Content>
         </CharacterStyleRange>
```

Must be associated with #499, right?

**Comment by pglatza** [comment]
Correct; and solved now (conversion tool is updated).

**Comment by gerritbruening** [comment]
Yes, thanks!
