### ISSUE TITLE
misplaced ] before / before_2260, before:2274, before_2291

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-gen-html#504]
`vor 2260 MEPHISTOPHELES nimmt den Bohrer ] / zu Frosch`

`vor 2274 SIEBEL ] / indem bis nähert`

`vor 2291 ALLE ] / indem bis läuft`

**Comment by gerritbruening** [comment]
Hätte eigentlich im Rahmen von #477 gefixt werden soll. Würde das auf die erste Fahne verschieben.

**Comment by dietmarpravida** [comment]
falls noch aktuell, milestone auf 1.0 verschoben
