### ISSUE TITLE
position of line numbers in print edition

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-gen-html#506]
* Verszahlen sollten an der Linie des Satzspiegels stehen, nicht mitten in der Seite
* derzeit stehen sie innerhalb des Satzspiegels, ist das so beabsichtigt? Wenn ja, was wird dann bei den Prosaszenen gemacht? Dort können sie ja nur außerhalb des Spiegels stehen, oder?
* es wurde zwar einmal festgelegt, dass die Verszahlen immer links stehen. Ich gebe aber zu bedenken, dass es seltsam aussieht, wenn die Seitenzahlen mit linken und rechten Seiten springen, die Verszahen aber nicht. Es dürfte unmöglich sein, die Seitenzahlen auf Mitte am Seitenfuß zu setzen, der Vorteil wäre gewesen, dass dann wenigstens alle diese Teile in ihrer Position konstant gehalten werden. Aber das müssen wir wohl so hinnehmen.

**Comment by markusciupke** [comment]
Die unbearbeiteten IDML-Dateien sind auf den linken Seiten alle 23 mm zu weit rechts. Davon dürft ihr euch nicht irritieren lassen. Das wird beim Setzten zurechtgerückt. Der Vers beginnt dann am linken Satzspiegelrand (es sein denn, es sind eingerückte Verse). Der Verszähler sitzt rechtsbündig 4mm links davon. Bei den Prosazeilen ist es genau, nur dass der Satzspiegel von TTF 4 mm schmaler ist, damit wir den Zeilenfall vernünftig nach A einrichten können. Auch dass muss ich beim Setzen einrichten.
Ja, es ist unmöglich, die Seitenzahlen aus den Fuß zu setzen. Darüber hatten wir gesprochen.

**Comment by dietmarpravida** [comment]
okay
