### ISSUE TITLE
Bibliography for critical apparatus 

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#508]
Description: faust://bibliography/carriere1869
Description: faust://bibliography/D.3
Description: faust://bibliography/D.4
Description: faust://bibliography/D.4alpha
Description: faust://bibliography/duentzer1882a
Description: faust://bibliography/fiedler1943
Description: faust://bibliography/frankenberger1926
Description: faust://bibliography/hartung1855
Description: faust://bibliography/holland1882
Description: faust://bibliography/koch1882
Description: faust://bibliography/Q
Description: faust://bibliography/resenhoefft1975
Description: faust://bibliography/schroeer1881_1
Description: faust://bibliography/wa_I_14
Description: faust://bibliography/wa_I_15_1
Description: faust://bibliography/wa_I_53

**Comment by dietmarpravida** [comment]
hier geklärt
