### ISSUE TITLE
Query lowest and highest @n value of a witness

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#509]
@thvitt, how can I query the lowest and the highest `@n` of a witness' textual transcript?
Would be very nice to have this info as part of the metadata, also.

**Comment by gerritbruening** [comment]
Great, didn't know this.
Would be good to have this as **Verse** right after the idnos in the structure view.

**Comment by thvitt** [comment]
probably needs workflow adjustment since metadata html is currently generated independent of the textual transcript paths.

**Comment by gerritbruening** [comment]
Good to have this, thanks!
