### ISSUE TITLE
Combining macron in textual view

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#510]
@thvitt, have you ever seen that `Morgenſon̄e` is rendered like this:

![grafik](https://user-images.githubusercontent.com/10358005/40999926-abb587bc-690c-11e8-97d0-57b96f9ea48a.png)

This puzzles me.

**Comment by thvitt** [comment]
http://dev.faustedition.net/document?sigil=2_I_H.0a&page=63&view=text#lbefore_5987_b

**Comment by thvitt** [comment]
Italic font doesn’t have the `top` anchor point in its _n_ glyph. Cf. 5e5aa7ebf7932c3b761a2dadd84a7ba03bc0046c
