### ISSUE TITLE
Complete app entries

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#511]
`note type="textcrit" xml:id="app.before_2465_a.before"` ist lost in transformation, although #478 seems to be fixed. I am happy with that if this is the only case (see #530 for this).
Let's make a check:
Right now we have
563
`note[@type='textcrit']`, and 
562
times `ParagraphStyleRange[@AppliedParagraphStyle='ParagraphStyle/Apparat'`.
So this seems to be the only case.
@dietmarpravida, please make sure that this entry is added manually one way or another.

**Comment by dietmarpravida** [comment]
Fehlt:

- `before_2465_a[Die Hexe]{=} vor 2465] Die Hexe wird in A B C1 C3 nicht als Auftritt markiert (S unterscheidet typographisch nicht zwischen Auftritten und Sprecherangaben). [Typ 1c] `

**Comment by dietmarpravida** [comment]
@markusciupke Diese beiden (hier in nicht-transformierter Form erscheinenden) Einträge fehlen noch, ich kontrolliere noch den ganzen Rest. Bitte vorerst nicht manuell eintragen, bevor nicht geklärt ist (@gerritbruening ), was wir hierr tun.

**Comment by markusciupke** [comment]
Gut, dass du es gemerkt hast. Ich trage nichts manuell nach.

**Comment by dietmarpravida** [comment]
- [ ] - _21_ D4] _recte_ D4alpha (in Ausgangsdatei korrekt)
- [ ] - 666 u.ö. "konj" nicht kursiv (ebenso "emend")
- [ ] - 988 wird nach der Klammer ein "A" ergänzt, das da nicht hingehört
- [ ] - 2709 "ein umbrochener Vers" und "zwei Verse" nicht kursiv
- [ ] - 3179 erscheint "1_H.1" statt H1 mit hochgestelltem Index (nur hier, sonst korrekt)
- [ ] - 3356 steht der lange Text in der Fußnote, während es heißen muss `3356[]{} 3356–3357] zwei Verse H5 	Und ich, der Gottverhaßte, hatte nicht genug, S A B BA C1 C3 [Typ 2b] `
- [ ] - 3990-4015 steht nur die Verszahl, es fehlt der Fußnotentext `3990[]{} 3990–4015] Die Verse sind im Druck auffallend durch ihre zweistufige Einrückung, die aber optisch, nicht strukturell bedingt zu sein scheint (A 8, S. 198–199): 3900–3903 ½ cm eingerückt, 3996–4015 1,0 cm. [Typ 7]`

**Comment by dietmarpravida** [comment]
Fußnote zu 4261 `4261 nicht ] A B Ba H1 C1 C3 auch konj Frankenberger (III *)` möchte ich nachträglich entfallen lassen

**Comment by dietmarpravida** [comment]
Siehe auch #521

**Comment by markusciupke** [comment]
Das alpha ist da. Die griechische Schrift konnte von InDesign nicht dargestellt werden. Ich habe unsere übliche Schrift dafür eingesetzt und nach weiteren Alphas gesucht. Habe aber kein gefunden.

**Comment by markusciupke** [comment]
Achso. Ich muss die Datei auch hochladen!
[Fehlerhafte Apps.pdf](https://github.com/faustedition/faust-gen-html/files/2085781/Fehlerhafte.Apps.pdf)

**Comment by gerritbruening** [comment]
Vorschlag zum Verfahren:
Wenn im PDF was nicht stimmt, rückwärts nach der Ursache suchen, d.h.:
1. Ist die Datei [Story_u1aa.xml](https://raw.githubusercontent.com/gerritbruening/faust-data/master/idml/faust_i/Stories/Story_u1aa.xml?token=AJ4M9VnQpTvSXwkmRL3XqtuG_NOKCAe_ks5bJB3lwA%3D%3D) noch in Ordnung? Wenn die im Prinzip OK aussieht oder den Fehler zumindest nicht offensichtlich erklärt, @pglatza fragen (siehe auch https://github.com/faustedition/faust-gen-html/issues/387#issuecomment-395682294)

**Comment by markusciupke** [comment]
Natürlich müsst ihr rausfinden, woher der Fehler stammt. Das ist rückwärts gesehen notwendig. Auch um zu eruieren, ob es systematische Fehler oder auch nur einzelne weitere Fehler gibt. Klar. – Aber für mich ist vorwärts gesehen wichtig, dass ich weiterarbeiten kann, und dafür muss ich die Fehler, die wir jetzt sehen, schon vor der 1. Fahne korrigieren. Und das muss ich manuell tun, und das muss natürlich gründlichst geprüft werden. Aber: ich muss weiterarbeiten. Deswegen die Bitte, mir alle auszuführenden Korrekturen auf eine gut umzusetzende Art (also mit Korrekturzeichen auf einem Ausdruck) mitzuteilen. – Danke!

**Comment by gerritbruening** [comment]
Das ist auch nach vorwärts notwendig.
Wer sagt denn, dass jetzt alle Fehler gefunden sind. Deswegen müssen die Ursachen geklärt werden, damit weitere fehlerträchtige Stellen identifiziert und geprüft werden können. Und es geht dann ja auch noch um den Faust II.
Und wir brauchen einen Rückfluss der Daten am Ende, vorzugsweise IDML. Den vergleichen wir dann mit den Eingabedaten.

**Comment by dietmarpravida** [comment]
Story_u1aa.xml:
- 666: gibt es für "konj", "emend", "mon", "mark" etc überhaupt eine Regel? 
--in der Story_u1aa-Datei jedenfalls nicht ausgezeichnet 
--in idml mit `<note><abbr>konj</abbr>`

- 988: 
--Das A steht auch in der Story_u1aa-Datei
--es steht auch in idml: `<lem wit="faust://document/faustedition/A">stillt; <wit
                                            f:is-base="true" wit="faust://document/faustedition/A"
                                            >A</wit></lem>
                                    <rdg type="type_7">`

- before_2465_a "Die Hexe" 
-- Die Fußnote in fehlt der Story_u1aa-Datei
-- im idml vorhanden: `<rdg
                                wit="faust://document/faustedition/A faust://document/faustedition/B faust://document/faustedition/C.1_12 faust://document/faustedition/C.3_12"
                                type="type_1c*">Die Hexe <note>wird in <wit f:is-base="true"
                                        wit="faust://document/faustedition/A">A</wit>
                                    <wit wit="faust://document/faustedition/B">B</wit>  <wit
                                        wit="faust://document/faustedition/C.1_12">C<hi
                                            rend="superscript">1</hi></wit>  <wit
                                        wit="faust://document/faustedition/C.3_12">C<hi
                                            rend="superscript">3</hi></wit> nicht als Auftritt
                                    markiert (S unterscheidet typographisch nicht zwischen
                                    Auftritten und Sprecherangaben).</note></rdg>`


- before_2540_b 
--Die Fußnote in fehlt der Story_u1aa-Datei
-im idml vorhanden: `<rdg wit="faust://document/faustedition/S" type="type_8"
                                            ><note>In <wit wit="faust://document/faustedition/S"
                                                >S</wit> ist <quote>Die Hexe</quote> nicht als
                                            Sprecherbezeichnung kenntlich gemacht.</note></rdg>`

- 3179
-- steht in Story_u1aa-Datei `<CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Kursiv">
                     <Content> B.a1_H.1  </Content>` , d.h. ohne Leerzeichen zwischen „Ba“ und „1_H.1“
--ebenso in idml

- 3620 ??
- 3990-4015 
--fehlt der Fußnotentext auch in der Story_u1aa-Datei
-- ebenso in idml

**Comment by dietmarpravida** [comment]
@gerritbruening schaust du dir die obige Liste nochmal an?

**Comment by dietmarpravida** [comment]
Korrekturen im Satz sollten bitte auf einer anderen Seite dokumentiert werden (#521), sonst geht es hier durcheinander

**Comment by markusciupke** [comment]
Ich hoffe, der Ort ist für das folgende richtig. Jedenfalls beziehe ich mich auf obige Liste. 

Ich habe mir alle Stellen der obigen Liste genau angesehen und dazu folgende Bemerkungen:

21: Das Alpha ist da, es musste nur mit der richtigen Schrift versehen werden, damit es auch im Satz erscheint. Das ist geschehen.

666: Im App zu 666 war auch »mon Gö« nicht kursiv. Außerdem habe ich folgende editorischen Abkürzungen im Apparat kursiviert:
emend: 2633, 3369
konj: 666, 719,2302, vor 2392, 2455, 2791, 2921, 3395, 3557, 4051, 4261, TTF 16
mon: 4501
mon Gö: 666
mon Re: 4501
vorschl: nach 3409

988: A ist nun getilgt. – In der Online-Datei ist es aber da.

vor 2465: Ist eingefügt. Soll »Die Hexe« im Apparat als »Auftritt« formatiert werden (so habe ich es gemacht) oder normal groß/klein?

vor 2540: Ist eingefügt. Soll »Die Hexe« im Apparat als »Figur« formatiert werden (so habe ich es gemacht) oder normal groß/klein? – In der Online-Datei fehlt der Eintrag bei 1c*

vor 2709: Bei Apparat-Einträgen ohne Lemmaklammer (vor 2366-2377, 2540-2552, 2740-2741, 3356-3357, 3550-3551, 3871-3911, 3974-3977, 3994-4015 und 3994-4015) beginnt der kursive Apparattext nach 2 LZ immer mit Großschreibung. Das habe ich hier der Einheitlichkeit wegen auch so gemacht. – Die Wörter sind auch in der Online-Datei recte.

3179: Das habe ich entsprechend korrigiert. – In der Online-Datei fehlt zwischen »a« und »1« ein Leerzeichen.

3356: Ist eingefügt. Parallel zu den anderen Apparat-Einträgen ohne Lemma (siehe oben zu vor 2709) habe ich die Lemmaklammer entgegen dem Eintrag in der obigen Liste weggelassen und das »Zwei« groß geschrieben. Der Apparat ist insofern nicht ganz korrekt als in H5 »Und ich der Gott verhasste | Hatte nicht genug^« steht. Diese Informationen zu Schreibung und Interpunktion gehen gegenüber dem langen Apparat-Eintrag verloren. Ist das so gewollt? Der lange Eintrag steht zum direkten Vergleich darunter.

3990-3903: Ist eingefügt. Parallel zu den anderen Apparat-Einträgen ohne Lemma (siehe oben zu vor 2709) habe ich die Lemmaklammer entgegen dem Eintrag in der obigen Liste weggelassen. Die uneinheitlichen Maßangaben (1/2 cm und 1,0 cm) habe ich zu 5 mm und 10 mm vereinheitlicht (möglich  wäre auch 0,5 cm und 1,0 cm bzw. 1/2 cm und 1 cm). Eine Millimeter-Angabe ist aber nach meiner Meinung hier die beste. Um die Ziffern der Vers-Angaben und der Millimeter-Angaben aufeinanderfolgen zu lassen, habe ich jeweils ein »um« eingefügt.

Hier sind die entsprechenden Seiten (von den kursivierten editorischen Angaben ist hier nur der Apparat zu 666 dabei):

[Korrigierte Apps.pdf](https://github.com/faustedition/faust-gen-html/files/2087265/Korrigierte.Apps.pdf)

**Comment by gerritbruening** [comment]
> @gerritbruening schaust du dir die obige Liste nochmal an?

Ja, habe die Liste durchgearbeitet (editiert). Wo ich eigenes Issue aufgemacht habe, habe ich hier abgehakt.

**Comment by dietmarpravida** [comment]
(Übertrgh von #514

> Im Apparat zu 3497 fehlt zwischen dem gesperrten »liebte dich« und »S« ein LZ. 

In der Ausgangsdatei vorhanden, @dietmarpravida der Verlust des LZ muss in den Zwischendateien geprüft werden.

**Comment by dietmarpravida** [comment]
@gerritbruening auf 1.0 ummeilen?

**Comment by gerritbruening** [comment]
morgen!

**Comment by gerritbruening** [comment]
Es müssten jetzt noch einige ins XML nachgezogen werden.

**Comment by gerritbruening** [comment]
Teil von #497

**Comment by markusciupke** [comment]
Bis einschließlich 5. Oktober 2018 bin ich nicht im Büro. In dringenden Fällen wenden Sie sich bitte an meine Kollegin Lynn van Leewen (lvanleewen@wallstein-verlag.de).

Mit freundlichen Grüßen
Markus Ciupke

**Comment by dietmarpravida** [comment]
before_2465_a "Die Hexe"
-- online nach wie vor nicht an der passenden Stelle vor den drei anderen Einträge zur selben BA "außer", "große", "hinaus schlägt" eingeordnet (Problem der Versziffern?)

sonst sind alle oben genannten Stellen okay
