### ISSUE TITLE
before_2311i_b fails to get parsed

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-gen-html#512]
Sieht hier jemand das Problem, woran es liegen könnte?

WARNING:parse_xml: Failed to parse <speaker>Altmayer</speaker> / <stage>zieht <gap reason="ellipsis"/> entgegen. as xml, using unparsed version instead
--
`INFO:parse_app2norm: Parsed: before_2311i_b[]{} <i>vor 2311</i> <speaker>Altmayer</speaker> / <stage>zieht <gap reason="ellipsis"/> entgegen. <i>none</i></stage>] <speaker>Altmayer^</speaker> / <stage>zieht <gap reason="ellipsis"/> entgegen.</stage> <i>S</i> <speaker>Altmayer.</speaker> / <stage>zieht <gap reason="ellipsis"/> entgegen^</stage> <i>A </i> <speaker>Altmayer.</speaker> / <stage>zieht <gap reason="ellipsis"/> entgegen.</stage> <i>D.1</i> <speaker>Altmayer^</speaker> / <stage>zieht <gap reason="ellipsis"/> entgegen.</stage> <i>B</i> <speaker>Altmayer^</speaker> / <stage>(zieht <gap reason="ellipsis"/> entgegen).</stage> <i>B.a [type=8]</i>
WARNING:parse_xml: Failed to parse <speaker>Altmayer</speaker> / <stage>zieht <gap reason="ellipsis"/> entgegen. as xml, using unparsed version instead
Traceback (most recent call last):
  File "/mnt/data/jenkins/workspace/faust-gen-fast/src/main/xproc/text/app2xml.py", line 60, in parse_xml
    xml = etree.fromstring(pseudo_xml)
  File "src/lxml/etree.pyx", line 3213, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1757, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1067, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 600, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 710, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 639, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: stage line 1 and root, line 1, column 91`

**Comment by gerritbruening** [comment]
Das Problem ist dieses Konstrukt:
`<stage>zieht <gap reason="ellipsis"/> entgegen. <i>none</i></stage>`
So wie es aussieht, reicht das Zeichenformat `stage` zu weit.

**Comment by dietmarpravida** [comment]
ok, in der Ausgangsdatei geändert. Müsste geklärt sein, bei nächster Pushung prüfen.

**Comment by gerritbruening** [comment]
Zurzeit immer noch kaputt:
https://github.com/faustedition/faust-gen-html/blob/master/text/app1norm.txt#L145
Unverändert `<stage>zieht <gap reason="ellipsis"/> entgegen. <i>none</i></stage>` mit `i` innerhalb von `stage`.
Interessanterweise geht die Stelle in der IDML-Pipeline ganz kaputt:
![grafik](https://user-images.githubusercontent.com/10358005/41314721-df2a11c2-6e8d-11e8-9466-c69e48c2e89e.png)

**Comment by thvitt** [comment]
Schon bei der app2xml-Transformation wird das unwohlgeformte XML-Fragment vor dem `<i>none</i>` als Text interpretiert, das sagt ja auch die Warnung. Das entsprechende `<lem/>` wird dann nur noch aus der app1norm.xml in die faust.xml kopiert: 

```xml
<lem>&lt;speaker&gt;Altmayer&lt;/speaker&gt; / &lt;stage&gt;zieht &lt;gap reason="ellipsis"/&gt; entgegen.</lem>
```

**Comment by dietmarpravida** [comment]
scheint geklärt zu sein
