### ISSUE TITLE
Beim Satz bemerkte Unregelmäßigkeiten

### ISSUE THREAD

**Issue by markusciupke** [faustedition/faust-gen-html#514]
- [ ]  https://github.com/faustedition/faust-gen-html/issues/387#issuecomment-395549562
- [ ] https://github.com/faustedition/faust-gen-html/issues/275#issuecomment-395564777
- [ ] vor 482: vor »DER GEIST« sind in meiner Datei 2 LZ. Das erste ohne ZF das zweite mit ZF Auftritt.

**Comment by gerritbruening** [comment]
Das erste davon dürfte jeweils ungesperrt sein, das zweite gesperrt. Vielleicht hilft das beim Suchen und Ersetzen?

**Comment by markusciupke** [comment]
Das erste war darüber hinaus in 8,5 pt wie BAs, das zweite in 8,0 pt wie Auftritte. Aber das habe ich beim Suchen (und Ersetzen) bedacht. Diese drei Fälle habe ich korrigiert.

**Comment by markusciupke** [comment]
Vor 993 hat das LZ nach »VOLK« nicht das ZF »Figur«.

**Comment by markusciupke** [comment]
Vor 1278 habe ich »mit dem« parallel zu »SPAZIERGÄNGER aller Art ziehen hinaus (vor 808) das ZF »ohne« statt »Figur« zugewiesen.

**Comment by markusciupke** [comment]
Vor 1278 hat das LZ nach »PUDEL« nicht das ZF »Auftritt«. Ist korrigiert (wie auch oben vor 993).

**Comment by markusciupke** [comment]
Vor 1322 ist »Mephistopheles« ohne ZF. Er muss aber das ZF »Auftritt« erhalten. Ist korrigiert.

**Comment by markusciupke** [comment]
In Vers 1290 ist vor dem ersten Buchstaben des Verses ein Leerzeichen.
Ebenso in 2048, 3798 f., 3813-3815, 3825-3827, 3833. 
Ist korrigiert.

**Comment by markusciupke** [comment]
In den BAs vor 2337a (Auf), vor 4251 (Fortissimo) und Vor 4315 (CI-DEVANT) ist jeweils 1 LZ. Ist korrigiert.

**Comment by markusciupke** [comment]
Vor 2423: nach »Kater« und vor »Kätzinn« (ausgerechnet) ist das LZ ohne ZF. Richtig ist ZF Figur. Ist korrigiert.

**Comment by markusciupke** [comment]
Vor 2587 a und b: nach »DIE HEXE« und nach »FAUST« ist das LZ ohne ZF. Richtig ist ZF Figur. Ist korrigiert.

**Comment by markusciupke** [comment]
Ich bin jetzt alle Auftritte systematisch durchgegangen. Folgender Befund:
vor 1178: LZ vor »PUDEL« = Figur --> Auftritt. Ist korrigiert.
vor 2604: Punkt nach »FAUST« = Auftritt --> ohne. Ist korrigiert.
vor 3073: zwischen »mit« und »MEPHISTOPHELES« SIND 2 LZ. Das 1. LZ = ohne ZF, das 2. LZ = Auftritt. Das 1. LZ muss getilgt werden. Ist korrigiert.
vor 4399: Punkt nach »FAUST« = Auftritt --> ohne. Ist korrigiert.

**Comment by markusciupke** [comment]
Entschuldigt. Das muss oben »vor 2605« heißen.

**Comment by markusciupke** [comment]
Im Apparat zu 2769 steht »_D.3_« und »_D.4_«. Ist korrigiert zu _D3_ und _D4_ (Ziffern hochgestellt).

**Comment by markusciupke** [comment]
Im Apparat zu 3422 fehlt zwischen dem gesperrten »Muß« und »S« ein LZ. Dieses muss mitgesperrt werden. Ist korrigiert.

**Comment by markusciupke** [comment]
Im Apparat zu 3422 ist das Muß/Muss/ M u ß  jeweils groß geschrieben. In der digitalen Ausgabe und oben im KT ist es jeweils klein geschrieben. Ist korrigiert.
Im übrigen kann ich in S keine Sperrung des »muß« erkennen. Ein Versehen?

**Comment by markusciupke** [comment]
Ich habe jetzt systematisch gesucht und noch eine Stelle gefunden:
Im Apparat zu 1921 fehlt zwischen dem gesperrten »Drey« und »S« ein LZ. Dieses muss mitgesperrt werden. Ist korrigiert. – Diese Sperrung ist in S deutlich zu erkennen.

**Comment by dietmarpravida** [comment]
> vor 3208: »Marthe« hat hier das ZF »Figur«. »Marthe« ist allerdings in D1 etwas größer gedruckt und muss deswegen parallel zu Margarete, Faust und Mephistopheles das ZF »Auftritt« erhalten. Die WA macht es auch so. Einverstanden?

Nein, das ist eine Sprecherbezeichnung.

**Comment by dietmarpravida** [comment]
> Im Apparat zu 3422 ist das Muß/Muss/ M u ß jeweils groß geschrieben. In der digitalen Ausgabe und oben im KT ist es jeweils klein geschrieben. Ist korrigiert.

Soweit ich sehe, ist das "Muß" überall groß geschrieben. 

> Im übrigen kann ich in S keine Sperrung des »muß« erkennen. Ein Versehen?

Bitte gesperrt lassen.

**Comment by dietmarpravida** [comment]
> Im Apparat zu 2769 steht »D.3« und »D.4«. Ist korrigiert zu D3 und D4 (Ziffern hochgestellt).

mental note, @dietmarpravida: Muss hier nicht auch überall D.2 stehen?

**Comment by dietmarpravida** [comment]
> Im Apparat zu 3497 fehlt zwischen dem gesperrten »liebte dich« und »S« ein LZ. 

In der Ausgangsdatei vorhanden, @dietmarpravida der Verlust des LZ muss in den Zwischendateien geprüft werden.

**Comment by markusciupke** [comment]
>  (d.h. in 3422, dass es in 3421 klein ist, sollte hier keine Rolle spielen)

Oh verdammt. Entschuldige. Ich habe tatsächlich immer in Vers 3421 nachgesehen. Das spielt natürlich keine Rolle.

**Comment by markusciupke** [comment]
Im Apparat zu vor 4343 steht: »vor 4343  In H1 C1 C3 folgen die (ganz oder teilweise auch in H16 und H17 enthaltenen) Verse 4335 – 4342 (hier wiedergegeben nach H1):«
Die Verbindung »vor 4343 folgen« halte ich für ungünstig. Besser wäre nach meiner Meinung: »nach 4334   In H1 C1 C3 folgen die (ganz oder teilweise auch in H16 und H17 enthaltenen) Verse 4335 – 4342 (hier wiedergegeben nach H1):«
Das scheint mir auch logischer, weil man ja eher vorwärts als rückwärts zählt. Ich bitte um Rückmeldung.

**Comment by dietmarpravida** [comment]
ist hier noch was zu tun?

**Comment by markusciupke** [comment]
Von mir aus nicht mehr.
