### ISSUE TITLE
Zweizeilige BAs

### ISSUE THREAD

**Issue by markusciupke** [faustedition/faust-gen-html#517]
Ich weiß, es ist spät, aber mir ist beim Feinsatz eine Sache aufgefallen, die ich gern noch mit euch besprechen möchte. Und zwar wirkt der Zeilenabstand bei zweizeiligen BAs dadurch, dass die Schrift kleiner, der Durchschuss aber weiterhin 13,2 pt ist, in meinen Augen zu groß. Die BA bildet optisch keine Einheit, sondern wirkt auseinandergerissen (siehe Var 1).
In Var 2 habe ich die zweite Zeile um 1 pt (das ist ca. 1/3 mm) angehoben und dadurch an die obere Zeile rangerückt und von der darunterliegenden Verszeile weggerückt. Das sieht für mich stimmiger aus. Der Unterschied ist fein, aber wahrnehmbar und ist in meinen Augen bessere Typographie.
[Faust Satz 106-107 Var 1.pdf](https://github.com/faustedition/faust-gen-html/files/2083487/Faust.Satz.106-107.Var.1.pdf)
[Faust Satz 106-107 Var 2.pdf](https://github.com/faustedition/faust-gen-html/files/2083488/Faust.Satz.106-107.Var.2.pdf)

Dann zum Zeilenfall zweizeiliger BAs: @gerritbruening wünscht sich, dass nicht so sehr Tannenbäume oder auf dem Kopf stehende Pyramiden gemacht werden sollen. Das sehe ich auch so. Das Prinzip, nach dem ich verfahren möchte, ist, grundsätzlich die obere Zeile so lang zu lassen wie der Satzspiegel es eben zulässt (so verfährt auch der Setzer von Cotta). Eingreifen würde ich dort, wo ein sehr unschöner Zeilenfall entstehen würde, der das Lesen und Verstehen behindert. Z.B. vor 354, wo die erste Zeile nach »unruhig« enden  würde und die zweite Zeile in meinen Augen unschön kurz wäre (siehe pdf von gestern). Hier würde ich nach »Zimmer,« umbrechen. Einverstanden? – Auf der Doppelseite 106-107 würde ich überhaupt nicht in den Zeilenfall eingreifen und habe das in den beiden Varianten auch nicht getan. Einverstanden?

Wenn ihr mit beidem einverstanden seid, würde ich auf diese Weise weiterverfahren.

**Comment by dietmarpravida** [comment]
Var. 2 scheint mir auf den ersten Blick besser, aber es fragt sich, was die Weiterungen sind. Z.B. wenn eine Personennennung mit Auftrittsfunktion käme, würde der kleinere Abstand dann nicht auf einmal zu klein scheinen?

**Comment by dietmarpravida** [comment]
bei mehrzeiigen BAs wäre ich spontan eher für eine blockartige Anmutung, sofern die Zeilen dadurch nicht zu kurz werden. Was Cotta & Co. tun, scheint mir in diesem Zusammenhang einerlei. Aber ich bin mir nicht sicher, ob sich daraus eine Regel machen lässt.

**Comment by markusciupke** [comment]
In Ordnung. Ich hebe 2. Zeilen einer BA an. Auf zweizeilige BAs, in deren 2. Zeile sich eine Figur oder ein Auftritt findet, werde ich achten und schauen, was da besser ist. Ich sage dann hier bescheid.

Blockartige Anordnung  ist auch eine Möglichkeit. Ich schaue mir die betroffenen BAs daraufhin nochmal an. Eine Regel, die sich auf die Länge bezieht, wird wohl nicht machbar sein, weil für den Zeilenfall auch die semantischen Abschnitte einer BA von Bedeutung sind.

**Comment by markusciupke** [comment]
Ich habe schon zwei gefunden:
[Faust Satz 027 Var 1.pdf](https://github.com/faustedition/faust-gen-html/files/2084870/Faust.Satz.027.Var.1.pdf)
[Faust Satz 027 Var 2.pdf](https://github.com/faustedition/faust-gen-html/files/2084871/Faust.Satz.027.Var.2.pdf)
[Faust Satz 031 Var 1.pdf](https://github.com/faustedition/faust-gen-html/files/2084872/Faust.Satz.031.Var.1.pdf)
[Faust Satz 031 Var 2.pdf](https://github.com/faustedition/faust-gen-html/files/2084873/Faust.Satz.031.Var.2.pdf)
Var 1 ist ohne Anhebung, Var 2 mit.
Ich finde, dass auch hier die Einheit der BA bei Var 2 besser gewährleistet ist.
Einverstanden?

**Comment by dietmarpravida** [comment]
ja

**Comment by dietmarpravida** [comment]
kann das geschlossen werden? Oder ist hier noch etwas offen?

**Comment by markusciupke** [comment]
Von mir aus kann es geschlossen werden.
