### ISSUE TITLE
BA vor 460

### ISSUE THREAD

**Issue by markusciupke** [faustedition/faust-gen-html#518]
Die BA vor 460 passt so gerade auf eine Zeile (Var 1).
Ich finde das unschön, weil die BA nahezu am linken Satzspiegelrand beginnt und fast für einen Vers gehalten werden könnte. So habe ich nach »erblickt« umbrochen (Var 2).
Bei einem Umbruch nach »Zeichen« wäre mir die zweite Zeile zu kurz.
Var 3 zeigt denselben Umbruch wie Var 2, allerdings mit der um 1 pt angehobenen zweiten Zeile (siehe #517).

[Faust Satz 030 Var. 1.pdf](https://github.com/faustedition/faust-gen-html/files/2083595/Faust.Satz.030.Var.1.pdf)
[Faust Satz 030 Var. 2.pdf](https://github.com/faustedition/faust-gen-html/files/2083596/Faust.Satz.030.Var.2.pdf)
[Faust Satz 030 Var. 3.pdf](https://github.com/faustedition/faust-gen-html/files/2083597/Faust.Satz.030.Var.3.pdf)

Wie soll ich verfahren?

**Comment by dietmarpravida** [comment]
Var 2 und 3 sind mir zu trichterförmig. Warum nicht vor "und" oder "erblickt" umbrechen?

**Comment by markusciupke** [comment]
[Faust Satz 030 Var 4.pdf](https://github.com/faustedition/faust-gen-html/files/2084828/Faust.Satz.030.Var.4.pdf)
[Faust Satz 030 Var 5.pdf](https://github.com/faustedition/faust-gen-html/files/2084829/Faust.Satz.030.Var.5.pdf)

Mir gefällt Var 4 besser. Bitte entscheide.

**Comment by dietmarpravida** [comment]
Hm, optisch finde ich 5 besser, verstehe aber natürlich die Präferenz für 4. Ich muss aber sagen, dass ich jede  Andeutung von Trichterförmigkeit (wie in 4) irgendwie anstößig finde. Ich wäre demnach für 5.

**Comment by markusciupke** [comment]
Da haben wir den Salat. Gerrit? Unterwirfst du dich? 0der bist du sowieso Dietmars Meinung?

Ich möchte anfügen, dass wir häufig eine längere und eine kürzere Zeile haben werden, wenn wir nach semantischen Kriterien abteilen – ob nun Trichter oder Tannenbaum. Kann man bei zwei Zeilen eigentlich schon von Trichter oder Tannenbaum sprechen?

Jedenfalls wird sich Anstößigkeit nicht ganz vermeiden lassen.
