### ISSUE TITLE
Apparat nach 3409

### ISSUE THREAD

**Issue by markusciupke** [faustedition/faust-gen-html#519]
Im Apparat zu nach 3409 steht: »nach 3409 ]  Strophenabstand H5  kein Strophenabstand S A B B  Strophenabstand vorschl. Gö mark G H6  kein Strophenabstand H1  Strophenabstand C1 C3  (II b)«
Ist »B B« korrekt? Oder muss es »B Ba« heißen?

**Comment by dietmarpravida** [comment]
ja, das ist ein Fehler: Es muss Ba heißen

**Comment by markusciupke** [comment]
Wird von mir korrigiert.
