### ISSUE TITLE
Join multiple lines with the same @n

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#52]
Some witnesses have different verses where there is only one verse in the canonical numbering:
```xml
<l n="8909">Tritt hervor aus flüchtigen Wolken</l>
<l n="8909">Hohe Sonne dieſes Tags,</l>
```
This may also appear with suffixes (cf. #50). 

In these cases, _in the apparatus_ the verses should be joined to be on one line, separated by `|`. 

However, this should only be the case iff the respective lines are directly adjacent, not if they are in separate `<div>`s etc.

**Comment by gerritbruening** [comment]
Do we have a Label for the n-associated problems?

**Comment by thvitt** [comment]
We need to double check the variants for [8891](http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=231&view=print#l8891). If these are correct, our maximum # of witnesses has increased to 17, which means styling adjustments

**Comment by thvitt** [comment]
[2 III H.23d](http://dev.faustedition.net/documentViewer?faustUri=faust://xml/document/archival/gm_duesseldorf/KK123_10.xml&page=1&view=print#l8891) is a corner case: two instances of v.8891, interrupted by a verse with non-canonical numbering. We handle this by representing the two 8891 instances of that witness as different variants, if this is unacceptable, please reopen with a better solution.

**Comment by gerritbruening** [comment]
This case is complicated because the lines of two metrically identical stanzas are mixed for exact correspondent of first and first, second and second, third and third line etc. of each stanza. It is good the way it is.
