### ISSUE TITLE
Bis-Strich im Apparat

### ISSUE THREAD

**Issue by markusciupke** [faustedition/faust-gen-html#520]
Im Jahrbuch des FDH benutzen wir den Halbgeviert-Strich als Bis-Strich. Das ist auch richtig.
Im Apparat empfinde ich den allerdings als etwas überbetonend (Var 1).
In Var 2 habe ich den Bindestrich genommen.
Was findet ihr besser?
[Faust Satz 034 Var. 1.pdf](https://github.com/faustedition/faust-gen-html/files/2084006/Faust.Satz.034.Var.1.pdf)
[Faust Satz 034 Var. 2.pdf](https://github.com/faustedition/faust-gen-html/files/2084007/Faust.Satz.034.Var.2.pdf)

**Comment by dietmarpravida** [comment]
bitte Var 1, man könnte aber mit der Spazionierung je nach einzelnen Ziffern variabel verfahren (z.B. bei der 5 im Beispiel, noch mehr wohl bei einer 1)

**Comment by markusciupke** [comment]
In Ordnung. Var 1.
Das, was du dir wünschst, ist aber feinster Feinsatz. Was wünschst du dir denn bei dieser »5«? Etwas mehr oder etwas weniger Luft?

**Comment by dietmarpravida** [comment]
ich dachte an weniger

**Comment by markusciupke** [comment]
In Ordnung.
Es sind insgesamt 18 Stellen, an denen das vorkommt. Am besten ist, du zeichnest das dann in die 1. Fahne ein, wo du weniger (oder auch mehr) Abstand haben möchtest.

**Comment by dietmarpravida** [comment]
@markusciupke ist hier für mich noch etwas zu beachten?

**Comment by markusciupke** [comment]
Wenn ich Zeit hab, schaue ich mir die 18 Stellen mit – 5 an und verringere den Abstand. Aber das ist die Kür ganz zum Schluss. Erstmal machen wir die Pflicht.
Gibt es weitere Paare aus – und Ziffer, die du bearbeitet wünschst?

**Comment by dietmarpravida** [comment]
ichs schaus mir an, aber nicht mehr heute, das hätte wenig Sinn
