### ISSUE TITLE
record all changes made in indesign for print

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-gen-html#521]
@markusciupke Trage doch bitte alle wesentlichen (im Zweifelsfall auch die unwesentlichen) Änderungen (Korrekturen wie z.B. #519 und #514) hier ein, damit wir später prüfen können, ob sie in die Datei für den online-Text übrtragen wurden.

**Comment by markusciupke** [comment]
Ich habe bislang alles gemeldet, was mir auffällt und werde so weiter verfahren. Dann trage ich jetzt alles hier und nichts mehr in #514 ein. Für zu diskutierende Fragen mache ich weiter eigene Issues auf.

**Comment by markusciupke** [comment]
3620    so  H5  H12  B  Ba    fehlt A  D1   (IV b) 
Hier fehlt anscheinend die Lemmaklammer.

**Comment by dietmarpravida** [comment]
ja, ist in der Ausgangsdatei aber korrekt

**Comment by markusciupke** [comment]
In der IDML-Datei, die ich von PG erhalten habe, fehlte sie schon.

**Comment by dietmarpravida** [comment]
Übertrag von #511 

markusciupke wrote (08-06-18, evening):

> @dietmarpravida: Ich habe die 10 betreffenden Seiten in der Form, die sie momentan (nach einigen Einrichtungsarbeiten) haben, in einer PDF-Datei abgespeichert. Es handelt sich noch nicht um einen fertigen Satz oder Seitenumbruch! Aber für meine Arbeit ist es sinnvoll, bzw. notwendig, wenn du auf Ausdrucken derselben mit den üblichen Korrekturzeichen die entsprechende Korrektur vornimmst und mir Scans davon schickst. Dann kann ich das ausführen, bevor ich den Feinsatz und den Seitenumbruch mache. Denn einige der Korrekturen sind ja voraussichtlich umbruchsrelevant. Dass das alles dann genauestens geprüft werden muss, versteht sich.

markusciupke wrote (08-06-18, evening):

> Achso. Ich muss die Datei auch hochladen!
[Fehlerhafte Apps.pdf](https://github.com/faustedition/faust-gen-html/files/2085781/Fehlerhafte.Apps.pdf)


markusciupke wrote (09-06-18, afternoon):

> Natürlich müsst ihr rausfinden, woher der Fehler stammt. Das ist rückwärts gesehen notwendig. Auch um zu eruieren, ob es systematische Fehler oder auch nur einzelne weitere Fehler gibt. Klar. – Aber für mich ist vorwärts gesehen wichtig, dass ich weiterarbeiten kann, und dafür muss ich die Fehler, die wir jetzt sehen, schon vor der 1. Fahne korrigieren. Und das muss ich manuell tun, und das muss natürlich gründlichst geprüft werden. Aber: ich muss weiterarbeiten. Deswegen die Bitte, mir alle auszuführenden Korrekturen auf eine gut umzusetzende Art (also mit Korrekturzeichen auf einem Ausdruck) mitzuteilen. – Danke! 

markusciupke wrote (09-06-18, afternoon):

> > Das ist auch nach vorwärts notwendig.
Wer sagt denn, dass jetzt alle Fehler gefunden sind. Deswegen müssen die Ursachen geklärt werden, damit weitere fehlerträchtige Stellen identifiziert und geprüft werden können. Und es geht dann ja auch noch um den Faust II.

> Ganz  klar. Das habe ich doch auch geschrieben. Da ist doch gar kein Widerspruch:

> Natürlich müsst ihr rausfinden, woher der Fehler stammt. Das ist rückwärts gesehen notwendig. Auch um zu eruieren, ob es systematische Fehler oder auch nur einzelne weitere Fehler gibt.

> Was  ich aber auch sage ist, dass ich jetzt mit dieser Datei weiterarbeiten will und dafür die Korrekturen ausführen muss. Und um das möglichst korrekt zu machen, bitte ich euch um eure Unterstützung. Insofern: Bitte tragt das zu Korrigierende auf Ausdrucken der Seiten ein und sendet Scans davon an mich. Oder sendet mir den Text der kompletten Fußnoten, so wie er sein soll als Word-Datei. Oder ist soll ich den Text in der Online-Datei suchen, kopieren und einsetzen? Das kann ich auch machen.

> Und: wenn ihr weitere Fehler findet, oder wenn ich weitere Fehler finde, dann werden diese natürlich ebenfalls sofort korrigiert. Es war doch zu erwarten, dass noch Fehler enthalten sind.

**Comment by dietmarpravida** [comment]
Übertrag von #511

markusciupke wrote (Samstag, 9. Juni 2018 21:32:10)

> Ich hoffe, der Ort ist für das folgende richtig. Jedenfalls beziehe ich mich auf obige Liste. 

> Ich habe mir alle Stellen der obigen Liste genau angesehen und dazu folgende Bemerkungen:

> 21: Das Alpha ist da, es musste nur mit der richtigen Schrift versehen werden, damit es auch im Satz erscheint. Das ist geschehen.

> 666: Im App zu 666 war auch »mon Gö« nicht kursiv. Außerdem habe ich folgende editorischen Abkürzungen im Apparat kursiviert:
> emend: 2633, 3369
> konj: 666, 719,2302, vor 2392, 2455, 2791, 2921, 3395, 3557, 4051, 4261, TTF 16
> mon: 4501
> mon Gö: 666
> mon Re: 4501
> vorschl: nach 3409

> 988: A ist nun getilgt. – In der Online-Datei ist es aber da.

> vor 2465: Ist eingefügt. Soll »Die Hexe« im Apparat als »Auftritt« formatiert werden (so habe ich es gemacht) oder normal groß/klein?

> vor 2540: Ist eingefügt. Soll »Die Hexe« im Apparat als »Figur« formatiert werden (so habe ich es gemacht) oder normal groß/klein? – In der Online-Datei fehlt der Eintrag bei 1c*

> vor 2709: Bei Apparat-Einträgen ohne Lemmaklammer (vor 2366-2377, 2540-2552, 2740-2741, 3356-3357, 3550-3551, 3871-3911, 3974-3977, 3994-4015 und 3994-4015) beginnt der kursive Apparattext nach 2 LZ immer mit Großschreibung. Das habe ich hier der Einheitlichkeit wegen auch so gemacht. – Die Wörter sind auch in der Online-Datei recte.

> 3179: Das habe ich entsprechend korrigiert. – In der Online-Datei fehlt zwischen »a« und »1« ein Leerzeichen.

> 3356: Ist eingefügt. Parallel zu den anderen Apparat-Einträgen ohne Lemma (siehe oben zu vor 2709) habe ich die Lemmaklammer entgegen dem Eintrag in der obigen Liste weggelassen und das »Zwei« groß geschrieben. Der Apparat ist insofern nicht ganz korrekt als in H5 »Und ich der Gott verhasste | Hatte nicht genug^« steht. Diese Informationen zu Schreibung und Interpunktion gehen gegenüber dem langen Apparat-Eintrag verloren. Ist das so gewollt? Der lange Eintrag steht zum direkten Vergleich darunter.

> 3990-3903: Ist eingefügt. Parallel zu den anderen Apparat-Einträgen ohne Lemma (siehe oben zu vor 2709) habe ich die Lemmaklammer entgegen dem Eintrag in der obigen Liste weggelassen. Die uneinheitlichen Maßangaben (1/2 cm und 1,0 cm) habe ich zu 5 mm und 10 mm vereinheitlicht (möglich  wäre auch 0,5 cm und 1,0 cm bzw. 1/2 cm und 1 cm). Eine Millimeter-Angabe ist aber nach meiner Meinung hier die beste. Um die Ziffern der Vers-Angaben und der Millimeter-Angaben aufeinanderfolgen zu lassen, habe ich jeweils ein »um« eingefügt.

> Hier sind die entsprechenden Seiten (von den kursivierten editorischen Angaben ist hier nur der Apparat zu 666 dabei):

> [Korrigierte Apps.pdf](https://github.com/faustedition/faust-gen-html/files/2087265/Korrigierte.Apps.pdf)

**Comment by dietmarpravida** [comment]
@markusciupke Beachtest du bitte auch die Korrekturen, die ich am 9. Juni 2018 20:16:06 gesandt habe? Danke.

**Comment by markusciupke** [comment]
Nachfrage zu »nach 2464«: Sowohl in der Online-Datei als auch in der nach Typen sortierten Apparat-Liste steht bei den vier Apparat-Einträgen immer »before 2465« bzw. »vor 2465«. Da diese BA auch im endgültigen Satz oben auf der Seite vor Vers 2465 stehen wird, wäre das nach meiner Meinung besser als jeweils »nach 2464«. Einverstanden?

**Comment by markusciupke** [comment]
Zwei Nachfragen zu 3356-3357: 
1. Parallel zu den anderen Apparat-Einträgen ohne Lemma habe ich das »Zwei« groß geschrieben. In Ordnung?
2. Der Apparat ist nicht korrekt, insofern als in H5 »Und ich der Gott verhasste | Hatte nicht genug^« steht. Diese Informationen zur in H5 gegenüber S A B Ba C1 und C3 abweichenden Schreibung und Interpunktion gehen gegenüber dem langen Apparat-Eintrag verloren. Ist das so gewollt?

**Comment by markusciupke** [comment]
Die letzte Nachfrag zu 3356-3357 hat sich erledigt. Ich habe die Antworten von @dietmarpravida weiter oben übersehen.

**Comment by markusciupke** [comment]
Zu vor 2465 und vor 2540: @dietmarpravida hat in seiner Korrektur jeweils »DIE HEXE« angewiesen. Da hier nun schon Versalien angewiesen sind, ist meine Frage, ob hier auch das jeweilige ZF zugewiesen werden soll. Vielleicht ist eine elegante Lösung hier im Apparat »die Hexe« (»die« klein / »Hexe« groß/klein) und kursiv zu setzen?

**Comment by markusciupke** [comment]
vor 3208: »Marthe« hat hier das ZF »Figur«. »Marthe« ist allerdings in D1 etwas größer gedruckt und muss deswegen parallel zu Margarete, Faust und Mephistopheles das ZF »Auftritt« erhalten. Die WA macht es auch so. Einverstanden?

**Comment by dietmarpravida** [comment]
> Nachfrage zu »nach 2464«: Sowohl in der Online-Datei als auch in der nach Typen sortierten Apparat-Liste steht bei den vier Apparat-Einträgen immer »before 2465« bzw. »vor 2465«. Da diese BA auch im endgültigen Satz oben auf der Seite vor Vers 2465 stehen wird, wäre das nach meiner Meinung besser als jeweils »nach 2464«. Einverstanden?

Bitte alles genau so machen, wie es in den Korrekturseiten steht.


```

**Comment by dietmarpravida** [comment]
> vor 3208: »Marthe« hat hier das ZF »Figur«. »Marthe« ist allerdings in D1 etwas größer gedruckt und muss deswegen parallel zu Margarete, Faust und Mephistopheles das ZF »Auftritt« erhalten. Die WA macht es auch so. Einverstanden?

Nein, das ist eine einfache Sprecherangabe.

**Comment by markusciupke** [comment]
Ich habe mit einem Fadenzähler nachgemessen. Marthe ist vor 3208 um ca. 0,5 mm höher (miss mal nur das M) und um ca. 1 mm breiter. Die Unterschiede bei Margarete vor 3204 sind auch nur marginal.

**Comment by dietmarpravida** [comment]
Übertrag von #514 

dietmarpravida wrote:



> > Im Apparat zu 2769 steht »D.3« und »D.4«. Ist korrigiert zu D3 und D4 (Ziffern hochgestellt).

> mental note, @dietmarpravida: Muss hier nicht auch überall D.2 stehen?

**Comment by dietmarpravida** [comment]
> Ich habe mit einem Fadenzähler nachgemessen. Marthe ist vor 3208 um ca. 0,5 mm höher (miss mal nur das M) und um ca. 1 mm breiter. Die Unterschiede bei Margarete vor 3204 sind auch nur marginal.

Mach dir darüber bitte keinen Kopf.

**Comment by dietmarpravida** [comment]
`4051[]{} 4051] <sp><speaker>Faust**.**</speaker><l n=4051_I>Verflucht Geſchnarr!</l></sp><sp><speaker>Mephistopheles**.**</l></speaker><l n=4051_F>Man muß ſich dran gewöhnen.</l></sp> konj faust://bibliography/resenhoefft1975#Resenhöfft [Typ 3*]`

Punkte entfernen (stehe auch im App zu 3550-3551 nicht) !

**Comment by markusciupke** [comment]
Vers 1194: In der am 7.6. gesandten IDML-Datei hat dieser Vers das Absatzformat »Vers Einrückung«. Richtig wäre »Vers Einrückung Abstand«. So ist es in den Drucken und auch in der Online-Ausgabe.
Ist jetzt korrigiert. Woher kommt der Fehler?

**Comment by gerritbruening** [comment]
> »Vers Einrückung«. Richtig wäre »Vers Einrückung Abstand« ... Woher kommt der Fehler?

Danke für den Hinweis, das würde mich auch interessieren. Kam das öfter vor oder scheint der Fall singulär zu sein? Nicht dass uns viele Versgruppenabstände verloren gegangen sind.

**Comment by markusciupke** [comment]
Mehr habe ich bislang nicht gefunden. Sonst hätte ich es hier vermerkt.

**Comment by markusciupke** [comment]
Im Apparat zu 2633 steht als Typ »_(2a*)_«. Richtig ist doch wohl »_(IIa*)_«.
Online und in der am 7.6. gelieferterten IDML-Datei steht: »_[2a*]_«.

**Comment by dietmarpravida** [comment]
ja, beruht auf einem Fehler in der Ausgangsdatei

**Comment by markusciupke** [comment]
Von mir wird hier nichts mehr kommen.

**Comment by dietmarpravida** [comment]
@gerritbruening ist das hier, soweit es den Milestone print angeht, erledigt?

**Comment by gerritbruening** [comment]
Ich denke, das wird für immer dunkel bleiben oder der späteren Forschung überlassen werden müssen.
