### ISSUE TITLE
Vers Einrückung Abstand für 1283, 1298, 1304

### ISSUE THREAD

**Issue by markusciupke** [faustedition/faust-gen-html#525]
Ich weiß nicht, ob es hierzu schon ein Issue gibt. Deswegen hier ein eigenes.
Folgendes ist mir aufgefallen:
1273 hat in D1  keinen Abstand nach oben (auch in A?), so auch im KT.
1283, 1298 und 1304 haben in D1  jeweils einen Abstand nach oben (auch in A?), nicht aber im KT.
Soll hier im KT immer AF Vers Einrückung Abstand zugewiesen werden.
Und, egal wie es gesetzt werden wird: Muss dazu nicht im Apparat ein Eintrag gemacht werden, in dem diese Unregelmäßigkeit nachgewiesen wird?

**Comment by markusciupke** [comment]
Im Online-Text ist überall Vers Einrückung Abstand eingerichtet. So mache ich es zunächst auch.

**Comment by dietmarpravida** [comment]
zu 1273: welchen Abstand haben wir denn vor 2759?
1283, 1298 und 1304 jeweils mit den sonst bei Strophen üblichen Abstand, würde ich sagen

**Comment by markusciupke** [comment]
vor 2759 haben wir keinen vergrößerten Abstand.1283, 1298 und 1304 mit Vers Einrückung Abstand (üblicher Abstand ist 1/2 LZ). Was ist mit  1273? D1 hat hier keine Abstand. WA und FA gleichen hier an. So lassen?

**Comment by gerritbruening** [comment]
>  1283, 1298 und 1304 haben in D1 jeweils einen Abstand nach oben (auch in A?), nicht aber im KT.

Das scheint mir eine Unregelmäßigkeit in Satz zu sein, auf diese Weise könnten allerhand Versgruppenabstände verlorgen gegangen sein. Bitte unter die Unregelmäßigkeiten eintragen.

http://dev.faustedition.net/document?sigil=A&page=72&view=facsimile_text#l1273 scheint mir der einzige fragliche Fall zu sein.

**Comment by markusciupke** [comment]
Und was tun? 
Genau wie in A? 
Nachteil: Dann haben wir  eine setzerische Unregelmäßigkeit auch im KT bewahrt. 
Vorteil: Ihr braucht keinen zusätzlichen Apparat-Eintrag zu formulieren.
Mit Abstand? Also angleichen wie in WA und FA?
Vorteil: Es ist setzerisch korrekt.
Nachteil: Die Änderung gegenüber A usw. muss im Apparat verzeichnet werden.

**Comment by dietmarpravida** [comment]
Mir scheint das keine Unregelmäßigkeit in A zu sein, was nicht heißt, dass wir keinen Abstand machen dürfen. Ich sehe den Druck aber nochmal durch.

**Comment by dietmarpravida** [comment]
Ein vergleichbarer Fall ist der Übergang von 2289 (Kurzvers) zu 2290 (Langvers) "Hier ist ein Wunder, glaubet nur! / Nun zieht die Pfropfen und genießt!", wo sich in _S A_ _etc_ ebenfalls kein vertikaler Abstand findet. In der online-Ausgabe aber mit Abstand (d.h. mit `<lg/>` kodiert). Dann machen wir halt in Gottes Namen einen Abstand, obwohl ich eigentlich nicht dafür bin.  @gerritbruening Muss das in der Fußnote kommentiert werden?


`

**Comment by markusciupke** [comment]
Ich bin ja selbst unentschieden. Ich wollte nur darauf hinweisen. Wenn du nicht dafür bist, lasse ich es ohne Abstand.

**Comment by dietmarpravida** [comment]
Hm, so einfach ist das nicht, da es sich nicht nur um diese eine Stelle handelt und auch der online-Text betroffen ist (der den Abstand hat).

**Comment by markusciupke** [comment]
In Ordnung. Hab ihn gerade wieder reingemacht und speicher jetzt das ganze ab.

**Comment by gerritbruening** [comment]
> Das scheint mir eine Unregelmäßigkeit in Satz zu sein, auf diese Weise könnten allerhand Versgruppenabstände verlorgen gegangen sein.

Damit meinte ich nicht Cotta, sondern die IDML.
Ich sehe nicht, warum ein Abstand sein muss, auch online könnte das geändert. Hatte das damals als Versgruppe interpretiert.

**Comment by gerritbruening** [comment]
`lg/following-sibling::*[1][self::lg]` hat ergeben, dass es tatsächlich nur diese beiden Fälle zu geben scheint (`lg` direkt hintereinander). Wie gesagt, ich kann die `lg`-Struktur wenn gewünscht auflösen.

**Comment by markusciupke** [comment]
Jetzt ist das doch ein Fall für die Korrektur in der 1. Fahne!

**Comment by dietmarpravida** [comment]
Bei 1283 ist im jetzigen Satz wegene Seitenwechsels nicht erkennbar, dass hier ein Versgruppenabstand ist, ws wegen 1273 etwas misslich ist; aber wir fangen jetzt nicht an, hier einrücken zu wollen, richtig @gerritbruening ?

sonst ist jetzt alles okay

**Comment by gerritbruening** [comment]
1283 lassen wir so, wenn es für dich OK ist.
