### ISSUE TITLE
Rückfluss aus ID

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#527]
@pglatza, mit Blick auf Unebenheiten wie 
* #387 
* https://github.com/faustedition/faust-gen-html/issues/511#issue-329826924

etc. wäre es uns lieb, aus der von @markusciupke erstellten ID-Datei einen diff-baren Rückfluss zu bekommen, z.B. IDML. Geht das einfach durch so etwas wie "Speichern unter" (schaust du mal danach, @markusciupke?). Oder was wäre da best practice?

**Comment by markusciupke** [comment]
Ja, ich kann mit Speichern unter eine IDML-Datei aus der ID-Datei erstellen. Soll ich das gleich machen oder wenn ich mit Faust I durch bin? Das wird spätestens morgen der Fall sein.

**Comment by gerritbruening** [comment]
GB:
> ich habe den IDML-Output deiner Pipeline mit dem Satzoutput von Markus 
> verglichen, und leider scheint das Markup jeweils ganz anders 
> gestrickt zu sein.
> Sogar die Tabs am Anfang von Textinhalten sind anders verteilt. Nach 
> der Pipeline hatten sie eigene CharacterStyleRange-Elemente, jetzt 
> stehen sie direkt vor den Wörtern. Weder das eine noch das andere ist 
> sachlich falsch, aber ein Vergleich, der das Markup mit einschlösse 
> (Formatvergaben und - reichweiten), scheint mir dadurch unmöglich zu sein.
> Das ist wohl nichts, was man irgendwie beeinflussen könnte, oder?
> Es scheint mir aber ein ziemliches Hindernis zu sein, wenn man in 
> Richtung roundtripping arbeiten wollte.

**Comment by gerritbruening** [comment]
Die nächste Idee war, in "Speichern unter" (oder wie immer das in ID heißt), ein normales Textverarbeitungsformat auszuprobieren (docx oder rtf oder was ID anbietet) und zu schauen, ob man damit weiterkommt.
Jetzt noch einmal anders:
@markusciupke, könntest du die gelieferte IDML zuerst in deine ID-Instanz einlesen und dann nochmals nochmals unter IDML speichern?  Meine Annahme ist, dass die oben beschriebenen Unterschiede dann alle passieren und kein so großer Unterschied mehr zur Satzdatei besteht wie beim ursprünglichen, in Transpect generierten IDML.

**Comment by gerritbruening** [comment]
Ich adde @thvitt, der bei so etwas auch immer gute Ideen hat.
Zum Zwischenstand: die durch öffnen und speichern unter entstandene IDML lässt sich schon besser mit der IDML der ersten Fahne vergleichen. Ein opaker Zwischenschritt allerdings, schlecht.

**Comment by thvitt** [comment]
Funktioniert’s denn wenigstens erstmal mit dem reinen Text ohne Berücksichtigung des Whitespace?

Ist auch eine Frage, was geprüft werden soll. Man könnte vielleicht auch z.B. im Ausgangs- und im Nachfeinsatz-IDML die Nicht-Whitespace-Only-Textinhalte tokenisieren und für jedes Token Zeichen- & Absatzformat festhalten, um die Unterschiede zu vergleichen. So à la

Token | Absatzformat | Zeichenformat
---------|--------------------|---------------------
Faust | Titel (Faust)    |  [No character style]
Eine  | Untertitel (Faust) | [No character style]
Tragödie | Untertitel (Faust) | [No character style]

Man könnte auch einen Postprocessing-Schritt überlegen, der aufeinanderfolgende Tokens mit denselben Styles zusammenfasst. Kommt ein wenig drauf an, wie unterschiedlich das markup tatsächklich ist und wieviel Zeit man investieren will …

**Comment by gerritbruening** [comment]
> Funktioniert’s denn wenigstens erstmal mit dem reinen Text ohne Berücksichtigung des Whitespace?

Habe ich noch nicht probiert, gleich nach höherem gestrebt.
Die Tabelle klingt für mich nach einer guten Idee, aber auch Arbeit. Welche identischen Formate zusammengefasst werden und welche nicht, ist für mich im Moment nicht durchschaubar. Mein Eindruck ist nur, dass transpect vieles noch nicht zusammenfasst, aber ID dann.
Ich würde jetzt als nächstes gern ein Textverarbeitungsformat probieren, dass kompaktes Markup ergibt (docx, rtf). Vielleicht kommen da irgendwelche Feinheiten nicht rüber, aber vielleicht kann @pglatza jemand in seiner Firma fragen, wie das am leichtesten geht (Dokumentinhalt von ID in Word reinkopieren geht jedenfalls, das hat @markusciupke ausprobiert, und da kommt schon sehr viel rüber; zur Noten nehmen wir einfach das).

**Comment by thvitt** [comment]
Das ist identisch zu #497, oder?

**Comment by gerritbruening** [comment]
Ich denke schon, was besseres ist jetzt nicht erreichbar.
