### ISSUE TITLE
Remove xml:space when redundant

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#53]
For general information, see https://wiki.tei-c.org/index.php/XML_Whitespace.

For the genesis of the problem, see https://faustedition.uni-wuerzburg.de/wiki/index.php/Kodierungsregeln#Kodierung.2FNormierung_von_Leerzeichen

For possible solutions, see https://faustedition.uni-wuerzburg.de/wiki/index.php/Benutzer:Bruening#Whitespace

We don't have to remove `xml:space` in the original source data, but we should remove it in the TEI P5 output that is offered for download (see https://github.com/faustedition/faust-web/issues/214).

**Comment by gerritbruening** [comment]
| match | output |
|--------|--------|
|`c[@xml:space="preserve"]`       |  ` ` (at least one blank) |
|       |        |
|       |        |

**Comment by thvitt** [comment]
There are [quite a lot of instances of `<c xml:space="preserve">`](https://github.com/faustedition/faust-gen-html/files/2348666/c-space-preserve.zip) …

**Comment by gerritbruening** [comment]
Yes, incredible. Bizarre fallacy. Consequence of an early loss of whitespace which was never fully understood.

**Comment by gerritbruening** [comment]
But keep `c[@xml:space]` if `c` es empty, because it's pretty sure that significant whitespace still got lost some way and has to be restored. So if you encounter this, replace it by one blank.

**Comment by thvitt** [comment]
I do not understand your last comment: `<c xml:space='preserve'/>` is meaningless since there is no space to preserve. Or what’s your definition of empty?

**Comment by thvitt** [comment]
BTW this needs to be checked with Moritz’ rendering

**Comment by gerritbruening** [comment]
> I do not understand your last comment: `<c xml:space='preserve'/>` is meaningless since there is no space to preserve. Or what’s your definition of empty?

Well, my hypothesis would be that these empty `c` once were `<c xml:space='preserve'> </c>` (with whitespace in it). It may have happened that some application did not honor this since this was whitespace only content, and removed it.
