### ISSUE TITLE
App entries outside chunk elements

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#530]
As [has been reported earlier](https://github.com/faustedition/faust-gen-html/issues/511#issue-329826924), the app with the id `app.before_2465_a.before` was dropped when transformed to IDML. I suspect this is due to the fact that this apparatus entry is not descendant of a chunk element (is this correct, @pglatza?).
This will be repaired manually for the printed edition. But I would like to know:
* Is it intended that this app entry is not moved into a chunk element?
* Are there any consequences in the online text rendering that we have to be aware of?
* How can I query whether there are similar cases in Faust II?

**Comment by gerritbruening** [comment]
> 8 Apparateinträge außerhalb von Zeilen

Wer lesen kann, ist im Vorteil!

**Comment by pglatza** [comment]
Eigenartig, ich finde aktuell nur 6 (`//note[@type = 'textcrit'][not(ancestor::*/name() = ('head', 'l', 'p', 'speaker', 'stage'))]`):
 - app.before_2465_a.before
 - app.after_6062.only-app
 - app.after_6358.only-app
 - app.6362.after
 - app.after_11287.regumi21
 - app.before_12045_b.iv

Es betrifft mMn solche Apparateinträge, die zwischen Block-Elementen (=später: Absätze) stehen. Daher der obenstehende XPath mit Selektierung aller Apparateinträge, welche nicht in einer Überschrift, einem Vers, Sprecher oder einer Bühnenanweisung stehen.


> 8 Apparateinträge außerhalb von Zeilen
Woher stammt die Info? Konnte zunächst in Issues/Mails nicht auf anhieb etwas finden. Gibt es einen XPath-Ausdruck dazu?

- - -
Eine Abfrage der Elternelemente aller Apparateinträge (`distinct-values(//note[@type = 'textcrit']/parent::*/name())`) bringt:

- `l`
- `stage`
- `speaker`
- `div`
- `head`
- `p`
- `ab`
- `sp`
- `note`

**Comment by gerritbruening** [comment]
Danke für die XPath-Ausdrücke, wieder was dazugelernt!
Das sind die 8 Treffer:
<table><thead><tr><th>Referenz</th><th>@n</th><th>f:ins/@place</th><th>erstes eingefügtes Element</th><th>@n davor</th><th>@n danach</th></tr></thead><tbody><tr><td>vor 2465</td><td>before_2465_a</td><td>before</td><td>move</td><td></td><td></td></tr><tr><td>vor 2465</td><td>before_2465_a</td><td>before</td><td>move</td><td></td><td></td></tr><tr><td>4</td><td>ttf_4</td><td></td><td></td><td></td><td></td></tr><tr><td>16</td><td>ttf_16</td><td></td><td></td><td></td><td></td></tr><tr><td>31</td><td>ttf_31</td><td></td><td></td><td></td><td></td></tr><tr><td>34</td><td>ttf_34</td><td></td><td></td><td></td><td></td></tr><tr><td>42</td><td>ttf_42</td><td></td><td></td><td></td><td></td></tr><tr><td>vor 6363</td><td>6362</td><td>after</td><td></td><td>6362</td><td>6363</td></tr></tbody></table>

**Comment by gerritbruening** [comment]
Die Frage ist für mich jetzt im Grunde nur, warum der Eintrag `app.before_2465_a.before`  verloren ging, damit ich weiß, wo ich beim Faust II aufpassen muss oder was geschehen könnte, damit so ein Fehler nicht mehr passiert.

**Comment by pglatza** [comment]
Es kam zum Verlust, da ich in den mapping-Regeln der Synthese mich nicht, bzw. nur um einen solchen Fall gekümmert hatte.
Das was zwischen Absätzen 'hängt', schafft es nicht nach InDesign.

**Comment by gerritbruening** [comment]
Da `vor 6363` richtig ankommt, schließe ich das hier.
