### ISSUE TITLE
Ignore abbr

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#531]
@pglatza, this is maybe similar to #494.
`abbr` has undermined the assignment of the `Kursiv` format in the IDML transformation, see @markusciupke|s report https://github.com/faustedition/faust-gen-html/issues/521#issuecomment-396063942.
As `abbr` is frequently used in Faust I, a fix (if feasible) would be very much appreciated.

**Comment by pglatza** [comment]
Sure! The `abbr` element is dissolved earlier, now (revision 77).
Results to 57 changes. You can check it yourself – the online conversion is up to date.

**Comment by gerritbruening** [comment]
Yes, thanks!

**Comment by gerritbruening** [comment]
Yes, thanks!
