### ISSUE TITLE
CharacterStyle/Figur and CharacterStyle/Auftritt not rendered in ID sometimes 

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#532]
@pglatza, as @markusciupke reports, some passages where not assigned the expected format in ID.
* https://github.com/faustedition/faust-gen-html/issues/514#issuecomment-396025671
* https://github.com/faustedition/faust-gen-html/issues/514#issuecomment-396026292

I have checked the IDML, and there I see the following, which seems perfectly correct:

```xml
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Figur">
            <Content>Das Volk</Content>
         </CharacterStyleRange>
```
and
```xml
         <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Auftritt">
            <Content>Pudel</Content>
         </CharacterStyleRange>
```
I would like to avoid that similar problems appear in Faust II. Can you explain this phaenomenon?

**Comment by pglatza** [comment]
With revision 79 (upload converter is productive) there are many positive changes for `milestone:msfaustii`.

The reason and solution was, that a lot of whitespace cleanups were necessary (I should have done that for a long time) as another preprocessing step before synthesizing IDML.

**Comment by gerritbruening** [comment]
I see many change, to many for me to comprehend. Thanks, anyway.
I would still be interested to know why the elements mentioned above did not appear as expected in ID, although they seemed to be correct even before this last change.
