### ISSUE TITLE
Apparat zu Vers 3550-3551

### ISSUE THREAD

**Issue by markusciupke** [faustedition/faust-gen-html#534]
Mit der Einrichtung des Apparats zu 3550-3551 bin ich noch nicht glücklich. Wenn man den Vers wie in H5 darstellt, ist eine Hinzusetzung der Verszahl 3550 irreführend, weil es in H5 Vers 1242 ist.
Gibt es nicht eine andere Möglichkeit? Mehr wie im Apparat zu 2709:
»_ein antilabischer Vers in H5  zwei Verse S A B Ba  (II a)_« ?

Außerdem geht in meinen Augen bei dieser Form des Apparats unter, dass sich diese Passage auch im Wortlaut von jener in H5 unterscheidet. Die ganze Aufmerksamkeit wird aber auf die Antilabe gelenkt. Kann hier nicht angenommen werden, dass es sich um eine von Goethe intendierte Änderung handelt und nicht um einen setzerischen Eingriff oder ein setzerisches Versehen?

Habt ihr eine Idee?
[App 3550-3551 neu.pdf](https://github.com/faustedition/faust-gen-html/files/2089863/App.3550-3551.neu.pdf)

**Comment by markusciupke** [comment]
In Ordnung. Danke.

**Comment by dietmarpravida** [comment]
schließe ich jetzt mal
