### ISSUE TITLE
render footnotes in testimonies

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#536]
Footnotes in testimonies may be encoded in different ways:
* at the end of the document with an xml:id that is pointed to
* directly embedded in the text flow

The first is a legacy from the zeno.org data, the latter is more canonic and comes directly from the TEI docx conversion.
@thvitt, is it feasible to make the rendering robust against such dialect differences?

**Comment by thvitt** [comment]
we would need a spec of what is encoded exactly how and how it should be rendered.

Footnotes in original sources typically need to be converted to end notes (which is what Editura did for the zeno data). _End_ requires a definition of where the end is (e.g., `<text>` or outermost div etc.), additionally there’s the question of the footnote sign.

**Comment by gerritbruening** [comment]
Here's a snippet from the original encoding:
```xml
                <lb/>Pasquill hab’ ich nirgends kein
                    <note place="foot" n="1">* Sprechweise wie in <persName>Schiller</persName>’s <title>Wallenstein</title>’s Tod III, 15, 157: „Alles 
                        <lb/>ist Vartei und nirgends kein Richter!“ oder in <persName>Goethe</persName>’s Meeresstille:
                    <lb/>„Keine Luft von keiner Seite.“</note>* 
                Wort gehört, und kann auf 
```
It's not yet perfect and will be given a polish in the near future.

**Comment by thvitt** [comment]
so the footnote sign is `1` and the `*` are unwanted artefacts?

**Comment by gerritbruening** [comment]
The zeno TEI looks like this:
```xml
               <l> Für Dich ist seine Bürde leicht.<anchor xml:id="N57"/>
                  <ref target="#F57">
                     <hi rend="sup">1</hi>
                  </ref>
               </l>
```
with a corresponding
```xml
            <p>
               <anchor xml:id="F57"/>
               <ref target="#N57">1</ref> Diese Verse sind wohl nicht ganz richtig, obgleich ich sie
               oft ins Gedächtniß zurückgerufen habe. Nur den Reim glaube ich als ächt bezeichnen zu
               können, und den Sinn gewiß.</p>
```
at the end of the respective `div` element.

**Comment by gerritbruening** [comment]
> so the footnote sign is `1` and the `*` are unwanted artefacts?

The `*` is from the source:
![grafik](https://user-images.githubusercontent.com/10358005/41284103-aa57fdb0-6e38-11e8-84ac-0698ec9f670c.png)
![grafik](https://user-images.githubusercontent.com/10358005/41284131-bbf0b2b0-6e38-11e8-999a-786ba0d08254.png)

**Comment by thvitt** [comment]
In the example from your comment above:

```xml
<note place="foot" n="1">* Sprechweise wie in <persName>Schiller</persName>’s <title>Wallenstein</title>’s Tod III, 15, 157: „Alles 
                        <lb/>ist Vartei und nirgends kein Richter!“ oder in <persName>Goethe</persName>’s Meeresstille:
                    <lb/>„Keine Luft von keiner Seite.“</note>*
```

where does the n come from? According to [the TEI guidelines](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-note.html), I think this might be a valid (and usable) encoding:

```xml
<note place="foot" anchored="true" n="*">Sprechweise wie in <persName>Schiller</persName>’s <title>Wallenstein</title>’s Tod III, 15, 157: „Alles 
                        <lb/>ist Vartei und nirgends kein Richter!“ oder in <persName>Goethe</persName>’s Meeresstille:
                    <lb/>„Keine Luft von keiner Seite.“</note>
```

**Comment by sandrakrause** [comment]
Would the footnotes be clickable if we use this encoding? (I don't really know what "`anchored`" is referring to? Would there be a link between the `*` in the text an the footnote?)
Because I think clickable links that lead to the corresponding footnote are helpful for readers. Especially when they are at the end of a long text. 

On a sidenote: I noticed, that in `crueger1884.xml` the footnotes are not displayed in the edition. My guess would be, that it's because the footnotes are collected in a seperated <div>? Should probably be integrated in the text-div then?

**Comment by thvitt** [comment]
> Would the footnotes be clickable if we use this encoding? (I don't really know what "`anchored`" is referring to? Would there be a link between the `*` in the text an the footnote?)
> Because I think clickable links that lead to the corresponding footnote are helpful for readers. Especially when they are at the end of a long text. 

needs to be implemented, but yes. anchor means there is a footnote sign visible in the original transcribed text, from the TEI guidelines link above:

> The anchored attribute indicates whether any explicit location is given, whether by symbol or by prose cross-reference. The value true indicates that such an explicit location is indicated in the copy text; the value false indicates that the copy text does not indicate a specific place of attachment for the note. If the specific symbols used in the copy text at the location the note is anchored are to be recorded, use the n attribute.

> On a sidenote: I noticed, that in `crueger1884.xml` the footnotes are not displayed in the edition. My guess would be, that it's because the footnotes are collected in a seperated `<div>`? Should probably be integrated in the text-div then?

Yes, would be easiest. We retain only the div surrounding each testimony.

**Comment by sandrakrause** [comment]
Okay, I think I got it now. Thank you.

All right, I will change that in crueger1884 right away.

**Comment by gerritbruening** [comment]
I find notes at the bottom very book-like (except for that you won't be able to simultaneously see both). Can't we have notes on the left margin?

**Comment by thvitt** [comment]
I have not seen the ) and just done what the guidelines’ element page says. n="*)" would be possible as well, of course.

The zeno-like encoding does not make the footnotes explicit at all, so they are just rendered as regular text with cross-references. 

The left margin of the testimony display contains the metadata record, and sicne the apparatus is on the right, that would be a better place for margin notes, wouldn’t it?

**Comment by gerritbruening** [comment]
> on the right, that would be a better place for margin notes, wouldn’t it?

Yes, much better! But I didn't dare to propose this, since there is no free place there at the moment.

I still think that `*)` and the like are better stored as text rather than as attribute values, especially when layout features come in that demand for markup (superscript and the like). This conforms to a general recommendation that I found very reasonable:
> Characters appearing in the source text should typically be given as character data content in the document, rather than as the value of an attribute; again, rendition text may optionally be excepted from this rule.
(http://www.tei-c.org/release/doc/tei-p5-doc/en/html/DI.html)

**Comment by thvitt** [comment]
In any margin means that we either have two different styles for footnotes or that we must try to detect and reformat the zeno-style pseudo-footnotes

**Comment by sandrakrause** [comment]
Gibt es hier jetzt eine finale Entscheidung?
Und gibt es noch etwas, was wir da für die 1.0 tun können?

**Comment by gerritbruening** [comment]
Ich im Moment nicht, fürchte ich.

**Comment by thvitt** [comment]
ich kann da nichts mehr tun
