### ISSUE TITLE
Wechsel von eingerückten und nicht eingerückten Versen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#539]
`lg[not(@rend='indented')]/following-sibling::*[1][self::lg][@rend='indented']` should be `Vers Einrückung Abstand` in the result, but this does not see to happen, as [@markusciupke reports](https://github.com/faustedition/faust-gen-html/issues/521#issuecomment-397190394).

It seems as if the succession of `lg[@rend='indented']` and `lg[not(@rend='indented')]` would undermine the normal rules for `lg` handling. Is this correct, @pglatza? Is there a quick fix for this? Otherwise we can keep track of the cases manually.

**Comment by gerritbruening** [comment]
Für @markusciupke bemerke ich, dass folgende Fälle im Faust I betroffen sind:
- [ ] 1194 (hattest du genannt)
- [ ] 1273 (zufälligerweise richtig so, weil A keinen Abstand hat, was hattest du mit @dietmarpravida jetzt beschlossen?)
- [ ] 1283 
- [ ] 1298
- [ ] 1304

@dietmarpravida, @markusciupke, bitte abhaken, wenn kontrolliert und gelöst.

**Comment by markusciupke** [comment]
In allen 5 Fällen ist derzeit ein Abstand.
Vor 1194 muss nach A ein Abstand sein.
Vor 1273 steht nun parallel zu 1283, 1298 und 1304 ein Abstand. In A und der Online-Ausgabe steht hier jeweils ebenfalls ein Abstand. Vor 2290 steht wiederum parallel zu diesen vier Fällen ein Abstand, obwohl dieser in A nicht gegeben ist. Die Entscheidung, speziell über 1273 und 2290 müsst ihr fällen.

**Comment by pglatza** [comment]
*ack*. Mit r78 habe ich die Korrektur vorgenommen. Upload-Formular ist aktuell.

**Comment by gerritbruening** [comment]
Danke!

**Comment by gerritbruening** [comment]
@dietmarpravida, vor 
[11432](http://dev.faustedition.net/document?sigil=2_H&page=357&view=facsimile_text#l11432) ist eigentlich kein Versgruppenabstand, oder? Im Grund bin ich dafür, hier keine Ende einer Versgruppe zu markieren, sondern nur eingerückte Verse.

**Comment by dietmarpravida** [comment]
Schöne macht hier auch keinen Abstand, ich würde auch keinen machen

**Comment by gerritbruening** [comment]
Schöne macht allerdings auch 12013 keinen Abstand, wo man vielleicht doch einen machen sollte, oder?

**Comment by markusciupke** [comment]
Wenn ihr vor 11432 keinen Abstand macht, was auch ich gut fände, dürfte wohl auch vor 2290 kein Abstand stehen (hier macht Schöne einen – die WA allerdings macht jeweils keinen). Vor 12013 und nach 12019 fände ich einen Abstand gut. Auch die WA setzt hier Abstände.

**Comment by gerritbruening** [comment]
11432 wird jetzt ohne Abstand rüberkommen, 12013ff. habe ich so belassen, wie sie waren.

**Comment by markusciupke** [comment]
@dietmarpravida: 
Und 1273?  --> Abstand wie 1283, 1298 und 1304?
Und 2290? --> kein Abstand wie 11432?

@gerritbruening: 
Folgefragen:

In H sind vor und nach 12013-12019 neben der Einrückung leicht vergrößerte Abstände zu erkennen.
12020-12023 sind hier **nicht** eingerückt

Im KT der Online-Ausgabe (OA) sind Einrückung und Abstände vor und nach  12013-12019 gegeben.
12020-12023 sind hier ebenfalls eingerückt.

In der Dokumentarischen Transkription der OA sind eine Einrückung aber keine Abstände gegeben.
12020-12023 sind hier **nicht** eingerückt.

In der Textuellen Transkription der OA sind Einrückung und Abstände vor und nach  12013-12019 gegeben. 12020-12023 sind hier ebenfalls eingerückt.

Im Transkriptionsband zum Faksimile ist hier derzeit eine Einrückung und ein Abstand vor 12013, aber kein Abstand nach 12019 gegeben. 12020-12023 sind hier **nicht** eingerückt.

Nach meiner Auffassung sollte das überall vereinheitlicht werden zu Einrückung und Abstand vor und nach 12013-12019. 12020-12023 sollen überall **nicht** eingerückt erscheinen. So erscheint diese Passage derzeit allerdings an keiner Stelle.

**Comment by dietmarpravida** [comment]
Es scheint klar, dass 12013-12019 im Text (vom Faksimile spreche ich hier nicht) eingerückt werden müssen und Abstände haben (Strophenform), 12020-12023 aber nicht (Kreuzreim). Das einzige, was mir offen scheint, ist, ob nach 12023 ein Abstand kommt oder nicht. H legt das immerhin sehr deutlich nahe. Also scheint mir der gegenwärtige Zustand richtig zu sein. (Markus' Bemerkungen zum Textueen Tranksript verstehe ich nicht so recht; vielleicht wurde da zwischenzeitlich etwas korrigiert?)

**Comment by gerritbruening** [comment]
> Es scheint klar, dass 12013-12019 im Text (vom Faksimile spreche ich hier nicht) eingerückt werden müssen und Abstände haben (Strophenform),

> 12020-12023 aber nicht (Kreuzreim). 

> Das einzige, was mir offen scheint, ist, ob nach 12023 ein Abstand kommt oder nicht. H legt das immerhin sehr deutlich nahe. Also scheint mir der gegenwärtige Zustand richtig zu sein. (Markus' Bemerkungen zum Textuellen Tranksript verstehe ich nicht so recht; vielleicht wurde da zwischenzeitlich etwas korrigiert?)

**Comment by dietmarpravida** [comment]
auf das (Pseudo-?)Problem von 1283 habe ich andernwärts aufmerksam gemacht (finde ich nicht sogleich, bitte Issue hier nachtragen), sonst F-I geprüft und oben abgehakt

**Comment by gerritbruening** [comment]
`//lg[not(@rend='indented')]/following-sibling::*[1][self::lg][@rend='indented']` kontrolliert, alle korrekt (Ausnahme 5944; Korrektur folgt).
`//l[@rend='indented']` sind auch korrekt.
