### ISSUE TITLE
remove lg

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#541]
```xml
    <f:ins n="10067" place="enclosing-lg">
      <lg rend=""/>
    </f:ins>
    <f:ins n="10073" place="enclosing-lg">
      <lg rend=""/>
    </f:ins>
```
It is not expressed that the resulting `lg` without `@rend` is redundant and may be dropped. Currently there is no way to express this, is there?
Note that in other cases the `lg` are still important, because there are two of them in one speech.

**Comment by thvitt** [comment]
No, there isn’t.

**Comment by gerritbruening** [comment]
Thanks, no reason to hurry. Will keep that in mind.

**Comment by thvitt** [comment]
It’s implemented now – only in the XML format, using `<f:ins place="enclosing-lg"><f:remove-lg/></f:ins>`, see the schema.

**Comment by gerritbruening** [comment]
Great! Will try to use this as soon as I can.

**Comment by gerritbruening** [comment]
Have to check if this works:
https://github.com/faustedition/faust-gen-html/blob/a5f4ab1689c8797b6816d0d89f6e29f968882093/text/app12norm_special-cases.xml#L309-L310

**Comment by gerritbruening** [comment]
Note that we now have 

https://github.com/faustedition/faust-gen-html/blob/5722b7f2b96ebd5610b2138ee447d3810b119fc8/text/app12norm_special-cases.xml#L375-L376

which seems necessary as otherwise there is no app entry inserted:
![grafik](https://user-images.githubusercontent.com/10358005/49579529-c99adb80-f94c-11e8-8249-3f80a8899d59.png)

but is forbidden by the schema.

**Comment by thvitt** [comment]
The code that uses that says 
https://github.com/faustedition/faust-gen-html/blob/8fa8e10585e0ead7d878673ee2054a8cd9808b18/xslt/text-insert-app.xsl#L66-L67
so for `<l n="3994 3995">`, it will handle both `<f:ins n="3994">` and `<f:ins n="3995">`. I wonder why I have written it that way: we probably have a use case for that?

**Comment by gerritbruening** [comment]
> Have to check if this works: ...

Yes, works fine.

**Comment by gerritbruening** [comment]
File is still not valid because of 

https://github.com/faustedition/faust-gen-html/blob/5722b7f2b96ebd5610b2138ee447d3810b119fc8/text/app12norm_special-cases.xml#L375-L376

**Comment by thvitt** [comment]
mir ist grad nicht ganz klar, wieso es trotz dieser Codierung funktioniert, aber korrekte, unterstützte Codierung für die app*.xml wäre wie oben geschrieben `<f:ins n="3994">`

**Comment by thvitt** [comment]
since it works: see separate issues for the remaining issues
