### ISSUE TITLE
whitespace-only del/note in app2norm.xml

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#542]
There are a couple of cases like
```xml
    <rdg wit="2_I_H.0a" type="type_2d*">
      <subst>
        <del>beging <note> </note></del>
```
with whitespace as only content in `<note> </note>`.
This does not seem to cause any harm.
But it seems redundant. Is this intended? Is there a flaw in the source data?

**Comment by gerritbruening** [comment]
>  This does not seem to cause any harm.

May add confustion to the IDML, though ...

**Comment by thvitt** [comment]
it’s an artifact of the apparatus subst encoding #366

**Comment by gerritbruening** [comment]
Right, had slipt out of my memory.

**Comment by gerritbruening** [comment]
I see the changes, thanks!
