### ISSUE TITLE
Inter-element whitespace lost

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#543]
As [reported earlier](https://github.com/faustedition/faust-gen-html/issues/514#issuecomment-396245410):

```xml
                                    <rdg wit="faust://document/faustedition/S" type="type_2a*"
                                            ><emph>liebte dich</emph>
                                        <wit wit="faust://document/faustedition/S">S</wit></rdg>
```
leads to 
```xml
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Sperrung">
                     <Content>liebte dich</Content>
                  </CharacterStyleRange>
                  <CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Kursiv">
                     <Content>S</Content>
                  </CharacterStyleRange>
```
with to words erroneously lumped together.
This may also appear in Faust II. Is there a quick fix are a good search pattern I can use to spot possible cases?

**Comment by pglatza** [comment]
It is because of the missing / wrong whitespace normalisation before revision 79 (see also https://github.com/faustedition/faust-gen-html/issues/532#issuecomment-398404891).

Currently, with latest commit (=r79), there are two whitespace characters between `<emph>liebte dich</emph>` and `S`.

**Comment by gerritbruening** [comment]
Hier wird nichts mehr geschehen.
