### ISSUE TITLE
Create list of editorial decisions ordered by type

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-gen-html#550]
Im Nachwort der Druckausgabe würden wir gern einen Index zu den Textentscheidungen bringen, und zwar nur die betreffenden Versziffern nach den 8 Typen geordnet. @thvitt Kannst du uns bitte, den Inhalt der ref-Elemente nach Typen extrahieren? Da wir das Teil bis zum 12.7. benötigen, ist es leider eilig.

**Comment by thvitt** [comment]
d.h. wie http://dev.faustedition.net/print/app aber nur die VErsziffern?

**Comment by thvitt** [comment]
http://dev.faustedition.net/print/reflist

Wenn noch andere Wünsche, mach’s wieder auf

**Comment by dietmarpravida** [comment]
Danke!

@gerritbruening Bist du okay damit?

**Comment by gerritbruening** [comment]
Ich bin okay mit das!

**Comment by dietmarpravida** [comment]
@thvitt eine Frage: Bei Typ Ia z.B. steht in der Liste "vor 2448", aber "before_6097" (u.ö.) Woran liegt das?

**Comment by gerritbruening** [comment]
> weil das so in app2norm.txt steht (kursiv):

Ist durch https://github.com/faustedition/faust-gen-html/commit/146ebd107971b2bdc99877ddef8ced4a7dce4803 gefixt.
