### ISSUE TITLE
div[@type='stueck'] in gesplitteten Hs.

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#551]
> Ws ist hier mit der online-Textanzeige ?

Verstehe die Frage nicht. Was ist hier das Problem, @dietmarpravida?

**Comment by thvitt** [comment]
`div type="stueck"`?

**Comment by dietmarpravida** [comment]
Bei mir funktioniert hier die Anzeige der Textansicht nicht, ich habe weitgehend weißen Schirm:

![ii h74](https://user-images.githubusercontent.com/26788529/42691290-ad6c5208-86a7-11e8-9922-ac3731656e66.JPG)

![ii h74-2](https://user-images.githubusercontent.com/26788529/42691339-e66d0796-86a7-11e8-8c13-e749021dbd3a.JPG)

**Comment by thvitt** [comment]
wie ich befürchtet habe: Die Codierung hier sieht so aus, dass es einen Haufen `<div type='stueck'>` unterschiedlicher auf oberster Ebene (direkt unter `<text>`) gibt. Jedes dieser Stücke wird wie eine eigene Szene behandelt. Über die Blätterknöpfe :fast_forward: / :rewind: rechts in der Textansicht kannst Du umblättern, bzw. in die Gesamtanasicht schauen. 

Was sind denn diese Stücke inhaltlich? Irgendwo gibt es einen Zeugen, der ausschließlich aus zwei jeweils ziemlich langen solchen divs besteht …

**Comment by dietmarpravida** [comment]
mir nicht (oder nicht mehr) bekannt, im wiki steht dazu folgendes: 
- https://faustedition.uni-wuerzburg.de/wiki/index.php/Lesetextdarstellung#todo_Feature
- https://faustedition.uni-wuerzburg.de/wiki/index.php/27._M%C3%A4rz_2015#Lesetext_und_Varianten
- https://faustedition.uni-wuerzburg.de/wiki/index.php/3._Februar_2016#Lesetext

**Comment by dietmarpravida** [comment]
Es scheint darum zu gehen, dass sich unter dem sichtbaren geschriebenen Text noch Dispoitionsnotizen mit Bleistiftnotizen befinden. Man kann bzw. muss diese Notizen als eigenen Text ansehen, so dass auf der Seite also zwei verschiedene Text(teil)e stehen.

**Comment by thvitt** [comment]
Es ist wohl nötig, die stuecke aufgrund ihrer Verstreutheut irgendwo mit reinzuziehen oder so. Das ist buganfällig, wir hatten schon [unseren](#537) [Spaß](#390) damit. D.h. erstmal Verzeichnis der Notizen, dann über Lösung nachdenken …

**Comment by dietmarpravida** [comment]
Eigentlich müsste man dafür sogar neue Paralipomenanummern vergeben.

**Comment by thvitt** [comment]
Das kann ja unabhängig davon geschehen; die Codierung der P. ist ja mit `<milestone>` erfolgt und unabhängig von divs soweit ich mich erinnere

**Comment by dietmarpravida** [comment]
ist ein anderes Problem, mit einer Sammlung aller `<div type='stueck'>`-Stellen, wird man überlegen können, ob man es noch lösen sollte

**Comment by thvitt** [comment]
Die entsprechende Liste ist in ca. 10 min [unverlinkt in der Dev-Version](http://dev.faustedition.net/print/stuecke) verfügbar

**Comment by thvitt** [comment]
In den Hs, die aufgesplittet werden, gibt es offenbar folgende Fälle:
* text mit mehreren normalen divs, danach neuer text mit diversen stuecken
   * 2 H, 2 V H.2
* ein kurzer text mit normalem div, danach mehrere texte mit diversen stuecken
   * 2 I H.32 (preceding-detection geht schief!?)
* kurzer text _ohne_ div, danach text mit diversen stuecken
   * 2 II H.69
* text mit diversen stuecken, danach text mit normalen divs
   * 2 II H.74
* ein text, zunächst vier normale divs, dann zwei stuecke, dann ein normales div
   * 2 IV H.8

Vermutlich ist es zunächst am klügsten, beim split-Kriterium einfach alle stuecke und ihre Inhalte herauszunehmen. 

Dann müssten die splits etwas zugeschlagen werden. Ich tendiere zum vorherigen div, es sei denn, es gibt keins, dann dem folgenden.

**Comment by gerritbruening** [comment]
Herrlich; angesichts von 2 II H.74 würde ich sagen, wir haben jetzt eine Handschrift mehr.

**Comment by gerritbruening** [comment]
> Herrlich; angesichts von 2 II H.74 würde ich sagen, wir haben jetzt eine Handschrift mehr.

Stimmt leider nicht so ganz, der Klick auf
http://dev.faustedition.net/document?sigil=2_II_H.74&page=49&section=2#scene_2.2.3.4
führt immer auf diese Ansicht:
![grafik](https://user-images.githubusercontent.com/10358005/44035662-483f60c4-9f10-11e8-9985-038369e1d796.png)

Ich vermute gleichlautende `pb`s dahinter.

**Comment by thvitt** [comment]
see [issue in the document viewer](https://github.com/faustedition/faust-web/issues/462)
