### ISSUE TITLE
"Goethe an Reichel, 22. Januar 1828" in app entries may link to graef_1590

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#553]

**Comment by thvitt** [comment]
:confused: Diese Phrase finde ich [nirgends im Apparat](http://dev.faustedition.net/print/app). Was genau soll ich tun?

**Comment by gerritbruening** [comment]
https://github.com/faustedition/faust-gen-html/commit/4e13008efe6bea2ec965f3dd81c3560a1be6162b
