### ISSUE TITLE
Exclude type_4a

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#554]
@pglatza, nur wenn es praktisch keine Arbeit macht:
Könntest du mit `note[@type = 'textcrit'][descendant::*[@type= 'type_4a']]` genauso verfahren, wie du es bereits nach #496 mit `@type= 'type_8'` tust?
D.h., Diese footnotes im Text rauslassen und stattdessen als Absätze hintendran oder extra? Die werden jetzt nämlich auch ausgelagert, und dann müsste man die für den Faust II nicht händisch verschieben.

**Comment by pglatza** [comment]
Ja, das lässt sich recht einfach nachtragen.
Ist mit Revision 80 umgesetzt. Das Upload-Formular habe ich auch soeben aktualisiert.
Diese Absätze erhalten auch das (vom Namen nicht ganz passende) Format `Appendix_TypeVIII`.

**Comment by gerritbruening** [comment]
Das ging ja schnell, danke!
Sieht im IDML gut aus, so weit ich das sehen kann. Formatname ist OK, dass es den auch noch braucht, hatte ich vergessen.
