### ISSUE TITLE
VI --> VI*

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#555]
`*`, da postum vorgenommene Eingriffe nicht übernommen?
Man könnte aber auch sagen, wir nehmen etwas zurück, was im Zeugen geschehen ist. Bei den anderen `*` tun wir nichts, wo spätere Editoren etwas getan haben.

**Comment by dietmarpravida** [comment]
Ja. Ich frage nur, was hier die intuitivste Lösung wäre

**Comment by gerritbruening** [comment]
Das close ich jetzt mal, OK?
