### ISSUE TITLE
Link app entries to textcrit note

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#558]
@dietmarpravida, should we indicate that there is a note on an app entry? These app entries could, for example, have an appropriate symbol at the and.
In any case we should link app entries and critical notes in the digital text.

**Comment by gerritbruening** [comment]
Happy to hear that because we don't have to change anything in the printed edition.
Let's keep that in mind for the digital part.

**Comment by gerritbruening** [comment]
@thvitt, what would be required to generate these links? Can we use the app-ids or are they too unstable for that purpose?

**Comment by thvitt** [comment]
I’m a little confused: We don’t have these notes online yet?

The app ids are built from the app entries’ verse no and lemma, so they should be pretty stable.

**Comment by dietmarpravida** [comment]
no, I wrote them in a hurry to have them dispatched to Goettingen just in time. Presently they figure only in  a googledoc.

**Comment by gerritbruening** [comment]
After this is finished, we will import them to XML. Until that we could work with test data.
Would be good to define there internal structure, also for the printed edition. In any case they will have `ref` like phrases, maybe they also include a lemma if there is one.

**Comment by dietmarpravida** [comment]
Die Einbindung der Anmerkrungsn müssten wir uns überlegen. So ähnlich wie bei den Typen nehme ich an?

**Comment by dietmarpravida** [comment]
@gerritbruening Ist für die online-Einbindung der Erläuterungen schon etwas geschehen?

**Comment by gerritbruening** [comment]
Nein, wenn überhaupt, schaffen wir es, den groben Text der Textrechtfertigung einzubinden.

**Comment by gerritbruening** [comment]
https://github.com/faustedition/faust-web/issues/552
