### ISSUE TITLE
Reorganize splitting of large texts

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#56]
Currently, iff a document is to be split, the `<tei:div>`s on act and scene level are extracted to separate files and replaced with TOCs in the original files.

This should be modified to:

* there will be no more pages for the _act_ level, just one cover/toc page and several scene pages
* all text content appears at _scene_ level
* text content that appears before or between scenes (e.g, act headings) will be moved to the first following scene page
* text content that appears after the last scene will be rendered at the end of the last scene.

Accordingly, the TOC in the right margin will be much simpler: Just previous/next scene, on one page/on separate pages, and a preliminary link to the metadata (for prints only).

**Comment by thvitt** [comment]
Act level `<div>`s that do not contain scene level `<div>`s need to be treated like scenes (to care for stuff like the _Zueignung_)

**Comment by sbruemmer** [comment]
This issue is affecting some tasks in https://github.com/faustedition/faust-web/issues/113

**Comment by sbruemmer** [comment]
Afterwards review styling, see https://github.com/faustedition/faust-web/issues/145
