### ISSUE TITLE
app//emph not rendered in list

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#560]
See
http://dev.faustedition.net/print/faust.7#app.1921.drey
There are italics in the app entry in the text view, but not in the list ordered by types.

Note that there is also `add/emph` sometimes
http://dev.faustedition.net/print/faust.37#app.10107.ich

**Comment by thvitt** [comment]
`.l .emph`, probably to distinguish it from `.stage .emph` which is small-caps
