### ISSUE TITLE
enable search for 4335-4343

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-gen-html#561]
Lines 4335-4343 don't figure in our reading text because they were added in 1 H.1 only (they do appear in consecutive prints C.1 and C.3). Presently, it is impossible to search for any verse in this intervall in our edition.

![4335](https://user-images.githubusercontent.com/26788529/43591938-bd35246c-9674-11e8-95be-f6ba8f70beff.JPG)

**Comment by dietmarpravida** [comment]
You get to 4335 by way of searching for 4334, of course. But when you have come this far, you won't be able to see the hand written lines on p .219 of 1 H.1:
![1 h1 p219](https://user-images.githubusercontent.com/26788529/43593039-2dcb693c-9677-11e8-8bb3-3c3eac059f60.JPG)

**Comment by thvitt** [comment]
* The link generated from the search tool is http://dev.faustedition.net/print/faust.#l4335
* The corresponding text appears in the apparatus entry at http://dev.faustedition.net/print/faust.25#lbefore_4343. Would need to check how we handle the apparatus anyway

**Comment by thvitt** [comment]
works after deploying the newest version of the search app.

We simply find the l/@n in the reading text's textcrit notes now.
