### ISSUE TITLE
erg mal angezeigt, mal nicht

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#563]
![grafik](https://user-images.githubusercontent.com/10358005/43724014-5808f0fa-9999-11e8-80bb-540e2169aade.png)

**Comment by gerritbruening** [comment]
Das Komma nach "Mutter" ist in H auch ergänzt.

**Comment by gerritbruening** [comment]
Wahrscheinlich Teil des großen Issues zur Zeilensynopse.

**Comment by thvitt** [comment]
ja, in der Einblendungsapparatansicht ist das Mutterkomma auch 〈erg〉
https://github.com/faustedition/faust-web/issues/283
