### ISSUE TITLE
msfaustii version taggen

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#566]
@thvitt, aus dieser Version
2018-08-06T23:34:52.601+02:00
(https://github.com/gerritbruening/faust-data/blob/7c65c1a778b584f34702dd154a93671b4b7b1165/lesetext/faust.xml)
habe ich die Faust II-Manuskript erzeugt.
Können wir das irgendwie vermerken?

**Comment by thvitt** [comment]
erledigt
