### ISSUE TITLE
Where is Lesetext in line synopsis

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#567]
Look at
![grafik](https://user-images.githubusercontent.com/10358005/43902629-e23edeb2-9bea-11e8-9ede-03102ee3c68e.png)
C.1 and C.3 are disconnected for some reason in the macrogenesis data. Is it by random where the reading text is? It would be more logical to put it together whith the base witness if it is identical with it.

**Comment by thvitt** [comment]
Lesetext is always last, which makes sense from a chronological perspective :) If it is identical with the newest witness’s emended version, they are grouped together.

There’s no path from C.1 12 to C.3 12 in the current graph, so maybe its info is suboptimal

**Comment by gerritbruening** [comment]
Order would be
H.32
H
H.0a
C.1
C.3
meaning that there are some gaps in the data, sigh...
Not sure wether I agree about the reading text. It in a way represents a pre-existing historic state within textual history. Which is identical to H.0a in this case.

**Comment by gerritbruening** [comment]
Last position was approved in last F2F/TelKo meeting.
