### ISSUE TITLE
App list by textual order

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#571]
@thvitt, would it be complicated to render the `/app` list a second time by textual order?
(The list ordered by types is still very helpful.)
I think it would be best to have these two lists on separate pages.

**Comment by thvitt** [comment]
http://dev.faustedition.net/print/app-by-scene

Müssten mal überlegen, wie / wo wir das sinnvoll verlinken

**Comment by gerritbruening** [comment]
Sehr gut, danke, die Szenenüberschriften sind eine gute Idee!
