### ISSUE TITLE
before 3183

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-gen-html#573]
Sollte diese Unregelmäßigkeit des Drucks nach "fort" nicht beschrieben werden? Derzeit nur as "fährt fort[^]" angegeben.

![before 3183](https://user-images.githubusercontent.com/26788529/44003235-9a177772-9e4f-11e8-96e1-d5d2763a3e30.JPG)

**Comment by markusciupke** [comment]
Platz für 1 Zeile Apparat wäre noch auf der Textseite, und auch im Editorischen Bericht ist noch Platz. Aber wie beschreiben? Ich würde das als Fliegendreck bezeichnen und bei einer Druckfahnenkorrektur einkreisen und mit # markieren. Ich weiß aber nicht, ob das allgemein so genannt bzw. gehandhabt wird. Konnte auf die Schnelle auch nichts im Internet dazu finden. Weißt du etwas?

**Comment by dietmarpravida** [comment]
ein Spieß?

**Comment by gerritbruening** [comment]
> ein Spieß?

Ja

**Comment by dietmarpravida** [comment]
ist auch in dem anderen hinter mir stehenden Hochstifts-Exemplar zu finden

**Comment by markusciupke** [comment]
ist auch in meinem Faksimile von D1

**Comment by gerritbruening** [comment]
Spieße verzeichnen wir auch sonst nicht.

**Comment by dietmarpravida** [comment]
ist aber beinah mit einem verdruckten Komma zu verwechseln

**Comment by dietmarpravida** [comment]
bleibt wie es ist
