### ISSUE TITLE
in 3206?

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-gen-html#574]
In den Lesarten steht bei "MARGARETE" die Angabe "vor 3206", eigentlich ist es aber, da inmitten einer Antilabe, "in 3206". Wie drücken wir das aus?

**Comment by dietmarpravida** [comment]
Das sind aber auch zwei verschiedene Verse, nehmen wir lieber die Formulierung "in Vers"

**Comment by markusciupke** [comment]
Laut Düntzer und Schmidt nicht. »in Vers« versteht man wohl auch, finde aber a und b wie in der digitalen Edition besser. Egal. Du korrigierst, ich führe aus.

**Comment by gerritbruening** [comment]
Finde "in" nicht schlecht, besser als nur die Verszahl.

**Comment by dietmarpravida** [comment]
ok, "in" ist es
