### ISSUE TITLE
’was unsearchable

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-gen-html#575]
words beginning with an apostroph (like `’was`) seem to be unsearchable

**Comment by dietmarpravida** [comment]
However, I don't get any hits for pure "was" either

![was](https://user-images.githubusercontent.com/26788529/44003764-a0810926-9e58-11e8-8fc8-efb0ed3a47bc.JPG)

**Comment by thvitt** [comment]
problem seems to be a stopword list that needs to be turned off.
