### ISSUE TITLE
Remaining errors in IDML synthesis

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#576]
(FWIW)

- [x] Im App zu vor 6319 ist die `⟨` hinter `Mephisto)` verschoben.
- [x] andere `⟨`? https://github.com/faustedition/xml/issues/535
- [x] BAs zwischen Versgruppen erscheinen ohne Abstand (Korrekturanweisungen für den Faust II notiert)
- [x] eingerückte Verse ohne eingerückte `lg` (war nicht kommuniziert worden) https://github.com/faustedition/faust-gen-html/issues/539#issuecomment-416404143
- [x] kursive Doppelpunkte _:_

Folgende Formate sind nicht angekommen:
- [x] CHOR und ECHO (stattdessen falsch CHOR UND ECHO); betrifft auch **vor 11604 und ff.**

Folgende Überschrifts-Formate sind nicht angekommen:
- [x] ­ Szene vor Szenenunter
- [x] ­ Szenenunter
- [x] ­ Unterszene vor Szenenunter
- [x] ­ Unterszene nach Szene vor Unterszenenunter

und dem Vernehmen nach auch nicht eingesetzt worden (zu allem diesem siehe https://github.com/faustedition/faust-gen-html/issues/331).

Evtl.
- #543

**Comment by gerritbruening** [comment]
@dietmarpravida, hier gibt es Fehlerquellen, die theoretisch auch den Faust I betreffen könnten, v.a.
> BAs zwischen Versgruppen erscheinen ohne Abstand.

**Comment by gerritbruening** [comment]
(DP hat seine abgearbeitet)

**Comment by gerritbruening** [comment]
Hier stand im Manuskript 
> CHOR UND ECHO

wo es richtig 
> CHOR und ECHO 

hätte sein sollen; betrifft auch vor 11604 und ff.

Description: before_7654
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[2]/div[3]/div[3]/sp[14]/speaker[1]/@n

Description: before_7660
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[2]/div[3]/div[3]/sp[15]/speaker[1]/@n

Description: before_8044_a
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[2]/div[3]/div[4]/sp[2]/speaker[1]/@n

Description: before_8064
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[2]/div[3]/div[4]/sp[4]/speaker[1]/@n

Description: before_8168
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[2]/div[3]/div[4]/sp[15]/speaker[1]/@n

Description: before_8178
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[2]/div[3]/div[4]/sp[17]/speaker[1]/@n

Description: before_8186
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[2]/div[3]/div[4]/sp[19]/speaker[1]/@n

Description: before_8194
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[2]/div[3]/div[4]/sp[21]/speaker[1]/@n

Description: before_8196
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[2]/div[3]/div[4]/sp[23]/speaker[1]/@n

Description: before_8210
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[2]/div[3]/div[4]/sp[25]/speaker[1]/@n

Description: before_8359_a
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[2]/div[3]/div[5]/sp[12]/speaker[1]/@n

Description: before_9737
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[3]/div[3]/sp[20]/speaker[1]/@n

Description: before_9755_a
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[3]/div[3]/sp[24]/speaker[1]/@n

Description: before_9785
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[3]/div[3]/sp[28]/speaker[1]/@n

Description: before_9819
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[3]/div[3]/sp[33]/speaker[1]/@n

Description: before_9877
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[3]/div[3]/sp[43]/speaker[1]/@n

Description: before_9891
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[3]/div[3]/sp[45]/speaker[1]/@n

Description: before_9903_b
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[3]/div[3]/sp[50]/speaker[1]/@n

Description: before_11288_b
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[5]/div[3]/sp[1]/speaker[1]/@n

Description: before_11604_b
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[5]/div[4]/div[1]/sp[1]/speaker[1]/@n

Description: before_11606
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[5]/div[4]/div[1]/sp[2]/speaker[1]/@n

Description: before_11608
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[5]/div[4]/div[1]/sp[3]/speaker[1]/@n

Description: before_11610
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[5]/div[4]/div[1]/sp[4]/speaker[1]/@n

Description: before_11844_c
XPath location: /TEI[1]/text[1]/body[1]/div[5]/div[5]/div[5]/sp[1]/speaker[1]/@n

@dietmarpravida, wenn du gelegentlich schaust?

**Comment by dietmarpravida** [comment]
- [ ] Description: before_7654
- [ ] Description: before_7660
- [ ] Description: before_8044_a
- [ ] Description: before_8064
- [ ] Description: before_8168
- [ ] Description: before_8178
- [ ] Description: before_8186
- [ ] Description: before_8194
- [ ] Description: before_8196
- [ ] Description: before_8210
- [ ] Description: before_8359_a
- [ ] Description: before_9737
- [ ] Description: before_9755_a
- [ ] Description: before_9785
- [ ] Description: before_9819
- [ ] Description: before_9877
- [ ] Description: before_9891
- [ ] Description: before_9903_b
- [ ] Description: before_11288_b
- [ ] Description: before_11604_b
- [ ] Description: before_11606
- [ ] Description: before_11608
- [ ] Description: before_11610
- [ ] Description: before_11844_c

**Comment by dietmarpravida** [comment]
die abgehakten Fälle haben im Satz Großbuchstaben, die nichtabgehakten kleine, before_8168 hat sozusagen legitimerweise große (muss man hier eingreifen?)

**Comment by dietmarpravida** [comment]
beiläufig: 

> Hier stand im Manuskript



du meinst damit den Satz?

**Comment by gerritbruening** [comment]
> before_8168 hat sozusagen legitimerweise große (muss man hier eingreifen?)

Nein, denn ich hatte das als UNTERSTRICHEN -- im Vgl. dazu nicht wirklich unterstrichen -- UNTERSTRICHEN gedeutet oder, wie man sagt, textbehandelt.

**Comment by dietmarpravida** [comment]
> Korrekturbedarf gibt es bei den abgehakten Fällen, richtig?

ja

**Comment by gerritbruening** [comment]
Danke!

**Comment by gerritbruening** [comment]
> die Koorekturen wurden mc kommuniziert

Dann ist das hier gefixt.
