### ISSUE TITLE
Links from paralipomena use deprecated documentViewer?faustUri

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#577]
http://dev.faustedition.net/paralipomena

**Comment by thvitt** [comment]
There was an old documentViewer.php lingering on the beta server disrupting the redirection, which is fixed now. 

Still, the paralipomena table should use /document?sigil urls

**Comment by thvitt** [comment]
* [ ] put `sigil_t` inside paralipomena.js [faust-gen-html]
* [ ] use it in the inline script in paralipomena.php

Alternatively, replace paralipomena.php with a generated page.
