### ISSUE TITLE
Abstände nach SAs 6111, 6119 (Satz, Seite 260)

### ISSUE THREAD

**Issue by dietmarpravida** [faustedition/faust-gen-html#579]
@markusciupke sind hier die Abstände nach den Sprecherangaben jeweils gleich groß?

**Comment by dietmarpravida** [comment]
((steht hier im falschen Zweig, ich weiß))

**Comment by markusciupke** [comment]
Ja, sind gleich groß.

**Comment by dietmarpravida** [comment]
danke!
