### ISSUE TITLE
Address of 1.0 version

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#581]
@thvitt, is it `faustedition.net` or `www.faustedition.net`?

We'll need this info for the back of the title page were it is desired to make a reference to the digital edition.

**Comment by thvitt** [comment]
I intend to have them both point to v1, with one being a redirect (probably www is the canonical version?)

**Comment by gerritbruening** [comment]
The draft ackknowledgement reads

> unter faustedition.net

Is that appropriate? I like it because an explicit "www." reference seems old-fashioned to me.

**Comment by thvitt** [comment]
ok
