### ISSUE TITLE
Lesetext update broken?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#582]
From this commit on:
https://github.com/faustedition/faust-gen-html/commit/5b0f61402d46cbbc6e87c9c95458368a44251c3d
the Lesetext does not seem to be updated anymore.

**Comment by gerritbruening** [comment]
Also, the Grundschicht stuff is `HTTP ERROR 404`

**Comment by thvitt** [comment]
[Build 1030 has been aborted](http://dev.digital-humanities.de/ci/view/Faust/job/faust-gen-fast/1030/) due to load issues on the build server. There have been builds after that, everything looks fine now.
