### ISSUE TITLE
invalid elements in apparatus’ literal xml

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#585]
The following non-TEI elements appear in apparatus entries. They probably are remains of the original word files and need to be removed/replaced in text-insert-app.xsl.

* [ ] `tab`, e.g. in before_354_c
* [ ] `br`, e.g. in before_2320_c (should probably become an `lb`?)

Requirement of #443

**Comment by thvitt** [comment]
687ae2e708a1cb43e54f056afda65977e06c76d3 nimmt sich dem an. Bitte prüft ob das tatsächlich das ist, was ihr mit den Tags im Apparat intendiert hattet.

**Comment by dietmarpravida** [comment]
- br in meiner Datei entfernt
- tabs müssten @gerritbruening angehen

**Comment by thvitt** [comment]
Mein Skript ersetzt die `<tab/>` durch einzelne Leerzeichen

**Comment by dietmarpravida** [comment]
das heißt das hier wäre erledigt? Oder soll ich die tabs rauschmeißen?

**Comment by thvitt** [comment]
wenn die Tabs keine andere Bedeutung haben ist das erledigt
