### ISSUE TITLE
app zu 3990

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#587]
im App-Eintrag zu 3990 sind eine ganze Reihe von Problemen:
```xml
  <!--       3990[]{} <i>3990–4015</i> <i>Die Verse sind im Druck zweistufig eingerückt (A 8, S. 198–199): 3990–3995 um 5 mm eingerückt, was für Kurzverse normal</i>]  <i>ist<Fett>;</Fett> 3996 – 3999 auf Seite 198 um 10 mm<Fett>;</Fett> ebenso 4000 – 4003 und 4008 – 4015 (beidemale wohl versehentlich) sowie 4004 – 4007 (wohl korrekt) auf Seite 199 um 10 mm.. [type=7 Typ 1c]</i>-->
  <app>
    <f:ins n="3990" place="only-app"/>
    <ref>3990–4015</ref>
    <lem wit="S"> <note>Die Verse sind im Druck zweistufig eingerückt (A 8, <wit>S</wit>. 198–199): 3990–3995 um 5 mm eingerückt, was für Kurzverse normal</note></lem>
    <rdg> <note>ist<Fett>;</Fett> 3996 – 3999 auf Seite 198 um 10 mm<Fett>;</Fett> ebenso 4000 – 4003 und 4008 – 4015 (beidemale wohl versehentlich) sowie 4004 – 4007 (wohl korrekt) auf Seite 199 um 10 mm.. [type=7 Typ 1c]</note></rdg>
  </app>
```

* [ ] `<Fett>`? Hier ist vermutlich  `<hi rend="bold">` gemeint? oder kommt das aus den Skripten von @gerritbruening ?
* [ ] Zwei Punkte `..` am Ende
* [ ] `[type=7 Typ 1c]` wird nicht verstanden. Hat das einzelne Reading mehrere Types?
* [ ] `A 8` wird nicht als Sigle erkannt (`A`)

**Comment by dietmarpravida** [comment]
- nicht fett (korrigiert, soweit es an mir liegt)
- ein Punkt (korrigiert)
- hat mehrere Types, siehe https://github.com/faustedition/xml/issues/542#issuecomment-416717928
- ist hier der einzige Fall, wo der Band angegeben wird, da eine Seitenangabe folgt im Grunde identisch mit bloßer Angabe von A

**Comment by gerritbruening** [comment]
@dietmarpravida, bitte den über diesem comment verlinkten commit bzw. sein Ergebnis prüfen.

**Comment by gerritbruening** [comment]
> ist hier der einzige Fall, wo der Band angegeben wird, da eine Seitenangabe folgt im Grunde identisch mit bloßer Angabe von A

Habe ich vorwitzig entfernt, bitte um Entschuldigung. Wieder einbauen?

**Comment by dietmarpravida** [comment]
ganz egal

**Comment by gerritbruening** [comment]
A8 dann auch online zu A ändern?

**Comment by gerritbruening** [comment]
Check A 8 in app on 3990

**Comment by gerritbruening** [comment]
Hm, the apparatus entry appears to be unchanged. Is the volume number automatically dropped, @thvitt?

**Comment by thvitt** [comment]
In the HTML representations, the sigils in the apparatus are only used to identify the corresponding witness. The link text is taken from the document’s metadata, so the same document is always referred to in the same way.

**Comment by gerritbruening** [comment]
OK, thanks, I have moved the  `8` outside the `wit`.
