### ISSUE TITLE
Include and enhance editorial introduction

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#592]
Pretty sure that IDML would be the best interchange format. It is verbose, though.
Advise from @pglatza would be appreciated.
@markusciupke would have to send over the IDML.
Secondly, all the idnos which are rendered in italics would have to become proper links (should work semi-automatically, at least).

**Comment by thvitt** [comment]
Would need to see that. @markusciupke, can you send me both IDML and docx?

@gerritbruening, it is probably not intended to maintain the stuff in IDML but rather in HTML or TEI?

**Comment by markusciupke** [comment]
I send it via e-mail.

**Comment by thvitt** [comment]
danke.

Die Referenzen zu extrahieren wird hinreichend nervig. Im IDML sieht sowas z.B. so aus:

```xml
<CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Kursiv">
	<Content>H</Content>
</CharacterStyleRange>
<CharacterStyleRange AppliedCharacterStyle="CharacterStyle/Versalziffer kursiv hoch">
	<Content>5</Content>
</CharacterStyleRange>
```

* die Siglen sind unvollständig, dh 1/2 etc. muss geraten werden
* erstmal erkennen dass die zusammengehören
* α

**Comment by gerritbruening** [comment]
> die Siglen sind unvollständig, dh 1/2 etc. muss geraten werden

Ja, deswegen semi-automatisch, bzw.:
* Faust II-Handschriften-Siglen haben immer römische Präfixe
* `H` ist immer `2_H`
* `C...` müssen wir disambiguieren. Es wäre aber gut, da schonmal `ref` und `@uri` (notfalls ohne Wert) oder was immer da genommen wird, einzusetzen, damit wir nicht komplett händisch auszeichnen müssen.
* bei α gab es irgendein ID-Problem, ich weiß nicht, ob am Ende nicht manchmal `a` dasteht. Könnte aber korrigiert worden sein.

**Comment by gerritbruening** [comment]
> @gerritbruening, it is probably not intended to maintain the stuff in IDML but rather in HTML or TEI?

Yes!

**Comment by gerritbruening** [comment]
(sollten klären, ob das zur 1.0 sein muss)

**Comment by thvitt** [comment]
mein vorschlag wäre docx → tei (via ex. skripte), dann gucken ob man die referenzen auflöst, dann entweder in tei pflegen oder nach html und darin pflegen, können wir nachher besprechen

**Comment by gimsieke** [comment]
Philipp hat diese Woche Urlaub. Wie umfangreich/komplex ist denn das InDesign? Wir könnten eine weitere Pipeline aufsetzen, die IDML nach TEI konvertiert.

**Comment by pglatza** [comment]
Um die Aufgabe(n) und Lösungsvorschläge besser einschätzen zu können: um welchen Bereich, in welcher Datenquelle, handelt es sich?

**Comment by thvitt** [comment]
### Siglenerkennung

1. `<hi rend="Kursiv">A</hi>`
2. `<hi rend="Kursiv">C</hi><hi rend="Versalziffer_kursiv_hoch">3</hi>`
3. `<hi rend="Kursiv">III H</hi><hi rend="Versalziffer_kursiv_hoch">2</hi>`, hier würde tokenisieren stören
4. Doppelt: `<hi rend="Kursiv">B B</hi><hi rend="Kursiv_Hochgestellt">a</hi>`
5. `<hi rend="Kursiv">C</hi><hi rend="Versalziffer_kursiv_hoch">2</hi><hi end="Kursiv_Hoch_Agora">a</hi><hi rend="Kursiv" xml:space="preserve"> C</hi><hi rend="Versalziffer_kursiv_hoch">3</hi><hi rend="Kursiv">4</hi>` müsste `C.3 4` werden
6. Dagegen `<hi rend="Kursiv">G</hi>`
7. Dagegen besonders nervig `<hi rend="Kursiv">durch Rasur H</hi>`

**Comment by gerritbruening** [comment]
Klingt hinreichend nervig, aber wir sind bei Fuß.

**Comment by thvitt** [comment]
ich habe euch das TEI-File ja geschickt. Bevor ich wieder dran bin, müsst Ihr ein paar Entscheidungen treffen, z.B. wie das gepflegt werden soll, wo das hin soll, was davon relevant ist, welche Konvertierungen noch anstehen aus eurer Sicht. Können bei bedarf gern drüber sprechen

**Comment by gerritbruening** [comment]
> ich habe euch das TEI-File ja geschickt

Oh, das ist mir durchgerutscht, und ich finde es nicht mehr wieder. Kannst du es nochmal schicken?

**Comment by thvitt** [comment]
done

**Comment by gerritbruening** [comment]
> z.B. wie das gepflegt werden soll, 
am besten in `xml`, wo die anderen Sachen auch liegen.

> wo das hin soll

`intro_text.php`

**Comment by gerritbruening** [comment]
OK, danke!
Wie sieht es mit diesen komischen Konstrukten aus:
`Faust  <hi rend="Faust_I/II1">I</hi>`
(https://github.com/gerritbruening/faust-data/blob/03db6484b710c1858109b3e08794b3fcf44db965/faust-gen-html-issue592/EdBerichtFixed.xml#L80)
Steht dazwischen ein geschätztes Leerzeichen? Dann ist gut, aber wahrscheinlich brauchen wir da `&nbsp;`?
Und kann `<hi rend="Faust_I/II1">` per `apply-templates` entfallen?

**Comment by gerritbruening** [comment]
Fußnotenzählung um -2 verschoben?
https://github.com/gerritbruening/faust-data/blob/03db6484b710c1858109b3e08794b3fcf44db965/faust-gen-html-issue592/EdBerichtFixed.xml#L128

**Comment by gerritbruening** [comment]
Worttrennungen scheinen überlebt zu haben:
https://github.com/gerritbruening/faust-data/blob/03db6484b710c1858109b3e08794b3fcf44db965/faust-gen-html-issue592/EdBerichtFixed.xml#L114
(`Gesamtaus­-gabe` mit soft hyphen)

**Comment by thvitt** [comment]
>> z.B. wie das gepflegt werden soll,
> am besten in xml, wo die anderen Sachen auch liegen.

wenn’s in tei weitergepflegt werden soll und nicht in html, ok

> intro_text.php

das widerspricht dem oben aber. Kann man vielleicht über eine Aufteilung nachdenken. Das wird ja sonst ein riesenlanges Bleiwüstendokument. 

>  `Faust  <hi rend="Faust_I/II1">I</hi>`

Die Absatz- / Zeichenformate und direkten Formatierungen wurden übernommen, auch geschützte Leerzeichen und bedingte Trennstriche sollten noch da sein. (Ich nehme an, im Druck ist die I leicht verkleinert.) `&nbsp;` bitte nicht verwenden, das gibts allenfalls in HTML. Geschützte Leerzeichen sind doch ok, wir haben ja eh UTF-8-codierte Daten.

Bei den ganzen Formatierungen muss man mal überlegen, welche wie irgendwann im HTML landen sollen, für rend="Kursiv" gibt’s ja auch keine Regeln.

**Comment by gerritbruening** [comment]
Mit `intro_text.php` meinte ich, dort soll das landen, was aus dem TEI gemacht wird. Ich bin aber sehr für eine Aufteilung, d.h. jede Überschrift oder so bekommt ein eigenes Dokument.
Dann würde ich sagen, `hi[rend="Faust_I/II1]"` soll durch den Inhalt ersetzt werden.

**Comment by gerritbruening** [comment]
Können wir hier zur 1.0 noch was tun?
Was ich machen kann: ein TEI bereitstellen, meinetwegen auch aufgesplittet nach präsumptiven faust-web-Seiten, mit Links auf Zeugen.
Was wir da aber brauchten, wäre eine brauchbare Anzeige der `note`-Inhalte (Fußnoten) am rechten Rand oder so. Sonst stehen die Mittendrin, das sähe dann komisch aus. Ich könnte sie allerdings für die 1.0 auskommentieren, wenn das bis dahin nichts werden würde.
Also, @thvitt, soll ich ein TEI basteln?

**Comment by thvitt** [comment]
wieso willst du jetzt ein TEI basteln? hatte ich doch schonmal gemacht & auch die meisten der Siglen verlinkt?

**Comment by gerritbruening** [comment]
> basteln

d.h., über das von dir generierte drübergehen
aber wir können es auch jetzt schon rendern, gesplittet natürlich
Wo würdest du das XML hosten? Oder soll dann sowieso gleich direkt das generierte html weitergepflegt werden? (mir egal)
Fußnoten gehen aber dann noch nicht?

**Comment by gerritbruening** [comment]
`hi rend` bleibt stehen

**Comment by gerritbruening** [comment]
Am Schluss nach 

        geltende Schreibung des griechischen Namens <hi rend="Griechisch">’Ericqå</hi> als
        »Erichtho« ist eigentlich ein hyperkorrekter Graezismus, da das Latei­nische die Verbindung
        der Laute -chth- (-<hi rend="Griechisch">cq</hi>-) nicht kennt. ­Lateinisch korrekt wäre die

schauen

**Comment by gerritbruening** [comment]
Hier das Mapping:

Elemente | Kontext | Umsetzung |  
-- | -- | -- | --
hi rend="Kolumne_links_(MC)" | p rend="Text Stumpf" | raus |  
hi rend="Faust_I/II1" |   | apply-templates
hi rend="Kursiv" |   | emph |  
hi   rend="Hochgestellt" |   | apply-templates
`note/@n` |   | neu durchzählen daraus Nummern
`<hi   rend="Kursiv" xml:space="preserve">autornah   </hi>` | wenn möglich, trailing blank nach   rechts raus, dann kann xml:space weg
`<hi   rend="Kursiv">C.1</hi>` |   | gerne schonmal ein ref mit leerem   @target um den Inhalt
`<hi   rend="Kursiv">C.3</hi>` |   |   |  
hi rend="Kursiv" | gefolgt von hi rend="Versalziffer_kursiv_hoch" | zusammen lumpen in ein emph/ref
dito | dito gefolgt von hi rend="Kursiv_Hochgestellt" | dito |  
hi rend="Tiefgestellt" |   | Punkt gefolgt von text()
p rend="Teil" |   | raus |  
p rend="Szene" |   | h2 | das ist bei uns die höchste, oder? Sonst halt h1 usw.
p rend="Unterszene nach Szene" |   | h3 |  
p rend="Unterszene" |   | h3 |  
p rend="Unterszenenunter" |   | h4 |  
p rend="Faust I/II" |   | h5 |  
p rend="Text Hängend 1" |   | li |  
p   rend="Text Hängend römisch 1" | li |  
p   rend="Text Hängend römisch 2" | ul/li | untergeordnet
p   rend="Text Hängend römisch 3" | dito |  
p rend="Text Hs 2" |   | li |  
`<hi   rend="Tiefgestellt_^_Text">^</hi>` |   | da hast du irgendwas für, oder?
hi rend="Tiefgestellt_^" |   |   | dito
hi rend="italic" |   | emph |

**Comment by thvitt** [comment]
- note
- ref

**Comment by gerritbruening** [comment]
Danke!
Ich würde das im Grundsatz dann [so](https://github.com/faustedition/faust-web/commit/117c1da9eeb8dea34b7cb9e9f71d83aadd071951) machen. Ist das in Ordnung? Aufteilung in sub-Seiten entlang der `div`s können wir uns dann noch überlegen, aber es gibt noch ein paar Suchen-und-Ersetzen-Sachen, die ich vorher gern machen würde (Anführungszeichen und so).

**Comment by gerritbruening** [comment]
Wenn das ungefähr das ist, was bei diesem Issue rauskommen sollte, kann @thvitt das closen, und wir regeln die weiteren Einzelheiten in `faust-web`.

**Comment by thvitt** [comment]
das mit den sidenotes klappt noch nicht … muss ich noch ein wenig schauen

**Comment by thvitt** [comment]
@gerritbruening, bitte für weitere anzupassende Dateien die Änderung aus
https://github.com/faustedition/faust-web/commit/9a92b7f89f751ef42c9c6803208d9428e3148772 beachten. Dies bewirkt, dass für die Randnotizen Raum reserviert wird, sollte jetzt also auf jeden Bildschirm passen. Wenn’s zu schmal ist, zum Beispiel auf pure-u-4-5 ändern.

**Comment by gerritbruening** [comment]
Sieht gut aus, danke!
