### ISSUE TITLE
Make ⟨...⟩ grey in app entries 

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#598]
(according to inline apparatus)
For an example, see http://dev.faustedition.net/print/faust.30#l5357
http://dev.faustedition.net/print/faust.30#app.before_6319_a.only-app

**Comment by gerritbruening** [comment]
Regression?

**Comment by thvitt** [comment]
There’s no `<span class="generated-text">` around the `〈`, so probably yes.

**Comment by thvitt** [comment]
It doesn’t even work with 
https://github.com/faustedition/faust-gen-html/commit/5ca1ea06bbe82e44e98e6669acd9f78f9ca8ae70
