### ISSUE TITLE
Info on B.a in self_print.xml not used?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#599]
`xml/macrogenesis/self/self_print.xml` seems to be ignored? I see no effect on the Faust I bar diagrams.

**Comment by thvitt** [comment]
Wird schon berücksichtigt, z.B. http://dev.faustedition.net/macrogenesis/J.1

aber die Quelle ist flasch → `faust://self`

**Comment by gerritbruening** [comment]
```xml
    <!--  Ba 9 : Erscheinungsdatum zweite Hälfte 1817, zwischen 00-06-1817 und 00-12-1817 -->
    <date notBefore="1817-06-01" notAfter="1817-12-31">
        <source uri="faust://self"/>
        <item uri="faust://print/hagen/B.a"/>
    </date>
```
scheint der problematische Fall zu sein.

**Comment by gerritbruening** [comment]
aus #595

**Comment by thvitt** [comment]
im lokalen build ist’s da, nur auf dev nicht

**Comment by thvitt** [comment]
[jetzt ist es da.](http://dev.faustedition.net/macrogenesis/B.a) [Der Build](http://dev.digital-humanities.de/ci/job/faust-macrogen/) war einfach noch nicht gelaufen.
