### ISSUE TITLE
Sigil mixup with 2 IV H.13a

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#601]
* links in `xml/document` file seem ok
* links in `xml/transcript` seem ok
* images on `tools/facsimiles` seem ok

But still the images seem completely wrong here:
http://dev.faustedition.net/document?sigil=2_IV_H.13a&page=1&view=facsimile_document

This image would be the right one for p 1:
![grafik](https://user-images.githubusercontent.com/10358005/46046022-d797d900-c11f-11e8-85af-a350bceae5af.png)

Images are from here:
http://beta.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2.4/gsa_390595.xml&page=1&view=structure

There is something wrong with the Findbuch Sigle, I think.

**Comment by thvitt** [comment]
In the current state of the data, _two_ documents have the same faustedition sigil, which cannot work.

```
archival/bb_cologny/G-30_08.xml
12:        <idno type="faustedition">2 IV H.13a</idno>

faust/2.4/gsa_390595.xml
13:      <idno type="faustedition">2 IV H.13a</idno>
```

**Comment by thvitt** [comment]
is the only case of duplicate faustedition sigils in the current data.

**Comment by dietmarpravida** [comment]
archival/bb_cologny/G-30_08.xml = **2 IV H.13a**

faust/2.4/gsa_390595.xml = **2 IV H.13b**

Der Fehler stand schon in meiner alten "Neue Faust-Siglen"-Datei

**Comment by gerritbruening** [comment]
Jetzt:

      <idno type="faustedition">2 IV H.13b</idno>
      <idno type="gsa_1">GSA 25/XVIII,5,14:2</idno>
      <idno type="gsa_2">GSA 25/W 1684</idno>
      <idno type="gsa_ident">390595</idno>

**Comment by dietmarpravida** [comment]
Die Bilder stimmen jetzt anscheinend, aber die Metadaten noch nicht?
