### ISSUE TITLE
dots before lb type="semantic"

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#605]
(sigh)

```xml
                     <stage n="before_10067_a"><hi>Ein Sieben-Meilenſtiefel</hi>
                        (tappt auf)<lb type="semantic"/>ein <hi>Anderer</hi> folgt
                           alsbald.<lb type="semantic"/><hi>Mephiſtopheles</hi>
                        (ſteigt ab)<lb type="semantic"/>Die <hi>Stiefel</hi> ſchreiten
                        eilig weiter.</stage>
```
These dots are kept in the text, but I'm not sure why. I am just changing the stage type to `long`.
The dots shouldn't be kept, and this is part of #344.

**Comment by thvitt** [comment]
dots are kept because there never was a spec to drop them (cf. #204, [text-cleanup.xsl](https://github.com/faustedition/faust-gen-html/blob/master/xslt/text-cleanup.xsl)).
