### ISSUE TITLE
"vorschl." mit Punkt im App zu nach 3409

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#616]
@thvitt, hast du eine Idee, wie der `vorschl.` Punkt in http://dev.faustedition.net/print/faust.18#app.3410.before zustande kommt?
In
```xml
    <rdg wit="1_H.6"> <note>Strophenabstand vorschl Gö mark G <wit>1_H.6</wit></note></rdg>
```
steht er nicht.

**Comment by thvitt** [comment]
Ja, hierher:

https://github.com/faustedition/faust-gen-html/blame/master/xslt/text-postprocess.xsl#L23-L33

Die Diskussion in #233 ging so lange hin und her, dass der Stand 'mit Punkt' wohl implementiert wurde.

**Comment by thvitt** [comment]
Es scheint mehrere abbr-Handler zu geben, denn andernorts _ist_ ein Punkt und es wird sogar irnkwie expandiert …

**Comment by thvitt** [comment]
die og implementierung ist obsolet. Die aktuelle Implementierung für das abbr-Zeugs ist hier:
https://github.com/faustedition/faust-gen-html/blob/93f8bbbb7244e4af74f1cff74c6804afca1985e9/xslt/text-insert-app.xsl#L497-L514
allerdings erwischt sie die Abkürzungen in der Note zu after_3409 nicht

**Comment by gerritbruening** [comment]
Ah, danke!
