### ISSUE TITLE
4436 Kranz

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#624]
Online `Ic`, obwohl ohne Eingriff. Typ fraglich.

**Comment by dietmarpravida** [comment]
im Druck ist es `Ic*`. Vielleicht zu`VII` ändern?

**Comment by gerritbruening** [comment]
Und nicht 1b*?

**Comment by dietmarpravida** [comment]
ginge auch, letztlich weiß aber niemand, obs wirklich ein Fehler ist.

**Comment by gerritbruening** [comment]
Mein Punkt war, dass ich nicht erklären könnte, warum es ein typographischer Fehler sein soll (und keiner der Interpunktion). Mit `VII` machen wir nichts verkehrt, ein Lob auf Typ VII.
