### ISSUE TITLE
Update Text according to 2nd edition

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#631]
See referencing commits as well as earlier ones of the same file.

- [x] Indentations on pages 175 – 177 have been modified and checked.
- [x] see referencing issues.

**Comment by gerritbruening** [comment]
@dietmarpravida, bitte um Prüfung von http://dev.faustedition.net/print/faust.24#app.3956.only-app an. Mir sind im Druck übrigens Dinge wie `4004-4007` aufgefallen (Binde- statt Bis-Strich zwischen den Zahlen).

**Comment by gerritbruening** [comment]
Benutze den workflow beschrieben https://github.com/faustedition/faust-gen-html/issues/497#issuecomment-442839610.

**Comment by markusciupke** [comment]
> Mir sind im Druck übrigens Dinge wie 4004-4007 aufgefallen (Binde- statt Bis-Strich zwischen den Zahlen).

Danke für den Hinweis. Ich habe den Fehler zweimal gefunden: auf S. 176 letzte Zeile und auf S. 177 vorletzte Zeile. Laut Suchfunktion im ganzen Dokument gibt es kein weiteres Vorkommnis. Tut mir leid, dass ich das übersehen habe. Ich habe das in der Datei bereits für die 3. Auflage korrigiert.

Nebenbei: gestern ist unsere neue Vorschau aus der Druckerei gekommen und auf der U3 ist die neue Ausgabe des KT mit neuer ISBN angekündigt. Die Vorschau ist auf unserer Homepage runterzuladen www.wallstein-verlag.de, wenn ihr euch das anschauen wollt. Die 2. Auflage wird wie es aussieht am 13. oder 14. Dezember fertig. Ihr erhaltet 20 Freiexemplare direkt von der Druckerei.

**Comment by thvitt** [comment]
@gerritbruening kannst Du das bitte schließen und ggf. noch offenes rausziehen, damit der Status für den Milestone dokumentiert ist?

**Comment by gerritbruening** [comment]
Habe den Milestone geändert.
