### ISSUE TITLE
Fake variants because of standalone orig

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#632]
This is all basically one variant:

```xml
<l n="8626"><orig>Ue</orig>ber die Zinne des Kerkers hin</l>|	2_III_H.3, 2_III_H.3a_1
<l n="8626">Ueber die Zinne des Kerkers hin</l>|	C.1_4, C.2alpha_4
<l n="8626"><orig>Ue</orig>ber die Zinne des Kerkers hin</l>|	2_H
<l n="8626">Ueber die Zinne des Kerkers hin</l>|	C.3_4
```

Why is the standalone orig there in the text? should we eliminate it in the workflow that generates the pseudo xml that is the base for determining variants?

**Comment by gerritbruening** [comment]
Yes, you may drop it anywhere as long as it is preserved in the source files.
Interesting that I never stumbled over such variants. I don't use the edition as often as I should ...
