### ISSUE TITLE
Link archive_prints from app entries

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#633]
I have tried this:

https://github.com/faustedition/faust-gen-html/blob/4c6574a0e35c59d1a8dc44eda6fe891568bb3c00/text/app12norm_special-cases.xml#L293

But this is ignored, of course. @thvitt, what do think about this? Is it useful, feasible?

**Comment by thvitt** [comment]
This is TEI, try `<ref target="/archive_prints">späteren</ref>`

**Comment by gerritbruening** [comment]
Thanks for the advice, I have made the change and will see what happens.
