### ISSUE TITLE
Remove heading "Archivalien" 

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#65]
See https://github.com/faustedition/faust-web/blob/826a0ee770cbae9899ddacab1b2200d3d25c274b/archive_locations_detail.php#L12

**Comment by thvitt** [comment]
ist eigentlich offensichtlich, wa? Ich kann's ja mal umsetzen bei gelegenheit

**Comment by gerritbruening** [comment]
(sorry, ist natürlich ein faust-web-issue)
