### ISSUE TITLE
Wanted: XSLT to complete `l/@n` numbering

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#658]
We once had an xslt on https://faustedition.uni-wuerzburg.de/xml/ that completes the `l/@n`.
You had to indicate `n="1"` and non-trivial values (e.g., where one value had to be repeated or skipped).
This was very helpful, and I would like to use it again.
@thvitt, I can find it in the "[tools](https://github.com/faustedition/faust-gen-html/tree/master/tools)" folder, maybe the script never made it there. Do you have an idea where I could find it?

**Comment by gerritbruening** [comment]
Forgot to mention that I cannot access https://faustedition.uni-wuerzburg.de/xml/ anymore (if this is still extant).

**Comment by thvitt** [comment]
I guess it’s [verszaehlung.xsl](https://github.com/faustedition/faust-data-nonpublic/blob/nonpublic/xml/xslt/verszaehlung.xsl) in the repository for the old stuff …

**Comment by thvitt** [comment]
btw. everything from <https://faustedition.uni-wuerzburg.de/xml/> has moved there (albeit for published data faust-xml has the newer versions)

**Comment by gerritbruening** [comment]
Thanks for the hint, I had overlooked this repo!
The xslt still works fine.
Good to have this data here, since not all of it is outdated; some data, e.g., `edition`, has no newer equivalent, I guess.
