### ISSUE TITLE
Section mis-association for Nacht. Offen Feld.

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#66]
[Nacht. Offen Feld.](http://dev.faustedition.net/print/A8_IIIB18.27#scene_1.26) is misassosiated with the preceding _Trüber Tag. Feld._ section (cf. the breadcrumb), at least in A8

**Comment by thvitt** [comment]
@gerritbruening, folgender Vorschlag:

1. Du verpasst möglichst allen `<div>`s, die potentiell im TOC bzw. Breadcrumb erscheinen können, ein `n`-Attribut mit einer wie auch immer gearteten, aber konsistenten Nummerierung.
2. in [scenes.xml](https://github.com/faustedition/faust-gen-html/blob/master/xslt/scenes.xml) gleichst Du die entsprechenden Einträge für `id` und `n` ggf. angeglichen.
3. Gliederungsebenen, die nicht Akt sind, die in TOC/Breadcrumb auftauchen sollen, aber noch nicht vorhanden sind & nicht für das Balkendiagramm benötigt werden, ergänzt Du entsprechend in der scenes.xml; die line mappings kannst Du weglassen.
4. wenn das fertig ist, sollte es schon automatisch keine Fehlassoziationen mehr geben; ggf. rüste ich `<add-metadata.xsl>` entsprechend nach.
5. die für die Webapplikation verwendete json-Datei mit den Mappings generiere ich künftig aus scenes.xml statt umgekehrt wie bisher.

**Comment by gerritbruening** [comment]
@thvitt, das klingt sehr gut.
Frage zu 1: Es gibt viele `<div>`s mit @ `n`, obwohl redundand, da sehr kleine Handschriften (enthalten lediglich Teile einer Szene und keine andere Szene). Z.B. `391501.xml`. Stören solche @ `n`?

**Comment by thvitt** [comment]
Werden die betreffenden Werte in scenes.xml vorkommen (mit anderer Bedeutung)?

**Comment by gerritbruening** [comment]
Wenn sie übereinstimmen, sollten sie auch dieselbe Bedeutung haben.

**Comment by thvitt** [comment]
Dann stören die anderen nicht.

**Comment by gerritbruening** [comment]
Was ich jetzt nicht verstehe: Was haben die `<div>`s eigentlich mit dem Problem mit [Nacht. Offen Feld.](http://dev.faustedition.net/print/A8_IIIB18.27#scene_1.26) zu tun?

**Comment by gerritbruening** [comment]
@thvitt, andere Frage: Brauchen wir in `scenes.xml` eigentlich

    <scene n="1.1">
        <title>Der Tragödie erster Teil</title>
        <id>1.1</id>
    </scene>

damit diese Ebene im ToC existiert? Oder ist das wie bei den Faust II-Akten, dass das auch so geht?

**Comment by gerritbruening** [comment]
@thvitt, die zweite der beiden folgenden Szenen ist im XML Kind der ersten. Ist das ein Problem?

    <scene n="2.5.3">
        <rangeStart>11288</rangeStart>
        <rangeEnd>11383</rangeEnd>
        <title>Tiefe Nacht</title>
        <id>2.5.3</id>
    </scene>
    <scene n="2.5.3.1">
        <rangeStart>11384</rangeStart>
        <rangeEnd>11510</rangeEnd>
        <title>Mitternacht</title>
        <id>2.5.3.1</id>
    </scene>

**Comment by gerritbruening** [comment]
@thvitt, könntest du dir im Licht der letzten Fragen die von mir hergestellte Version von scenes.xml ansehen? Wenn alles OK ist, würde ich zumindest Trüber Tag. Feld in den Daten kennzeichnen.

**Comment by thvitt** [comment]
Ich implementiere die Unterstützung dafür gerade.

Die Strategie ist, dass divs, an denen geteilt wird, sowie divs, deren n-Attribut in scenes.xml gefunden wird, jeweils einen Inhaltsverzeichniseintrag bekommen. Die für diesen Eintrag verwendete Überschrift wird nach #71 bestimmt. 

Geteilt wird in entsprechend großen Dokumenten an <div>s der 2. Ebene sowie an divs der 1. Ebene, sofern diese keine div-Nachkommen haben. 

Einen TOC-Eintrag gibt es zur Zeit für alle divs von außen bis zu divs, an denen geteilt wird (s.o.), sowie für die erste <titlePage>. Künftig werden auch <div>s unterhalb von denen, an denen geteilt wird, im TOC verzeichnet, sofern sie oder einer ihrer Nachfahren in der scenes.xml verzeichnet ist.

Von daher:
* die Schachtelung im TEI wird kein Problem sein
* ohne Eintrag im scenes.xml wird auch im Lesetext die aus dem Zeugen generierte Überschrift „Der Tragödie erster Theil“ verwendet

**Comment by gerritbruening** [comment]
> ohne Eintrag im scenes.xml wird auch im Lesetext die aus dem Zeugen generierte Überschrift „Der Tragödie erster Theil“ verwendet

D.h., wenn wir "Der Tragödie erster **Teil**" haben wollen, dann brauchts scene 1.1, richtig?

**Comment by thvitt** [comment]
ja genau

**Comment by gerritbruening** [comment]
Danke!

**Comment by gerritbruening** [comment]
Aber woher kommt dann "1. Akt" usw.?

**Comment by thvitt** [comment]
achja. Sonderfall. Akte im Faust 2 werden generiert nach dem Schema »n. Akt«

**Comment by gerritbruening** [comment]
Hatte ich vermutet, aber durch Suche im Repository nicht gefunden. Soll das nicht auch im Breadcrumb wiedergespiegelt werden? Nur dass `2. Akt > Laboratorium` nicht zwei, sondern nur **ein** Link auf das Balkendiagramm zur Szene ist?
