### ISSUE TITLE
Ubuntu font lacks ⟨ ⟩

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#7]
Problem appears only on a device that doesn't have a font containing ⟨ ⟩. Options to fix this:
1. create a derived version of the Ubuntu font that contains ⟨ and ⟩, maybe by editing ‹› or <>.
2. find a WOFF font containing these characters and deliver it (only for these characters)
3. switch everything to a different font

Maybe defer this after the design decisions?

**Comment by gerritbruening** [comment]
Können wir beeinflussen, welcher Font ersatzweise genommen wird? Bei mir sieht es vertretbar aus, jedenfalls entsteht kein Schaden wie vergrößerter Zeilenabstand oder so.

**Comment by thvitt** [comment]
Bei mir sieht es ebenfalls gut aus — nur auf dem Tablet, da fehlen die ⟨
⟩ einfach. Ich glaube die Strategie ist, das zu ignorieren bis wir es
lösen, und es dann so zu lösen, dass wir einfach den Font ergänzen.

Es gibt AFAIK irgendwelche CSS-Mechanismen für Fonts für
Unicode-Bereiche, die jedoch von den Browsern nicht implementiert sind.
