### ISSUE TITLE
Adapt 1 H.5's ToC to wording in XML source

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#71]
http://dev.faustedition.net/documentViewer.php?faustUri=faust://xml/document/faust/0/gsa_390028.xml&page=1&view=print&section=390028

For example, "Studierzimmer II" is irritating because this heading is from a much later time.

Ideally, the first appearing `<head>` or `<stage>` element would be used.

**Comment by thvitt** [comment]
We surely don't want special handling for only one witness? 

Suggestion:

* Lesetext → normalized heading
* there is a `<head>` → use that 
* else `[`normalized heading`]`

I would prefer to avoid `<stage>` since this [can cause very long headings](http://beta.faustedition.net/print/faust2.21).

**Comment by gerritbruening** [comment]
I agree that we should avoid very long headings. We should have special treatment for the reading text, not for only a few witnesses.

Maybe we can abbreviate them by dots if the stage is longer than, say, 60 chars? The dots could appear after the first period of the stage's content.

**Comment by thvitt** [comment]
So its (first match wins):

* Lesetext → normalized heading
* there is a `<head>` → use that 
* first stage ≤ 60 chars → `[`first stage`]`
* `[`replace(stage[1], '\..*', '. …')`]`

**Comment by gerritbruening** [comment]
That would be great, thanks!
