### ISSUE TITLE
Adapt previous / next scene naviagtion to ToC headings

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#76]
See http://dev.faustedition.net/documentViewer.php?faustUri=faust://xml/document/faust/0/gsa_390028.xml&page=1&view=print&section=390028.1#scene_1.4
where the next scene is labeled "Studirzimmer".

Related to https://github.com/faustedition/faust-gen-html/issues/71.

**Comment by thvitt** [comment]
???

Previous / next scene navigation & TOC headings already use the same data. The next scene on the page linked above is “Mephistopheles im Schlafrock eine grose Perrücke auf. …” since it doesn't have a heading.

**Comment by gerritbruening** [comment]
Now I see the correct label. I think that I saw "Studirzimmer" yesterday.
