### ISSUE TITLE
Create prepare-reading-text.xpl

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#81]
(old deprecated encoding practice)

We should get rid of @ status it in the course of the generation of the reading text, that is, in `apply-edits`. Eventually, we could even delete it in the XML sources. @thvitt , could you adapt `apply-edits` so that //stage//hi/@status is suppressed?

**Comment by gerritbruening** [comment]
Maybe introduce a specia `output` for this and similar purposes?

**Comment by thvitt** [comment]
Vllt. besprechen wir das mal am Rande am Montag oder so.

**Comment by gerritbruening** [comment]
OK!

**Comment by gerritbruening** [comment]
See https://github.com/faustedition/faust-gen-html/blob/master/text/readme_text.md#adapt-apply-edits
