### ISSUE TITLE
teiHeader in transcript

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#84]
- [x] basic information to make all `teiHeader`s valid
   - Editionsinformationen
   - Handschrifteninformationen
- [x] licence
- [x] no `msDesc`-like `tei:xenoData`

**Comment by gerritbruening** [comment]
Licence? Was für eine Licence? Brauchen wir das?

**Comment by thvitt** [comment]
du hast das aufgemacht.

ja, sollten wir haben. Die Lizenz ist irgendwas CCiges. Definier das doch gleich mit, wenn Du die Header definierst, und ich baus dann alles zusammen ein.

**Comment by gerritbruening** [comment]
With the referencing commit I have added a template that may fit to our needs.

**Comment by gerritbruening** [comment]
* `<edition><!-- generiert: Versionsname --></edition>` bleibt weg
* `<date><!-- generiert: date/@when --></date>` bleibt weg
* `<repository>generiert aus archives/archive/city/text()</repository>` gefolgt von `<idno>idno</idno>` nicht gut

**Comment by thvitt** [comment]
ich nerv nur ungern nochmal.

`<repository>` wieso ausgerechnet city und nicht displayName oder so? Bei Weimar ist das mehrdeutig.

**Comment by gerritbruening** [comment]
> `<repository>` wieso ausgerechnet city 

Das ist ein Fehler, ich dachte wohl mal, da sei `location` obligatorisch, und das war nicht so, und dann hab ich versehentlich nur den tag-Namen ausgetauscht.
Egal, einfach das richtige tun, also `displayName`.
