### ISSUE TITLE
1 H.5 not properly displayed in "Trüber Tag"

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#87]
For example, see http://dev.faustedition.net/print/faust1.26#lttf_2.

1 H.5 has

    <milestone unit="refline" n="ttf_2"/>verirrt!</s> <s>Als Miſſetäterinn im Kerker

but is supposed to have "verirrt und nun gefangen! Als Missethäterin im Kerker"

**Comment by thvitt** [comment]
1 H.5 ist der einzige Zeuge mit `<s>`, oder? Brauchen wir die für irgendwas? Ich vermute die Ursache darin

**Comment by thvitt** [comment]
Die _Trüber Tag. Feld._-Kodierung ist in 1 H.5 in zweierlei hinsicht problematisch (d.h. von den getesteten TTF-Zeugen abweichend) und führt dazu, dass prose2lines.xsl nicht so funktioniert, wie es sollte:
1. Die `<s>`-Elemente als zusätzliche, konfligierende Hierarchieebene. prose2lines.xsl geht davon aus, dass die die Referenzzeilen anzeigenden `<milestone>`-Elemente unmittelbare Kinder des `<p>` sind, in den anderen Zeugen ist dies auch der Fall.
2. in 1 H.5 steht die erste `refline` außerhalb des durch sie aufgesplitteten `<p>`, dadurch wird die entsprechende Versnummer nicht gefunden und die erste Refline bleibt ohne Apparat.

@gerritbruening, was davon kannst Du im TEI beheben? Wenn die `<s>` drinbleiben müssen, schmeiße ich sie für die Beta 2 in prose2lines weg, ansonsten müsste ich das Skript umschreiben, dafür bleibt keine Zeit.

**Comment by gerritbruening** [comment]
Ad 1: Hatte ich befürchtet. Von mir aus brauchen wir die `<s>` nicht. Es gibt sie aber [in vielen Transkripten](https://faustedition.uni-wuerzburg.de/new/xml-query/?folder=transcript&xpath=%2F%2Ftei%3As&mode=files). Deswegen wär es mir lieber, sie würden in prose2lines weggeworfen.

**Comment by gerritbruening** [comment]
Ad 2: OK, dann tue ich die in die `<p>`.

**Comment by gerritbruening** [comment]
OK, ist gemacht!
