### ISSUE TITLE
URIs in list of testimonies

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-gen-html#92]
Arbeitsplan: https://faustedition.uni-wuerzburg.de/wiki/index.php/Dokumente_zur_Entstehungsgeschichte#Integration_in_Beta.2

Erster Schritt: grobe Fehler in der excel entfernen (DP)

> irgendwann danach machen wir aus der Druckort-Spalte drei: (i) die aktuelle Variante, entfällt später (beta 3) nach vollständiger Umstellung auf URIs; (ii) Spalte _nur_ für die URIs, (iii) Spalte für spezifizierende Angaben (Seitenzahlen etc.). Für (ii) und (iii) kann ich bei Gelegenheit automatisiert eine Rohform erzeugen, die nicht gefundenen Einträge müssen dann nachgearbeitet werden.

--> Spalten:
1. aktuelle (entfällt mit beta 3)
2. Spalte mit URIs
3. Seitenangaben etc.

**Comment by gerritbruening** [comment]
@thvitt, ist das überholt? Ich verstehe das issue nicht mehr so ganz.

**Comment by thvitt** [comment]
Denke schon. 

Offen ist noch:

1. was mit der Druckorte-Spalte geschehen soll – faustedition/faust-web#250 – also ob irgendeine Form der Zitation in der Tabelle auftauchen soll
2. neue Spalte für Testimonies, die auch Textzeugen sind faustedition/xml#259
