### ISSUE TITLE
Searching for sigils that violate lucene syntax fails

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#94]
E.g. GSA signatures contain a /, but [searching for 27/26](http://dev.faustedition.net/search?q=27/26) just shows the exception display.

Probably catch the exception of the two queries individually and only show the error display when both either failed or produced no results?

**Comment by thvitt** [comment]
Priority depends. Do people search for GSA signatures?

**Comment by gerritbruening** [comment]
May happen, but rarely.
