### ISSUE TITLE
Seckendorf is missing sigil and link in list of prints

### ISSUE THREAD

**Issue by thvitt** [faustedition/faust-gen-html#99]
The generated snippet is:

```html
<tr>
  <td><a href="print/"></a></td>
  <td data-value="1">Volks- und andere Lieder von Siegmund Freyherrn von Seckendorff, 1782.</td>
</tr>
```
although the metadata looks OK (it should be J.1)

**Comment by thvitt** [comment]
@gerritbruening, `print-labels.xml` (XML root folder) contains
```xml
    <item uri="faust://xml/transcript/gsa/GSA_32_1420/GSA_32_1420.xml">Volks- und andere Lieder von Siegmund Freyherrn von Seckendorff, 1782.</item>
```
This file can no longer be found, have you moved it somewhere? Could you adapt the print-labels.xml?

**Comment by gerritbruening** [comment]
Yes, it's now

    <item uri="faust://xml/print/seckendorff1782.xml">Volks- und andere Lieder von Siegmund Freyherrn von Seckendorff, 1782.</item>
